package dto

type Anl_maceral_maturity struct {
	Analysis_id                 string   `json:"analysis_id" default:"source"`
	Anl_source                  string   `json:"anl_source" default:"source"`
	Measurement_obs_no          int      `json:"measurement_obs_no" default:"1"`
	Active_ind                  *string  `json:"active_ind" default:""`
	Coal_rank_id                *string  `json:"coal_rank_id" default:""`
	Effective_date              *string  `json:"effective_date" default:""`
	Expiry_date                 *string  `json:"expiry_date" default:""`
	Fluor_color                 *string  `json:"fluor_color" default:""`
	Fluor_intensity_desc        *string  `json:"fluor_intensity_desc" default:""`
	Fluor_intensity_value       *float64 `json:"fluor_intensity_value" default:""`
	Fluor_intensity_value_ouom  *string  `json:"fluor_intensity_value_ouom" default:""`
	Mean_max_reflectance        *float64 `json:"mean_max_reflectance" default:""`
	Mean_random_reflectance     *float64 `json:"mean_random_reflectance" default:""`
	Measurements_count          *int     `json:"measurements_count" default:""`
	Population_name             *string  `json:"population_name" default:""`
	Population_num              *string  `json:"population_num" default:""`
	Population_obs_no           *int     `json:"population_obs_no" default:""`
	Ppdm_guid                   *string  `json:"ppdm_guid" default:""`
	Preferred_ind               *string  `json:"preferred_ind" default:""`
	Problem_ind                 *string  `json:"problem_ind" default:""`
	Reflect_max_meas_value      *float64 `json:"reflect_max_meas_value" default:""`
	Reflect_max_meas_value_ouom *string  `json:"reflect_max_meas_value_ouom" default:""`
	Reflect_max_meas_value_uom  *string  `json:"reflect_max_meas_value_uom" default:""`
	Reflect_meas_value          *float64 `json:"reflect_meas_value" default:""`
	Reflect_meas_value_ouom     *string  `json:"reflect_meas_value_ouom" default:""`
	Reflect_meas_value_uom      *string  `json:"reflect_meas_value_uom" default:""`
	Reflect_min_meas_value      *float64 `json:"reflect_min_meas_value" default:""`
	Reflect_min_meas_value_ouom *string  `json:"reflect_min_meas_value_ouom" default:""`
	Reflect_min_meas_value_uom  *string  `json:"reflect_min_meas_value_uom" default:""`
	Reflect_std_dev_value       *float64 `json:"reflect_std_dev_value" default:""`
	Refl_random_meas_value      *float64 `json:"refl_random_meas_value" default:""`
	Refl_random_meas_value_ouom *string  `json:"refl_random_meas_value_ouom" default:""`
	Refl_random_meas_value_uom  *string  `json:"refl_random_meas_value_uom" default:""`
	Remark                      *string  `json:"remark" default:""`
	Reworked_percent            *float64 `json:"reworked_percent" default:""`
	Sample_tot_maceral_val      *float64 `json:"sample_tot_maceral_val" default:""`
	Sample_tot_maceral_val_ouom *string  `json:"sample_tot_maceral_val_ouom" default:""`
	Source                      *string  `json:"source" default:""`
	Step_seq_no                 *int     `json:"step_seq_no" default:""`
	Substance_id                *string  `json:"substance_id" default:""`
	Row_changed_by              *string  `json:"row_changed_by" default:""`
	Row_changed_date            *string  `json:"row_changed_date" default:""`
	Row_created_by              *string  `json:"row_created_by" default:""`
	Row_created_date            *string  `json:"row_created_date" default:""`
	Row_effective_date          *string  `json:"row_effective_date" default:""`
	Row_expiry_date             *string  `json:"row_expiry_date" default:""`
	Row_quality                 *string  `json:"row_quality" default:""`
}
