package dto

type Anl_oil_distill struct {
	Analysis_id             string   `json:"analysis_id" default:"source"`
	Anl_source              string   `json:"anl_source" default:"source"`
	Dstl_summary_obs_no     int      `json:"dstl_summary_obs_no" default:"1"`
	Active_ind              *string  `json:"active_ind" default:""`
	Atmosp_dstl_press       *float64 `json:"atmosp_dstl_press" default:""`
	Atmosp_dstl_press_ouom  *string  `json:"atmosp_dstl_press_ouom" default:""`
	Atmosp_dstl_temp        *float64 `json:"atmosp_dstl_temp" default:""`
	Atmosp_dstl_temp_ouom   *string  `json:"atmosp_dstl_temp_ouom" default:""`
	Calculated_ind          *string  `json:"calculated_ind" default:""`
	Calculate_method_id     *string  `json:"calculate_method_id" default:""`
	Effective_date          *string  `json:"effective_date" default:""`
	Expiry_date             *string  `json:"expiry_date" default:""`
	Final_boil_pt_temp      *float64 `json:"final_boil_pt_temp" default:""`
	Final_boil_pt_temp_ouom *string  `json:"final_boil_pt_temp_ouom" default:""`
	Measurement_temp        *float64 `json:"measurement_temp" default:""`
	Measurement_temp_ouom   *string  `json:"measurement_temp_ouom" default:""`
	Ppdm_guid               *string  `json:"ppdm_guid" default:""`
	Preferred_ind           *string  `json:"preferred_ind" default:""`
	Problem_ind             *string  `json:"problem_ind" default:""`
	Remark                  *string  `json:"remark" default:""`
	Reported_ind            *string  `json:"reported_ind" default:""`
	Source                  *string  `json:"source" default:""`
	Start_boil_pt_temp      *float64 `json:"start_boil_pt_temp" default:""`
	Start_boil_pt_temp_ouom *string  `json:"start_boil_pt_temp_ouom" default:""`
	Step_seq_no             *int     `json:"step_seq_no" default:""`
	Substance_id            *string  `json:"substance_id" default:""`
	Volume_fraction_type    *string  `json:"volume_fraction_type" default:""`
	Vol_fraction_temp       *float64 `json:"vol_fraction_temp" default:""`
	Vol_fraction_temp_ouom  *string  `json:"vol_fraction_temp_ouom" default:""`
	Vol_fraction_value      *float64 `json:"vol_fraction_value" default:""`
	Vol_fraction_value_ouom *string  `json:"vol_fraction_value_ouom" default:""`
	Weight_cut              *float64 `json:"weight_cut" default:""`
	Weight_cut_ouom         *string  `json:"weight_cut_ouom" default:""`
	Row_changed_by          *string  `json:"row_changed_by" default:""`
	Row_changed_date        *string  `json:"row_changed_date" default:""`
	Row_created_by          *string  `json:"row_created_by" default:""`
	Row_created_date        *string  `json:"row_created_date" default:""`
	Row_effective_date      *string  `json:"row_effective_date" default:""`
	Row_expiry_date         *string  `json:"row_expiry_date" default:""`
	Row_quality             *string  `json:"row_quality" default:""`
}
