package dto

type Anl_problem struct {
	Analysis_id            string   `json:"analysis_id" default:"source"`
	Anl_source             string   `json:"anl_source" default:"source"`
	Problem_obs_no         int      `json:"problem_obs_no" default:"1"`
	Active_ind             *string  `json:"active_ind" default:""`
	Activity_set_id        *string  `json:"activity_set_id" default:""`
	Anl_problem_ind        *string  `json:"anl_problem_ind" default:""`
	Ba_problem_ind         *string  `json:"ba_problem_ind" default:""`
	Confidence_type        *string  `json:"confidence_type" default:""`
	Effective_date         *string  `json:"effective_date" default:""`
	Equip_problem_ind      *string  `json:"equip_problem_ind" default:""`
	Expiry_date            *string  `json:"expiry_date" default:""`
	Method_id              *string  `json:"method_id" default:""`
	Method_problem_ind     *string  `json:"method_problem_ind" default:""`
	Percent_of_sample      *float64 `json:"percent_of_sample" default:""`
	Ppdm_guid              *string  `json:"ppdm_guid" default:""`
	Problem_desc           *string  `json:"problem_desc" default:""`
	Problem_result         *string  `json:"problem_result" default:""`
	Problem_result_desc    *string  `json:"problem_result_desc" default:""`
	Problem_severity       *string  `json:"problem_severity" default:""`
	Problem_severity_desc  *string  `json:"problem_severity_desc" default:""`
	Problem_type           *string  `json:"problem_type" default:""`
	Referenced_column_name *string  `json:"referenced_column_name" default:""`
	Referenced_ppdm_guid   *string  `json:"referenced_ppdm_guid" default:""`
	Referenced_system_id   *string  `json:"referenced_system_id" default:""`
	Referenced_table_name  *string  `json:"referenced_table_name" default:""`
	Remark                 *string  `json:"remark" default:""`
	Resolution_method      *string  `json:"resolution_method" default:""`
	Resolution_method_desc *string  `json:"resolution_method_desc" default:""`
	Resolution_step_seq_no *int     `json:"resolution_step_seq_no" default:""`
	Resolved_by_ba_id      *string  `json:"resolved_by_ba_id" default:""`
	Sample_problem_ind     *string  `json:"sample_problem_ind" default:""`
	Source                 *string  `json:"source" default:""`
	Step_seq_no            *int     `json:"step_seq_no" default:""`
	Valid_problem_obs_no   *int     `json:"valid_problem_obs_no" default:""`
	Row_changed_by         *string  `json:"row_changed_by" default:""`
	Row_changed_date       *string  `json:"row_changed_date" default:""`
	Row_created_by         *string  `json:"row_created_by" default:""`
	Row_created_date       *string  `json:"row_created_date" default:""`
	Row_effective_date     *string  `json:"row_effective_date" default:""`
	Row_expiry_date        *string  `json:"row_expiry_date" default:""`
	Row_quality            *string  `json:"row_quality" default:""`
}
