package dto

type Land_sale_request struct {
	Land_request_id       string   `json:"land_request_id" default:"source"`
	Active_ind            *string  `json:"active_ind" default:""`
	Advance_booking_ind   *string  `json:"advance_booking_ind" default:""`
	Ami_ind               *string  `json:"ami_ind" default:""`
	Area_id               *string  `json:"area_id" default:""`
	Area_type             *string  `json:"area_type" default:""`
	Bid_ind               *string  `json:"bid_ind" default:""`
	Broker_ba_id          *string  `json:"broker_ba_id" default:""`
	Contact_ba_id         *string  `json:"contact_ba_id" default:""`
	Critical_date         *string  `json:"critical_date" default:""`
	Drilling_priority_ind *string  `json:"drilling_priority_ind" default:""`
	Effective_date        *string  `json:"effective_date" default:""`
	Expiry_date           *string  `json:"expiry_date" default:""`
	Granted_right_type    *string  `json:"granted_right_type" default:""`
	Gross_size            *float64 `json:"gross_size" default:""`
	Gross_size_ouom       *string  `json:"gross_size_ouom" default:""`
	Investigator          *string  `json:"investigator" default:""`
	Jurisdiction          *string  `json:"jurisdiction" default:""`
	Land_req_status       *string  `json:"land_req_status" default:""`
	Land_right_id         *string  `json:"land_right_id" default:""`
	Land_right_subtype    *string  `json:"land_right_subtype" default:""`
	Land_sale_number      *string  `json:"land_sale_number" default:""`
	Land_sale_offering_id *string  `json:"land_sale_offering_id" default:""`
	Lessor_refused_date   *string  `json:"lessor_refused_date" default:""`
	Originator_ba_id      *string  `json:"originator_ba_id" default:""`
	Ppdm_guid             *string  `json:"ppdm_guid" default:""`
	Previous_request_id   *string  `json:"previous_request_id" default:""`
	Purpose               *string  `json:"purpose" default:""`
	Reference_num         *string  `json:"reference_num" default:""`
	Remark                *string  `json:"remark" default:""`
	Requested_sale_date   *string  `json:"requested_sale_date" default:""`
	Requested_sale_name   *string  `json:"requested_sale_name" default:""`
	Requester             *string  `json:"requester" default:""`
	Request_cancel_date   *string  `json:"request_cancel_date" default:""`
	Request_description   *string  `json:"request_description" default:""`
	Request_received_date *string  `json:"request_received_date" default:""`
	Request_size          *float64 `json:"request_size" default:""`
	Request_size_ouom     *string  `json:"request_size_ouom" default:""`
	Request_type          *string  `json:"request_type" default:""`
	Response_date         *string  `json:"response_date" default:""`
	Response_desc         *string  `json:"response_desc" default:""`
	Source                *string  `json:"source" default:""`
	Submitted_date        *string  `json:"submitted_date" default:""`
	Term_duration         *float64 `json:"term_duration" default:""`
	Term_duration_ouom    *string  `json:"term_duration_ouom" default:""`
	Uwi                   *string  `json:"uwi" default:""`
	Well_license_id       *string  `json:"well_license_id" default:""`
	Well_source           *string  `json:"well_source" default:""`
	Withdrawn_date        *string  `json:"withdrawn_date" default:""`
	Row_changed_by        *string  `json:"row_changed_by" default:""`
	Row_changed_date      *string  `json:"row_changed_date" default:""`
	Row_created_by        *string  `json:"row_created_by" default:""`
	Row_created_date      *string  `json:"row_created_date" default:""`
	Row_effective_date    *string  `json:"row_effective_date" default:""`
	Row_expiry_date       *string  `json:"row_expiry_date" default:""`
	Row_quality           *string  `json:"row_quality" default:""`
}
