package dto

type Pden_vol_summary struct {
	Pden_subtype              string   `json:"pden_subtype" default:"source"`
	Pden_id                   string   `json:"pden_id" default:"source"`
	Period_id                 string   `json:"period_id" default:"source"`
	Pden_source               string   `json:"pden_source" default:"source"`
	Volume_method             string   `json:"volume_method" default:"source"`
	Activity_type             string   `json:"activity_type" default:"source"`
	Period_type               string   `json:"period_type" default:"source"`
	Amendment_seq_no          int      `json:"amendment_seq_no" default:"1"`
	Active_ind                *string  `json:"active_ind" default:""`
	Amend_reason              *string  `json:"amend_reason" default:""`
	Boe_cum_volume            *float64 `json:"boe_cum_volume" default:""`
	Boe_volume                *float64 `json:"boe_volume" default:""`
	Boe_volume_ouom           *string  `json:"boe_volume_ouom" default:""`
	Boe_ytd_volume            *float64 `json:"boe_ytd_volume" default:""`
	Co2_cum_volume            *float64 `json:"co_2_cum_volume" default:""`
	Co2_volume                *float64 `json:"co_2_volume" default:""`
	Co2_volume_ouom           *string  `json:"co_2_volume_ouom" default:""`
	Co2_ytd_volume            *float64 `json:"co_2_ytd_volume" default:""`
	Effective_date            *string  `json:"effective_date" default:""`
	Expiry_date               *string  `json:"expiry_date" default:""`
	Gas_cum_volume            *float64 `json:"gas_cum_volume" default:""`
	Gas_energy                *float64 `json:"gas_energy" default:""`
	Gas_energy_ouom           *string  `json:"gas_energy_ouom" default:""`
	Gas_quality               *float64 `json:"gas_quality" default:""`
	Gas_quality_ouom          *string  `json:"gas_quality_ouom" default:""`
	Gas_volume                *float64 `json:"gas_volume" default:""`
	Gas_volume_ouom           *string  `json:"gas_volume_ouom" default:""`
	Gas_ytd_volume            *float64 `json:"gas_ytd_volume" default:""`
	Injection_cycle           *float64 `json:"injection_cycle" default:""`
	Injection_pressure        *float64 `json:"injection_pressure" default:""`
	Injection_pressure_ouom   *string  `json:"injection_pressure_ouom" default:""`
	Inventory_close_balance   *float64 `json:"inventory_close_balance" default:""`
	Inventory_open_balance    *float64 `json:"inventory_open_balance" default:""`
	Inventory_product         *string  `json:"inventory_product" default:""`
	Invent_close_bal_ouom     *string  `json:"invent_close_bal_ouom" default:""`
	Invent_open_bal_ouom      *string  `json:"invent_open_bal_ouom" default:""`
	Ngl_cum_volume            *float64 `json:"ngl_cum_volume" default:""`
	Ngl_volume                *float64 `json:"ngl_volume" default:""`
	Ngl_volume_ouom           *string  `json:"ngl_volume_ouom" default:""`
	Ngl_ytd_volume            *float64 `json:"ngl_ytd_volume" default:""`
	Nitrogen_cum_volume       *float64 `json:"nitrogen_cum_volume" default:""`
	Nitrogen_volume           *float64 `json:"nitrogen_volume" default:""`
	Nitrogen_volume_ouom      *string  `json:"nitrogen_volume_ouom" default:""`
	Nitrogen_ytd_volume       *float64 `json:"nitrogen_ytd_volume" default:""`
	No_of_gas_wells           *float64 `json:"no_of_gas_wells" default:""`
	No_of_injection_wells     *float64 `json:"no_of_injection_wells" default:""`
	No_of_oil_wells           *float64 `json:"no_of_oil_wells" default:""`
	Oil_cum_volume            *float64 `json:"oil_cum_volume" default:""`
	Oil_quality               *float64 `json:"oil_quality" default:""`
	Oil_quality_ouom          *string  `json:"oil_quality_ouom" default:""`
	Oil_volume                *float64 `json:"oil_volume" default:""`
	Oil_volume_ouom           *string  `json:"oil_volume_ouom" default:""`
	Oil_ytd_volume            *float64 `json:"oil_ytd_volume" default:""`
	Period_on_injection       *float64 `json:"period_on_injection" default:""`
	Period_on_injection_ouom  *string  `json:"period_on_injection_ouom" default:""`
	Period_on_production      *float64 `json:"period_on_production" default:""`
	Period_on_production_ouom *string  `json:"period_on_production_ouom" default:""`
	Posted_date               *string  `json:"posted_date" default:""`
	Ppdm_guid                 *string  `json:"ppdm_guid" default:""`
	Primary_allowable         *float64 `json:"primary_allowable" default:""`
	Primary_allowable_ouom    *string  `json:"primary_allowable_ouom" default:""`
	Primary_product           *string  `json:"primary_product" default:""`
	Project_id                *string  `json:"project_id" default:""`
	Remark                    *string  `json:"remark" default:""`
	Report_ind                *string  `json:"report_ind" default:""`
	Source                    *string  `json:"source" default:""`
	Sulphur_cum_volume        *float64 `json:"sulphur_cum_volume" default:""`
	Sulphur_volume            *float64 `json:"sulphur_volume" default:""`
	Sulphur_volume_ouom       *string  `json:"sulphur_volume_ouom" default:""`
	Sulphur_ytd_volume        *float64 `json:"sulphur_ytd_volume" default:""`
	Volume_date               *string  `json:"volume_date" default:""`
	Volume_date_desc          *string  `json:"volume_date_desc" default:""`
	Volume_period             *float64 `json:"volume_period" default:""`
	Volume_period_ouom        *string  `json:"volume_period_ouom" default:""`
	Water_cum_volume          *float64 `json:"water_cum_volume" default:""`
	Water_volume              *float64 `json:"water_volume" default:""`
	Water_volume_ouom         *string  `json:"water_volume_ouom" default:""`
	Water_ytd_volume          *float64 `json:"water_ytd_volume" default:""`
	Row_changed_by            *string  `json:"row_changed_by" default:""`
	Row_changed_date          *string  `json:"row_changed_date" default:""`
	Row_created_by            *string  `json:"row_created_by" default:""`
	Row_created_date          *string  `json:"row_created_date" default:""`
	Row_effective_date        *string  `json:"row_effective_date" default:""`
	Row_expiry_date           *string  `json:"row_expiry_date" default:""`
	Row_quality               *string  `json:"row_quality" default:""`
}
