package dto

type Pden_volume_analysis struct {
	Pden_subtype                string   `json:"pden_subtype" default:"source"`
	Pden_id                     string   `json:"pden_id" default:"source"`
	Pden_source                 string   `json:"pden_source" default:"source"`
	Product_type                string   `json:"product_type" default:"source"`
	Case_id                     string   `json:"case_id" default:"source"`
	Active_ind                  *string  `json:"active_ind" default:""`
	Area_size                   *float64 `json:"area_size" default:""`
	Area_size_ouom              *string  `json:"area_size_ouom" default:""`
	Case_name                   *string  `json:"case_name" default:""`
	Date_format_desc            *string  `json:"date_format_desc" default:""`
	Effective_date              *string  `json:"effective_date" default:""`
	End_date                    *string  `json:"end_date" default:""`
	Expiry_date                 *string  `json:"expiry_date" default:""`
	Gas_abandon_compress        *float64 `json:"gas_abandon_compress" default:""`
	Gas_abandon_press           *float64 `json:"gas_abandon_press" default:""`
	Gas_abandon_press_ouom      *string  `json:"gas_abandon_press_ouom" default:""`
	Gas_init_compress           *float64 `json:"gas_init_compress" default:""`
	Gas_init_pressure           *float64 `json:"gas_init_pressure" default:""`
	Gas_in_place                *float64 `json:"gas_in_place" default:""`
	Gas_in_place_ouom           *string  `json:"gas_in_place_ouom" default:""`
	Gas_original_in_place       *float64 `json:"gas_original_in_place" default:""`
	Gas_original_in_place_ouom  *string  `json:"gas_original_in_place_ouom" default:""`
	Gas_ratio_bgi               *float64 `json:"gas_ratio_bgi" default:""`
	Gas_recovery                *float64 `json:"gas_recovery" default:""`
	Gross_net_pay_ratio         *float64 `json:"gross_net_pay_ratio" default:""`
	Gross_pay                   *float64 `json:"gross_pay" default:""`
	Gross_pay_ouom              *string  `json:"gross_pay_ouom" default:""`
	Init_res_temp               *float64 `json:"init_res_temp" default:""`
	Init_res_temp_ouom          *string  `json:"init_res_temp_ouom" default:""`
	Net_pay                     *float64 `json:"net_pay" default:""`
	Net_pay_ouom                *string  `json:"net_pay_ouom" default:""`
	Oil_in_place                *float64 `json:"oil_in_place" default:""`
	Oil_in_place_ouom           *string  `json:"oil_in_place_ouom" default:""`
	Oil_original_in_place       *float64 `json:"oil_original_in_place" default:""`
	Oil_original_in_place_ouom  *string  `json:"oil_original_in_place_ouom" default:""`
	Oil_recovery_primary        *float64 `json:"oil_recovery_primary" default:""`
	Oil_recovery_secondary      *float64 `json:"oil_recovery_secondary" default:""`
	Oil_recovery_total          *float64 `json:"oil_recovery_total" default:""`
	Oil_residual_sat            *float64 `json:"oil_residual_sat" default:""`
	Oil_shrinkage               *float64 `json:"oil_shrinkage" default:""`
	Original_gor                *float64 `json:"original_gor" default:""`
	Original_gor_ouom           *string  `json:"original_gor_ouom" default:""`
	Orig_sol_gas_in_place       *float64 `json:"orig_sol_gas_in_place" default:""`
	Orig_sol_gas_in_place_ouom  *string  `json:"orig_sol_gas_in_place_ouom" default:""`
	Permeability                *float64 `json:"permeability" default:""`
	Permeability_ouom           *string  `json:"permeability_ouom" default:""`
	Porosity                    *float64 `json:"porosity" default:""`
	Ppdm_guid                   *string  `json:"ppdm_guid" default:""`
	Project_id                  *string  `json:"project_id" default:""`
	Recov_gor                   *float64 `json:"recov_gor" default:""`
	Recov_sol_gas_in_place      *float64 `json:"recov_sol_gas_in_place" default:""`
	Recov_sol_gas_in_place_ouom *string  `json:"recov_sol_gas_in_place_ouom" default:""`
	Remark                      *string  `json:"remark" default:""`
	Sol_gas_recovery            *float64 `json:"sol_gas_recovery" default:""`
	Source                      *string  `json:"source" default:""`
	Start_date                  *string  `json:"start_date" default:""`
	Volume                      *float64 `json:"volume" default:""`
	Volume_ouom                 *string  `json:"volume_ouom" default:""`
	Volume_uom                  *string  `json:"volume_uom" default:""`
	Water_saturation            *float64 `json:"water_saturation" default:""`
	Row_changed_by              *string  `json:"row_changed_by" default:""`
	Row_changed_date            *string  `json:"row_changed_date" default:""`
	Row_created_by              *string  `json:"row_created_by" default:""`
	Row_created_date            *string  `json:"row_created_date" default:""`
	Row_effective_date          *string  `json:"row_effective_date" default:""`
	Row_expiry_date             *string  `json:"row_expiry_date" default:""`
	Row_quality                 *string  `json:"row_quality" default:""`
}
