package dto

type Report_hier_level struct {
	Report_hierarchy_id    string  `json:"report_hierarchy_id" default:"source"`
	Component_id           string  `json:"component_id" default:"source"`
	Active_ind             *string `json:"active_ind" default:""`
	Area_id                *string `json:"area_id" default:""`
	Area_type              *string `json:"area_type" default:""`
	Ba_organization_id     *string `json:"ba_organization_id" default:""`
	Ba_organization_seq_no *int    `json:"ba_organization_seq_no" default:""`
	Business_associate_id  *string `json:"business_associate_id" default:""`
	Component_type         *string `json:"component_type" default:""`
	Contract_id            *string `json:"contract_id" default:""`
	Effective_date         *string `json:"effective_date" default:""`
	Equipment_id           *string `json:"equipment_id" default:""`
	Expiry_date            *string `json:"expiry_date" default:""`
	Facility_id            *string `json:"facility_id" default:""`
	Facility_type          *string `json:"facility_type" default:""`
	Field_id               *string `json:"field_id" default:""`
	Finance_id             *string `json:"finance_id" default:""`
	Hierarchy_type_id      *string `json:"hierarchy_type_id" default:""`
	Land_right_id          *string `json:"land_right_id" default:""`
	Land_right_subtype     *string `json:"land_right_subtype" default:""`
	Level_seq_no           *int    `json:"level_seq_no" default:""`
	Parent_component_id    *string `json:"parent_component_id" default:""`
	Pool_id                *string `json:"pool_id" default:""`
	Ppdm_guid              *string `json:"ppdm_guid" default:""`
	Project_id             *string `json:"project_id" default:""`
	Remark                 *string `json:"remark" default:""`
	Sf_subtype             *string `json:"sf_subtype" default:""`
	Source                 *string `json:"source" default:""`
	Strat_name_set_id      *string `json:"strat_name_set_id" default:""`
	Strat_unit_id          *string `json:"strat_unit_id" default:""`
	Support_facility_id    *string `json:"support_facility_id" default:""`
	Uwi                    *string `json:"uwi" default:""`
	Row_changed_by         *string `json:"row_changed_by" default:""`
	Row_changed_date       *string `json:"row_changed_date" default:""`
	Row_created_by         *string `json:"row_created_by" default:""`
	Row_created_date       *string `json:"row_created_date" default:""`
	Row_effective_date     *string `json:"row_effective_date" default:""`
	Row_expiry_date        *string `json:"row_expiry_date" default:""`
	Row_quality            *string `json:"row_quality" default:""`
}
