package dto

type Rm_info_item_content struct {
	Info_item_subtype        string  `json:"info_item_subtype" default:"source"`
	Information_item_id      string  `json:"information_item_id" default:"source"`
	Content_obs_no           int     `json:"content_obs_no" default:"1"`
	Active_ind               *string `json:"active_ind" default:""`
	Activity_obs_no          *int    `json:"activity_obs_no" default:""`
	Analysis_id              *string `json:"analysis_id" default:""`
	Application_id           *string `json:"application_id" default:""`
	Applic_attachment_id     *string `json:"applic_attachment_id" default:""`
	Area_id                  *string `json:"area_id" default:""`
	Area_type                *string `json:"area_type" default:""`
	Authority_id             *string `json:"authority_id" default:""`
	Ba_licensee_ba_id        *string `json:"ba_licensee_ba_id" default:""`
	Ba_license_id            *string `json:"ba_license_id" default:""`
	Bin_grid_id              *string `json:"bin_grid_id" default:""`
	Bin_grid_source          *string `json:"bin_grid_source" default:""`
	Business_associate_id    *string `json:"business_associate_id" default:""`
	Catalogue_equip_id       *string `json:"catalogue_equip_id" default:""`
	Column_name              *string `json:"column_name" default:""`
	Consent_id               *string `json:"consent_id" default:""`
	Consult_id               *string `json:"consult_id" default:""`
	Content_type             *string `json:"content_type" default:""`
	Contest_id               *string `json:"contest_id" default:""`
	Contract_id              *string `json:"contract_id" default:""`
	Discussion_id            *string `json:"discussion_id" default:""`
	Drill_report_id          *string `json:"drill_report_id" default:""`
	Ecozone_id               *string `json:"ecozone_id" default:""`
	Ecozone_set_id           *string `json:"ecozone_set_id" default:""`
	Effective_date           *string `json:"effective_date" default:""`
	Entitlement_id           *string `json:"entitlement_id" default:""`
	Equipment_id             *string `json:"equipment_id" default:""`
	Expiry_date              *string `json:"expiry_date" default:""`
	Facility_id              *string `json:"facility_id" default:""`
	Facility_license_id      *string `json:"facility_license_id" default:""`
	Facility_type            *string `json:"facility_type" default:""`
	Field_id                 *string `json:"field_id" default:""`
	Finance_id               *string `json:"finance_id" default:""`
	Fossil_desc_id           *string `json:"fossil_desc_id" default:""`
	Fossil_id                *string `json:"fossil_id" default:""`
	Hse_incident_id          *string `json:"hse_incident_id" default:""`
	Instrument_id            *string `json:"instrument_id" default:""`
	Interest_set_id          *string `json:"interest_set_id" default:""`
	Interest_set_seq_no      *int    `json:"interest_set_seq_no" default:""`
	Interp_id                *string `json:"interp_id" default:""`
	Jurisdiction             *string `json:"jurisdiction" default:""`
	Land_request_id          *string `json:"land_request_id" default:""`
	Land_right_id            *string `json:"land_right_id" default:""`
	Land_right_subtype       *string `json:"land_right_subtype" default:""`
	Land_sale_number         *string `json:"land_sale_number" default:""`
	Land_sale_offering_id    *string `json:"land_sale_offering_id" default:""`
	Lithology_log_id         *string `json:"lithology_log_id" default:""`
	Lith_log_source          *string `json:"lith_log_source" default:""`
	Lith_sample_id           *string `json:"lith_sample_id" default:""`
	Notification_id          *string `json:"notification_id" default:""`
	Obligation_id            *string `json:"obligation_id" default:""`
	Obligation_seq_no        *int    `json:"obligation_seq_no" default:""`
	Organization_id          *string `json:"organization_id" default:""`
	Organization_seq_no      *int    `json:"organization_seq_no" default:""`
	Paleo_summary_id         *string `json:"paleo_summary_id" default:""`
	Pden_id                  *string `json:"pden_id" default:""`
	Pden_source              *string `json:"pden_source" default:""`
	Pden_subtype             *string `json:"pden_subtype" default:""`
	Physical_item_custody_id *string `json:"physical_item_custody_id" default:""`
	Physical_item_id         *string `json:"physical_item_id" default:""`
	Platform_id              *string `json:"platform_id" default:""`
	Platform_sf_subtype      *string `json:"platform_sf_subtype" default:""`
	Pool_id                  *string `json:"pool_id" default:""`
	Ppdm_audit_row_guid      *string `json:"ppdm_audit_row_guid" default:""`
	Ppdm_audit_seq_no        *int    `json:"ppdm_audit_seq_no" default:""`
	Ppdm_guid                *string `json:"ppdm_guid" default:""`
	Product_type             *string `json:"product_type" default:""`
	Prod_string_id           *string `json:"prod_string_id" default:""`
	Prod_string_source       *string `json:"prod_string_source" default:""`
	Project_id               *string `json:"project_id" default:""`
	Project_step_id          *string `json:"project_step_id" default:""`
	Rate_schedule_id         *string `json:"rate_schedule_id" default:""`
	Remark                   *string `json:"remark" default:""`
	Resent_id                *string `json:"resent_id" default:""`
	Reserve_class_id         *string `json:"reserve_class_id" default:""`
	Reserve_product          *string `json:"reserve_product" default:""`
	Reserve_revision_id      *string `json:"reserve_revision_id" default:""`
	Reserve_revision_obs_no  *int    `json:"reserve_revision_obs_no" default:""`
	Reserve_summary_id       *string `json:"reserve_summary_id" default:""`
	Reserve_summary_obs_no   *int    `json:"reserve_summary_obs_no" default:""`
	Restriction_id           *string `json:"restriction_id" default:""`
	Restriction_version      *int    `json:"restriction_version" default:""`
	Sample_anal_source       *string `json:"sample_anal_source" default:""`
	Seis_license_id          *string `json:"seis_license_id" default:""`
	Seis_patch_id            *string `json:"seis_patch_id" default:""`
	Seis_set_id              *string `json:"seis_set_id" default:""`
	Seis_set_subtype         *string `json:"seis_set_subtype" default:""`
	Source                   *string `json:"source" default:""`
	Source_document_id       *string `json:"source_document_id" default:""`
	Spatial_description_id   *string `json:"spatial_description_id" default:""`
	Spatial_obs_no           *int    `json:"spatial_obs_no" default:""`
	Strat_column_id          *string `json:"strat_column_id" default:""`
	Strat_column_source      *string `json:"strat_column_source" default:""`
	Strat_field_station_id   *string `json:"strat_field_station_id" default:""`
	Strat_name_set_id        *string `json:"strat_name_set_id" default:""`
	Strat_unit_id            *string `json:"strat_unit_id" default:""`
	Support_facility_id      *string `json:"support_facility_id" default:""`
	Support_facility_subtype *string `json:"support_facility_subtype" default:""`
	System_id                *string `json:"system_id" default:""`
	Table_name               *string `json:"table_name" default:""`
	Uwi                      *string `json:"uwi" default:""`
	Velocity_volume_id       *string `json:"velocity_volume_id" default:""`
	Wc_core_id               *string `json:"wc_core_id" default:""`
	Wc_source                *string `json:"wc_source" default:""`
	Wc_uwi                   *string `json:"wc_uwi" default:""`
	Wds_source               *string `json:"wds_source" default:""`
	Wds_survey_id            *string `json:"wds_survey_id" default:""`
	Wds_uwi                  *string `json:"wds_uwi" default:""`
	Well_activity_source     *string `json:"well_activity_source" default:""`
	Well_license_id          *string `json:"well_license_id" default:""`
	Well_license_source      *string `json:"well_license_source" default:""`
	Well_log_curve_id        *string `json:"well_log_curve_id" default:""`
	Well_log_id              *string `json:"well_log_id" default:""`
	Well_log_source          *string `json:"well_log_source" default:""`
	Wl_dgtz_curve_id         *string `json:"wl_dgtz_curve_id" default:""`
	Work_order_id            *string `json:"work_order_id" default:""`
	Wtf_fluid_type           *string `json:"wtf_fluid_type" default:""`
	Wtf_period_obs_no        *int    `json:"wtf_period_obs_no" default:""`
	Wtf_period_type          *string `json:"wtf_period_type" default:""`
	Wtf_run_num              *string `json:"wtf_run_num" default:""`
	Wtf_source               *string `json:"wtf_source" default:""`
	Wtf_test_num             *string `json:"wtf_test_num" default:""`
	Wtf_test_type            *string `json:"wtf_test_type" default:""`
	Wtp_period_obs_no        *int    `json:"wtp_period_obs_no" default:""`
	Wtp_period_type          *string `json:"wtp_period_type" default:""`
	Wtp_run_num              *string `json:"wtp_run_num" default:""`
	Wtp_source               *string `json:"wtp_source" default:""`
	Wtp_test_num             *string `json:"wtp_test_num" default:""`
	Wtp_test_type            *string `json:"wtp_test_type" default:""`
	Row_changed_by           *string `json:"row_changed_by" default:""`
	Row_changed_date         *string `json:"row_changed_date" default:""`
	Row_created_by           *string `json:"row_created_by" default:""`
	Row_created_date         *string `json:"row_created_date" default:""`
	Row_effective_date       *string `json:"row_effective_date" default:""`
	Row_expiry_date          *string `json:"row_expiry_date" default:""`
	Row_quality              *string `json:"row_quality" default:""`
}
