package dto

type Sample struct {
	Sample_id               string   `json:"sample_id" default:"source"`
	Active_ind              *string  `json:"active_ind" default:""`
	Base_md                 *float64 `json:"base_md" default:""`
	Base_md_ouom            *string  `json:"base_md_ouom" default:""`
	Base_strat_unit_id      *string  `json:"base_strat_unit_id" default:""`
	Collected_by_ba_id      *string  `json:"collected_by_ba_id" default:""`
	Collected_date          *string  `json:"collected_date" default:""`
	Collected_equip_id      *string  `json:"collected_equip_id" default:""`
	Collected_for_ba_id     *string  `json:"collected_for_ba_id" default:""`
	Collected_time          *string  `json:"collected_time" default:""`
	Collection_phase_type   *string  `json:"collection_phase_type" default:""`
	Collection_press        *float64 `json:"collection_press" default:""`
	Collection_press_ouom   *string  `json:"collection_press_ouom" default:""`
	Collection_temp         *float64 `json:"collection_temp" default:""`
	Collection_temp_ouom    *string  `json:"collection_temp_ouom" default:""`
	Collection_test_type    *string  `json:"collection_test_type" default:""`
	Collection_type         *string  `json:"collection_type" default:""`
	Composite_sample_count  *int     `json:"composite_sample_count" default:""`
	Composite_sample_ind    *string  `json:"composite_sample_ind" default:""`
	Condensed_section_ind   *string  `json:"condensed_section_ind" default:""`
	Current_length          *float64 `json:"current_length" default:""`
	Current_length_ouom     *string  `json:"current_length_ouom" default:""`
	Current_length_percent  *float64 `json:"current_length_percent" default:""`
	Current_volume          *float64 `json:"current_volume" default:""`
	Current_volume_ouom     *string  `json:"current_volume_ouom" default:""`
	Current_volume_percent  *float64 `json:"current_volume_percent" default:""`
	Current_weight          *float64 `json:"current_weight" default:""`
	Current_weight_ouom     *string  `json:"current_weight_ouom" default:""`
	Current_weight_percent  *float64 `json:"current_weight_percent" default:""`
	Cylinder_press          *float64 `json:"cylinder_press" default:""`
	Cylinder_press_ouom     *string  `json:"cylinder_press_ouom" default:""`
	Cylinder_temp           *float64 `json:"cylinder_temp" default:""`
	Cylinder_temp_ouom      *string  `json:"cylinder_temp_ouom" default:""`
	Destroyed_date          *string  `json:"destroyed_date" default:""`
	Effective_date          *string  `json:"effective_date" default:""`
	Expiry_date             *string  `json:"expiry_date" default:""`
	Initial_length          *float64 `json:"initial_length" default:""`
	Initial_length_ouom     *string  `json:"initial_length_ouom" default:""`
	Initial_length_percent  *float64 `json:"initial_length_percent" default:""`
	Initial_volume          *float64 `json:"initial_volume" default:""`
	Initial_volume_ouom     *string  `json:"initial_volume_ouom" default:""`
	Initial_volume_percent  *float64 `json:"initial_volume_percent" default:""`
	Initial_weight          *float64 `json:"initial_weight" default:""`
	Initial_weight_ouom     *string  `json:"initial_weight_ouom" default:""`
	Initial_weight_percent  *float64 `json:"initial_weight_percent" default:""`
	Interval_percent        *float64 `json:"interval_percent" default:""`
	Oil_stained_ind         *string  `json:"oil_stained_ind" default:""`
	Physical_item_id        *string  `json:"physical_item_id" default:""`
	Ppdm_guid               *string  `json:"ppdm_guid" default:""`
	Remark                  *string  `json:"remark" default:""`
	Reported_mud_desc       *string  `json:"reported_mud_desc" default:""`
	Reported_res_press      *float64 `json:"reported_res_press" default:""`
	Reported_res_press_ouom *string  `json:"reported_res_press_ouom" default:""`
	Sample_count            *int     `json:"sample_count" default:""`
	Sample_diameter         *float64 `json:"sample_diameter" default:""`
	Sample_diameter_ouom    *string  `json:"sample_diameter_ouom" default:""`
	Sample_interval         *float64 `json:"sample_interval" default:""`
	Sample_interval_ouom    *string  `json:"sample_interval_ouom" default:""`
	Sample_quality          *string  `json:"sample_quality" default:""`
	Sample_quality_desc     *string  `json:"sample_quality_desc" default:""`
	Sample_ref_num          *string  `json:"sample_ref_num" default:""`
	Sample_shape_type       *string  `json:"sample_shape_type" default:""`
	Sample_type             *string  `json:"sample_type" default:""`
	Sample_width            *float64 `json:"sample_width" default:""`
	Sample_width_ouom       *string  `json:"sample_width_ouom" default:""`
	Separator_press         *float64 `json:"separator_press" default:""`
	Separator_press_ouom    *string  `json:"separator_press_ouom" default:""`
	Separator_temp          *float64 `json:"separator_temp" default:""`
	Separator_temp_ouom     *string  `json:"separator_temp_ouom" default:""`
	Source                  *string  `json:"source" default:""`
	Stored_equip_id         *string  `json:"stored_equip_id" default:""`
	Stored_phase_type       *string  `json:"stored_phase_type" default:""`
	Strat_name_set_id       *string  `json:"strat_name_set_id" default:""`
	Sub_sample_ind          *string  `json:"sub_sample_ind" default:""`
	Top_md                  *float64 `json:"top_md" default:""`
	Top_md_ouom             *string  `json:"top_md_ouom" default:""`
	Top_strat_unit_id       *string  `json:"top_strat_unit_id" default:""`
	Total_length            *float64 `json:"total_length" default:""`
	Total_length_ouom       *string  `json:"total_length_ouom" default:""`
	Total_volume            *float64 `json:"total_volume" default:""`
	Total_volume_ouom       *string  `json:"total_volume_ouom" default:""`
	Total_weight            *float64 `json:"total_weight" default:""`
	Total_weight_ouom       *string  `json:"total_weight_ouom" default:""`
	Well_datum_type         *string  `json:"well_datum_type" default:""`
	Row_changed_by          *string  `json:"row_changed_by" default:""`
	Row_changed_date        *string  `json:"row_changed_date" default:""`
	Row_created_by          *string  `json:"row_created_by" default:""`
	Row_created_date        *string  `json:"row_created_date" default:""`
	Row_effective_date      *string  `json:"row_effective_date" default:""`
	Row_expiry_date         *string  `json:"row_expiry_date" default:""`
	Row_quality             *string  `json:"row_quality" default:""`
}
