package dto

type Seis_acqtn_design struct {
	Acqtn_design_id              string   `json:"acqtn_design_id" default:"source"`
	Acqtn_completed_date         *string  `json:"acqtn_completed_date" default:""`
	Acqtn_completed_date_desc    *string  `json:"acqtn_completed_date_desc" default:""`
	Acqtn_dimension              *string  `json:"acqtn_dimension" default:""`
	Acqtn_direction              *string  `json:"acqtn_direction" default:""`
	Acqtn_inline_bin_size        *float64 `json:"acqtn_inline_bin_size" default:""`
	Acqtn_inline_bin_size_ouom   *string  `json:"acqtn_inline_bin_size_ouom" default:""`
	Acqtn_remark                 *string  `json:"acqtn_remark" default:""`
	Acqtn_shotpt_interval        *float64 `json:"acqtn_shotpt_interval" default:""`
	Acqtn_shotpt_interval_ouom   *string  `json:"acqtn_shotpt_interval_ouom" default:""`
	Acqtn_shot_line_spacing      *float64 `json:"acqtn_shot_line_spacing" default:""`
	Acqtn_shot_line_spacing_ouom *string  `json:"acqtn_shot_line_spacing_ouom" default:""`
	Acqtn_shot_time_intvl        *float64 `json:"acqtn_shot_time_intvl" default:""`
	Acqtn_shot_time_intvl_ouom   *string  `json:"acqtn_shot_time_intvl_ouom" default:""`
	Acqtn_start_date             *string  `json:"acqtn_start_date" default:""`
	Acqtn_start_date_desc        *string  `json:"acqtn_start_date_desc" default:""`
	Acqtn_xline_bin_size         *float64 `json:"acqtn_xline_bin_size" default:""`
	Acqtn_xline_bin_size_ouom    *string  `json:"acqtn_xline_bin_size_ouom" default:""`
	Active_ind                   *string  `json:"active_ind" default:""`
	Actual_ind                   *string  `json:"actual_ind" default:""`
	Cdp_coverage                 *float64 `json:"cdp_coverage" default:""`
	Effective_date               *string  `json:"effective_date" default:""`
	Energy_charge_size           *float64 `json:"energy_charge_size" default:""`
	Energy_charge_size_ouom      *string  `json:"energy_charge_size_ouom" default:""`
	Energy_oprg_psr              *float64 `json:"energy_oprg_psr" default:""`
	Energy_oprg_psr_ouom         *string  `json:"energy_oprg_psr_ouom" default:""`
	Energy_oprg_volume           *float64 `json:"energy_oprg_volume" default:""`
	Energy_oprg_volume_ouom      *string  `json:"energy_oprg_volume_ouom" default:""`
	Energy_shot_depth            *float64 `json:"energy_shot_depth" default:""`
	Energy_shot_depth_ouom       *string  `json:"energy_shot_depth_ouom" default:""`
	Energy_src_array_spc         *float64 `json:"energy_src_array_spc" default:""`
	Energy_src_array_spc_ouom    *string  `json:"energy_src_array_spc_ouom" default:""`
	Energy_src_array_type        *string  `json:"energy_src_array_type" default:""`
	Energy_src_make              *string  `json:"energy_src_make" default:""`
	Energy_src_per_shot          *float64 `json:"energy_src_per_shot" default:""`
	Energy_sweep_duration        *float64 `json:"energy_sweep_duration" default:""`
	Energy_sweep_duration_ouom   *string  `json:"energy_sweep_duration_ouom" default:""`
	Energy_sweep_end_freq        *float64 `json:"energy_sweep_end_freq" default:""`
	Energy_sweep_freq_ouom       *string  `json:"energy_sweep_freq_ouom" default:""`
	Energy_sweep_mvup_dist       *float64 `json:"energy_sweep_mvup_dist" default:""`
	Energy_sweep_mvup_dist_ouom  *string  `json:"energy_sweep_mvup_dist_ouom" default:""`
	Energy_sweep_no              *int     `json:"energy_sweep_no" default:""`
	Energy_sweep_st_freq         *float64 `json:"energy_sweep_st_freq" default:""`
	Energy_sweep_taper           *float64 `json:"energy_sweep_taper" default:""`
	Energy_sweep_taper_ouom      *string  `json:"energy_sweep_taper_ouom" default:""`
	Energy_sweep_type            *string  `json:"energy_sweep_type" default:""`
	Energy_type                  *string  `json:"energy_type" default:""`
	Environment                  *string  `json:"environment" default:""`
	Expiry_date                  *string  `json:"expiry_date" default:""`
	Monitor_depth                *float64 `json:"monitor_depth" default:""`
	Monitor_depth_ouom           *string  `json:"monitor_depth_ouom" default:""`
	Nominal_ind                  *string  `json:"nominal_ind" default:""`
	Ppdm_guid                    *string  `json:"ppdm_guid" default:""`
	Rcrd_channel_count           *int     `json:"rcrd_channel_count" default:""`
	Rcrd_format_type             *string  `json:"rcrd_format_type" default:""`
	Rcrd_gain_mode               *string  `json:"rcrd_gain_mode" default:""`
	Rcrd_hf_freq                 *float64 `json:"rcrd_hf_freq" default:""`
	Rcrd_hf_slope                *float64 `json:"rcrd_hf_slope" default:""`
	Rcrd_lf_freq                 *float64 `json:"rcrd_lf_freq" default:""`
	Rcrd_lf_slope                *float64 `json:"rcrd_lf_slope" default:""`
	Rcrd_make                    *string  `json:"rcrd_make" default:""`
	Rcrd_near_surf_corr          *string  `json:"rcrd_near_surf_corr" default:""`
	Rcrd_near_surf_corr_ouom     *string  `json:"rcrd_near_surf_corr_ouom" default:""`
	Rcrd_nf_freq                 *float64 `json:"rcrd_nf_freq" default:""`
	Rcrd_nf_ind                  *string  `json:"rcrd_nf_ind" default:""`
	Rcrd_polarity                *string  `json:"rcrd_polarity" default:""`
	Rcrd_rec_length              *float64 `json:"rcrd_rec_length" default:""`
	Rcrd_rec_length_ouom         *string  `json:"rcrd_rec_length_ouom" default:""`
	Rcrd_sample_rate             *float64 `json:"rcrd_sample_rate" default:""`
	Rcrd_sample_rate_ouom        *string  `json:"rcrd_sample_rate_ouom" default:""`
	Rcvr_line_spacing            *float64 `json:"rcvr_line_spacing" default:""`
	Rcvr_line_spacing_ouom       *string  `json:"rcvr_line_spacing_ouom" default:""`
	Remark                       *string  `json:"remark" default:""`
	Rep_water_acoustic_vel       *float64 `json:"rep_water_acoustic_vel" default:""`
	Rep_water_acoustic_vel_ouom  *string  `json:"rep_water_acoustic_vel_ouom" default:""`
	Shot_by                      *string  `json:"shot_by" default:""`
	Shot_for                     *string  `json:"shot_for" default:""`
	Source                       *string  `json:"source" default:""`
	Well_src_azimuth             *float64 `json:"well_src_azimuth" default:""`
	Well_src_azimuth_north       *string  `json:"well_src_azimuth_north" default:""`
	Well_src_offset              *float64 `json:"well_src_offset" default:""`
	Well_src_offset_ouom         *string  `json:"well_src_offset_ouom" default:""`
	Row_changed_by               *string  `json:"row_changed_by" default:""`
	Row_changed_date             *string  `json:"row_changed_date" default:""`
	Row_created_by               *string  `json:"row_created_by" default:""`
	Row_created_date             *string  `json:"row_created_date" default:""`
	Row_effective_date           *string  `json:"row_effective_date" default:""`
	Row_expiry_date              *string  `json:"row_expiry_date" default:""`
	Row_quality                  *string  `json:"row_quality" default:""`
}
