package dto

type Seis_sp_survey struct {
	Seis_set_subtype      string   `json:"seis_set_subtype" default:"source"`
	Seis_set_id           string   `json:"seis_set_id" default:"source"`
	Seis_point_id         string   `json:"seis_point_id" default:"source"`
	Seis_sp_survey_obs_no int      `json:"seis_sp_survey_obs_no" default:"1"`
	Active_ind            *string  `json:"active_ind" default:""`
	Azimuth               *float64 `json:"azimuth" default:""`
	Azimuth_ouom          *string  `json:"azimuth_ouom" default:""`
	Effective_date        *string  `json:"effective_date" default:""`
	Ew_direction          *string  `json:"ew_direction" default:""`
	Ew_distance           *float64 `json:"ew_distance" default:""`
	Ew_distance_ouom      *string  `json:"ew_distance_ouom" default:""`
	Ew_start_line         *string  `json:"ew_start_line" default:""`
	Expiry_date           *string  `json:"expiry_date" default:""`
	Location_type         *string  `json:"location_type" default:""`
	Monument_id           *string  `json:"monument_id" default:""`
	Monument_sf_subtype   *string  `json:"monument_sf_subtype" default:""`
	North_type            *string  `json:"north_type" default:""`
	Ns_direction          *string  `json:"ns_direction" default:""`
	Ns_distance           *float64 `json:"ns_distance" default:""`
	Ns_distance_ouom      *string  `json:"ns_distance_ouom" default:""`
	Ns_start_line         *string  `json:"ns_start_line" default:""`
	Orientation           *string  `json:"orientation" default:""`
	Point_offset          *float64 `json:"point_offset" default:""`
	Point_offset_ouom     *string  `json:"point_offset_ouom" default:""`
	Ppdm_guid             *string  `json:"ppdm_guid" default:""`
	Reference_loc         *string  `json:"reference_loc" default:""`
	Remark                *string  `json:"remark" default:""`
	Source                *string  `json:"source" default:""`
	Surface_loc           *string  `json:"surface_loc" default:""`
	Well_node_id          *string  `json:"well_node_id" default:""`
	Row_changed_by        *string  `json:"row_changed_by" default:""`
	Row_changed_date      *string  `json:"row_changed_date" default:""`
	Row_created_by        *string  `json:"row_created_by" default:""`
	Row_created_date      *string  `json:"row_created_date" default:""`
	Row_effective_date    *string  `json:"row_effective_date" default:""`
	Row_expiry_date       *string  `json:"row_expiry_date" default:""`
	Row_quality           *string  `json:"row_quality" default:""`
}
