package dto

type Sf_component struct {
	Sf_subtype             string  `json:"sf_subtype" default:"source"`
	Support_facility_id    string  `json:"support_facility_id" default:"source"`
	Use_id                 string  `json:"use_id" default:"source"`
	Component_obs_no       int     `json:"component_obs_no" default:"1"`
	Active_ind             *string `json:"active_ind" default:""`
	Area_id                *string `json:"area_id" default:""`
	Area_type              *string `json:"area_type" default:""`
	Ba_licensee_ba_id      *string `json:"ba_licensee_ba_id" default:""`
	Ba_license_id          *string `json:"ba_license_id" default:""`
	Business_associate_id  *string `json:"business_associate_id" default:""`
	Consent_id             *string `json:"consent_id" default:""`
	Consult_id             *string `json:"consult_id" default:""`
	Contest_id             *string `json:"contest_id" default:""`
	Contract_id            *string `json:"contract_id" default:""`
	Effective_date         *string `json:"effective_date" default:""`
	Expiry_date            *string `json:"expiry_date" default:""`
	Facility_id            *string `json:"facility_id" default:""`
	Facility_license_id    *string `json:"facility_license_id" default:""`
	Facility_type          *string `json:"facility_type" default:""`
	Field_id               *string `json:"field_id" default:""`
	Field_station_id       *string `json:"field_station_id" default:""`
	Finance_id             *string `json:"finance_id" default:""`
	Hse_incident_id        *string `json:"hse_incident_id" default:""`
	Information_item_id    *string `json:"information_item_id" default:""`
	Info_item_subtype      *string `json:"info_item_subtype" default:""`
	Instrument_id          *string `json:"instrument_id" default:""`
	Interest_set_id        *string `json:"interest_set_id" default:""`
	Interest_set_seq_no    *int    `json:"interest_set_seq_no" default:""`
	Land_right_id          *string `json:"land_right_id" default:""`
	Land_right_subtype     *string `json:"land_right_subtype" default:""`
	Land_sale_jurisdiction *string `json:"land_sale_jurisdiction" default:""`
	Land_sale_number       *string `json:"land_sale_number" default:""`
	Obligation_id          *string `json:"obligation_id" default:""`
	Obligation_seq_no      *int    `json:"obligation_seq_no" default:""`
	Pden_id                *string `json:"pden_id" default:""`
	Pden_source            *string `json:"pden_source" default:""`
	Pden_subtype           *string `json:"pden_subtype" default:""`
	Pool_id                *string `json:"pool_id" default:""`
	Ppdm_guid              *string `json:"ppdm_guid" default:""`
	Ppdm_system_id         *string `json:"ppdm_system_id" default:""`
	Ppdm_table_name        *string `json:"ppdm_table_name" default:""`
	Prod_string_id         *string `json:"prod_string_id" default:""`
	Prod_string_source     *string `json:"prod_string_source" default:""`
	Project_id             *string `json:"project_id" default:""`
	Pr_str_form_obs_no     *int    `json:"pr_str_form_obs_no" default:""`
	Rate_schedule_id       *string `json:"rate_schedule_id" default:""`
	Remark                 *string `json:"remark" default:""`
	Seis_license_id        *string `json:"seis_license_id" default:""`
	Seis_set_id            *string `json:"seis_set_id" default:""`
	Seis_set_subtype       *string `json:"seis_set_subtype" default:""`
	Sf_component_type      *string `json:"sf_component_type" default:""`
	Source                 *string `json:"source" default:""`
	Source_document_id     *string `json:"source_document_id" default:""`
	Sw_application_id      *string `json:"sw_application_id" default:""`
	Uwi                    *string `json:"uwi" default:""`
	Well_license_id        *string `json:"well_license_id" default:""`
	Well_license_source    *string `json:"well_license_source" default:""`
	Well_set_id            *string `json:"well_set_id" default:""`
	Work_order_id          *string `json:"work_order_id" default:""`
	Row_changed_by         *string `json:"row_changed_by" default:""`
	Row_changed_date       *string `json:"row_changed_date" default:""`
	Row_created_by         *string `json:"row_created_by" default:""`
	Row_created_date       *string `json:"row_created_date" default:""`
	Row_effective_date     *string `json:"row_effective_date" default:""`
	Row_expiry_date        *string `json:"row_expiry_date" default:""`
	Row_quality            *string `json:"row_quality" default:""`
}
