package dto

type Sf_rig struct {
	Sf_subtype                 string   `json:"sf_subtype" default:"source"`
	Rig_id                     string   `json:"rig_id" default:"source"`
	Active_ind                 *string  `json:"active_ind" default:""`
	Boiler_manufacturer        *string  `json:"boiler_manufacturer" default:""`
	Boiler_power               *float64 `json:"boiler_power" default:""`
	Boiler_power_ouom          *string  `json:"boiler_power_ouom" default:""`
	Choke_manifold_press       *float64 `json:"choke_manifold_press" default:""`
	Choke_manifold_press_ouom  *string  `json:"choke_manifold_press_ouom" default:""`
	Choke_manifold_size        *float64 `json:"choke_manifold_size" default:""`
	Choke_manifold_size_ouom   *string  `json:"choke_manifold_size_ouom" default:""`
	Clear_work_height          *float64 `json:"clear_work_height" default:""`
	Clear_work_height_ouom     *string  `json:"clear_work_height_ouom" default:""`
	Commission_date            *string  `json:"commission_date" default:""`
	Decommission_date          *string  `json:"decommission_date" default:""`
	Desander_type              *string  `json:"desander_type" default:""`
	Desilter_type              *string  `json:"desilter_type" default:""`
	Drawworks_type             *string  `json:"drawworks_type" default:""`
	Effective_date             *string  `json:"effective_date" default:""`
	Expiry_date                *string  `json:"expiry_date" default:""`
	Hookblock_rating           *float64 `json:"hookblock_rating" default:""`
	Hookblock_rating_ouom      *string  `json:"hookblock_rating_ouom" default:""`
	Hookblock_type             *string  `json:"hookblock_type" default:""`
	Hook_load_capacity         *float64 `json:"hook_load_capacity" default:""`
	Hook_load_capacity_ouom    *string  `json:"hook_load_capacity_ouom" default:""`
	Kb_ground_dist             *float64 `json:"kb_ground_dist" default:""`
	Kb_ground_dist_ouom        *string  `json:"kb_ground_dist_ouom" default:""`
	Mast_height                *float64 `json:"mast_height" default:""`
	Mast_height_ouom           *string  `json:"mast_height_ouom" default:""`
	Mast_type                  *string  `json:"mast_type" default:""`
	Max_depth                  *float64 `json:"max_depth" default:""`
	Max_depth_ouom             *string  `json:"max_depth_ouom" default:""`
	Mud_tank_count             *int     `json:"mud_tank_count" default:""`
	Mud_tank_size              *float64 `json:"mud_tank_size" default:""`
	Mud_tank_size_ouom         *string  `json:"mud_tank_size_ouom" default:""`
	Operator_ba_id             *string  `json:"operator_ba_id" default:""`
	Owner_ba_id                *string  `json:"owner_ba_id" default:""`
	Ppdm_guid                  *string  `json:"ppdm_guid" default:""`
	Remark                     *string  `json:"remark" default:""`
	Rig_category               *string  `json:"rig_category" default:""`
	Rig_class                  *string  `json:"rig_class" default:""`
	Rig_code                   *string  `json:"rig_code" default:""`
	Rig_name                   *string  `json:"rig_name" default:""`
	Rig_type                   *string  `json:"rig_type" default:""`
	Rotary_table_cap           *float64 `json:"rotary_table_cap" default:""`
	Rotary_table_cap_ouom      *string  `json:"rotary_table_cap_ouom" default:""`
	Rotary_table_size          *float64 `json:"rotary_table_size" default:""`
	Rotary_table_size_ouom     *string  `json:"rotary_table_size_ouom" default:""`
	Source                     *string  `json:"source" default:""`
	Substructure_type          *string  `json:"substructure_type" default:""`
	Substruct_casing_cap       *float64 `json:"substruct_casing_cap" default:""`
	Substruct_casing_cap_ouom  *string  `json:"substruct_casing_cap_ouom" default:""`
	Substruct_setback_cap      *float64 `json:"substruct_setback_cap" default:""`
	Substruct_setback_cap_ouom *string  `json:"substruct_setback_cap_ouom" default:""`
	Swivel_rating              *float64 `json:"swivel_rating" default:""`
	Swivel_rating_ouom         *string  `json:"swivel_rating_ouom" default:""`
	Swivel_type                *string  `json:"swivel_type" default:""`
	Top_drive_model            *string  `json:"top_drive_model" default:""`
	Top_drive_rating           *float64 `json:"top_drive_rating" default:""`
	Top_drive_rating_ouom      *string  `json:"top_drive_rating_ouom" default:""`
	Water_depth_capacity       *float64 `json:"water_depth_capacity" default:""`
	Water_depth_datum          *string  `json:"water_depth_datum" default:""`
	Water_depth_ouom           *string  `json:"water_depth_ouom" default:""`
	Working_pressure           *float64 `json:"working_pressure" default:""`
	Working_pressure_ouom      *string  `json:"working_pressure_ouom" default:""`
	Row_changed_by             *string  `json:"row_changed_by" default:""`
	Row_changed_date           *string  `json:"row_changed_date" default:""`
	Row_created_by             *string  `json:"row_created_by" default:""`
	Row_created_date           *string  `json:"row_created_date" default:""`
	Row_effective_date         *string  `json:"row_effective_date" default:""`
	Row_expiry_date            *string  `json:"row_expiry_date" default:""`
	Row_quality                *string  `json:"row_quality" default:""`
}
