package dto

type Sf_waste_disposal struct {
	Sf_subtype             string   `json:"sf_subtype" default:"source"`
	Waste_facility_id      string   `json:"waste_facility_id" default:"source"`
	Waste_id               string   `json:"waste_id" default:"source"`
	Active_ind             *string  `json:"active_ind" default:""`
	Adjust_reason          *string  `json:"adjust_reason" default:""`
	Amount_adjustment      *float64 `json:"amount_adjustment" default:""`
	Amount_adjustment_ouom *string  `json:"amount_adjustment_ouom" default:""`
	Amount_adjustment_uom  *string  `json:"amount_adjustment_uom" default:""`
	Amount_received        *float64 `json:"amount_received" default:""`
	Amount_received_ouom   *string  `json:"amount_received_ouom" default:""`
	Amount_received_uom    *string  `json:"amount_received_uom" default:""`
	Amount_shipped         *float64 `json:"amount_shipped" default:""`
	Amount_shipped_ouom    *string  `json:"amount_shipped_ouom" default:""`
	Amount_shipped_uom     *string  `json:"amount_shipped_uom" default:""`
	Contract_id            *string  `json:"contract_id" default:""`
	Description            *string  `json:"description" default:""`
	Effective_date         *string  `json:"effective_date" default:""`
	End_date               *string  `json:"end_date" default:""`
	Expiry_date            *string  `json:"expiry_date" default:""`
	Operator_ba_id         *string  `json:"operator_ba_id" default:""`
	Origin_facility_id     *string  `json:"origin_facility_id" default:""`
	Origin_facility_type   *string  `json:"origin_facility_type" default:""`
	Origin_hse_incident_id *string  `json:"origin_hse_incident_id" default:""`
	Origin_uwi             *string  `json:"origin_uwi" default:""`
	Ppdm_guid              *string  `json:"ppdm_guid" default:""`
	Provision_id           *string  `json:"provision_id" default:""`
	Rate_schedule_id       *string  `json:"rate_schedule_id" default:""`
	Receiver_ba_id         *string  `json:"receiver_ba_id" default:""`
	Remark                 *string  `json:"remark" default:""`
	Reporting_uom          *string  `json:"reporting_uom" default:""`
	Service_quality        *string  `json:"service_quality" default:""`
	Service_type           *string  `json:"service_type" default:""`
	Shipped_date           *string  `json:"shipped_date" default:""`
	Source                 *string  `json:"source" default:""`
	Transport_ba_id        *string  `json:"transport_ba_id" default:""`
	Waste_handling_method  *string  `json:"waste_handling_method" default:""`
	Waste_hazard           *string  `json:"waste_hazard" default:""`
	Waste_material         *string  `json:"waste_material" default:""`
	Waste_origin           *string  `json:"waste_origin" default:""`
	Row_changed_by         *string  `json:"row_changed_by" default:""`
	Row_changed_date       *string  `json:"row_changed_date" default:""`
	Row_created_by         *string  `json:"row_created_by" default:""`
	Row_created_date       *string  `json:"row_created_date" default:""`
	Row_effective_date     *string  `json:"row_effective_date" default:""`
	Row_expiry_date        *string  `json:"row_expiry_date" default:""`
	Row_quality            *string  `json:"row_quality" default:""`
}
