package dto

type Sp_line_point_version struct {
	Line_id               string   `json:"line_id" default:"source"`
	Point_seq_no          int      `json:"point_seq_no" default:"1"`
	Source                string   `json:"source" default:"source"`
	Version_obs_no        int      `json:"version_obs_no" default:"1"`
	Acquisition_id        *string  `json:"acquisition_id" default:""`
	Active_ind            *string  `json:"active_ind" default:""`
	Area_id               *string  `json:"area_id" default:""`
	Area_type             *string  `json:"area_type" default:""`
	Easting               *float64 `json:"easting" default:""`
	Easting_ouom          *string  `json:"easting_ouom" default:""`
	Effective_date        *string  `json:"effective_date" default:""`
	Elev                  *float64 `json:"elev" default:""`
	Elev_ouom             *string  `json:"elev_ouom" default:""`
	Ew_direction          *string  `json:"ew_direction" default:""`
	Expiry_date           *string  `json:"expiry_date" default:""`
	Geog_coord_system_id  *string  `json:"geog_coord_system_id" default:""`
	Latitude              *float64 `json:"latitude" default:""`
	Legal_survey_type     *string  `json:"legal_survey_type" default:""`
	Local_coord_system_id *string  `json:"local_coord_system_id" default:""`
	Location_qualifier    *string  `json:"location_qualifier" default:""`
	Location_quality      *string  `json:"location_quality" default:""`
	Longitude             *float64 `json:"longitude" default:""`
	Map_coord_system_id   *string  `json:"map_coord_system_id" default:""`
	Md                    *float64 `json:"md" default:""`
	Md_ouom               *string  `json:"md_ouom" default:""`
	Monument_id           *string  `json:"monument_id" default:""`
	Monument_sf_subtype   *string  `json:"monument_sf_subtype" default:""`
	Node_position         *string  `json:"node_position" default:""`
	Northing              *float64 `json:"northing" default:""`
	Northing_ouom         *string  `json:"northing_ouom" default:""`
	North_type            *string  `json:"north_type" default:""`
	Ns_direction          *string  `json:"ns_direction" default:""`
	Original_ind          *string  `json:"original_ind" default:""`
	Original_ref_num      *string  `json:"original_ref_num" default:""`
	Polar_azimuth         *float64 `json:"polar_azimuth" default:""`
	Polar_offset          *float64 `json:"polar_offset" default:""`
	Polar_offset_ouom     *string  `json:"polar_offset_ouom" default:""`
	Ppdm_guid             *string  `json:"ppdm_guid" default:""`
	Preferred_ind         *string  `json:"preferred_ind" default:""`
	Remark                *string  `json:"remark" default:""`
	Reported_tvd          *float64 `json:"reported_tvd" default:""`
	Reported_tvd_ouom     *string  `json:"reported_tvd_ouom" default:""`
	Version_type          *string  `json:"version_type" default:""`
	X_coordinate          *float64 `json:"x_coordinate" default:""`
	X_offset              *float64 `json:"x_offset" default:""`
	X_offset_ouom         *string  `json:"x_offset_ouom" default:""`
	Y_coordinate          *float64 `json:"y_coordinate" default:""`
	Y_offset              *float64 `json:"y_offset" default:""`
	Y_offset_ouom         *string  `json:"y_offset_ouom" default:""`
	Row_changed_by        *string  `json:"row_changed_by" default:""`
	Row_changed_date      *string  `json:"row_changed_date" default:""`
	Row_created_by        *string  `json:"row_created_by" default:""`
	Row_created_date      *string  `json:"row_created_date" default:""`
	Row_effective_date    *string  `json:"row_effective_date" default:""`
	Row_expiry_date       *string  `json:"row_expiry_date" default:""`
	Row_quality           *string  `json:"row_quality" default:""`
}
