package dto

type Substance struct {
	Substance_id         string   `json:"substance_id" default:"source"`
	Active_ind           *string  `json:"active_ind" default:""`
	Api_gravity_max      *float64 `json:"api_gravity_max" default:""`
	Api_gravity_min      *float64 `json:"api_gravity_min" default:""`
	Atomic_mass          *float64 `json:"atomic_mass" default:""`
	Atomic_mass_number   *string  `json:"atomic_mass_number" default:""`
	Atomic_weight        *float64 `json:"atomic_weight" default:""`
	Carbon_count         *int     `json:"carbon_count" default:""`
	Carbon_count_max     *int     `json:"carbon_count_max" default:""`
	Carbon_count_min     *int     `json:"carbon_count_min" default:""`
	Composition_formula  *string  `json:"composition_formula" default:""`
	Conversion_quantity  *string  `json:"conversion_quantity" default:""`
	Effective_date       *string  `json:"effective_date" default:""`
	Expiry_date          *string  `json:"expiry_date" default:""`
	Ionic_charge         *float64 `json:"ionic_charge" default:""`
	Molecular_mass       *float64 `json:"molecular_mass" default:""`
	M_z_ion              *string  `json:"m_z_ion" default:""`
	Phase_type           *string  `json:"phase_type" default:""`
	Ph_value             *float64 `json:"ph_value" default:""`
	Ppdm_guid            *string  `json:"ppdm_guid" default:""`
	Preferred_ind        *string  `json:"preferred_ind" default:""`
	Preferred_long_name  *string  `json:"preferred_long_name" default:""`
	Preferred_short_name *string  `json:"preferred_short_name" default:""`
	Preferred_uom_id     *string  `json:"preferred_uom_id" default:""`
	Property_set_id      *string  `json:"property_set_id" default:""`
	Remark               *string  `json:"remark" default:""`
	Source               *string  `json:"source" default:""`
	Source_document_id   *string  `json:"source_document_id" default:""`
	Substance_definition *string  `json:"substance_definition" default:""`
	Valence_value        *float64 `json:"valence_value" default:""`
	Row_changed_by       *string  `json:"row_changed_by" default:""`
	Row_changed_date     *string  `json:"row_changed_date" default:""`
	Row_created_by       *string  `json:"row_created_by" default:""`
	Row_created_date     *string  `json:"row_created_date" default:""`
	Row_effective_date   *string  `json:"row_effective_date" default:""`
	Row_expiry_date      *string  `json:"row_expiry_date" default:""`
	Row_quality          *string  `json:"row_quality" default:""`
}
