package dto

type Well_core_sample_anal struct {
	Uwi                        string   `json:"uwi" default:"source"`
	Source                     string   `json:"source" default:"source"`
	Core_id                    string   `json:"core_id" default:"source"`
	Analysis_obs_no            int      `json:"analysis_obs_no" default:"1"`
	Sample_num                 string   `json:"sample_num" default:"source"`
	Sample_analysis_obs_no     int      `json:"sample_analysis_obs_no" default:"1"`
	Active_ind                 *string  `json:"active_ind" default:""`
	Analysis_source            *string  `json:"analysis_source" default:""`
	Bulk_density               *float64 `json:"bulk_density" default:""`
	Bulk_density_ouom          *string  `json:"bulk_density_ouom" default:""`
	Bulk_mass_oil_sat          *float64 `json:"bulk_mass_oil_sat" default:""`
	Bulk_mass_oil_sat_ouom     *string  `json:"bulk_mass_oil_sat_ouom" default:""`
	Bulk_mass_sand_sat         *float64 `json:"bulk_mass_sand_sat" default:""`
	Bulk_mass_sand_sat_ouom    *string  `json:"bulk_mass_sand_sat_ouom" default:""`
	Bulk_mass_water_sat        *float64 `json:"bulk_mass_water_sat" default:""`
	Bulk_mass_water_sat_ouom   *string  `json:"bulk_mass_water_sat_ouom" default:""`
	Bulk_volume_oil_sat        *float64 `json:"bulk_volume_oil_sat" default:""`
	Bulk_volume_water_sat      *float64 `json:"bulk_volume_water_sat" default:""`
	Confine_perm_pressure      *float64 `json:"confine_perm_pressure" default:""`
	Confine_perm_pressure_ouom *string  `json:"confine_perm_pressure_ouom" default:""`
	Confine_por_pressure       *float64 `json:"confine_por_pressure" default:""`
	Confine_por_pressure_ouom  *string  `json:"confine_por_pressure_ouom" default:""`
	Confine_sat_pressure       *float64 `json:"confine_sat_pressure" default:""`
	Confine_sat_pressure_ouom  *string  `json:"confine_sat_pressure_ouom" default:""`
	Effective_date             *string  `json:"effective_date" default:""`
	Effective_porosity         *float64 `json:"effective_porosity" default:""`
	Expiry_date                *string  `json:"expiry_date" default:""`
	Gas_sat_volume             *float64 `json:"gas_sat_volume" default:""`
	Grain_density              *float64 `json:"grain_density" default:""`
	Grain_density_ouom         *string  `json:"grain_density_ouom" default:""`
	Grain_mass_oil_sat         *float64 `json:"grain_mass_oil_sat" default:""`
	Grain_mass_oil_sat_ouom    *string  `json:"grain_mass_oil_sat_ouom" default:""`
	Grain_mass_water_sat       *float64 `json:"grain_mass_water_sat" default:""`
	Grain_mass_water_sat_ouom  *string  `json:"grain_mass_water_sat_ouom" default:""`
	Interval_depth             *float64 `json:"interval_depth" default:""`
	Interval_depth_ouom        *string  `json:"interval_depth_ouom" default:""`
	Interval_length            *float64 `json:"interval_length" default:""`
	Interval_length_ouom       *string  `json:"interval_length_ouom" default:""`
	K90                        *float64 `json:"k_90" default:""`
	K90_ouom                   *string  `json:"k_90_ouom" default:""`
	K90_qualifier              *string  `json:"k_90_qualifier" default:""`
	Kmax                       *float64 `json:"kmax" default:""`
	Kmax_ouom                  *string  `json:"kmax_ouom" default:""`
	Kmax_qualifier             *string  `json:"kmax_qualifier" default:""`
	Kvert                      *float64 `json:"kvert" default:""`
	Kvert_ouom                 *string  `json:"kvert_ouom" default:""`
	Kvert_qualifier            *string  `json:"kvert_qualifier" default:""`
	Oil_sat                    *float64 `json:"oil_sat" default:""`
	Pore_volume_gas_sat        *float64 `json:"pore_volume_gas_sat" default:""`
	Pore_volume_oil_sat        *float64 `json:"pore_volume_oil_sat" default:""`
	Pore_volume_water_sat      *float64 `json:"pore_volume_water_sat" default:""`
	Porosity                   *float64 `json:"porosity" default:""`
	Ppdm_guid                  *string  `json:"ppdm_guid" default:""`
	Remark                     *string  `json:"remark" default:""`
	Top_depth                  *float64 `json:"top_depth" default:""`
	Top_depth_ouom             *string  `json:"top_depth_ouom" default:""`
	Water_sat                  *float64 `json:"water_sat" default:""`
	Row_changed_by             *string  `json:"row_changed_by" default:""`
	Row_changed_date           *string  `json:"row_changed_date" default:""`
	Row_created_by             *string  `json:"row_created_by" default:""`
	Row_created_date           *string  `json:"row_created_date" default:""`
	Row_effective_date         *string  `json:"row_effective_date" default:""`
	Row_expiry_date            *string  `json:"row_expiry_date" default:""`
	Row_quality                *string  `json:"row_quality" default:""`
}
