package dto

type Well_license struct {
	Uwi                        string   `json:"uwi" default:"source"`
	Source                     string   `json:"source" default:"source"`
	License_id                 string   `json:"license_id" default:"source"`
	Active_ind                 *string  `json:"active_ind" default:""`
	Agent                      *string  `json:"agent" default:""`
	Application_id             *string  `json:"application_id" default:""`
	Authorized_strat_unit_id   *string  `json:"authorized_strat_unit_id" default:""`
	Bidding_round_num          *string  `json:"bidding_round_num" default:""`
	Contractor                 *string  `json:"contractor" default:""`
	Direction_to_loc           *float64 `json:"direction_to_loc" default:""`
	Direction_to_loc_ouom      *string  `json:"direction_to_loc_ouom" default:""`
	Distance_ref_point         *string  `json:"distance_ref_point" default:""`
	Distance_to_loc            *float64 `json:"distance_to_loc" default:""`
	Distance_to_loc_ouom       *string  `json:"distance_to_loc_ouom" default:""`
	Drill_rig_num              *string  `json:"drill_rig_num" default:""`
	Drill_slot_no              *int     `json:"drill_slot_no" default:""`
	Drill_tool                 *string  `json:"drill_tool" default:""`
	Effective_date             *string  `json:"effective_date" default:""`
	Exception_granted          *string  `json:"exception_granted" default:""`
	Exception_requested        *string  `json:"exception_requested" default:""`
	Expired_ind                *string  `json:"expired_ind" default:""`
	Expiry_date                *string  `json:"expiry_date" default:""`
	Fees_paid_ind              *string  `json:"fees_paid_ind" default:""`
	Licensee                   *string  `json:"licensee" default:""`
	Licensee_contact_id        *string  `json:"licensee_contact_id" default:""`
	License_date               *string  `json:"license_date" default:""`
	License_num                *string  `json:"license_num" default:""`
	No_of_wells                *float64 `json:"no_of_wells" default:""`
	Offshore_completion_type   *string  `json:"offshore_completion_type" default:""`
	Permit_reference_num       *string  `json:"permit_reference_num" default:""`
	Permit_reissue_date        *string  `json:"permit_reissue_date" default:""`
	Permit_type                *string  `json:"permit_type" default:""`
	Platform_name              *string  `json:"platform_name" default:""`
	Ppdm_guid                  *string  `json:"ppdm_guid" default:""`
	Projected_depth            *float64 `json:"projected_depth" default:""`
	Projected_depth_ouom       *string  `json:"projected_depth_ouom" default:""`
	Projected_strat_unit_id    *string  `json:"projected_strat_unit_id" default:""`
	Projected_tvd              *float64 `json:"projected_tvd" default:""`
	Projected_tvd_ouom         *string  `json:"projected_tvd_ouom" default:""`
	Proposed_spud_date         *string  `json:"proposed_spud_date" default:""`
	Purpose                    *string  `json:"purpose" default:""`
	Rate_schedule_id           *string  `json:"rate_schedule_id" default:""`
	Regulation_text            *string  `json:"regulation_text" default:""`
	Regulation_text_source_doc *string  `json:"regulation_text_source_doc" default:""`
	Regulatory_agency          *string  `json:"regulatory_agency" default:""`
	Regulatory_contact_id      *string  `json:"regulatory_contact_id" default:""`
	Remark                     *string  `json:"remark" default:""`
	Rig_code                   *string  `json:"rig_code" default:""`
	Rig_sf_subtype             *string  `json:"rig_sf_subtype" default:""`
	Rig_substr_height          *float64 `json:"rig_substr_height" default:""`
	Rig_substr_height_ouom     *string  `json:"rig_substr_height_ouom" default:""`
	Rig_support_facility_id    *string  `json:"rig_support_facility_id" default:""`
	Rig_type                   *string  `json:"rig_type" default:""`
	Section_of_regulation      *string  `json:"section_of_regulation" default:""`
	Strat_name_set_id          *string  `json:"strat_name_set_id" default:""`
	Surveyor                   *string  `json:"surveyor" default:""`
	Target_objective_fluid     *string  `json:"target_objective_fluid" default:""`
	Violation_ind              *string  `json:"violation_ind" default:""`
	Row_changed_by             *string  `json:"row_changed_by" default:""`
	Row_changed_date           *string  `json:"row_changed_date" default:""`
	Row_created_by             *string  `json:"row_created_by" default:""`
	Row_created_date           *string  `json:"row_created_date" default:""`
	Row_effective_date         *string  `json:"row_effective_date" default:""`
	Row_expiry_date            *string  `json:"row_expiry_date" default:""`
	Row_quality                *string  `json:"row_quality" default:""`
}
