package dto

type Well_payzone struct {
	Uwi                        string   `json:"uwi" default:"source"`
	Source                     string   `json:"source" default:"source"`
	Zone_id                    string   `json:"zone_id" default:"source"`
	Zone_source                string   `json:"zone_source" default:"source"`
	Payzone_type               string   `json:"payzone_type" default:"source"`
	Fluid_type                 string   `json:"fluid_type" default:"source"`
	Active_ind                 *string  `json:"active_ind" default:""`
	Base_depth                 *float64 `json:"base_depth" default:""`
	Base_depth_ouom            *string  `json:"base_depth_ouom" default:""`
	Base_strat_unit_id         *string  `json:"base_strat_unit_id" default:""`
	Effective_date             *string  `json:"effective_date" default:""`
	Expiry_date                *string  `json:"expiry_date" default:""`
	Gas_oil_contact_depth      *float64 `json:"gas_oil_contact_depth" default:""`
	Gas_oil_contact_depth_ouom *string  `json:"gas_oil_contact_depth_ouom" default:""`
	Gas_wtr_contact_depth      *float64 `json:"gas_wtr_contact_depth" default:""`
	Gas_wtr_contact_depth_ouom *string  `json:"gas_wtr_contact_depth_ouom" default:""`
	Gross_pay                  *float64 `json:"gross_pay" default:""`
	Gross_pay_ouom             *string  `json:"gross_pay_ouom" default:""`
	Net_pay                    *float64 `json:"net_pay" default:""`
	Net_pay_ouom               *string  `json:"net_pay_ouom" default:""`
	Oil_wtr_contact_depth      *float64 `json:"oil_wtr_contact_depth" default:""`
	Oil_wtr_contact_depth_ouom *string  `json:"oil_wtr_contact_depth_ouom" default:""`
	Ppdm_guid                  *string  `json:"ppdm_guid" default:""`
	Remark                     *string  `json:"remark" default:""`
	Strat_name_set_id          *string  `json:"strat_name_set_id" default:""`
	Top_depth                  *float64 `json:"top_depth" default:""`
	Top_depth_ouom             *string  `json:"top_depth_ouom" default:""`
	Top_strat_unit_id          *string  `json:"top_strat_unit_id" default:""`
	Row_changed_by             *string  `json:"row_changed_by" default:""`
	Row_changed_date           *string  `json:"row_changed_date" default:""`
	Row_created_by             *string  `json:"row_created_by" default:""`
	Row_created_date           *string  `json:"row_created_date" default:""`
	Row_effective_date         *string  `json:"row_effective_date" default:""`
	Row_expiry_date            *string  `json:"row_expiry_date" default:""`
	Row_quality                *string  `json:"row_quality" default:""`
}
