package dto

type Well_drill_period struct {
	Uwi                        string   `json:"uwi" default:"source"`
	Period_obs_no              int      `json:"period_obs_no" default:"1"`
	Active_ind                 *string  `json:"active_ind" default:""`
	Bha_weight                 *float64 `json:"bha_weight" default:""`
	Bha_weight_ouom            *string  `json:"bha_weight_ouom" default:""`
	Boiler_fuel                *float64 `json:"boiler_fuel" default:""`
	Boiler_fuel_ouom           *string  `json:"boiler_fuel_ouom" default:""`
	Camp_ind                   *string  `json:"camp_ind" default:""`
	Casing_press_max           *float64 `json:"casing_press_max" default:""`
	Casing_press_max_ouom      *string  `json:"casing_press_max_ouom" default:""`
	Circ_pressure              *float64 `json:"circ_pressure" default:""`
	Circ_pressure_max          *float64 `json:"circ_pressure_max" default:""`
	Circ_pressure_max_ouom     *string  `json:"circ_pressure_max_ouom" default:""`
	Circ_pressure_min          *float64 `json:"circ_pressure_min" default:""`
	Circ_pressure_min_ouom     *string  `json:"circ_pressure_min_ouom" default:""`
	Circ_pressure_ouom         *string  `json:"circ_pressure_ouom" default:""`
	Circ_pressure_type         *string  `json:"circ_pressure_type" default:""`
	Contractor_ba_id           *string  `json:"contractor_ba_id" default:""`
	Contractor_rep_ba_id       *string  `json:"contractor_rep_ba_id" default:""`
	Contractor_rep_name        *string  `json:"contractor_rep_name" default:""`
	Contractor_rep_signed_ind  *string  `json:"contractor_rep_signed_ind" default:""`
	Cum_crew_safety_days       *int     `json:"cum_crew_safety_days" default:""`
	Cum_rig_safety_days        *int     `json:"cum_rig_safety_days" default:""`
	Drill_activity_set_id      *string  `json:"drill_activity_set_id" default:""`
	Drill_activity_type_id     *string  `json:"drill_activity_type_id" default:""`
	Drill_pipe_single_count    *int     `json:"drill_pipe_single_count" default:""`
	Drill_pipe_single_len      *float64 `json:"drill_pipe_single_len" default:""`
	Drill_pipe_single_len_ouom *string  `json:"drill_pipe_single_len_ouom" default:""`
	Drill_pipe_stand_count     *int     `json:"drill_pipe_stand_count" default:""`
	Drill_pipe_stand_len       *float64 `json:"drill_pipe_stand_len" default:""`
	Drill_pipe_stand_len_ouom  *string  `json:"drill_pipe_stand_len_ouom" default:""`
	Drill_string_torque        *float64 `json:"drill_string_torque" default:""`
	Drill_string_torque_ouom   *string  `json:"drill_string_torque_ouom" default:""`
	Effective_date             *string  `json:"effective_date" default:""`
	End_date                   *string  `json:"end_date" default:""`
	End_time                   *string  `json:"end_time" default:""`
	End_timezone               *string  `json:"end_timezone" default:""`
	Expiry_date                *string  `json:"expiry_date" default:""`
	Finance_id                 *string  `json:"finance_id" default:""`
	Hole_drag                  *float64 `json:"hole_drag" default:""`
	Hole_drag_ouom             *string  `json:"hole_drag_ouom" default:""`
	Hole_fill_length           *float64 `json:"hole_fill_length" default:""`
	Hole_fill_length_ouom      *string  `json:"hole_fill_length_ouom" default:""`
	Hookload_max               *float64 `json:"hookload_max" default:""`
	Hookload_max_ouom          *string  `json:"hookload_max_ouom" default:""`
	Job_num                    *string  `json:"job_num" default:""`
	Kb_down_length             *float64 `json:"kb_down_length" default:""`
	Kb_down_length_ouom        *string  `json:"kb_down_length_ouom" default:""`
	Mud_system_type            *string  `json:"mud_system_type" default:""`
	Mud_type_oil_ind           *string  `json:"mud_type_oil_ind" default:""`
	Mud_type_water_ind         *string  `json:"mud_type_water_ind" default:""`
	Operator_ba_id             *string  `json:"operator_ba_id" default:""`
	Operator_fuel              *float64 `json:"operator_fuel" default:""`
	Operator_fuel_ouom         *string  `json:"operator_fuel_ouom" default:""`
	Operator_fuel_uom          *string  `json:"operator_fuel_uom" default:""`
	Operator_rep_ba_id         *string  `json:"operator_rep_ba_id" default:""`
	Operator_rep_name          *string  `json:"operator_rep_name" default:""`
	Operator_rep_signed_ind    *string  `json:"operator_rep_signed_ind" default:""`
	Ppdm_guid                  *string  `json:"ppdm_guid" default:""`
	Primary_activity_ind       *string  `json:"primary_activity_ind" default:""`
	Rate_schedule_id           *string  `json:"rate_schedule_id" default:""`
	Reentry_ind                *string  `json:"reentry_ind" default:""`
	Remark                     *string  `json:"remark" default:""`
	Reported_base_location     *string  `json:"reported_base_location" default:""`
	Reported_kb_elev           *float64 `json:"reported_kb_elev" default:""`
	Reported_kb_elev_ouom      *string  `json:"reported_kb_elev_ouom" default:""`
	Reported_license_num       *string  `json:"reported_license_num" default:""`
	Reported_period_num        *string  `json:"reported_period_num" default:""`
	Reported_profile_type      *string  `json:"reported_profile_type" default:""`
	Reported_rig_name          *string  `json:"reported_rig_name" default:""`
	Reported_rig_rel_date      *string  `json:"reported_rig_rel_date" default:""`
	Reported_rig_rel_time      *string  `json:"reported_rig_rel_time" default:""`
	Reported_rig_rel_timezone  *string  `json:"reported_rig_rel_timezone" default:""`
	Reported_spud_date         *string  `json:"reported_spud_date" default:""`
	Reported_spud_time         *string  `json:"reported_spud_time" default:""`
	Reported_spud_timezone     *string  `json:"reported_spud_timezone" default:""`
	Reported_top_location      *string  `json:"reported_top_location" default:""`
	Reported_uwi               *string  `json:"reported_uwi" default:""`
	Reported_well_name         *string  `json:"reported_well_name" default:""`
	Report_time_type           *string  `json:"report_time_type" default:""`
	Rig_fuel                   *float64 `json:"rig_fuel" default:""`
	Rig_fuel_ouom              *string  `json:"rig_fuel_ouom" default:""`
	Rig_fuel_uom               *string  `json:"rig_fuel_uom" default:""`
	Safety_meeting_topic       *string  `json:"safety_meeting_topic" default:""`
	Source                     *string  `json:"source" default:""`
	Start_date                 *string  `json:"start_date" default:""`
	Start_time                 *string  `json:"start_time" default:""`
	Start_timezone             *string  `json:"start_timezone" default:""`
	Tot_drill_tool_length      *float64 `json:"tot_drill_tool_length" default:""`
	Tot_drill_tool_length_ouom *string  `json:"tot_drill_tool_length_ouom" default:""`
	Tot_drill_tool_weight      *float64 `json:"tot_drill_tool_weight" default:""`
	Tot_drill_tool_weight_ouom *string  `json:"tot_drill_tool_weight_ouom" default:""`
	Row_changed_by             *string  `json:"row_changed_by" default:""`
	Row_changed_date           *string  `json:"row_changed_date" default:""`
	Row_created_by             *string  `json:"row_created_by" default:""`
	Row_created_date           *string  `json:"row_created_date" default:""`
	Row_effective_date         *string  `json:"row_effective_date" default:""`
	Row_expiry_date            *string  `json:"row_expiry_date" default:""`
	Row_quality                *string  `json:"row_quality" default:""`
}
