package dto

type Well struct {
	Uwi                       string   `json:"uwi" default:"source"`
	Abandonment_date          *string  `json:"abandonment_date" default:""`
	Active_ind                *string  `json:"active_ind" default:""`
	Area_id                   *string  `json:"area_id" default:""`
	Area_type                 *string  `json:"area_type" default:""`
	Assigned_field            *string  `json:"assigned_field" default:""`
	Base_depth                *float64 `json:"base_depth" default:""`
	Base_depth_ouom           *string  `json:"base_depth_ouom" default:""`
	Base_node_id              *string  `json:"base_node_id" default:""`
	Base_strat_name_set_id    *string  `json:"base_strat_name_set_id" default:""`
	Base_strat_unit_id        *string  `json:"base_strat_unit_id" default:""`
	Bottom_hole_latitude      *float64 `json:"bottom_hole_latitude" default:""`
	Bottom_hole_longitude     *float64 `json:"bottom_hole_longitude" default:""`
	Casing_flange_elev        *float64 `json:"casing_flange_elev" default:""`
	Casing_flange_elev_ouom   *string  `json:"casing_flange_elev_ouom" default:""`
	Completion_date           *string  `json:"completion_date" default:""`
	Confidential_date         *string  `json:"confidential_date" default:""`
	Confidential_depth        *float64 `json:"confidential_depth" default:""`
	Confidential_depth_ouom   *string  `json:"confidential_depth_ouom" default:""`
	Confidential_type         *string  `json:"confidential_type" default:""`
	Confid_strat_name_set_id  *string  `json:"confid_strat_name_set_id" default:""`
	Confid_strat_unit_id      *string  `json:"confid_strat_unit_id" default:""`
	Current_class             *string  `json:"current_class" default:""`
	Current_status            *string  `json:"current_status" default:""`
	Current_status_date       *string  `json:"current_status_date" default:""`
	Deepest_depth             *float64 `json:"deepest_depth" default:""`
	Deepest_depth_ouom        *string  `json:"deepest_depth_ouom" default:""`
	Depth_datum               *string  `json:"depth_datum" default:""`
	Depth_datum_elev          *float64 `json:"depth_datum_elev" default:""`
	Depth_datum_elev_ouom     *string  `json:"depth_datum_elev_ouom" default:""`
	Derrick_floor_elev        *float64 `json:"derrick_floor_elev" default:""`
	Derrick_floor_elev_ouom   *string  `json:"derrick_floor_elev_ouom" default:""`
	Difference_lat_msl        *float64 `json:"difference_lat_msl" default:""`
	Discovery_ind             *string  `json:"discovery_ind" default:""`
	Drill_td                  *float64 `json:"drill_td" default:""`
	Drill_td_ouom             *string  `json:"drill_td_ouom" default:""`
	Effective_date            *string  `json:"effective_date" default:""`
	Elev_ref_datum            *string  `json:"elev_ref_datum" default:""`
	Environment_type          *string  `json:"environment_type" default:""`
	Expiry_date               *string  `json:"expiry_date" default:""`
	Faulted_ind               *string  `json:"faulted_ind" default:""`
	Final_drill_date          *string  `json:"final_drill_date" default:""`
	Final_td                  *float64 `json:"final_td" default:""`
	Final_td_ouom             *string  `json:"final_td_ouom" default:""`
	Ground_elev               *float64 `json:"ground_elev" default:""`
	Ground_elev_ouom          *string  `json:"ground_elev_ouom" default:""`
	Ground_elev_type          *string  `json:"ground_elev_type" default:""`
	Initial_class             *string  `json:"initial_class" default:""`
	Kb_elev                   *float64 `json:"kb_elev" default:""`
	Kb_elev_ouom              *string  `json:"kb_elev_ouom" default:""`
	Lease_name                *string  `json:"lease_name" default:""`
	Lease_num                 *string  `json:"lease_num" default:""`
	Legal_survey_type         *string  `json:"legal_survey_type" default:""`
	Location_type             *string  `json:"location_type" default:""`
	Log_td                    *float64 `json:"log_td" default:""`
	Log_td_ouom               *string  `json:"log_td_ouom" default:""`
	Max_tvd                   *float64 `json:"max_tvd" default:""`
	Max_tvd_ouom              *string  `json:"max_tvd_ouom" default:""`
	Net_pay                   *float64 `json:"net_pay" default:""`
	Net_pay_ouom              *string  `json:"net_pay_ouom" default:""`
	Oldest_strat_age          *string  `json:"oldest_strat_age" default:""`
	Oldest_strat_name_set_age *string  `json:"oldest_strat_name_set_age" default:""`
	Oldest_strat_name_set_id  *string  `json:"oldest_strat_name_set_id" default:""`
	Oldest_strat_unit_id      *string  `json:"oldest_strat_unit_id" default:""`
	Operator                  *string  `json:"operator" default:""`
	Platform_id               *string  `json:"platform_id" default:""`
	Platform_sf_subtype       *string  `json:"platform_sf_subtype" default:""`
	Plot_name                 *string  `json:"plot_name" default:""`
	Plot_symbol               *string  `json:"plot_symbol" default:""`
	Plugback_depth            *float64 `json:"plugback_depth" default:""`
	Plugback_depth_ouom       *string  `json:"plugback_depth_ouom" default:""`
	Ppdm_guid                 *string  `json:"ppdm_guid" default:""`
	Primary_source            *string  `json:"primary_source" default:""`
	Profile_type              *string  `json:"profile_type" default:""`
	Regulatory_agency         *string  `json:"regulatory_agency" default:""`
	Remark                    *string  `json:"remark" default:""`
	Rig_on_site_date          *string  `json:"rig_on_site_date" default:""`
	Rig_release_date          *string  `json:"rig_release_date" default:""`
	Rotary_table_elev         *float64 `json:"rotary_table_elev" default:""`
	Rotary_table_elev_ouom    *string  `json:"rotary_table_elev_ouom" default:""`
	Source_document_id        *string  `json:"source_document_id" default:""`
	Spud_date                 *string  `json:"spud_date" default:""`
	Status_type               *string  `json:"status_type" default:""`
	Subsea_elev_ref_type      *string  `json:"subsea_elev_ref_type" default:""`
	Surface_latitude          *float64 `json:"surface_latitude" default:""`
	Surface_longitude         *float64 `json:"surface_longitude" default:""`
	Surface_node_id           *string  `json:"surface_node_id" default:""`
	Tax_credit_code           *string  `json:"tax_credit_code" default:""`
	Td_strat_age              *string  `json:"td_strat_age" default:""`
	Td_strat_name_set_age     *string  `json:"td_strat_name_set_age" default:""`
	Td_strat_name_set_id      *string  `json:"td_strat_name_set_id" default:""`
	Td_strat_unit_id          *string  `json:"td_strat_unit_id" default:""`
	Top_depth                 *float64 `json:"top_depth" default:""`
	Top_depth_ouom            *string  `json:"top_depth_ouom" default:""`
	Top_strat_name_set_id     *string  `json:"top_strat_name_set_id" default:""`
	Top_strat_unit_id         *string  `json:"top_strat_unit_id" default:""`
	Water_acoustic_vel        *float64 `json:"water_acoustic_vel" default:""`
	Water_acoustic_vel_ouom   *string  `json:"water_acoustic_vel_ouom" default:""`
	Water_depth               *float64 `json:"water_depth" default:""`
	Water_depth_datum         *string  `json:"water_depth_datum" default:""`
	Water_depth_ouom          *string  `json:"water_depth_ouom" default:""`
	Well_event_num            *string  `json:"well_event_num" default:""`
	Well_government_id        *string  `json:"well_government_id" default:""`
	Well_intersect_md         *float64 `json:"well_intersect_md" default:""`
	Well_level_type           *string  `json:"well_level_type" default:""`
	Well_name                 *string  `json:"well_name" default:""`
	Well_num                  *string  `json:"well_num" default:""`
	Whipstock_depth           *float64 `json:"whipstock_depth" default:""`
	Whipstock_depth_ouom      *string  `json:"whipstock_depth_ouom" default:""`
	Row_changed_by            *string  `json:"row_changed_by" default:""`
	Row_changed_date          *string  `json:"row_changed_date" default:""`
	Row_created_by            *string  `json:"row_created_by" default:""`
	Row_created_date          *string  `json:"row_created_date" default:""`
	Row_effective_date        *string  `json:"row_effective_date" default:""`
	Row_expiry_date           *string  `json:"row_expiry_date" default:""`
	Row_quality               *string  `json:"row_quality" default:""`
}
