package dto

type Well_dir_srvy struct {
	Uwi                         string   `json:"uwi" default:"source"`
	Survey_id                   string   `json:"survey_id" default:"source"`
	Source                      string   `json:"source" default:"source"`
	Active_ind                  *string  `json:"active_ind" default:""`
	Azimuth_coord_sys_id        *string  `json:"azimuth_coord_sys_id" default:""`
	Azimuth_coord_sys_qualifier *string  `json:"azimuth_coord_sys_qualifier" default:""`
	Azimuth_coord_sys_remark    *string  `json:"azimuth_coord_sys_remark" default:""`
	Azimuth_corr_angle          *float64 `json:"azimuth_corr_angle" default:""`
	Azimuth_corr_angle_ouom     *string  `json:"azimuth_corr_angle_ouom" default:""`
	Azimuth_corr_angle_type     *string  `json:"azimuth_corr_angle_type" default:""`
	Azimuth_north_type          *string  `json:"azimuth_north_type" default:""`
	Base_depth                  *float64 `json:"base_depth" default:""`
	Base_depth_ouom             *string  `json:"base_depth_ouom" default:""`
	Compute_method              *string  `json:"compute_method" default:""`
	Confidential_type           *string  `json:"confidential_type" default:""`
	Coord_acquisition_id        *string  `json:"coord_acquisition_id" default:""`
	Dir_survey_class            *string  `json:"dir_survey_class" default:""`
	Effective_date              *string  `json:"effective_date" default:""`
	Expiry_date                 *string  `json:"expiry_date" default:""`
	Extrapolate_depth           *float64 `json:"extrapolate_depth" default:""`
	Extrapolate_depth_ouom      *string  `json:"extrapolate_depth_ouom" default:""`
	Extrapolate_ind             *string  `json:"extrapolate_ind" default:""`
	Geog_coord_sys_id           *string  `json:"geog_coord_sys_id" default:""`
	Local_coord_sys_id          *string  `json:"local_coord_sys_id" default:""`
	Magnetic_declination        *float64 `json:"magnetic_declination" default:""`
	Magnetic_declination_ouom   *string  `json:"magnetic_declination_ouom" default:""`
	Mag_decl_ew_direction       *string  `json:"mag_decl_ew_direction" default:""`
	Offset_coord_sys_id         *string  `json:"offset_coord_sys_id" default:""`
	Offset_coord_sys_qualifier  *string  `json:"offset_coord_sys_qualifier" default:""`
	Offset_coord_sys_remark     *string  `json:"offset_coord_sys_remark" default:""`
	Offset_north_type           *string  `json:"offset_north_type" default:""`
	Plane_of_proposal           *float64 `json:"plane_of_proposal" default:""`
	Plane_of_proposal_ouom      *string  `json:"plane_of_proposal_ouom" default:""`
	Ppdm_guid                   *string  `json:"ppdm_guid" default:""`
	Preferred_ind               *string  `json:"preferred_ind" default:""`
	Rad_uncert_dist             *float64 `json:"rad_uncert_dist" default:""`
	Rad_uncert_dist_ouom        *string  `json:"rad_uncert_dist_ouom" default:""`
	Rad_uncert_dist_reason      *string  `json:"rad_uncert_dist_reason" default:""`
	Record_mode                 *string  `json:"record_mode" default:""`
	Remark                      *string  `json:"remark" default:""`
	Report_apd                  *float64 `json:"report_apd" default:""`
	Report_log_datum            *string  `json:"report_log_datum" default:""`
	Report_log_datum_elev       *float64 `json:"report_log_datum_elev" default:""`
	Report_log_datum_elev_ouom  *string  `json:"report_log_datum_elev_ouom" default:""`
	Report_perm_datum           *string  `json:"report_perm_datum" default:""`
	Report_perm_datum_elev      *float64 `json:"report_perm_datum_elev" default:""`
	Report_perm_datum_elev_ouom *string  `json:"report_perm_datum_elev_ouom" default:""`
	Resample_interval           *float64 `json:"resample_interval" default:""`
	Resample_interval_ouom      *string  `json:"resample_interval_ouom" default:""`
	Rpt_coord_sys_id            *string  `json:"rpt_coord_sys_id" default:""`
	Rpt_coord_sys_qualifier     *string  `json:"rpt_coord_sys_qualifier" default:""`
	Rpt_coord_sys_remark        *string  `json:"rpt_coord_sys_remark" default:""`
	Rpt_corr_angle              *float64 `json:"rpt_corr_angle" default:""`
	Rpt_corr_angle_ouom         *string  `json:"rpt_corr_angle_ouom" default:""`
	Rpt_corr_angle_type         *string  `json:"rpt_corr_angle_type" default:""`
	Rpt_north_type              *string  `json:"rpt_north_type" default:""`
	Rpt_survey_type             *string  `json:"rpt_survey_type" default:""`
	Rpt_tie_azimuth             *float64 `json:"rpt_tie_azimuth" default:""`
	Rpt_tie_azimuth_ouom        *string  `json:"rpt_tie_azimuth_ouom" default:""`
	Rpt_tie_inclination         *float64 `json:"rpt_tie_inclination" default:""`
	Rpt_tie_inclination_ouom    *string  `json:"rpt_tie_inclination_ouom" default:""`
	Rpt_tie_md                  *float64 `json:"rpt_tie_md" default:""`
	Rpt_tie_md_ouom             *string  `json:"rpt_tie_md_ouom" default:""`
	Rpt_tie_point_ind           *string  `json:"rpt_tie_point_ind" default:""`
	Rpt_tie_tvd                 *float64 `json:"rpt_tie_tvd" default:""`
	Rpt_tie_tvd_ouom            *string  `json:"rpt_tie_tvd_ouom" default:""`
	Rpt_tie_x_offset            *float64 `json:"rpt_tie_x_offset" default:""`
	Rpt_tie_x_offset_ew_dir     *string  `json:"rpt_tie_x_offset_ew_dir" default:""`
	Rpt_tie_x_offset_ouom       *string  `json:"rpt_tie_x_offset_ouom" default:""`
	Rpt_tie_y_offset            *float64 `json:"rpt_tie_y_offset" default:""`
	Rpt_tie_y_offset_ns_dir     *string  `json:"rpt_tie_y_offset_ns_dir" default:""`
	Rpt_tie_y_offset_ouom       *string  `json:"rpt_tie_y_offset_ouom" default:""`
	Source_document_id          *string  `json:"source_document_id" default:""`
	Survey_company_ba_id        *string  `json:"survey_company_ba_id" default:""`
	Survey_compiler_ba_id       *string  `json:"survey_compiler_ba_id" default:""`
	Survey_digital_prvdr_ba_id  *string  `json:"survey_digital_prvdr_ba_id" default:""`
	Survey_end_date             *string  `json:"survey_end_date" default:""`
	Survey_end_date_qualifier   *string  `json:"survey_end_date_qualifier" default:""`
	Survey_process_method       *string  `json:"survey_process_method" default:""`
	Survey_quality              *string  `json:"survey_quality" default:""`
	Survey_ref_num              *string  `json:"survey_ref_num" default:""`
	Survey_report_type          *string  `json:"survey_report_type" default:""`
	Survey_run_num              *string  `json:"survey_run_num" default:""`
	Survey_start_date           *string  `json:"survey_start_date" default:""`
	Survey_start_date_qualifier *string  `json:"survey_start_date_qualifier" default:""`
	Survey_type                 *string  `json:"survey_type" default:""`
	Top_depth                   *float64 `json:"top_depth" default:""`
	Top_depth_ouom              *string  `json:"top_depth_ouom" default:""`
	Row_changed_by              *string  `json:"row_changed_by" default:""`
	Row_changed_date            *string  `json:"row_changed_date" default:""`
	Row_created_by              *string  `json:"row_created_by" default:""`
	Row_created_date            *string  `json:"row_created_date" default:""`
	Row_effective_date          *string  `json:"row_effective_date" default:""`
	Row_expiry_date             *string  `json:"row_expiry_date" default:""`
	Row_quality                 *string  `json:"row_quality" default:""`
}
