package dto

type Well_test_recorder struct {
	Uwi                        string   `json:"uwi" default:"source"`
	Source                     string   `json:"source" default:"source"`
	Test_type                  string   `json:"test_type" default:"source"`
	Run_num                    string   `json:"run_num" default:"source"`
	Test_num                   string   `json:"test_num" default:"source"`
	Recorder_id                string   `json:"recorder_id" default:"source"`
	Active_ind                 *string  `json:"active_ind" default:""`
	Effective_date             *string  `json:"effective_date" default:""`
	Expiry_date                *string  `json:"expiry_date" default:""`
	Max_capacity_pressure      *float64 `json:"max_capacity_pressure" default:""`
	Max_capacity_pressure_ouom *string  `json:"max_capacity_pressure_ouom" default:""`
	Max_capacity_temp          *float64 `json:"max_capacity_temp" default:""`
	Max_capacity_temp_ouom     *string  `json:"max_capacity_temp_ouom" default:""`
	Performance_quality        *string  `json:"performance_quality" default:""`
	Ppdm_guid                  *string  `json:"ppdm_guid" default:""`
	Recorder_depth             *float64 `json:"recorder_depth" default:""`
	Recorder_depth_ouom        *string  `json:"recorder_depth_ouom" default:""`
	Recorder_inside_ind        *string  `json:"recorder_inside_ind" default:""`
	Recorder_max_temp          *float64 `json:"recorder_max_temp" default:""`
	Recorder_max_temp_ouom     *string  `json:"recorder_max_temp_ouom" default:""`
	Recorder_min_temp          *float64 `json:"recorder_min_temp" default:""`
	Recorder_min_temp_ouom     *string  `json:"recorder_min_temp_ouom" default:""`
	Recorder_position          *string  `json:"recorder_position" default:""`
	Recorder_resolution        *float64 `json:"recorder_resolution" default:""`
	Recorder_resolution_ouom   *string  `json:"recorder_resolution_ouom" default:""`
	Recorder_type              *string  `json:"recorder_type" default:""`
	Recorder_used_ind          *string  `json:"recorder_used_ind" default:""`
	Remark                     *string  `json:"remark" default:""`
	Row_changed_by             *string  `json:"row_changed_by" default:""`
	Row_changed_date           *string  `json:"row_changed_date" default:""`
	Row_created_by             *string  `json:"row_created_by" default:""`
	Row_created_date           *string  `json:"row_created_date" default:""`
	Row_effective_date         *string  `json:"row_effective_date" default:""`
	Row_expiry_date            *string  `json:"row_expiry_date" default:""`
	Row_quality                *string  `json:"row_quality" default:""`
}
