package dto

type Well_activity struct {
	Uwi                        string   `json:"uwi" default:"source"`
	Source                     string   `json:"source" default:"source"`
	Activity_obs_no            int      `json:"activity_obs_no" default:"1"`
	Active_ind                 *string  `json:"active_ind" default:""`
	Activity_duration          *float64 `json:"activity_duration" default:""`
	Activity_duration_ouom     *string  `json:"activity_duration_ouom" default:""`
	Activity_product           *string  `json:"activity_product" default:""`
	Activity_set_id            *string  `json:"activity_set_id" default:""`
	Activity_type_id           *string  `json:"activity_type_id" default:""`
	Base_depth                 *float64 `json:"base_depth" default:""`
	Base_depth_ouom            *string  `json:"base_depth_ouom" default:""`
	Base_strat_unit_id         *string  `json:"base_strat_unit_id" default:""`
	Blowout_fluid              *string  `json:"blowout_fluid" default:""`
	Control_date               *string  `json:"control_date" default:""`
	Control_depth              *float64 `json:"control_depth" default:""`
	Control_depth_ouom         *string  `json:"control_depth_ouom" default:""`
	Downtime_type              *string  `json:"downtime_type" default:""`
	Effective_date             *string  `json:"effective_date" default:""`
	End_date                   *string  `json:"end_date" default:""`
	End_time                   *string  `json:"end_time" default:""`
	End_timezone               *string  `json:"end_timezone" default:""`
	Event_date                 *string  `json:"event_date" default:""`
	Event_depth                *float64 `json:"event_depth" default:""`
	Event_depth_ouom           *string  `json:"event_depth_ouom" default:""`
	Expiry_date                *string  `json:"expiry_date" default:""`
	Final_mud_density          *float64 `json:"final_mud_density" default:""`
	Final_mud_density_ouom     *string  `json:"final_mud_density_ouom" default:""`
	Final_mud_viscosity        *float64 `json:"final_mud_viscosity" default:""`
	Final_mud_viscosity_ouom   *string  `json:"final_mud_viscosity_ouom" default:""`
	Lithology                  *string  `json:"lithology" default:""`
	Lost_circ_severity         *string  `json:"lost_circ_severity" default:""`
	Lost_material_amount       *float64 `json:"lost_material_amount" default:""`
	Lost_material_amount_ouom  *string  `json:"lost_material_amount_ouom" default:""`
	Lost_material_type         *string  `json:"lost_material_type" default:""`
	Lost_volume                *float64 `json:"lost_volume" default:""`
	Lost_volume_ouom           *string  `json:"lost_volume_ouom" default:""`
	Lost_volume_product        *string  `json:"lost_volume_product" default:""`
	Lost_volume_uom            *string  `json:"lost_volume_uom" default:""`
	Period_obs_no              *int     `json:"period_obs_no" default:""`
	Ppdm_guid                  *string  `json:"ppdm_guid" default:""`
	Prod_string_id             *string  `json:"prod_string_id" default:""`
	Prod_string_source         *string  `json:"prod_string_source" default:""`
	Pr_str_form_obs_no         *int     `json:"pr_str_form_obs_no" default:""`
	Remark                     *string  `json:"remark" default:""`
	Reported_code              *string  `json:"reported_code" default:""`
	Reported_time_elapsed      *float64 `json:"reported_time_elapsed" default:""`
	Reported_time_elapsed_ouom *string  `json:"reported_time_elapsed_ouom" default:""`
	Reported_tvd               *float64 `json:"reported_tvd" default:""`
	Reported_tvd_ouom          *string  `json:"reported_tvd_ouom" default:""`
	Start_date                 *string  `json:"start_date" default:""`
	Start_mud_density          *float64 `json:"start_mud_density" default:""`
	Start_mud_density_ouom     *string  `json:"start_mud_density_ouom" default:""`
	Start_mud_viscosity        *float64 `json:"start_mud_viscosity" default:""`
	Start_mud_viscosity_ouom   *string  `json:"start_mud_viscosity_ouom" default:""`
	Start_time                 *string  `json:"start_time" default:""`
	Start_timezone             *string  `json:"start_timezone" default:""`
	Strat_name_set_id          *string  `json:"strat_name_set_id" default:""`
	Top_depth                  *float64 `json:"top_depth" default:""`
	Top_depth_ouom             *string  `json:"top_depth_ouom" default:""`
	Top_strat_unit_id          *string  `json:"top_strat_unit_id" default:""`
	Total_time_elapsed         *float64 `json:"total_time_elapsed" default:""`
	Total_time_elapsed_ouom    *string  `json:"total_time_elapsed_ouom" default:""`
	Row_changed_by             *string  `json:"row_changed_by" default:""`
	Row_changed_date           *string  `json:"row_changed_date" default:""`
	Row_created_by             *string  `json:"row_created_by" default:""`
	Row_created_date           *string  `json:"row_created_date" default:""`
	Row_effective_date         *string  `json:"row_effective_date" default:""`
	Row_expiry_date            *string  `json:"row_expiry_date" default:""`
	Row_quality                *string  `json:"row_quality" default:""`
}
