package dto

type Well_treatment struct {
	Uwi                        string   `json:"uwi" default:"source"`
	Source                     string   `json:"source" default:"source"`
	Treatment_type             string   `json:"treatment_type" default:"source"`
	Treatment_obs_no           int      `json:"treatment_obs_no" default:"1"`
	Active_ind                 *string  `json:"active_ind" default:""`
	Additive_type              *string  `json:"additive_type" default:""`
	Base_depth                 *float64 `json:"base_depth" default:""`
	Base_depth_ouom            *string  `json:"base_depth_ouom" default:""`
	Base_strat_unit_id         *string  `json:"base_strat_unit_id" default:""`
	Completion_obs_no          *int     `json:"completion_obs_no" default:""`
	Completion_source          *string  `json:"completion_source" default:""`
	Effective_date             *string  `json:"effective_date" default:""`
	Expiry_date                *string  `json:"expiry_date" default:""`
	Form_break_pressure        *float64 `json:"form_break_pressure" default:""`
	Form_break_pressure_ouom   *string  `json:"form_break_pressure_ouom" default:""`
	Injection_rate             *float64 `json:"injection_rate" default:""`
	Injection_rate_ouom        *string  `json:"injection_rate_ouom" default:""`
	Instant_si_pressure        *float64 `json:"instant_si_pressure" default:""`
	Instant_si_pressure_ouom   *string  `json:"instant_si_pressure_ouom" default:""`
	Ppdm_guid                  *string  `json:"ppdm_guid" default:""`
	Proppant_agent_amount      *float64 `json:"proppant_agent_amount" default:""`
	Proppant_agent_amount_ouom *string  `json:"proppant_agent_amount_ouom" default:""`
	Proppant_agent_amount_uom  *string  `json:"proppant_agent_amount_uom" default:""`
	Proppant_agent_mesh_size   *string  `json:"proppant_agent_mesh_size" default:""`
	Proppant_agent_type        *string  `json:"proppant_agent_type" default:""`
	Remark                     *string  `json:"remark" default:""`
	Run_num                    *string  `json:"run_num" default:""`
	Stage_no                   *int     `json:"stage_no" default:""`
	Strat_name_set_id          *string  `json:"strat_name_set_id" default:""`
	Test_num                   *string  `json:"test_num" default:""`
	Test_type                  *string  `json:"test_type" default:""`
	Top_depth                  *float64 `json:"top_depth" default:""`
	Top_depth_ouom             *string  `json:"top_depth_ouom" default:""`
	Top_strat_unit_id          *string  `json:"top_strat_unit_id" default:""`
	Treatment_amount           *float64 `json:"treatment_amount" default:""`
	Treatment_amount_ouom      *string  `json:"treatment_amount_ouom" default:""`
	Treatment_amount_uom       *string  `json:"treatment_amount_uom" default:""`
	Treatment_ba_id            *string  `json:"treatment_ba_id" default:""`
	Treatment_date             *string  `json:"treatment_date" default:""`
	Treatment_fluid_type       *string  `json:"treatment_fluid_type" default:""`
	Treatment_pressure         *float64 `json:"treatment_pressure" default:""`
	Treatment_pressure_ouom    *string  `json:"treatment_pressure_ouom" default:""`
	Treatment_status           *string  `json:"treatment_status" default:""`
	Treatment_status_type      *string  `json:"treatment_status_type" default:""`
	Well_test_source           *string  `json:"well_test_source" default:""`
	Row_changed_by             *string  `json:"row_changed_by" default:""`
	Row_changed_date           *string  `json:"row_changed_date" default:""`
	Row_created_by             *string  `json:"row_created_by" default:""`
	Row_created_date           *string  `json:"row_created_date" default:""`
	Row_effective_date         *string  `json:"row_effective_date" default:""`
	Row_expiry_date            *string  `json:"row_expiry_date" default:""`
	Row_quality                *string  `json:"row_quality" default:""`
}
