package dto

type Well_mud_property struct {
	Sample_analysis_id     string   `json:"sample_analysis_id" default:"source"`
	Sample_analysis_source string   `json:"sample_analysis_source" default:"source"`
	Property_obs_no        int      `json:"property_obs_no" default:"1"`
	Active_ind             *string  `json:"active_ind" default:""`
	Average_value          *float64 `json:"average_value" default:""`
	Average_value_ouom     *string  `json:"average_value_ouom" default:""`
	Average_value_uom      *string  `json:"average_value_uom" default:""`
	Date_format_desc       *string  `json:"date_format_desc" default:""`
	Effective_date         *string  `json:"effective_date" default:""`
	Expiry_date            *string  `json:"expiry_date" default:""`
	Max_value              *float64 `json:"max_value" default:""`
	Max_value_ouom         *string  `json:"max_value_ouom" default:""`
	Max_value_uom          *string  `json:"max_value_uom" default:""`
	Min_value              *float64 `json:"min_value" default:""`
	Min_value_ouom         *string  `json:"min_value_ouom" default:""`
	Min_value_uom          *string  `json:"min_value_uom" default:""`
	Mud_anl_obs_no         *int     `json:"mud_anl_obs_no" default:""`
	Mud_property           *string  `json:"mud_property" default:""`
	Mud_property_code      *string  `json:"mud_property_code" default:""`
	Mud_property_desc      *string  `json:"mud_property_desc" default:""`
	Mud_property_ref       *string  `json:"mud_property_ref" default:""`
	Ppdm_guid              *string  `json:"ppdm_guid" default:""`
	Reference_value        *float64 `json:"reference_value" default:""`
	Reference_value_ouom   *string  `json:"reference_value_ouom" default:""`
	Reference_value_uom    *string  `json:"reference_value_uom" default:""`
	Remark                 *string  `json:"remark" default:""`
	Sample_type            *string  `json:"sample_type" default:""`
	Source                 *string  `json:"source" default:""`
	Step_seq_no            *int     `json:"step_seq_no" default:""`
	Uwi                    *string  `json:"uwi" default:""`
	Row_changed_by         *string  `json:"row_changed_by" default:""`
	Row_changed_date       *string  `json:"row_changed_date" default:""`
	Row_created_by         *string  `json:"row_created_by" default:""`
	Row_created_date       *string  `json:"row_created_date" default:""`
	Row_effective_date     *string  `json:"row_effective_date" default:""`
	Row_expiry_date        *string  `json:"row_expiry_date" default:""`
	Row_quality            *string  `json:"row_quality" default:""`
}
