package dto

type Well_test struct {
	Uwi                         string   `json:"uwi" default:"source"`
	Source                      string   `json:"source" default:"source"`
	Test_type                   string   `json:"test_type" default:"source"`
	Run_num                     string   `json:"run_num" default:"source"`
	Test_num                    string   `json:"test_num" default:"source"`
	Active_ind                  *string  `json:"active_ind" default:""`
	Base_depth                  *float64 `json:"base_depth" default:""`
	Base_depth_ouom             *string  `json:"base_depth_ouom" default:""`
	Base_strat_unit_id          *string  `json:"base_strat_unit_id" default:""`
	Bhp_z                       *float64 `json:"bhp_z" default:""`
	Bottom_choke_desc           *string  `json:"bottom_choke_desc" default:""`
	Bsw_percent                 *float64 `json:"bsw_percent" default:""`
	Caliper_hole_diameter       *float64 `json:"caliper_hole_diameter" default:""`
	Caliper_hole_diameter_ouom  *string  `json:"caliper_hole_diameter_ouom" default:""`
	Cased_hole_ind              *string  `json:"cased_hole_ind" default:""`
	Casing_pressure             *float64 `json:"casing_pressure" default:""`
	Casing_pressure_ouom        *string  `json:"casing_pressure_ouom" default:""`
	Choke_size_desc             *string  `json:"choke_size_desc" default:""`
	Completion_obs_no           *int     `json:"completion_obs_no" default:""`
	Completion_source           *string  `json:"completion_source" default:""`
	Condensate_amount_percent   *float64 `json:"condensate_amount_percent" default:""`
	Condensate_flow_amount      *float64 `json:"condensate_flow_amount" default:""`
	Condensate_flow_amount_ouom *string  `json:"condensate_flow_amount_ouom" default:""`
	Condensate_flow_amount_uom  *string  `json:"condensate_flow_amount_uom" default:""`
	Condensate_gravity          *float64 `json:"condensate_gravity" default:""`
	Condensate_ratio            *float64 `json:"condensate_ratio" default:""`
	Condensate_ratio_ouom       *string  `json:"condensate_ratio_ouom" default:""`
	Damage_quality              *string  `json:"damage_quality" default:""`
	Effective_date              *string  `json:"effective_date" default:""`
	Event_obs_no                *int     `json:"event_obs_no" default:""`
	Event_source                *string  `json:"event_source" default:""`
	Expiry_date                 *string  `json:"expiry_date" default:""`
	Flow_pressure               *float64 `json:"flow_pressure" default:""`
	Flow_pressure_ouom          *string  `json:"flow_pressure_ouom" default:""`
	Flow_temperature            *float64 `json:"flow_temperature" default:""`
	Flow_temperature_ouom       *string  `json:"flow_temperature_ouom" default:""`
	Gas_flow_amount             *float64 `json:"gas_flow_amount" default:""`
	Gas_flow_amount_ouom        *string  `json:"gas_flow_amount_ouom" default:""`
	Gas_flow_amount_uom         *string  `json:"gas_flow_amount_uom" default:""`
	Gas_gravity                 *float64 `json:"gas_gravity" default:""`
	Gor                         *float64 `json:"gor" default:""`
	Gor_ouom                    *string  `json:"gor_ouom" default:""`
	H2s_percent                 *float64 `json:"h_2_s_percent" default:""`
	Hole_condition              *string  `json:"hole_condition" default:""`
	Max_condens_flow_rate       *float64 `json:"max_condens_flow_rate" default:""`
	Max_condens_flow_rate_ouom  *string  `json:"max_condens_flow_rate_ouom" default:""`
	Max_gas_flow_rate           *float64 `json:"max_gas_flow_rate" default:""`
	Max_gas_flow_rate_ouom      *string  `json:"max_gas_flow_rate_ouom" default:""`
	Max_hydrostatic_pressure    *float64 `json:"max_hydrostatic_pressure" default:""`
	Max_hydrostatic_press_ouom  *string  `json:"max_hydrostatic_press_ouom" default:""`
	Max_oil_flow_rate           *float64 `json:"max_oil_flow_rate" default:""`
	Max_oil_flow_rate_ouom      *string  `json:"max_oil_flow_rate_ouom" default:""`
	Max_water_flow_rate         *float64 `json:"max_water_flow_rate" default:""`
	Max_water_flow_rate_ouom    *string  `json:"max_water_flow_rate_ouom" default:""`
	Oil_amount_percent          *float64 `json:"oil_amount_percent" default:""`
	Oil_flow_amount             *float64 `json:"oil_flow_amount" default:""`
	Oil_flow_amount_ouom        *string  `json:"oil_flow_amount_ouom" default:""`
	Oil_flow_amount_uom         *string  `json:"oil_flow_amount_uom" default:""`
	Oil_gravity                 *float64 `json:"oil_gravity" default:""`
	Permeability_quality        *string  `json:"permeability_quality" default:""`
	Ppdm_guid                   *string  `json:"ppdm_guid" default:""`
	Primary_fluid_recovered     *string  `json:"primary_fluid_recovered" default:""`
	Production_method           *string  `json:"production_method" default:""`
	Prod_string_id              *string  `json:"prod_string_id" default:""`
	Prod_str_form_obs_no        *int     `json:"prod_str_form_obs_no" default:""`
	Rat_hole_diameter           *float64 `json:"rat_hole_diameter" default:""`
	Rat_hole_diameter_ouom      *string  `json:"rat_hole_diameter_ouom" default:""`
	Rat_hole_length             *float64 `json:"rat_hole_length" default:""`
	Rat_hole_length_ouom        *string  `json:"rat_hole_length_ouom" default:""`
	Remark                      *string  `json:"remark" default:""`
	Reported_strat_unit_id      *string  `json:"reported_strat_unit_id" default:""`
	Report_temperature          *float64 `json:"report_temperature" default:""`
	Report_temperature_ouom     *string  `json:"report_temperature_ouom" default:""`
	Report_test_num             *string  `json:"report_test_num" default:""`
	Show_type                   *string  `json:"show_type" default:""`
	Si_flow_ratio               *float64 `json:"si_flow_ratio" default:""`
	Start_time                  *string  `json:"start_time" default:""`
	Start_timezone              *string  `json:"start_timezone" default:""`
	Static_pressure             *float64 `json:"static_pressure" default:""`
	Static_pressure_ouom        *string  `json:"static_pressure_ouom" default:""`
	Strat_age                   *string  `json:"strat_age" default:""`
	Strat_age_name_set_id       *string  `json:"strat_age_name_set_id" default:""`
	Strat_name_set_id           *string  `json:"strat_name_set_id" default:""`
	String_source               *string  `json:"string_source" default:""`
	Sulphur_ind                 *string  `json:"sulphur_ind" default:""`
	Td                          *float64 `json:"td" default:""`
	Td_ouom                     *string  `json:"td_ouom" default:""`
	Temperature_correction      *float64 `json:"temperature_correction" default:""`
	Temperature_correction_ind  *string  `json:"temperature_correction_ind" default:""`
	Temperature_correction_ouom *string  `json:"temperature_correction_ouom" default:""`
	Test_company                *string  `json:"test_company" default:""`
	Test_date                   *string  `json:"test_date" default:""`
	Test_duration               *float64 `json:"test_duration" default:""`
	Test_duration_ouom          *string  `json:"test_duration_ouom" default:""`
	Test_hole_diameter          *float64 `json:"test_hole_diameter" default:""`
	Test_hole_diameter_ouom     *string  `json:"test_hole_diameter_ouom" default:""`
	Test_result_code            *string  `json:"test_result_code" default:""`
	Test_subtype                *string  `json:"test_subtype" default:""`
	Tool_open_time              *string  `json:"tool_open_time" default:""`
	Tool_open_timezone          *string  `json:"tool_open_timezone" default:""`
	Top_choke_desc              *string  `json:"top_choke_desc" default:""`
	Top_depth                   *float64 `json:"top_depth" default:""`
	Top_depth_ouom              *string  `json:"top_depth_ouom" default:""`
	Top_strat_unit_id           *string  `json:"top_strat_unit_id" default:""`
	Water_amount_percent        *float64 `json:"water_amount_percent" default:""`
	Water_cut_percent           *float64 `json:"water_cut_percent" default:""`
	Water_flow_amount           *float64 `json:"water_flow_amount" default:""`
	Water_flow_amount_ouom      *string  `json:"water_flow_amount_ouom" default:""`
	Water_flow_amount_uom       *string  `json:"water_flow_amount_uom" default:""`
	Wellbore_completion_type    *string  `json:"wellbore_completion_type" default:""`
	Z_factor                    *float64 `json:"z_factor" default:""`
	Row_changed_by              *string  `json:"row_changed_by" default:""`
	Row_changed_date            *string  `json:"row_changed_date" default:""`
	Row_created_by              *string  `json:"row_created_by" default:""`
	Row_created_date            *string  `json:"row_created_date" default:""`
	Row_effective_date          *string  `json:"row_effective_date" default:""`
	Row_expiry_date             *string  `json:"row_expiry_date" default:""`
	Row_quality                 *string  `json:"row_quality" default:""`
}
