--------------------------------------------------------
--  File created - Monday-February-13-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ANL_ACCURACY
--------------------------------------------------------

  CREATE TABLE "ADMIN"."ANL_ACCURACY" 
   (	"ANALYSIS_ID" VARCHAR2(40), 
	"ANL_SOURCE" VARCHAR2(40), 
	"ACCURACY_OBS_NO" NUMBER(*,0), 
	"ACCURACY_DESC" VARCHAR2(240), 
	"ACCURACY_TYPE" VARCHAR2(40), 
	"ACTIVE_IND" VARCHAR2(1), 
	"CALCULATED_IND" VARCHAR2(1), 
	"CALCULATE_METHOD_ID" VARCHAR2(40), 
	"CONFIDENCE_TYPE" VARCHAR2(40), 
	"EFFECTIVE_DATE" TIMESTAMP (0), 
	"EXPIRY_DATE" TIMESTAMP (0), 
	"MEASURED_VALUE_IND" VARCHAR2(1), 
	"PPDM_GUID" VARCHAR2(38), 
	"RAW_VALUE_IND" VARCHAR2(1), 
	"REFERENCED_COLUMN_NAME" VARCHAR2(30), 
	"REFERENCED_PPDM_GUID" VARCHAR2(38), 
	"REFERENCED_SYSTEM_ID" VARCHAR2(40), 
	"REFERENCED_TABLE_NAME" VARCHAR2(30), 
	"REMARK" VARCHAR2(2000), 
	"REPEATABILITY_TYPE" VARCHAR2(40), 
	"REPORTED_IND" VARCHAR2(1), 
	"SOURCE" VARCHAR2(40), 
	"STEP_SEQ_NO" NUMBER(*,0), 
	"ROW_CHANGED_BY" VARCHAR2(30), 
	"ROW_CHANGED_DATE" TIMESTAMP (0), 
	"ROW_CREATED_BY" VARCHAR2(30), 
	"ROW_CREATED_DATE" TIMESTAMP (0), 
	"ROW_EFFECTIVE_DATE" TIMESTAMP (0), 
	"ROW_EXPIRY_DATE" TIMESTAMP (0), 
	"ROW_QUALITY" VARCHAR2(40)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table AREA
--------------------------------------------------------

  CREATE TABLE "ADMIN"."AREA" 
   (	"AREA_ID" VARCHAR2(40), 
	"AREA_TYPE" VARCHAR2(40), 
	"ACTIVE_IND" VARCHAR2(1), 
	"AREA_MAX_LATITUDE" NUMBER(14,9), 
	"AREA_MAX_LONGITUDE" NUMBER(14,9), 
	"AREA_MIN_LATITUDE" NUMBER(14,9), 
	"AREA_MIN_LONGITUDE" NUMBER(14,9), 
	"COORD_ACQUISITION_ID" VARCHAR2(40), 
	"COORD_SYSTEM_ID" VARCHAR2(40), 
	"EFFECTIVE_DATE" TIMESTAMP (0), 
	"EXPIRY_DATE" TIMESTAMP (0), 
	"LOCAL_COORD_SYSTEM_ID" VARCHAR2(40), 
	"PPDM_GUID" VARCHAR2(38), 
	"PREFERRED_NAME" VARCHAR2(255), 
	"REMARK" VARCHAR2(240), 
	"SOURCE" VARCHAR2(40), 
	"SOURCE_DOCUMENT_ID" VARCHAR2(40), 
	"ROW_CHANGED_BY" VARCHAR2(30), 
	"ROW_CHANGED_DATE" TIMESTAMP (0), 
	"ROW_CREATED_BY" VARCHAR2(30), 
	"ROW_CREATED_DATE" TIMESTAMP (0), 
	"ROW_EFFECTIVE_DATE" TIMESTAMP (0), 
	"ROW_EXPIRY_DATE" TIMESTAMP (0), 
	"ROW_QUALITY" VARCHAR2(40)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BA_ADDRESS
--------------------------------------------------------

  CREATE TABLE "ADMIN"."BA_ADDRESS" 
   (	"BUSINESS_ASSOCIATE_ID" VARCHAR2(40), 
	"SOURCE" VARCHAR2(40), 
	"ADDRESS_OBS_NO" NUMBER(*,0), 
	"ACTIVE_IND" VARCHAR2(1), 
	"ADDRESSEE_TEXT" VARCHAR2(240), 
	"ADDRESS_TYPE" VARCHAR2(40), 
	"CITY_AREA_ID" VARCHAR2(40), 
	"CITY_AREA_TYPE" VARCHAR2(40), 
	"COUNTRY_AREA_ID" VARCHAR2(40), 
	"COUNTRY_AREA_TYPE" VARCHAR2(40), 
	"EFFECTIVE_DATE" TIMESTAMP (0), 
	"EXPIRY_DATE" TIMESTAMP (0), 
	"FIRST_ADDRESS_LINE" VARCHAR2(1024), 
	"OFFICE_TYPE" VARCHAR2(40), 
	"POSTAL_ZIP_CODE" VARCHAR2(40), 
	"PPDM_GUID" VARCHAR2(38), 
	"PREFERRED_IND" VARCHAR2(1), 
	"PROVINCE_STATE_AREA_ID" VARCHAR2(40), 
	"PROVINCE_STATE_AREA_TYPE" VARCHAR2(40), 
	"REMARK" VARCHAR2(2000), 
	"SECOND_ADDRESS_LINE" VARCHAR2(1024), 
	"SERVICE_PERIOD" VARCHAR2(240), 
	"SERVICE_QUALITY" VARCHAR2(40), 
	"THIRD_ADDRESS_LINE" VARCHAR2(1024), 
	"WITHHOLDING_TAX_IND" VARCHAR2(1), 
	"ROW_CHANGED_BY" VARCHAR2(30), 
	"ROW_CHANGED_DATE" TIMESTAMP (0), 
	"ROW_CREATED_BY" VARCHAR2(30), 
	"ROW_CREATED_DATE" TIMESTAMP (0), 
	"ROW_EFFECTIVE_DATE" TIMESTAMP (0), 
	"ROW_EXPIRY_DATE" TIMESTAMP (0), 
	"ROW_QUALITY" VARCHAR2(40)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BA_ALIAS
--------------------------------------------------------

  CREATE TABLE "ADMIN"."BA_ALIAS" 
   (	"BUSINESS_ASSOCIATE_ID" VARCHAR2(40), 
	"SOURCE" VARCHAR2(40), 
	"BA_ALIAS_ID" VARCHAR2(40), 
	"ABBREVIATION" VARCHAR2(30), 
	"ACTIVE_IND" VARCHAR2(1), 
	"ALIAS_LONG_NAME" VARCHAR2(255), 
	"ALIAS_REASON_TYPE" VARCHAR2(40), 
	"ALIAS_SHORT_NAME" VARCHAR2(30), 
	"ALIAS_TYPE" VARCHAR2(40), 
	"AMENDED_DATE" TIMESTAMP (0), 
	"CREATED_DATE" TIMESTAMP (0), 
	"EFFECTIVE_DATE" TIMESTAMP (0), 
	"EXPIRY_DATE" TIMESTAMP (0), 
	"LANGUAGE_ID" VARCHAR2(40), 
	"ORIGINAL_IND" VARCHAR2(1), 
	"OWNER_BA_ID" VARCHAR2(40), 
	"PASSWORD" VARCHAR2(20), 
	"PPDM_GUID" VARCHAR2(38), 
	"PREFERRED_IND" VARCHAR2(1), 
	"REASON_DESC" VARCHAR2(240), 
	"REMARK" VARCHAR2(2000), 
	"SOURCE_DOCUMENT_ID" VARCHAR2(40), 
	"STRUCKOFF_DATE" TIMESTAMP (0), 
	"SW_APPLICATION_ID" VARCHAR2(40), 
	"USE_RULE" VARCHAR2(2000), 
	"ROW_CHANGED_BY" VARCHAR2(30), 
	"ROW_CHANGED_DATE" TIMESTAMP (0), 
	"ROW_CREATED_BY" VARCHAR2(30), 
	"ROW_CREATED_DATE" TIMESTAMP (0), 
	"ROW_EFFECTIVE_DATE" TIMESTAMP (0), 
	"ROW_EXPIRY_DATE" TIMESTAMP (0), 
	"ROW_QUALITY" VARCHAR2(40)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BUSINESS_ASSOCIATE
--------------------------------------------------------

  CREATE TABLE "ADMIN"."BUSINESS_ASSOCIATE" 
   (	"BUSINESS_ASSOCIATE_ID" VARCHAR2(40), 
	"ACTIVE_IND" VARCHAR2(1), 
	"BA_ABBREVIATION" VARCHAR2(12), 
	"BA_CATEGORY" VARCHAR2(40), 
	"BA_CODE" VARCHAR2(40), 
	"BA_LONG_NAME" VARCHAR2(255), 
	"BA_SHORT_NAME" VARCHAR2(30), 
	"BA_TYPE" VARCHAR2(40), 
	"CREDIT_CHECK_DATE" TIMESTAMP (0), 
	"CREDIT_CHECK_IND" VARCHAR2(1), 
	"CREDIT_CHECK_SOURCE" VARCHAR2(40), 
	"CREDIT_RATING" VARCHAR2(40), 
	"CREDIT_RATING_SOURCE" VARCHAR2(40), 
	"CURRENT_STATUS" VARCHAR2(40), 
	"EFFECTIVE_DATE" TIMESTAMP (0), 
	"EXPIRY_DATE" TIMESTAMP (0), 
	"FIRST_NAME" VARCHAR2(255), 
	"LAST_NAME" VARCHAR2(255), 
	"MIDDLE_INITIAL" VARCHAR2(30), 
	"PPDM_GUID" VARCHAR2(38), 
	"REMARK" VARCHAR2(2000), 
	"SERVICE_PERIOD" VARCHAR2(240), 
	"SOURCE" VARCHAR2(40), 
	"ROW_CHANGED_BY" VARCHAR2(30), 
	"ROW_CHANGED_DATE" TIMESTAMP (0), 
	"ROW_CREATED_BY" VARCHAR2(30), 
	"ROW_CREATED_DATE" TIMESTAMP (0), 
	"ROW_EFFECTIVE_DATE" TIMESTAMP (0), 
	"ROW_EXPIRY_DATE" TIMESTAMP (0), 
	"ROW_QUALITY" VARCHAR2(40)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CONT_TYPE
--------------------------------------------------------

  CREATE TABLE "ADMIN"."CONT_TYPE" 
   (	"CONTRACT_ID" VARCHAR2(40), 
	"CONTRACT_TYPE" VARCHAR2(40), 
	"ACTIVE_IND" VARCHAR2(1), 
	"EFFECTIVE_DATE" TIMESTAMP (0), 
	"EXPIRY_DATE" TIMESTAMP (0), 
	"PPDM_GUID" VARCHAR2(38), 
	"REMARK" VARCHAR2(2000), 
	"SOURCE" VARCHAR2(40), 
	"ROW_CHANGED_BY" VARCHAR2(30), 
	"ROW_CHANGED_DATE" TIMESTAMP (0), 
	"ROW_CREATED_BY" VARCHAR2(30), 
	"ROW_CREATED_DATE" TIMESTAMP (0), 
	"ROW_EFFECTIVE_DATE" TIMESTAMP (0), 
	"ROW_EXPIRY_DATE" TIMESTAMP (0), 
	"ROW_QUALITY" VARCHAR2(40)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FIELD
--------------------------------------------------------

  CREATE TABLE "ADMIN"."FIELD" 
   (	"FIELD_ID" VARCHAR2(40), 
	"ACTIVE_IND" VARCHAR2(1), 
	"AREA_ID" VARCHAR2(40), 
	"AREA_TYPE" VARCHAR2(40), 
	"DISCOVERY_DATE" TIMESTAMP (0), 
	"EFFECTIVE_DATE" TIMESTAMP (0), 
	"EXPIRY_DATE" TIMESTAMP (0), 
	"FIELD_ABBREVIATION" VARCHAR2(12), 
	"FIELD_AREA_OBS_NO" NUMBER(*,0), 
	"FIELD_NAME" VARCHAR2(255), 
	"FIELD_TYPE" VARCHAR2(40), 
	"GROUP_FIELD_ID" VARCHAR2(40), 
	"PPDM_GUID" VARCHAR2(38), 
	"REMARK" VARCHAR2(2000), 
	"SOURCE" VARCHAR2(40), 
	"ROW_CHANGED_BY" VARCHAR2(30), 
	"ROW_CHANGED_DATE" TIMESTAMP (0), 
	"ROW_CREATED_BY" VARCHAR2(30), 
	"ROW_CREATED_DATE" TIMESTAMP (0), 
	"ROW_EFFECTIVE_DATE" TIMESTAMP (0), 
	"ROW_EXPIRY_DATE" TIMESTAMP (0), 
	"ROW_QUALITY" VARCHAR2(40)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LAND_RIGHT
--------------------------------------------------------

  CREATE TABLE "ADMIN"."LAND_RIGHT" 
   (	"LAND_RIGHT_SUBTYPE" VARCHAR2(30), 
	"LAND_RIGHT_ID" VARCHAR2(40), 
	"ACQTN_DATE" TIMESTAMP (0), 
	"ACTIVE_IND" VARCHAR2(1), 
	"AREA_ID" VARCHAR2(40), 
	"AREA_TYPE" VARCHAR2(40), 
	"CALCULATED_INTEREST" NUMBER(15,12), 
	"CASE_SERIAL_NUM" VARCHAR2(30), 
	"CONFIDENTIAL_IND" VARCHAR2(1), 
	"COST_CENTER_NUM" VARCHAR2(30), 
	"EFFECTIVE_DATE" TIMESTAMP (0), 
	"EXPIRY_DATE" TIMESTAMP (0), 
	"FIRST_PLATFORM_APPROVE_DATE" TIMESTAMP (0), 
	"FIRST_PLATFORM_INSTALL_DATE" TIMESTAMP (0), 
	"FIRST_PRODUCTION_DATE" TIMESTAMP (0), 
	"FRACTIONAL_INTEREST" VARCHAR2(100), 
	"GRANTED_RIGHT_TYPE" VARCHAR2(40), 
	"GROSS_SIZE" NUMBER(20,10), 
	"GROSS_SIZE_OUOM" VARCHAR2(40), 
	"HIGH_WATER_DEPTH" NUMBER(15,5), 
	"HIGH_WATER_DEPTH_OUOM" VARCHAR2(40), 
	"INACTIVATION_DATE" TIMESTAMP (0), 
	"INCENT_CERT_NO" NUMBER(*,0), 
	"ISSUE_DATE" TIMESTAMP (0), 
	"JURISDICTION" VARCHAR2(40), 
	"LAND_ACQTN_METHOD" VARCHAR2(40), 
	"LAND_CASE_ACTION" VARCHAR2(40), 
	"LAND_CASE_TYPE" VARCHAR2(40), 
	"LAND_PROPERTY_TYPE" VARCHAR2(40), 
	"LAND_RIGHT_CATEGORY" VARCHAR2(40), 
	"LAND_SALE_NUMBER" VARCHAR2(30), 
	"LAND_SALE_OFFERING_ID" VARCHAR2(40), 
	"LAST_ACTION_DATE" TIMESTAMP (0), 
	"LESSOR_NAME" VARCHAR2(255), 
	"LESSOR_NUM" VARCHAR2(30), 
	"LESSOR_TYPE" VARCHAR2(40), 
	"LOW_WATER_DEPTH" NUMBER(15,5), 
	"LOW_WATER_DEPTH_OUOM" VARCHAR2(40), 
	"MUNICIPALITY" VARCHAR2(40), 
	"OCCUPANT_NAME" VARCHAR2(255), 
	"OFFSHORE_DISTANCE" NUMBER(10,3), 
	"OFFSHORE_DISTANCE_OUOM" VARCHAR2(40), 
	"OIL_SAND_DEPOSIT" VARCHAR2(40), 
	"OVERLAP_IND" VARCHAR2(1), 
	"PLATFORM_COUNT" NUMBER(*,0), 
	"PPDM_GUID" VARCHAR2(38), 
	"PRIMARY_TERM" NUMBER(10,5), 
	"PRIMARY_TERM_OUOM" VARCHAR2(40), 
	"PRODUCING_IND" VARCHAR2(1), 
	"PROPRIETARY_NUM" VARCHAR2(30), 
	"QUALIFICATION_DATE" TIMESTAMP (0), 
	"RECLAMATION_CERT_NUM" VARCHAR2(40), 
	"RECLAMATION_END_DATE" TIMESTAMP (0), 
	"RECLAMATION_START_DATE" TIMESTAMP (0), 
	"RELINQUISHABLE_IND" VARCHAR2(1), 
	"REMARK" VARCHAR2(2000), 
	"RENTAL_ALLOCATION_IND" VARCHAR2(1), 
	"REPORT_ACREAGE_IND" VARCHAR2(1), 
	"SCHEME_APPROVAL_NUM" VARCHAR2(30), 
	"SCHEME_EXPIRY_DATE" TIMESTAMP (0), 
	"SECONDARY_TERM" NUMBER(10,5), 
	"SECONDARY_TERM_OUOM" VARCHAR2(40), 
	"SOURCE" VARCHAR2(40), 
	"SUBSURFACE_IND" VARCHAR2(1), 
	"SURFACE_IND" VARCHAR2(1), 
	"TERMIN_NOTICE_PERIOD" NUMBER(10,5), 
	"TERMIN_NOTICE_PERIOD_OUOM" VARCHAR2(40), 
	"TERM_EXIRY_DATE" TIMESTAMP (0), 
	"UNIT_OPERATED_IND" VARCHAR2(1), 
	"WELL_QUALIFIC_TYPE" VARCHAR2(40), 
	"ROW_CHANGED_BY" VARCHAR2(30), 
	"ROW_CHANGED_DATE" TIMESTAMP (0), 
	"ROW_CREATED_BY" VARCHAR2(30), 
	"ROW_CREATED_DATE" TIMESTAMP (0), 
	"ROW_EFFECTIVE_DATE" TIMESTAMP (0), 
	"ROW_EXPIRY_DATE" TIMESTAMP (0), 
	"ROW_QUALITY" VARCHAR2(40)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LAND_SIZE
--------------------------------------------------------

  CREATE TABLE "ADMIN"."LAND_SIZE" 
   (	"LAND_RIGHT_SUBTYPE" VARCHAR2(30), 
	"LAND_RIGHT_ID" VARCHAR2(40), 
	"SIZE_TYPE" VARCHAR2(40), 
	"SIZE_SEQ_NO" NUMBER(*,0), 
	"ACTIVE_IND" VARCHAR2(1), 
	"BUSINESS_ASSOCIATE_ID" VARCHAR2(40), 
	"EFFECTIVE_DATE" TIMESTAMP (0), 
	"EXPIRY_DATE" TIMESTAMP (0), 
	"GROSS_SIZE" NUMBER(20,10), 
	"INTEREST_SET_ID" VARCHAR2(40), 
	"INTEREST_SET_SEQ_NO" NUMBER(*,0), 
	"NET_SIZE" NUMBER(20,10), 
	"PARTNER_OBS_NO" NUMBER(*,0), 
	"PPDM_GUID" VARCHAR2(38), 
	"REMARK" VARCHAR2(2000), 
	"SIZE_OUOM" VARCHAR2(40), 
	"SOURCE" VARCHAR2(40), 
	"ROW_CHANGED_BY" VARCHAR2(30), 
	"ROW_CHANGED_DATE" TIMESTAMP (0), 
	"ROW_CREATED_BY" VARCHAR2(30), 
	"ROW_CREATED_DATE" TIMESTAMP (0), 
	"ROW_EFFECTIVE_DATE" TIMESTAMP (0), 
	"ROW_EXPIRY_DATE" TIMESTAMP (0), 
	"ROW_QUALITY" VARCHAR2(40)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PPDM_QUALITY_CONTROL
--------------------------------------------------------

  CREATE TABLE "ADMIN"."PPDM_QUALITY_CONTROL" 
   (	"SYSTEM_ID" VARCHAR2(40), 
	"TABLE_NAME" VARCHAR2(30), 
	"QC_SEQ_NO" NUMBER(*,0), 
	"ACTIVE_IND" VARCHAR2(1), 
	"CHECKED_BY_BA_ID" VARCHAR2(40), 
	"COLUMN_NAME" VARCHAR2(30), 
	"CURRENT_DATE_VALUE" TIMESTAMP (0), 
	"CURRENT_NUMERIC_VALUE" FLOAT(126), 
	"CURRENT_NUMERIC_VALUE_OUOM" VARCHAR2(40), 
	"CURRENT_NUMERIC_VALUE_UOM" VARCHAR2(40), 
	"CURRENT_ROW_GUID" VARCHAR2(38), 
	"CURRENT_TEXT_VALUE" VARCHAR2(2000), 
	"DATA_TYPE" VARCHAR2(40), 
	"DONE_BY_BA_ID" VARCHAR2(40), 
	"EFFECTIVE_DATE" TIMESTAMP (0), 
	"EXPIRY_DATE" TIMESTAMP (0), 
	"NULL_DESCRIPTION" VARCHAR2(1024), 
	"PPDM_GUID" VARCHAR2(38), 
	"QC_DATETIME" TIMESTAMP (0), 
	"QC_DESC" VARCHAR2(1024), 
	"QC_STATUS" VARCHAR2(40), 
	"QC_TYPE" VARCHAR2(40), 
	"QUALITY_TYPE" VARCHAR2(40), 
	"REMARK" VARCHAR2(2000), 
	"RETENTION_PERIOD" VARCHAR2(40), 
	"SOURCE" VARCHAR2(40), 
	"ROW_CHANGED_BY" VARCHAR2(30), 
	"ROW_CHANGED_DATE" TIMESTAMP (0), 
	"ROW_CREATED_BY" VARCHAR2(30), 
	"ROW_CREATED_DATE" TIMESTAMP (0), 
	"ROW_EFFECTIVE_DATE" TIMESTAMP (0), 
	"ROW_EXPIRY_DATE" TIMESTAMP (0), 
	"ROW_QUALITY" VARCHAR2(40)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PROJECT
--------------------------------------------------------

  CREATE TABLE "ADMIN"."PROJECT" 
   (	"PROJECT_ID" VARCHAR2(40), 
	"ACTIVE_IND" VARCHAR2(1), 
	"COMPLETE_DATE" TIMESTAMP (0), 
	"CONFIDENTIAL_IND" VARCHAR2(1), 
	"CONFIDENTIAL_RELEASE_DATE" TIMESTAMP (0), 
	"DESCRIPTION" VARCHAR2(240), 
	"EFFECTIVE_DATE" TIMESTAMP (0), 
	"EXPIRY_DATE" TIMESTAMP (0), 
	"FIELD_STATION_IND" VARCHAR2(1), 
	"LAND_RIGHT_IND" VARCHAR2(1), 
	"PDEN_IND" VARCHAR2(1), 
	"PPDM_GUID" VARCHAR2(38), 
	"PROJECT_NAME" VARCHAR2(255), 
	"PROJECT_NUM" VARCHAR2(30), 
	"PROJECT_TYPE" VARCHAR2(40), 
	"REMARK" VARCHAR2(2000), 
	"SEIS_SET_IND" VARCHAR2(1), 
	"SOURCE" VARCHAR2(40), 
	"START_DATE" TIMESTAMP (0), 
	"STRAT_COLUMN_IND" VARCHAR2(1), 
	"STRAT_INTERPRETATION_IND" VARCHAR2(1), 
	"WELL_IND" VARCHAR2(1), 
	"ROW_CHANGED_BY" VARCHAR2(30), 
	"ROW_CHANGED_DATE" TIMESTAMP (0), 
	"ROW_CREATED_BY" VARCHAR2(30), 
	"ROW_CREATED_DATE" TIMESTAMP (0), 
	"ROW_EFFECTIVE_DATE" TIMESTAMP (0), 
	"ROW_EXPIRY_DATE" TIMESTAMP (0), 
	"ROW_QUALITY" VARCHAR2(40)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RA_LR_SIZE_TYPE
--------------------------------------------------------

  CREATE TABLE "ADMIN"."RA_LR_SIZE_TYPE" 
   (	"SIZE_TYPE" VARCHAR2(40), 
	"ALIAS_ID" VARCHAR2(40), 
	"ABBREVIATION" VARCHAR2(30), 
	"ACTIVE_IND" VARCHAR2(1), 
	"ALIAS_LONG_NAME" VARCHAR2(255), 
	"ALIAS_REASON_TYPE" VARCHAR2(40), 
	"ALIAS_SHORT_NAME" VARCHAR2(30), 
	"ALIAS_TYPE" VARCHAR2(40), 
	"AMENDED_DATE" TIMESTAMP (0), 
	"CREATED_DATE" TIMESTAMP (0), 
	"EFFECTIVE_DATE" TIMESTAMP (0), 
	"EXPIRY_DATE" TIMESTAMP (0), 
	"LANGUAGE_ID" VARCHAR2(40), 
	"ORIGINAL_IND" VARCHAR2(1), 
	"OWNER_BA_ID" VARCHAR2(40), 
	"PPDM_GUID" VARCHAR2(38), 
	"PREFERRED_IND" VARCHAR2(1), 
	"REASON_DESC" VARCHAR2(2000), 
	"REMARK" VARCHAR2(2000), 
	"SOURCE" VARCHAR2(40), 
	"SOURCE_DOCUMENT" VARCHAR2(40), 
	"STRUCKOFF_DATE" TIMESTAMP (0), 
	"SW_APPLICATION_ID" VARCHAR2(40), 
	"USE_RULE" VARCHAR2(2000), 
	"ROW_CHANGED_BY" VARCHAR2(30), 
	"ROW_CHANGED_DATE" TIMESTAMP (0), 
	"ROW_CREATED_BY" VARCHAR2(30), 
	"ROW_CREATED_DATE" TIMESTAMP (0), 
	"ROW_EFFECTIVE_DATE" TIMESTAMP (0), 
	"ROW_EXPIRY_DATE" TIMESTAMP (0), 
	"ROW_QUALITY" VARCHAR2(40)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RA_MEDIA_TYPE
--------------------------------------------------------

  CREATE TABLE "ADMIN"."RA_MEDIA_TYPE" 
   (	"MEDIA_TYPE" VARCHAR2(40), 
	"ALIAS_ID" VARCHAR2(40), 
	"ABBREVIATION" VARCHAR2(30), 
	"ACTIVE_IND" VARCHAR2(1), 
	"ALIAS_LONG_NAME" VARCHAR2(255), 
	"ALIAS_REASON_TYPE" VARCHAR2(40), 
	"ALIAS_SHORT_NAME" VARCHAR2(30), 
	"ALIAS_TYPE" VARCHAR2(40), 
	"AMENDED_DATE" TIMESTAMP (0), 
	"CREATED_DATE" TIMESTAMP (0), 
	"EFFECTIVE_DATE" TIMESTAMP (0), 
	"EXPIRY_DATE" TIMESTAMP (0), 
	"LANGUAGE_ID" VARCHAR2(40), 
	"ORIGINAL_IND" VARCHAR2(1), 
	"OWNER_BA_ID" VARCHAR2(40), 
	"PPDM_GUID" VARCHAR2(38), 
	"PREFERRED_IND" VARCHAR2(1), 
	"REASON_DESC" VARCHAR2(2000), 
	"REMARK" VARCHAR2(2000), 
	"SOURCE" VARCHAR2(40), 
	"SOURCE_DOCUMENT" VARCHAR2(40), 
	"STRUCKOFF_DATE" TIMESTAMP (0), 
	"SW_APPLICATION_ID" VARCHAR2(40), 
	"USE_RULE" VARCHAR2(2000), 
	"ROW_CHANGED_BY" VARCHAR2(30), 
	"ROW_CHANGED_DATE" TIMESTAMP (0), 
	"ROW_CREATED_BY" VARCHAR2(30), 
	"ROW_CREATED_DATE" TIMESTAMP (0), 
	"ROW_EFFECTIVE_DATE" TIMESTAMP (0), 
	"ROW_EXPIRY_DATE" TIMESTAMP (0), 
	"ROW_QUALITY" VARCHAR2(40)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RESENT_PRODUCT
--------------------------------------------------------

  CREATE TABLE "ADMIN"."RESENT_PRODUCT" 
   (	"RESENT_ID" VARCHAR2(40), 
	"RESERVE_CLASS_ID" VARCHAR2(40), 
	"PRODUCT_TYPE" VARCHAR2(40), 
	"ACTIVE_IND" VARCHAR2(1), 
	"EFFECTIVE_DATE" TIMESTAMP (0), 
	"EXPIRY_DATE" TIMESTAMP (0), 
	"PPDM_GUID" VARCHAR2(38), 
	"REMARK" VARCHAR2(2000), 
	"REPORT_IND" VARCHAR2(1), 
	"SOURCE" VARCHAR2(40), 
	"ROW_CHANGED_BY" VARCHAR2(30), 
	"ROW_CHANGED_DATE" TIMESTAMP (0), 
	"ROW_CREATED_BY" VARCHAR2(30), 
	"ROW_CREATED_DATE" TIMESTAMP (0), 
	"ROW_EFFECTIVE_DATE" TIMESTAMP (0), 
	"ROW_EXPIRY_DATE" TIMESTAMP (0), 
	"ROW_QUALITY" VARCHAR2(40)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RESENT_VOL_SUMMARY
--------------------------------------------------------

  CREATE TABLE "ADMIN"."RESENT_VOL_SUMMARY" 
   (	"RESENT_ID" VARCHAR2(40), 
	"RESERVE_CLASS_ID" VARCHAR2(40), 
	"PRODUCT_TYPE" VARCHAR2(40), 
	"SUMMARY_ID" VARCHAR2(40), 
	"SUMMARY_OBS_NO" NUMBER(*,0), 
	"ACTIVE_IND" VARCHAR2(1), 
	"ANALYST_BA_ID" VARCHAR2(40), 
	"APPROVED_BY_BA_ID" VARCHAR2(40), 
	"APPROVED_DATE" TIMESTAMP (0), 
	"CREATED_DATE" TIMESTAMP (0), 
	"CREATED_DATE_DESC" VARCHAR2(8), 
	"CURRENT_BALANCE" NUMBER(14,4), 
	"CURRENT_BALANCE_OUOM" VARCHAR2(40), 
	"CURRENT_BALANCE_UOM" VARCHAR2(40), 
	"DECLINE_CASE_ID" VARCHAR2(40), 
	"EFFECTIVE_DATE" TIMESTAMP (0), 
	"EXPIRY_DATE" TIMESTAMP (0), 
	"GROSS_SUMMARY_IND" VARCHAR2(1), 
	"INTEREST_SET_ID" VARCHAR2(40), 
	"INTEREST_SET_PARTNER" VARCHAR2(40), 
	"INTEREST_SET_SEQ_NO" NUMBER(*,0), 
	"MATERIAL_BALANCE_CASE_ID" VARCHAR2(40), 
	"NET_SUMMARY_IND" VARCHAR2(1), 
	"OPEN_BALANCE" NUMBER(14,4), 
	"OPEN_BALANCE_OUOM" VARCHAR2(40), 
	"OPEN_BALANCE_UOM" VARCHAR2(40), 
	"PARTNER_OBS_NO" NUMBER(*,0), 
	"PDEN_ID" VARCHAR2(40), 
	"PDEN_PRODUCT_TYPE" VARCHAR2(40), 
	"PDEN_SOURCE" VARCHAR2(40), 
	"PDEN_SUBTYPE" VARCHAR2(30), 
	"PPDM_GUID" VARCHAR2(38), 
	"REMARK" VARCHAR2(2000), 
	"REPORT_IND" VARCHAR2(1), 
	"SOURCE" VARCHAR2(40), 
	"VOLUME_METHOD" VARCHAR2(40), 
	"VOL_ANAL_CASE_ID" VARCHAR2(40), 
	"YIELD_PARENT_PRODUCT" VARCHAR2(40), 
	"YIELD_RATE" NUMBER(14,4), 
	"YIELD_RATE_OUOM" VARCHAR2(40), 
	"YIELD_RATE_UOM" VARCHAR2(40), 
	"ROW_CHANGED_BY" VARCHAR2(30), 
	"ROW_CHANGED_DATE" TIMESTAMP (0), 
	"ROW_CREATED_BY" VARCHAR2(30), 
	"ROW_CREATED_DATE" TIMESTAMP (0), 
	"ROW_EFFECTIVE_DATE" TIMESTAMP (0), 
	"ROW_EXPIRY_DATE" TIMESTAMP (0), 
	"ROW_QUALITY" VARCHAR2(40)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RESERVE_CLASS
--------------------------------------------------------

  CREATE TABLE "ADMIN"."RESERVE_CLASS" 
   (	"RESERVE_CLASS_ID" VARCHAR2(40), 
	"ABBREVIATION" VARCHAR2(12), 
	"ACTIVE_IND" VARCHAR2(1), 
	"CONFIDENCE_TYPE" VARCHAR2(40), 
	"DEVELOPED_IND" VARCHAR2(1), 
	"EFFECTIVE_DATE" TIMESTAMP (0), 
	"EXPIRY_DATE" TIMESTAMP (0), 
	"LONG_NAME" VARCHAR2(255), 
	"OWNER_BA_ID" VARCHAR2(40), 
	"PPDM_GUID" VARCHAR2(38), 
	"PREFERRED_IND" VARCHAR2(1), 
	"PRODUCTION_IND" VARCHAR2(1), 
	"REMARK" VARCHAR2(2000), 
	"SHORT_NAME" VARCHAR2(30), 
	"SOURCE" VARCHAR2(40), 
	"USE_TYPE" VARCHAR2(40), 
	"ROW_CHANGED_BY" VARCHAR2(30), 
	"ROW_CHANGED_DATE" TIMESTAMP (0), 
	"ROW_CREATED_BY" VARCHAR2(30), 
	"ROW_CREATED_DATE" TIMESTAMP (0), 
	"ROW_EFFECTIVE_DATE" TIMESTAMP (0), 
	"ROW_EXPIRY_DATE" TIMESTAMP (0), 
	"ROW_QUALITY" VARCHAR2(40)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RM_DATA_STORE
--------------------------------------------------------

  CREATE TABLE "ADMIN"."RM_DATA_STORE" 
   (	"STORE_ID" VARCHAR2(40), 
	"ACTIVE_IND" VARCHAR2(1), 
	"ADDRESS_OBS_NO" NUMBER(*,0), 
	"ADDRESS_SOURCE" VARCHAR2(40), 
	"BUSINESS_ASSOCIATE_ID" VARCHAR2(40), 
	"CONTAINED_BY_STORE_ID" VARCHAR2(40), 
	"DATA_STORE_HIER_ID" VARCHAR2(40), 
	"DATA_STORE_NAME" VARCHAR2(255), 
	"DATA_STORE_TYPE" VARCHAR2(40), 
	"EFFECTIVE_DATE" TIMESTAMP (0), 
	"EXPIRY_DATE" TIMESTAMP (0), 
	"HIER_LEVEL_ID" VARCHAR2(40), 
	"LOCATION_ID" VARCHAR2(40), 
	"LONG_LOCATION" VARCHAR2(40), 
	"PHYSICAL_STORE_STATUS" VARCHAR2(40), 
	"PPDM_GUID" VARCHAR2(38), 
	"REMARK" VARCHAR2(2000), 
	"SHORT_LOCATION" VARCHAR2(40), 
	"SOURCE" VARCHAR2(40), 
	"TOTAL_CAPACITY" NUMBER(*,0), 
	"USED_CAPACITY" NUMBER(*,0), 
	"USED_CAPACITY_DATE" TIMESTAMP (0), 
	"ROW_CHANGED_BY" VARCHAR2(30), 
	"ROW_CHANGED_DATE" TIMESTAMP (0), 
	"ROW_CREATED_BY" VARCHAR2(30), 
	"ROW_CREATED_DATE" TIMESTAMP (0), 
	"ROW_EFFECTIVE_DATE" TIMESTAMP (0), 
	"ROW_EXPIRY_DATE" TIMESTAMP (0), 
	"ROW_QUALITY" VARCHAR2(40)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RM_DATA_STORE_HIER_LEVEL
--------------------------------------------------------

  CREATE TABLE "ADMIN"."RM_DATA_STORE_HIER_LEVEL" 
   (	"DATA_STORE_HIER_ID" VARCHAR2(40), 
	"HIER_LEVEL_ID" VARCHAR2(40), 
	"ACTIVE_IND" VARCHAR2(1), 
	"DATA_STORE_TYPE" VARCHAR2(40), 
	"EFFECTIVE_DATE" TIMESTAMP (0), 
	"EXPIRY_DATE" TIMESTAMP (0), 
	"LEVEL_NAME" VARCHAR2(255), 
	"LEVEL_SEQ_NO" NUMBER(*,0), 
	"PARENT_HIER_LEVEL_ID" VARCHAR2(40), 
	"PPDM_GUID" VARCHAR2(38), 
	"REMARK" VARCHAR2(2000), 
	"SOURCE" VARCHAR2(40), 
	"ROW_CHANGED_BY" VARCHAR2(30), 
	"ROW_CHANGED_DATE" TIMESTAMP (0), 
	"ROW_CREATED_BY" VARCHAR2(30), 
	"ROW_CREATED_DATE" TIMESTAMP (0), 
	"ROW_EFFECTIVE_DATE" TIMESTAMP (0), 
	"ROW_EXPIRY_DATE" TIMESTAMP (0), 
	"ROW_QUALITY" VARCHAR2(40)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RM_PHYSICAL_ITEM
--------------------------------------------------------

  CREATE TABLE "ADMIN"."RM_PHYSICAL_ITEM" 
   (	"PHYSICAL_ITEM_ID" VARCHAR2(40), 
	"ACTIVE_IND" VARCHAR2(1), 
	"BAR_CODE" VARCHAR2(240), 
	"CATALOGUE_BY_NAME" VARCHAR2(255), 
	"CATALOGUE_DATE" TIMESTAMP (0), 
	"CERTIFIED_TRUE_COPY_IND" VARCHAR2(1), 
	"CIRCULATION_ALLOWED_IND" VARCHAR2(1), 
	"CIRCULATION_OUT_IND" VARCHAR2(1), 
	"COLOR_FORMAT" VARCHAR2(40), 
	"CREATE_DATE" TIMESTAMP (0), 
	"DIGITAL_FORMAT" VARCHAR2(40), 
	"DIGITAL_SIZE" FLOAT(126), 
	"DIGITAL_SIZE_UOM" VARCHAR2(40), 
	"DIM_HEIGHT" NUMBER(10,5), 
	"DIM_HEIGHT_UOM" VARCHAR2(40), 
	"DIM_LENGTH" NUMBER(10,5), 
	"DIM_LENGTH_UOM" VARCHAR2(40), 
	"DIM_WEIGHT" NUMBER(10,5), 
	"DIM_WEIGHT_UOM" VARCHAR2(40), 
	"DIM_WIDTH" NUMBER(10,5), 
	"DIM_WIDTH_UOM" VARCHAR2(40), 
	"EFFECTIVE_DATE" TIMESTAMP (0), 
	"EXPIRY_DATE" TIMESTAMP (0), 
	"FILE_COUNT" NUMBER(*,0), 
	"GROUP_IND" VARCHAR2(1), 
	"IMAGE_RESOLUTION_UOM" VARCHAR2(40), 
	"IMAGE_X_RESOLUTION" NUMBER(10,5), 
	"IMAGE_Y_RESOLUTION" NUMBER(10,5), 
	"ITEM_CATEGORY" VARCHAR2(40), 
	"ITEM_SUB_CATEGORY" VARCHAR2(40), 
	"LABEL" VARCHAR2(30), 
	"LANGUAGE" VARCHAR2(40), 
	"LAST_CONDITION" VARCHAR2(40), 
	"LOCATION_REFERENCE" VARCHAR2(240), 
	"MEDIA_TYPE" VARCHAR2(40), 
	"ORIGINAL_FILE_NAME" VARCHAR2(255), 
	"ORIGINAL_IND" VARCHAR2(1), 
	"OUTPUT_FILE_NAME" VARCHAR2(255), 
	"PAGE_COUNT" NUMBER(10,5), 
	"PHYSICAL_ITEM_STATUS" VARCHAR2(40), 
	"PPDM_GUID" VARCHAR2(38), 
	"PREFERRED_IND" VARCHAR2(1), 
	"QC_BY_NAME" VARCHAR2(255), 
	"REMARK" VARCHAR2(2000), 
	"RETENTION_PERIOD" VARCHAR2(40), 
	"SALE_ALLOWED_IND" VARCHAR2(1), 
	"SOURCE" VARCHAR2(40), 
	"STORE_ID" VARCHAR2(40), 
	"ROW_CHANGED_BY" VARCHAR2(30), 
	"ROW_CHANGED_DATE" TIMESTAMP (0), 
	"ROW_CREATED_BY" VARCHAR2(30), 
	"ROW_CREATED_DATE" TIMESTAMP (0), 
	"ROW_EFFECTIVE_DATE" TIMESTAMP (0), 
	"ROW_EXPIRY_DATE" TIMESTAMP (0), 
	"ROW_QUALITY" VARCHAR2(40)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table R_ADDRESS_TYPE
--------------------------------------------------------

  CREATE TABLE "ADMIN"."R_ADDRESS_TYPE" 
   (	"ADDRESS_TYPE" VARCHAR2(40), 
	"ABBREVIATION" VARCHAR2(12), 
	"ACTIVE_IND" VARCHAR2(1), 
	"EFFECTIVE_DATE" TIMESTAMP (0), 
	"EXPIRY_DATE" TIMESTAMP (0), 
	"LONG_NAME" VARCHAR2(255), 
	"PPDM_GUID" VARCHAR2(38), 
	"REMARK" VARCHAR2(2000), 
	"SHORT_NAME" VARCHAR2(30), 
	"SOURCE" VARCHAR2(40), 
	"ROW_CHANGED_BY" VARCHAR2(30), 
	"ROW_CHANGED_DATE" TIMESTAMP (0), 
	"ROW_CREATED_BY" VARCHAR2(30), 
	"ROW_CREATED_DATE" TIMESTAMP (0), 
	"ROW_EFFECTIVE_DATE" TIMESTAMP (0), 
	"ROW_EXPIRY_DATE" TIMESTAMP (0), 
	"ROW_QUALITY" VARCHAR2(40)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table R_AUTHOR_TYPE
--------------------------------------------------------

  CREATE TABLE "ADMIN"."R_AUTHOR_TYPE" 
   (	"AUTHOR_TYPE" VARCHAR2(40), 
	"ABBREVIATION" VARCHAR2(12), 
	"ACTIVE_IND" VARCHAR2(1), 
	"EFFECTIVE_DATE" TIMESTAMP (0), 
	"EXPIRY_DATE" TIMESTAMP (0), 
	"LONG_NAME" VARCHAR2(255), 
	"PPDM_GUID" VARCHAR2(38), 
	"REMARK" VARCHAR2(2000), 
	"SHORT_NAME" VARCHAR2(30), 
	"SOURCE" VARCHAR2(40), 
	"ROW_CHANGED_BY" VARCHAR2(30), 
	"ROW_CHANGED_DATE" TIMESTAMP (0), 
	"ROW_CREATED_BY" VARCHAR2(30), 
	"ROW_CREATED_DATE" TIMESTAMP (0), 
	"ROW_EFFECTIVE_DATE" TIMESTAMP (0), 
	"ROW_EXPIRY_DATE" TIMESTAMP (0), 
	"ROW_QUALITY" VARCHAR2(40)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table R_BA_CATEGORY
--------------------------------------------------------

  CREATE TABLE "ADMIN"."R_BA_CATEGORY" 
   (	"BA_CATEGORY" VARCHAR2(40), 
	"ABBREVIATION" VARCHAR2(12), 
	"ACTIVE_IND" VARCHAR2(1), 
	"EFFECTIVE_DATE" TIMESTAMP (0), 
	"EXPIRY_DATE" TIMESTAMP (0), 
	"LONG_NAME" VARCHAR2(255), 
	"PPDM_GUID" VARCHAR2(38), 
	"REMARK" VARCHAR2(2000), 
	"SHORT_NAME" VARCHAR2(30), 
	"SOURCE" VARCHAR2(40), 
	"ROW_CHANGED_BY" VARCHAR2(30), 
	"ROW_CHANGED_DATE" TIMESTAMP (0), 
	"ROW_CREATED_BY" VARCHAR2(30), 
	"ROW_CREATED_DATE" TIMESTAMP (0), 
	"ROW_EFFECTIVE_DATE" TIMESTAMP (0), 
	"ROW_EXPIRY_DATE" TIMESTAMP (0), 
	"ROW_QUALITY" VARCHAR2(40)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table R_BA_STATUS
--------------------------------------------------------

  CREATE TABLE "ADMIN"."R_BA_STATUS" 
   (	"BA_STATUS" VARCHAR2(40), 
	"ABBREVIATION" VARCHAR2(12), 
	"ACTIVE_IND" VARCHAR2(1), 
	"EFFECTIVE_DATE" TIMESTAMP (0), 
	"EXPIRY_DATE" TIMESTAMP (0), 
	"LONG_NAME" VARCHAR2(255), 
	"PPDM_GUID" VARCHAR2(38), 
	"REMARK" VARCHAR2(2000), 
	"SHORT_NAME" VARCHAR2(30), 
	"SOURCE" VARCHAR2(40), 
	"ROW_CHANGED_BY" VARCHAR2(30), 
	"ROW_CHANGED_DATE" TIMESTAMP (0), 
	"ROW_CREATED_BY" VARCHAR2(30), 
	"ROW_CREATED_DATE" TIMESTAMP (0), 
	"ROW_EFFECTIVE_DATE" TIMESTAMP (0), 
	"ROW_EXPIRY_DATE" TIMESTAMP (0), 
	"ROW_QUALITY" VARCHAR2(40)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table R_BA_TYPE
--------------------------------------------------------

  CREATE TABLE "ADMIN"."R_BA_TYPE" 
   (	"BA_TYPE" VARCHAR2(40), 
	"ABBREVIATION" VARCHAR2(12), 
	"ACTIVE_IND" VARCHAR2(1), 
	"EFFECTIVE_DATE" TIMESTAMP (0), 
	"EXPIRY_DATE" TIMESTAMP (0), 
	"LONG_NAME" VARCHAR2(255), 
	"PPDM_GUID" VARCHAR2(38), 
	"REMARK" VARCHAR2(2000), 
	"SHORT_NAME" VARCHAR2(30), 
	"SOURCE" VARCHAR2(40), 
	"ROW_CHANGED_BY" VARCHAR2(30), 
	"ROW_CHANGED_DATE" TIMESTAMP (0), 
	"ROW_CREATED_BY" VARCHAR2(30), 
	"ROW_CREATED_DATE" TIMESTAMP (0), 
	"ROW_EFFECTIVE_DATE" TIMESTAMP (0), 
	"ROW_EXPIRY_DATE" TIMESTAMP (0), 
	"ROW_QUALITY" VARCHAR2(40)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table R_DATA_STORE_TYPE
--------------------------------------------------------

  CREATE TABLE "ADMIN"."R_DATA_STORE_TYPE" 
   (	"DATA_STORE_TYPE" VARCHAR2(40), 
	"ABBREVIATION" VARCHAR2(12), 
	"ACTIVE_IND" VARCHAR2(1), 
	"EFFECTIVE_DATE" TIMESTAMP (0), 
	"EXPIRY_DATE" TIMESTAMP (0), 
	"LONG_NAME" VARCHAR2(255), 
	"PPDM_GUID" VARCHAR2(38), 
	"REMARK" VARCHAR2(2000), 
	"SHORT_NAME" VARCHAR2(30), 
	"SOURCE" VARCHAR2(40), 
	"ROW_CHANGED_BY" VARCHAR2(30), 
	"ROW_CHANGED_DATE" TIMESTAMP (0), 
	"ROW_CREATED_BY" VARCHAR2(30), 
	"ROW_CREATED_DATE" TIMESTAMP (0), 
	"ROW_EFFECTIVE_DATE" TIMESTAMP (0), 
	"ROW_EXPIRY_DATE" TIMESTAMP (0), 
	"ROW_QUALITY" VARCHAR2(40)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table R_DOCUMENT_TYPE
--------------------------------------------------------

  CREATE TABLE "ADMIN"."R_DOCUMENT_TYPE" 
   (	"DOCUMENT_TYPE" VARCHAR2(40), 
	"ABBREVIATION" VARCHAR2(12), 
	"ACTIVE_IND" VARCHAR2(1), 
	"EFFECTIVE_DATE" TIMESTAMP (0), 
	"EXPIRY_DATE" TIMESTAMP (0), 
	"LONG_NAME" VARCHAR2(255), 
	"PPDM_GUID" VARCHAR2(38), 
	"REMARK" VARCHAR2(2000), 
	"SHORT_NAME" VARCHAR2(30), 
	"SOURCE" VARCHAR2(40), 
	"ROW_CHANGED_BY" VARCHAR2(30), 
	"ROW_CHANGED_DATE" TIMESTAMP (0), 
	"ROW_CREATED_BY" VARCHAR2(30), 
	"ROW_CREATED_DATE" TIMESTAMP (0), 
	"ROW_EFFECTIVE_DATE" TIMESTAMP (0), 
	"ROW_EXPIRY_DATE" TIMESTAMP (0), 
	"ROW_QUALITY" VARCHAR2(40)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table R_FAULT_TYPE
--------------------------------------------------------

  CREATE TABLE "ADMIN"."R_FAULT_TYPE" 
   (	"FAULT_TYPE" VARCHAR2(40), 
	"ABBREVIATION" VARCHAR2(12), 
	"ACTIVE_IND" VARCHAR2(1), 
	"EFFECTIVE_DATE" TIMESTAMP (0), 
	"EXPIRY_DATE" TIMESTAMP (0), 
	"LONG_NAME" VARCHAR2(255), 
	"PPDM_GUID" VARCHAR2(38), 
	"REMARK" VARCHAR2(2000), 
	"SHORT_NAME" VARCHAR2(30), 
	"SOURCE" VARCHAR2(40), 
	"ROW_CHANGED_BY" VARCHAR2(30), 
	"ROW_CHANGED_DATE" TIMESTAMP (0), 
	"ROW_CREATED_BY" VARCHAR2(30), 
	"ROW_CREATED_DATE" TIMESTAMP (0), 
	"ROW_EFFECTIVE_DATE" TIMESTAMP (0), 
	"ROW_EXPIRY_DATE" TIMESTAMP (0), 
	"ROW_QUALITY" VARCHAR2(40)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table R_LANGUAGE
--------------------------------------------------------

  CREATE TABLE "ADMIN"."R_LANGUAGE" 
   (	"LANGUAGE_ID" VARCHAR2(40), 
	"ABBREVIATION" VARCHAR2(12), 
	"ACTIVE_IND" VARCHAR2(1), 
	"EFFECTIVE_DATE" TIMESTAMP (0), 
	"EXPIRY_DATE" TIMESTAMP (0), 
	"LONG_NAME" VARCHAR2(255), 
	"PPDM_GUID" VARCHAR2(38), 
	"REMARK" VARCHAR2(2000), 
	"SHORT_NAME" VARCHAR2(30), 
	"SOURCE" VARCHAR2(40), 
	"ROW_CHANGED_BY" VARCHAR2(30), 
	"ROW_CHANGED_DATE" TIMESTAMP (0), 
	"ROW_CREATED_BY" VARCHAR2(30), 
	"ROW_CREATED_DATE" TIMESTAMP (0), 
	"ROW_EFFECTIVE_DATE" TIMESTAMP (0), 
	"ROW_EXPIRY_DATE" TIMESTAMP (0), 
	"ROW_QUALITY" VARCHAR2(40)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table R_PPDM_ROW_QUALITY
--------------------------------------------------------

  CREATE TABLE "ADMIN"."R_PPDM_ROW_QUALITY" 
   (	"ROW_QUALITY_ID" VARCHAR2(40), 
	"ABBREVIATION" VARCHAR2(12), 
	"ACTIVE_IND" VARCHAR2(1), 
	"EFFECTIVE_DATE" TIMESTAMP (0), 
	"EXPIRY_DATE" TIMESTAMP (0), 
	"LONG_NAME" VARCHAR2(255), 
	"PPDM_GUID" VARCHAR2(38), 
	"REMARK" VARCHAR2(2000), 
	"SHORT_NAME" VARCHAR2(30), 
	"SOURCE" VARCHAR2(40), 
	"ROW_CHANGED_BY" VARCHAR2(30), 
	"ROW_CHANGED_DATE" TIMESTAMP (0), 
	"ROW_CREATED_BY" VARCHAR2(30), 
	"ROW_CREATED_DATE" TIMESTAMP (0), 
	"ROW_EFFECTIVE_DATE" TIMESTAMP (0), 
	"ROW_EXPIRY_DATE" TIMESTAMP (0), 
	"ROW_QUALITY" VARCHAR2(40)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table R_PUBLICATION_NAME
--------------------------------------------------------

  CREATE TABLE "ADMIN"."R_PUBLICATION_NAME" 
   (	"PUBLICATION" VARCHAR2(40), 
	"ABBREVIATION" VARCHAR2(12), 
	"ACTIVE_IND" VARCHAR2(1), 
	"EFFECTIVE_DATE" TIMESTAMP (0), 
	"EXPIRY_DATE" TIMESTAMP (0), 
	"LONG_NAME" VARCHAR2(255), 
	"PPDM_GUID" VARCHAR2(38), 
	"REMARK" VARCHAR2(2000), 
	"SHORT_NAME" VARCHAR2(30), 
	"SOURCE" VARCHAR2(40), 
	"ROW_CHANGED_BY" VARCHAR2(30), 
	"ROW_CHANGED_DATE" TIMESTAMP (0), 
	"ROW_CREATED_BY" VARCHAR2(30), 
	"ROW_CREATED_DATE" TIMESTAMP (0), 
	"ROW_EFFECTIVE_DATE" TIMESTAMP (0), 
	"ROW_EXPIRY_DATE" TIMESTAMP (0), 
	"ROW_QUALITY" VARCHAR2(40)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table R_SERVICE_QUALITY
--------------------------------------------------------

  CREATE TABLE "ADMIN"."R_SERVICE_QUALITY" 
   (	"SERVICE_QUALITY" VARCHAR2(40), 
	"ABBREVIATION" VARCHAR2(12), 
	"ACTIVE_IND" VARCHAR2(1), 
	"EFFECTIVE_DATE" TIMESTAMP (0), 
	"EXPIRY_DATE" TIMESTAMP (0), 
	"LONG_NAME" VARCHAR2(255), 
	"PPDM_GUID" VARCHAR2(38), 
	"REMARK" VARCHAR2(2000), 
	"SHORT_NAME" VARCHAR2(30), 
	"SOURCE" VARCHAR2(40), 
	"ROW_CHANGED_BY" VARCHAR2(30), 
	"ROW_CHANGED_DATE" TIMESTAMP (0), 
	"ROW_CREATED_BY" VARCHAR2(30), 
	"ROW_CREATED_DATE" TIMESTAMP (0), 
	"ROW_EFFECTIVE_DATE" TIMESTAMP (0), 
	"ROW_EXPIRY_DATE" TIMESTAMP (0), 
	"ROW_QUALITY" VARCHAR2(40)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table R_SOURCE
--------------------------------------------------------

  CREATE TABLE "ADMIN"."R_SOURCE" 
   (	"SOURCE" VARCHAR2(40), 
	"ABBREVIATION" VARCHAR2(12), 
	"ACTIVE_IND" VARCHAR2(1), 
	"EFFECTIVE_DATE" TIMESTAMP (0), 
	"EXPIRY_DATE" TIMESTAMP (0), 
	"LONG_NAME" VARCHAR2(255), 
	"PPDM_GUID" VARCHAR2(38), 
	"REMARK" VARCHAR2(2000), 
	"ROW_SOURCE" VARCHAR2(40), 
	"SHORT_NAME" VARCHAR2(30), 
	"ROW_CHANGED_BY" VARCHAR2(30), 
	"ROW_CHANGED_DATE" TIMESTAMP (0), 
	"ROW_CREATED_BY" VARCHAR2(30), 
	"ROW_CREATED_DATE" TIMESTAMP (0), 
	"ROW_EFFECTIVE_DATE" TIMESTAMP (0), 
	"ROW_EXPIRY_DATE" TIMESTAMP (0), 
	"ROW_QUALITY" VARCHAR2(40)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table R_STORE_STATUS
--------------------------------------------------------

  CREATE TABLE "ADMIN"."R_STORE_STATUS" 
   (	"PHYSICAL_STORE_STATUS" VARCHAR2(40), 
	"ABBREVIATION" VARCHAR2(12), 
	"ACTIVE_IND" VARCHAR2(1), 
	"EFFECTIVE_DATE" TIMESTAMP (0), 
	"EXPIRY_DATE" TIMESTAMP (0), 
	"LONG_NAME" VARCHAR2(255), 
	"PPDM_GUID" VARCHAR2(38), 
	"REMARK" VARCHAR2(2000), 
	"SHORT_NAME" VARCHAR2(30), 
	"SOURCE" VARCHAR2(40), 
	"ROW_CHANGED_BY" VARCHAR2(30), 
	"ROW_CHANGED_DATE" TIMESTAMP (0), 
	"ROW_CREATED_BY" VARCHAR2(30), 
	"ROW_CREATED_DATE" TIMESTAMP (0), 
	"ROW_EFFECTIVE_DATE" TIMESTAMP (0), 
	"ROW_EXPIRY_DATE" TIMESTAMP (0), 
	"ROW_QUALITY" VARCHAR2(40)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table R_STRAT_STATUS
--------------------------------------------------------

  CREATE TABLE "ADMIN"."R_STRAT_STATUS" 
   (	"STRAT_STATUS" VARCHAR2(40), 
	"ABBREVIATION" VARCHAR2(12), 
	"ACTIVE_IND" VARCHAR2(1), 
	"EFFECTIVE_DATE" TIMESTAMP (0), 
	"EXPIRY_DATE" TIMESTAMP (0), 
	"LONG_NAME" VARCHAR2(255), 
	"PPDM_GUID" VARCHAR2(38), 
	"REMARK" VARCHAR2(2000), 
	"SHORT_NAME" VARCHAR2(30), 
	"SOURCE" VARCHAR2(40), 
	"ROW_CHANGED_BY" VARCHAR2(30), 
	"ROW_CHANGED_DATE" TIMESTAMP (0), 
	"ROW_CREATED_BY" VARCHAR2(30), 
	"ROW_CREATED_DATE" TIMESTAMP (0), 
	"ROW_EFFECTIVE_DATE" TIMESTAMP (0), 
	"ROW_EXPIRY_DATE" TIMESTAMP (0), 
	"ROW_QUALITY" VARCHAR2(40)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table R_STRAT_TYPE
--------------------------------------------------------

  CREATE TABLE "ADMIN"."R_STRAT_TYPE" 
   (	"STRAT_TYPE" VARCHAR2(40), 
	"ABBREVIATION" VARCHAR2(12), 
	"ACTIVE_IND" VARCHAR2(1), 
	"EFFECTIVE_DATE" TIMESTAMP (0), 
	"EXPIRY_DATE" TIMESTAMP (0), 
	"LONG_NAME" VARCHAR2(255), 
	"PPDM_GUID" VARCHAR2(38), 
	"REMARK" VARCHAR2(2000), 
	"SHORT_NAME" VARCHAR2(30), 
	"SOURCE" VARCHAR2(40), 
	"ROW_CHANGED_BY" VARCHAR2(30), 
	"ROW_CHANGED_DATE" TIMESTAMP (0), 
	"ROW_CREATED_BY" VARCHAR2(30), 
	"ROW_CREATED_DATE" TIMESTAMP (0), 
	"ROW_EFFECTIVE_DATE" TIMESTAMP (0), 
	"ROW_EXPIRY_DATE" TIMESTAMP (0), 
	"ROW_QUALITY" VARCHAR2(40)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SOURCE_DOCUMENT
--------------------------------------------------------

  CREATE TABLE "ADMIN"."SOURCE_DOCUMENT" 
   (	"SOURCE_DOCUMENT_ID" VARCHAR2(40), 
	"ABBREVIATION" VARCHAR2(12), 
	"ACTIVE_IND" VARCHAR2(1), 
	"DOCUMENT_TITLE" VARCHAR2(240), 
	"DOCUMENT_TYPE" VARCHAR2(40), 
	"EFFECTIVE_DATE" TIMESTAMP (0), 
	"EXPIRY_DATE" TIMESTAMP (0), 
	"FIGURE_REFERENCE" VARCHAR2(240), 
	"ISSUE" VARCHAR2(10), 
	"LANGUAGE" VARCHAR2(40), 
	"PAGE_REFERENCE" VARCHAR2(20), 
	"PLATE_REFERENCE" VARCHAR2(240), 
	"PPDM_GUID" VARCHAR2(38), 
	"PUBLICATION" VARCHAR2(40), 
	"PUBLICATION_DATE" TIMESTAMP (0), 
	"PUBLICATION_YEAR" NUMBER(*,0), 
	"PUBLISHER" VARCHAR2(240), 
	"REMARK" VARCHAR2(2000), 
	"SOURCE" VARCHAR2(40), 
	"ROW_CHANGED_BY" VARCHAR2(30), 
	"ROW_CHANGED_DATE" TIMESTAMP (0), 
	"ROW_CREATED_BY" VARCHAR2(30), 
	"ROW_CREATED_DATE" TIMESTAMP (0), 
	"ROW_EFFECTIVE_DATE" TIMESTAMP (0), 
	"ROW_EXPIRY_DATE" TIMESTAMP (0), 
	"ROW_QUALITY" VARCHAR2(40)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SOURCE_DOC_AUTHOR
--------------------------------------------------------

  CREATE TABLE "ADMIN"."SOURCE_DOC_AUTHOR" 
   (	"SOURCE_DOCUMENT_ID" VARCHAR2(40), 
	"AUTHOR_ID" VARCHAR2(40), 
	"ACTIVE_IND" VARCHAR2(1), 
	"AUTHOR_BA_ID" VARCHAR2(40), 
	"AUTHOR_FIRST_NAME" VARCHAR2(30), 
	"AUTHOR_INITIAL" VARCHAR2(30), 
	"AUTHOR_LAST_NAME" VARCHAR2(30), 
	"AUTHOR_SEQ_NO" NUMBER(*,0), 
	"AUTHOR_TYPE" VARCHAR2(40), 
	"EFFECTIVE_DATE" TIMESTAMP (0), 
	"EXPIRY_DATE" TIMESTAMP (0), 
	"PPDM_GUID" VARCHAR2(38), 
	"REMARK" VARCHAR2(2000), 
	"SOURCE" VARCHAR2(40), 
	"ROW_CHANGED_BY" VARCHAR2(30), 
	"ROW_CHANGED_DATE" TIMESTAMP (0), 
	"ROW_CREATED_BY" VARCHAR2(30), 
	"ROW_CREATED_DATE" TIMESTAMP (0), 
	"ROW_EFFECTIVE_DATE" TIMESTAMP (0), 
	"ROW_EXPIRY_DATE" TIMESTAMP (0), 
	"ROW_QUALITY" VARCHAR2(40)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SPATIAL_DESCRIPTION
--------------------------------------------------------

  CREATE TABLE "ADMIN"."SPATIAL_DESCRIPTION" 
   (	"SPATIAL_DESCRIPTION_ID" VARCHAR2(40), 
	"SPATIAL_OBS_NO" NUMBER(*,0), 
	"ACTIVE_IND" VARCHAR2(1), 
	"CARTER_IND" VARCHAR2(1), 
	"CONGRESS_IND" VARCHAR2(1), 
	"COORD_ACQUISITION_ID" VARCHAR2(40), 
	"COORD_SYSTEM_ID" VARCHAR2(40), 
	"DLS_IND" VARCHAR2(1), 
	"EFFECTIVE_DATE" TIMESTAMP (0), 
	"EXPIRY_DATE" TIMESTAMP (0), 
	"FPS_IND" VARCHAR2(1), 
	"GEODETIC_IND" VARCHAR2(1), 
	"GROSS_SIZE" NUMBER(20,10), 
	"GROSS_SIZE_OUOM" VARCHAR2(40), 
	"INACTIVATION_DATE" TIMESTAMP (0), 
	"LIBYA_IND" VARCHAR2(1), 
	"LINE_IND" VARCHAR2(1), 
	"LINE_VERSION_IND" VARCHAR2(1), 
	"LOCAL_COORD_SYSTEM_ID" VARCHAR2(40), 
	"MAX_LATITUDE" NUMBER(14,9), 
	"MAX_LONGITUDE" NUMBER(14,9), 
	"MINERAL_ZONE_IND" VARCHAR2(1), 
	"MIN_LATITUDE" NUMBER(14,9), 
	"MIN_LONGITUDE" NUMBER(14,9), 
	"NE_LOC_IND" VARCHAR2(1), 
	"NORTH_SEA_IND" VARCHAR2(1), 
	"NTS_IND" VARCHAR2(1), 
	"OFFSHORE_IND" VARCHAR2(1), 
	"OHIO_IND" VARCHAR2(1), 
	"PBL_IND" VARCHAR2(1), 
	"POINT_IND" VARCHAR2(1), 
	"POINT_VERSION_IND" VARCHAR2(1), 
	"POLYGON_IND" VARCHAR2(1), 
	"POLYGON_VERSION_IND" VARCHAR2(1), 
	"PPDM_GUID" VARCHAR2(38), 
	"REFERENCE_NUM" VARCHAR2(30), 
	"REMARK" VARCHAR2(2000), 
	"SOURCE" VARCHAR2(40), 
	"SPATIAL_DESC_TEXT_IND" VARCHAR2(1), 
	"SPATIAL_DESC_TYPE" VARCHAR2(40), 
	"TEXAS_IND" VARCHAR2(1), 
	"ROW_CHANGED_BY" VARCHAR2(30), 
	"ROW_CHANGED_DATE" TIMESTAMP (0), 
	"ROW_CREATED_BY" VARCHAR2(30), 
	"ROW_CREATED_DATE" TIMESTAMP (0), 
	"ROW_EFFECTIVE_DATE" TIMESTAMP (0), 
	"ROW_EXPIRY_DATE" TIMESTAMP (0), 
	"ROW_QUALITY" VARCHAR2(40)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STRAT_UNIT
--------------------------------------------------------

  CREATE TABLE "ADMIN"."STRAT_UNIT" 
   (	"STRAT_NAME_SET_ID" VARCHAR2(40), 
	"STRAT_UNIT_ID" VARCHAR2(40), 
	"ABBREVIATION" VARCHAR2(12), 
	"ACTIVE_IND" VARCHAR2(1), 
	"AREA_ID" VARCHAR2(40), 
	"AREA_TYPE" VARCHAR2(40), 
	"BUSINESS_ASSOCIATE_ID" VARCHAR2(40), 
	"CONFIDENCE_ID" VARCHAR2(40), 
	"CURRENT_STATUS_DATE" TIMESTAMP (0), 
	"DESCRIPTION" VARCHAR2(240), 
	"EFFECTIVE_DATE" TIMESTAMP (0), 
	"EXPIRY_DATE" TIMESTAMP (0), 
	"FAULT_TYPE" VARCHAR2(40), 
	"FORM_CODE" VARCHAR2(20), 
	"GROUP_CODE" VARCHAR2(20), 
	"LONG_NAME" VARCHAR2(255), 
	"ORDINAL_AGE_CODE" NUMBER(15,5), 
	"PPDM_GUID" VARCHAR2(38), 
	"PREFERRED_IND" VARCHAR2(1), 
	"REMARK" VARCHAR2(2000), 
	"SHORT_NAME" VARCHAR2(30), 
	"SOURCE" VARCHAR2(40), 
	"STRAT_INTERPRET_METHOD" VARCHAR2(40), 
	"STRAT_STATUS" VARCHAR2(40), 
	"STRAT_TYPE" VARCHAR2(40), 
	"STRAT_UNIT_TYPE" VARCHAR2(40), 
	"ROW_CHANGED_BY" VARCHAR2(30), 
	"ROW_CHANGED_DATE" TIMESTAMP (0), 
	"ROW_CREATED_BY" VARCHAR2(30), 
	"ROW_CREATED_DATE" TIMESTAMP (0), 
	"ROW_EFFECTIVE_DATE" TIMESTAMP (0), 
	"ROW_EXPIRY_DATE" TIMESTAMP (0), 
	"ROW_QUALITY" VARCHAR2(40)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for View BASIN
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "ADMIN"."BASIN" ("PROJECT_NAME", "STRAT_NAME_SET_ID", "STRAT_STATUS", "PRODUCT_TYPE", "RESERVE_CLASS_ID", "OPEN_BALANCE", "OPEN_BALANCE_OUOM", "SIZE_TYPE", "GROSS_SIZE", "STRAT_TYPE", "FAULT_TYPE", "SOURCE", "CHECKED_BY_BA_ID", "QC_STATUS") AS 
  select project.project_name, strat_unit.strat_name_set_id, 
    r_strat_status.strat_status, resent_product.product_type, reserve_class.reserve_class_id, 
    resent_vol_summary.open_balance, resent_vol_summary.open_balance_ouom, ra_lr_size_type.size_type,
    land_size.gross_size, r_strat_type.strat_type, r_fault_type.fault_type, r_source.source, ppdm_quality_control.checked_by_ba_id,
    ppdm_quality_control.qc_status from project, strat_unit, r_strat_status, resent_product, reserve_class, 
    resent_vol_summary, ra_lr_size_type, land_size, r_strat_type, r_fault_type, r_source, ppdm_quality_control
;
--------------------------------------------------------
--  DDL for View BIBLIOGRAPHY
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "ADMIN"."BIBLIOGRAPHY" ("PUBLISHER", "DOCUMENT_TITLE", "ISSUE", "AUTHOR_ID", "PUBLICATION_DATE", "DOCUMENT_TYPE", "DATA_STORE_NAME") AS 
  select source_document.publisher, source_document.document_title, source_document.issue, source_doc_author.author_id, source_document.publication_date, source_document.document_type, rm_data_store.data_store_name from source_document join source_doc_author on source_document.source_document_id = source_doc_author.source_document_id and source_document.source = source_doc_author.source join rm_data_store on rm_data_store.source = source_doc_author.source
;
--------------------------------------------------------
--  DDL for View FIELD_INFORMATION
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "ADMIN"."FIELD_INFORMATION" ("AREA_ID", "AREA_TYPE", "FIELD_NAME", "DISCOVERY_DATE", "FIELD_TYPE", "PASSWORD", "DIGITAL_SIZE", "DIGITAL_SIZE_UOM", "MEDIA_TYPE", "DATA_STORE_NAME", "REMARK", "QC_STATUS", "CHECKED_BY_BA_ID") AS 
  select field.area_id, field.area_type, 
    field.field_name, field.discovery_date, field.field_type, ba_alias.password,
    rm_physical_item.digital_size, rm_physical_item.digital_size_uom, 
    ra_media_type.media_type, rm_data_store.data_store_name, anl_accuracy.remark,
    ppdm_quality_control.qc_status, ppdm_quality_control.checked_by_ba_id 
    from field join ba_alias on field.source = ba_alias.source join rm_physical_item on 
    ba_alias.source = rm_physical_item.source join ra_media_type on rm_physical_item.source
    = ra_media_type.source join rm_data_store on ra_media_type.source = rm_data_store.source
    join anl_accuracy on rm_data_store.source = anl_accuracy.source
    join ppdm_quality_control on anl_accuracy.source = ppdm_quality_control.source
;
--------------------------------------------------------
--  DDL for View WORKING_AREA
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "ADMIN"."WORKING_AREA" ("AREA_ID", "AREA_TYPE", "BA_LONG_NAME", "BA_TYPE", "EFFECTIVE_DATE", "EXPIRY_DATE", "CONTRACT_TYPE", "GRANTED_RIGHT_TYPE", "GROSS_SIZE", "GROSS_SIZE_OUOM", "LAND_RIGHT_CATEGORY", "PRODUCING_IND", "ORIGINAL_FILE_NAME", "PASSWORD", "DIGITAL_SIZE", "DIGITAL_SIZE_UOM", "MEDIA_TYPE", "DATA_STORE_NAME", "SOURCE", "QC_STATUS", "CHECKED_BY_BA_ID") AS 
  select area.area_id, area.area_type, 
    business_associate.ba_long_name, business_associate.ba_type, 
    business_associate.effective_date, business_associate.expiry_date, 
    cont_type.contract_type, land_right.granted_right_type, spatial_description.gross_size, 
    spatial_description.gross_size_ouom, land_right.land_right_category, land_right.producing_ind, 
    rm_physical_item.original_file_name, ba_alias.password, rm_physical_item.digital_size, 
    rm_physical_item.digital_size_uom, ra_media_type.media_type, rm_data_store.data_store_name, 
    r_source.source, ppdm_quality_control.qc_status, ppdm_quality_control.checked_by_ba_id 
    from area join business_associate on area.source = business_associate.source join cont_type
    on business_associate.source = cont_type.source join land_right on cont_type.source = land_right.source
    join spatial_description on land_right.source = spatial_description.source join rm_physical_item
    on spatial_description.source = rm_physical_item.source join ba_alias on rm_physical_item.source = ba_alias.source
    join ra_media_type on ba_alias.source = ra_media_type.source join rm_data_store on ra_media_type.source = rm_data_store.source
    join r_source on ra_media_type.source = r_source.source join ppdm_quality_control on r_source.source = ppdm_quality_control.source
;
REM INSERTING into ADMIN.ANL_ACCURACY
SET DEFINE OFF;
Insert into ADMIN.ANL_ACCURACY (ANALYSIS_ID,ANL_SOURCE,ACCURACY_OBS_NO,ACCURACY_DESC,ACCURACY_TYPE,ACTIVE_IND,CALCULATED_IND,CALCULATE_METHOD_ID,CONFIDENCE_TYPE,EFFECTIVE_DATE,EXPIRY_DATE,MEASURED_VALUE_IND,PPDM_GUID,RAW_VALUE_IND,REFERENCED_COLUMN_NAME,REFERENCED_PPDM_GUID,REFERENCED_SYSTEM_ID,REFERENCED_TABLE_NAME,REMARK,REPEATABILITY_TYPE,REPORTED_IND,SOURCE,STEP_SEQ_NO,ROW_CHANGED_BY,ROW_CHANGED_DATE,ROW_CREATED_BY,ROW_CREATED_DATE,ROW_EFFECTIVE_DATE,ROW_EXPIRY_DATE,ROW_QUALITY) values ('A1','B1',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,'Paper',null,null,null,null,null,null,null,null);
Insert into ADMIN.ANL_ACCURACY (ANALYSIS_ID,ANL_SOURCE,ACCURACY_OBS_NO,ACCURACY_DESC,ACCURACY_TYPE,ACTIVE_IND,CALCULATED_IND,CALCULATE_METHOD_ID,CONFIDENCE_TYPE,EFFECTIVE_DATE,EXPIRY_DATE,MEASURED_VALUE_IND,PPDM_GUID,RAW_VALUE_IND,REFERENCED_COLUMN_NAME,REFERENCED_PPDM_GUID,REFERENCED_SYSTEM_ID,REFERENCED_TABLE_NAME,REMARK,REPEATABILITY_TYPE,REPORTED_IND,SOURCE,STEP_SEQ_NO,ROW_CHANGED_BY,ROW_CHANGED_DATE,ROW_CREATED_BY,ROW_CREATED_DATE,ROW_EFFECTIVE_DATE,ROW_EXPIRY_DATE,ROW_QUALITY) values ('A5','B1',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
REM INSERTING into ADMIN.AREA
SET DEFINE OFF;
Insert into ADMIN.AREA (AREA_ID,AREA_TYPE,ACTIVE_IND,AREA_MAX_LATITUDE,AREA_MAX_LONGITUDE,AREA_MIN_LATITUDE,AREA_MIN_LONGITUDE,COORD_ACQUISITION_ID,COORD_SYSTEM_ID,EFFECTIVE_DATE,EXPIRY_DATE,LOCAL_COORD_SYSTEM_ID,PPDM_GUID,PREFERRED_NAME,REMARK,SOURCE,SOURCE_DOCUMENT_ID,ROW_CHANGED_BY,ROW_CHANGED_DATE,ROW_CREATED_BY,ROW_CREATED_DATE,ROW_EFFECTIVE_DATE,ROW_EXPIRY_DATE,ROW_QUALITY) values ('A11','B10',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into ADMIN.AREA (AREA_ID,AREA_TYPE,ACTIVE_IND,AREA_MAX_LATITUDE,AREA_MAX_LONGITUDE,AREA_MIN_LATITUDE,AREA_MIN_LONGITUDE,COORD_ACQUISITION_ID,COORD_SYSTEM_ID,EFFECTIVE_DATE,EXPIRY_DATE,LOCAL_COORD_SYSTEM_ID,PPDM_GUID,PREFERRED_NAME,REMARK,SOURCE,SOURCE_DOCUMENT_ID,ROW_CHANGED_BY,ROW_CHANGED_DATE,ROW_CREATED_BY,ROW_CREATED_DATE,ROW_EFFECTIVE_DATE,ROW_EXPIRY_DATE,ROW_QUALITY) values ('A7','B7',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into ADMIN.AREA (AREA_ID,AREA_TYPE,ACTIVE_IND,AREA_MAX_LATITUDE,AREA_MAX_LONGITUDE,AREA_MIN_LATITUDE,AREA_MIN_LONGITUDE,COORD_ACQUISITION_ID,COORD_SYSTEM_ID,EFFECTIVE_DATE,EXPIRY_DATE,LOCAL_COORD_SYSTEM_ID,PPDM_GUID,PREFERRED_NAME,REMARK,SOURCE,SOURCE_DOCUMENT_ID,ROW_CHANGED_BY,ROW_CHANGED_DATE,ROW_CREATED_BY,ROW_CREATED_DATE,ROW_EFFECTIVE_DATE,ROW_EXPIRY_DATE,ROW_QUALITY) values ('A1','B1',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into ADMIN.AREA (AREA_ID,AREA_TYPE,ACTIVE_IND,AREA_MAX_LATITUDE,AREA_MAX_LONGITUDE,AREA_MIN_LATITUDE,AREA_MIN_LONGITUDE,COORD_ACQUISITION_ID,COORD_SYSTEM_ID,EFFECTIVE_DATE,EXPIRY_DATE,LOCAL_COORD_SYSTEM_ID,PPDM_GUID,PREFERRED_NAME,REMARK,SOURCE,SOURCE_DOCUMENT_ID,ROW_CHANGED_BY,ROW_CHANGED_DATE,ROW_CREATED_BY,ROW_CREATED_DATE,ROW_EFFECTIVE_DATE,ROW_EXPIRY_DATE,ROW_QUALITY) values ('A3','B1',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into ADMIN.AREA (AREA_ID,AREA_TYPE,ACTIVE_IND,AREA_MAX_LATITUDE,AREA_MAX_LONGITUDE,AREA_MIN_LATITUDE,AREA_MIN_LONGITUDE,COORD_ACQUISITION_ID,COORD_SYSTEM_ID,EFFECTIVE_DATE,EXPIRY_DATE,LOCAL_COORD_SYSTEM_ID,PPDM_GUID,PREFERRED_NAME,REMARK,SOURCE,SOURCE_DOCUMENT_ID,ROW_CHANGED_BY,ROW_CHANGED_DATE,ROW_CREATED_BY,ROW_CREATED_DATE,ROW_EFFECTIVE_DATE,ROW_EXPIRY_DATE,ROW_QUALITY) values ('A10','B1',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
REM INSERTING into ADMIN.BA_ADDRESS
SET DEFINE OFF;
REM INSERTING into ADMIN.BA_ALIAS
SET DEFINE OFF;
Insert into ADMIN.BA_ALIAS (BUSINESS_ASSOCIATE_ID,SOURCE,BA_ALIAS_ID,ABBREVIATION,ACTIVE_IND,ALIAS_LONG_NAME,ALIAS_REASON_TYPE,ALIAS_SHORT_NAME,ALIAS_TYPE,AMENDED_DATE,CREATED_DATE,EFFECTIVE_DATE,EXPIRY_DATE,LANGUAGE_ID,ORIGINAL_IND,OWNER_BA_ID,PASSWORD,PPDM_GUID,PREFERRED_IND,REASON_DESC,REMARK,SOURCE_DOCUMENT_ID,STRUCKOFF_DATE,SW_APPLICATION_ID,USE_RULE,ROW_CHANGED_BY,ROW_CHANGED_DATE,ROW_CREATED_BY,ROW_CREATED_DATE,ROW_EFFECTIVE_DATE,ROW_EXPIRY_DATE,ROW_QUALITY) values ('A1','Paper','C1',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
REM INSERTING into ADMIN.BUSINESS_ASSOCIATE
SET DEFINE OFF;
Insert into ADMIN.BUSINESS_ASSOCIATE (BUSINESS_ASSOCIATE_ID,ACTIVE_IND,BA_ABBREVIATION,BA_CATEGORY,BA_CODE,BA_LONG_NAME,BA_SHORT_NAME,BA_TYPE,CREDIT_CHECK_DATE,CREDIT_CHECK_IND,CREDIT_CHECK_SOURCE,CREDIT_RATING,CREDIT_RATING_SOURCE,CURRENT_STATUS,EFFECTIVE_DATE,EXPIRY_DATE,FIRST_NAME,LAST_NAME,MIDDLE_INITIAL,PPDM_GUID,REMARK,SERVICE_PERIOD,SOURCE,ROW_CHANGED_BY,ROW_CHANGED_DATE,ROW_CREATED_BY,ROW_CREATED_DATE,ROW_EFFECTIVE_DATE,ROW_EXPIRY_DATE,ROW_QUALITY) values ('A1',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into ADMIN.BUSINESS_ASSOCIATE (BUSINESS_ASSOCIATE_ID,ACTIVE_IND,BA_ABBREVIATION,BA_CATEGORY,BA_CODE,BA_LONG_NAME,BA_SHORT_NAME,BA_TYPE,CREDIT_CHECK_DATE,CREDIT_CHECK_IND,CREDIT_CHECK_SOURCE,CREDIT_RATING,CREDIT_RATING_SOURCE,CURRENT_STATUS,EFFECTIVE_DATE,EXPIRY_DATE,FIRST_NAME,LAST_NAME,MIDDLE_INITIAL,PPDM_GUID,REMARK,SERVICE_PERIOD,SOURCE,ROW_CHANGED_BY,ROW_CHANGED_DATE,ROW_CREATED_BY,ROW_CREATED_DATE,ROW_EFFECTIVE_DATE,ROW_EXPIRY_DATE,ROW_QUALITY) values ('A1',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
REM INSERTING into ADMIN.CONT_TYPE
SET DEFINE OFF;
Insert into ADMIN.CONT_TYPE (CONTRACT_ID,CONTRACT_TYPE,ACTIVE_IND,EFFECTIVE_DATE,EXPIRY_DATE,PPDM_GUID,REMARK,SOURCE,ROW_CHANGED_BY,ROW_CHANGED_DATE,ROW_CREATED_BY,ROW_CREATED_DATE,ROW_EFFECTIVE_DATE,ROW_EXPIRY_DATE,ROW_QUALITY) values ('A1','B1',null,null,null,null,null,null,null,null,null,null,null,null,null);
REM INSERTING into ADMIN.FIELD
SET DEFINE OFF;
Insert into ADMIN.FIELD (FIELD_ID,ACTIVE_IND,AREA_ID,AREA_TYPE,DISCOVERY_DATE,EFFECTIVE_DATE,EXPIRY_DATE,FIELD_ABBREVIATION,FIELD_AREA_OBS_NO,FIELD_NAME,FIELD_TYPE,GROUP_FIELD_ID,PPDM_GUID,REMARK,SOURCE,ROW_CHANGED_BY,ROW_CHANGED_DATE,ROW_CREATED_BY,ROW_CREATED_DATE,ROW_EFFECTIVE_DATE,ROW_EXPIRY_DATE,ROW_QUALITY) values ('A1',null,'D1',null,null,null,null,null,null,null,null,null,null,null,'Paper',null,null,null,null,null,null,null);
Insert into ADMIN.FIELD (FIELD_ID,ACTIVE_IND,AREA_ID,AREA_TYPE,DISCOVERY_DATE,EFFECTIVE_DATE,EXPIRY_DATE,FIELD_ABBREVIATION,FIELD_AREA_OBS_NO,FIELD_NAME,FIELD_TYPE,GROUP_FIELD_ID,PPDM_GUID,REMARK,SOURCE,ROW_CHANGED_BY,ROW_CHANGED_DATE,ROW_CREATED_BY,ROW_CREATED_DATE,ROW_EFFECTIVE_DATE,ROW_EXPIRY_DATE,ROW_QUALITY) values ('A3',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into ADMIN.FIELD (FIELD_ID,ACTIVE_IND,AREA_ID,AREA_TYPE,DISCOVERY_DATE,EFFECTIVE_DATE,EXPIRY_DATE,FIELD_ABBREVIATION,FIELD_AREA_OBS_NO,FIELD_NAME,FIELD_TYPE,GROUP_FIELD_ID,PPDM_GUID,REMARK,SOURCE,ROW_CHANGED_BY,ROW_CHANGED_DATE,ROW_CREATED_BY,ROW_CREATED_DATE,ROW_EFFECTIVE_DATE,ROW_EXPIRY_DATE,ROW_QUALITY) values ('A2',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into ADMIN.FIELD (FIELD_ID,ACTIVE_IND,AREA_ID,AREA_TYPE,DISCOVERY_DATE,EFFECTIVE_DATE,EXPIRY_DATE,FIELD_ABBREVIATION,FIELD_AREA_OBS_NO,FIELD_NAME,FIELD_TYPE,GROUP_FIELD_ID,PPDM_GUID,REMARK,SOURCE,ROW_CHANGED_BY,ROW_CHANGED_DATE,ROW_CREATED_BY,ROW_CREATED_DATE,ROW_EFFECTIVE_DATE,ROW_EXPIRY_DATE,ROW_QUALITY) values ('A4',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into ADMIN.FIELD (FIELD_ID,ACTIVE_IND,AREA_ID,AREA_TYPE,DISCOVERY_DATE,EFFECTIVE_DATE,EXPIRY_DATE,FIELD_ABBREVIATION,FIELD_AREA_OBS_NO,FIELD_NAME,FIELD_TYPE,GROUP_FIELD_ID,PPDM_GUID,REMARK,SOURCE,ROW_CHANGED_BY,ROW_CHANGED_DATE,ROW_CREATED_BY,ROW_CREATED_DATE,ROW_EFFECTIVE_DATE,ROW_EXPIRY_DATE,ROW_QUALITY) values ('A5',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
REM INSERTING into ADMIN.LAND_RIGHT
SET DEFINE OFF;
Insert into ADMIN.LAND_RIGHT (LAND_RIGHT_SUBTYPE,LAND_RIGHT_ID,ACQTN_DATE,ACTIVE_IND,AREA_ID,AREA_TYPE,CALCULATED_INTEREST,CASE_SERIAL_NUM,CONFIDENTIAL_IND,COST_CENTER_NUM,EFFECTIVE_DATE,EXPIRY_DATE,FIRST_PLATFORM_APPROVE_DATE,FIRST_PLATFORM_INSTALL_DATE,FIRST_PRODUCTION_DATE,FRACTIONAL_INTEREST,GRANTED_RIGHT_TYPE,GROSS_SIZE,GROSS_SIZE_OUOM,HIGH_WATER_DEPTH,HIGH_WATER_DEPTH_OUOM,INACTIVATION_DATE,INCENT_CERT_NO,ISSUE_DATE,JURISDICTION,LAND_ACQTN_METHOD,LAND_CASE_ACTION,LAND_CASE_TYPE,LAND_PROPERTY_TYPE,LAND_RIGHT_CATEGORY,LAND_SALE_NUMBER,LAND_SALE_OFFERING_ID,LAST_ACTION_DATE,LESSOR_NAME,LESSOR_NUM,LESSOR_TYPE,LOW_WATER_DEPTH,LOW_WATER_DEPTH_OUOM,MUNICIPALITY,OCCUPANT_NAME,OFFSHORE_DISTANCE,OFFSHORE_DISTANCE_OUOM,OIL_SAND_DEPOSIT,OVERLAP_IND,PLATFORM_COUNT,PPDM_GUID,PRIMARY_TERM,PRIMARY_TERM_OUOM,PRODUCING_IND,PROPRIETARY_NUM,QUALIFICATION_DATE,RECLAMATION_CERT_NUM,RECLAMATION_END_DATE,RECLAMATION_START_DATE,RELINQUISHABLE_IND,REMARK,RENTAL_ALLOCATION_IND,REPORT_ACREAGE_IND,SCHEME_APPROVAL_NUM,SCHEME_EXPIRY_DATE,SECONDARY_TERM,SECONDARY_TERM_OUOM,SOURCE,SUBSURFACE_IND,SURFACE_IND,TERMIN_NOTICE_PERIOD,TERMIN_NOTICE_PERIOD_OUOM,TERM_EXIRY_DATE,UNIT_OPERATED_IND,WELL_QUALIFIC_TYPE,ROW_CHANGED_BY,ROW_CHANGED_DATE,ROW_CREATED_BY,ROW_CREATED_DATE,ROW_EFFECTIVE_DATE,ROW_EXPIRY_DATE,ROW_QUALITY) values ('A1','B1',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
REM INSERTING into ADMIN.LAND_SIZE
SET DEFINE OFF;
REM INSERTING into ADMIN.PPDM_QUALITY_CONTROL
SET DEFINE OFF;
Insert into ADMIN.PPDM_QUALITY_CONTROL (SYSTEM_ID,TABLE_NAME,QC_SEQ_NO,ACTIVE_IND,CHECKED_BY_BA_ID,COLUMN_NAME,CURRENT_DATE_VALUE,CURRENT_NUMERIC_VALUE,CURRENT_NUMERIC_VALUE_OUOM,CURRENT_NUMERIC_VALUE_UOM,CURRENT_ROW_GUID,CURRENT_TEXT_VALUE,DATA_TYPE,DONE_BY_BA_ID,EFFECTIVE_DATE,EXPIRY_DATE,NULL_DESCRIPTION,PPDM_GUID,QC_DATETIME,QC_DESC,QC_STATUS,QC_TYPE,QUALITY_TYPE,REMARK,RETENTION_PERIOD,SOURCE,ROW_CHANGED_BY,ROW_CHANGED_DATE,ROW_CREATED_BY,ROW_CREATED_DATE,ROW_EFFECTIVE_DATE,ROW_EXPIRY_DATE,ROW_QUALITY) values ('A1','B1',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,'Paper',null,null,null,null,null,null,null);
REM INSERTING into ADMIN.PROJECT
SET DEFINE OFF;
REM INSERTING into ADMIN.RA_LR_SIZE_TYPE
SET DEFINE OFF;
REM INSERTING into ADMIN.RA_MEDIA_TYPE
SET DEFINE OFF;
Insert into ADMIN.RA_MEDIA_TYPE (MEDIA_TYPE,ALIAS_ID,ABBREVIATION,ACTIVE_IND,ALIAS_LONG_NAME,ALIAS_REASON_TYPE,ALIAS_SHORT_NAME,ALIAS_TYPE,AMENDED_DATE,CREATED_DATE,EFFECTIVE_DATE,EXPIRY_DATE,LANGUAGE_ID,ORIGINAL_IND,OWNER_BA_ID,PPDM_GUID,PREFERRED_IND,REASON_DESC,REMARK,SOURCE,SOURCE_DOCUMENT,STRUCKOFF_DATE,SW_APPLICATION_ID,USE_RULE,ROW_CHANGED_BY,ROW_CHANGED_DATE,ROW_CREATED_BY,ROW_CREATED_DATE,ROW_EFFECTIVE_DATE,ROW_EXPIRY_DATE,ROW_QUALITY) values ('A2','B2',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,'Paper',null,null,null,null,null,null,null,null,null,null,null);
Insert into ADMIN.RA_MEDIA_TYPE (MEDIA_TYPE,ALIAS_ID,ABBREVIATION,ACTIVE_IND,ALIAS_LONG_NAME,ALIAS_REASON_TYPE,ALIAS_SHORT_NAME,ALIAS_TYPE,AMENDED_DATE,CREATED_DATE,EFFECTIVE_DATE,EXPIRY_DATE,LANGUAGE_ID,ORIGINAL_IND,OWNER_BA_ID,PPDM_GUID,PREFERRED_IND,REASON_DESC,REMARK,SOURCE,SOURCE_DOCUMENT,STRUCKOFF_DATE,SW_APPLICATION_ID,USE_RULE,ROW_CHANGED_BY,ROW_CHANGED_DATE,ROW_CREATED_BY,ROW_CREATED_DATE,ROW_EFFECTIVE_DATE,ROW_EXPIRY_DATE,ROW_QUALITY) values ('A1','B1',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
REM INSERTING into ADMIN.RESENT_PRODUCT
SET DEFINE OFF;
REM INSERTING into ADMIN.RESENT_VOL_SUMMARY
SET DEFINE OFF;
REM INSERTING into ADMIN.RESERVE_CLASS
SET DEFINE OFF;
REM INSERTING into ADMIN.RM_DATA_STORE
SET DEFINE OFF;
Insert into ADMIN.RM_DATA_STORE (STORE_ID,ACTIVE_IND,ADDRESS_OBS_NO,ADDRESS_SOURCE,BUSINESS_ASSOCIATE_ID,CONTAINED_BY_STORE_ID,DATA_STORE_HIER_ID,DATA_STORE_NAME,DATA_STORE_TYPE,EFFECTIVE_DATE,EXPIRY_DATE,HIER_LEVEL_ID,LOCATION_ID,LONG_LOCATION,PHYSICAL_STORE_STATUS,PPDM_GUID,REMARK,SHORT_LOCATION,SOURCE,TOTAL_CAPACITY,USED_CAPACITY,USED_CAPACITY_DATE,ROW_CHANGED_BY,ROW_CHANGED_DATE,ROW_CREATED_BY,ROW_CREATED_DATE,ROW_EFFECTIVE_DATE,ROW_EXPIRY_DATE,ROW_QUALITY) values ('A1',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,'Paper',null,null,null,null,null,null,null,null,null,null);
Insert into ADMIN.RM_DATA_STORE (STORE_ID,ACTIVE_IND,ADDRESS_OBS_NO,ADDRESS_SOURCE,BUSINESS_ASSOCIATE_ID,CONTAINED_BY_STORE_ID,DATA_STORE_HIER_ID,DATA_STORE_NAME,DATA_STORE_TYPE,EFFECTIVE_DATE,EXPIRY_DATE,HIER_LEVEL_ID,LOCATION_ID,LONG_LOCATION,PHYSICAL_STORE_STATUS,PPDM_GUID,REMARK,SHORT_LOCATION,SOURCE,TOTAL_CAPACITY,USED_CAPACITY,USED_CAPACITY_DATE,ROW_CHANGED_BY,ROW_CHANGED_DATE,ROW_CREATED_BY,ROW_CREATED_DATE,ROW_EFFECTIVE_DATE,ROW_EXPIRY_DATE,ROW_QUALITY) values ('A2',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
REM INSERTING into ADMIN.RM_DATA_STORE_HIER_LEVEL
SET DEFINE OFF;
REM INSERTING into ADMIN.RM_PHYSICAL_ITEM
SET DEFINE OFF;
Insert into ADMIN.RM_PHYSICAL_ITEM (PHYSICAL_ITEM_ID,ACTIVE_IND,BAR_CODE,CATALOGUE_BY_NAME,CATALOGUE_DATE,CERTIFIED_TRUE_COPY_IND,CIRCULATION_ALLOWED_IND,CIRCULATION_OUT_IND,COLOR_FORMAT,CREATE_DATE,DIGITAL_FORMAT,DIGITAL_SIZE,DIGITAL_SIZE_UOM,DIM_HEIGHT,DIM_HEIGHT_UOM,DIM_LENGTH,DIM_LENGTH_UOM,DIM_WEIGHT,DIM_WEIGHT_UOM,DIM_WIDTH,DIM_WIDTH_UOM,EFFECTIVE_DATE,EXPIRY_DATE,FILE_COUNT,GROUP_IND,IMAGE_RESOLUTION_UOM,IMAGE_X_RESOLUTION,IMAGE_Y_RESOLUTION,ITEM_CATEGORY,ITEM_SUB_CATEGORY,LABEL,LANGUAGE,LAST_CONDITION,LOCATION_REFERENCE,MEDIA_TYPE,ORIGINAL_FILE_NAME,ORIGINAL_IND,OUTPUT_FILE_NAME,PAGE_COUNT,PHYSICAL_ITEM_STATUS,PPDM_GUID,PREFERRED_IND,QC_BY_NAME,REMARK,RETENTION_PERIOD,SALE_ALLOWED_IND,SOURCE,STORE_ID,ROW_CHANGED_BY,ROW_CHANGED_DATE,ROW_CREATED_BY,ROW_CREATED_DATE,ROW_EFFECTIVE_DATE,ROW_EXPIRY_DATE,ROW_QUALITY) values ('A1',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,'Paper',null,null,null,null,null,null,null,null);
REM INSERTING into ADMIN.R_ADDRESS_TYPE
SET DEFINE OFF;
REM INSERTING into ADMIN.R_AUTHOR_TYPE
SET DEFINE OFF;
REM INSERTING into ADMIN.R_BA_CATEGORY
SET DEFINE OFF;
REM INSERTING into ADMIN.R_BA_STATUS
SET DEFINE OFF;
REM INSERTING into ADMIN.R_BA_TYPE
SET DEFINE OFF;
REM INSERTING into ADMIN.R_DATA_STORE_TYPE
SET DEFINE OFF;
REM INSERTING into ADMIN.R_DOCUMENT_TYPE
SET DEFINE OFF;
REM INSERTING into ADMIN.R_FAULT_TYPE
SET DEFINE OFF;
REM INSERTING into ADMIN.R_LANGUAGE
SET DEFINE OFF;
REM INSERTING into ADMIN.R_PPDM_ROW_QUALITY
SET DEFINE OFF;
REM INSERTING into ADMIN.R_PUBLICATION_NAME
SET DEFINE OFF;
REM INSERTING into ADMIN.R_SERVICE_QUALITY
SET DEFINE OFF;
REM INSERTING into ADMIN.R_SOURCE
SET DEFINE OFF;
REM INSERTING into ADMIN.R_STORE_STATUS
SET DEFINE OFF;
REM INSERTING into ADMIN.R_STRAT_STATUS
SET DEFINE OFF;
REM INSERTING into ADMIN.R_STRAT_TYPE
SET DEFINE OFF;
REM INSERTING into ADMIN.SOURCE_DOCUMENT
SET DEFINE OFF;
Insert into ADMIN.SOURCE_DOCUMENT (SOURCE_DOCUMENT_ID,ABBREVIATION,ACTIVE_IND,DOCUMENT_TITLE,DOCUMENT_TYPE,EFFECTIVE_DATE,EXPIRY_DATE,FIGURE_REFERENCE,ISSUE,LANGUAGE,PAGE_REFERENCE,PLATE_REFERENCE,PPDM_GUID,PUBLICATION,PUBLICATION_DATE,PUBLICATION_YEAR,PUBLISHER,REMARK,SOURCE,ROW_CHANGED_BY,ROW_CHANGED_DATE,ROW_CREATED_BY,ROW_CREATED_DATE,ROW_EFFECTIVE_DATE,ROW_EXPIRY_DATE,ROW_QUALITY) values ('A1',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,'A3',null,null,null,null,null,null,null);
REM INSERTING into ADMIN.SOURCE_DOC_AUTHOR
SET DEFINE OFF;
Insert into ADMIN.SOURCE_DOC_AUTHOR (SOURCE_DOCUMENT_ID,AUTHOR_ID,ACTIVE_IND,AUTHOR_BA_ID,AUTHOR_FIRST_NAME,AUTHOR_INITIAL,AUTHOR_LAST_NAME,AUTHOR_SEQ_NO,AUTHOR_TYPE,EFFECTIVE_DATE,EXPIRY_DATE,PPDM_GUID,REMARK,SOURCE,ROW_CHANGED_BY,ROW_CHANGED_DATE,ROW_CREATED_BY,ROW_CREATED_DATE,ROW_EFFECTIVE_DATE,ROW_EXPIRY_DATE,ROW_QUALITY) values ('A1','A2',null,null,null,null,null,null,null,null,null,null,null,'A3',null,null,null,null,null,null,null);
REM INSERTING into ADMIN.SPATIAL_DESCRIPTION
SET DEFINE OFF;
REM INSERTING into ADMIN.STRAT_UNIT
SET DEFINE OFF;
--------------------------------------------------------
--  Constraints for Table ANL_ACCURACY
--------------------------------------------------------

  ALTER TABLE "ADMIN"."ANL_ACCURACY" MODIFY ("ANALYSIS_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."ANL_ACCURACY" MODIFY ("ANL_SOURCE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."ANL_ACCURACY" ADD PRIMARY KEY ("ANALYSIS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RESERVE_CLASS
--------------------------------------------------------

  ALTER TABLE "ADMIN"."RESERVE_CLASS" MODIFY ("RESERVE_CLASS_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."RESERVE_CLASS" ADD PRIMARY KEY ("RESERVE_CLASS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LAND_SIZE
--------------------------------------------------------

  ALTER TABLE "ADMIN"."LAND_SIZE" MODIFY ("LAND_RIGHT_SUBTYPE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."LAND_SIZE" MODIFY ("LAND_RIGHT_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."LAND_SIZE" MODIFY ("SIZE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."LAND_SIZE" ADD PRIMARY KEY ("LAND_RIGHT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table R_SOURCE
--------------------------------------------------------

  ALTER TABLE "ADMIN"."R_SOURCE" MODIFY ("SOURCE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."R_SOURCE" ADD PRIMARY KEY ("SOURCE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table R_ADDRESS_TYPE
--------------------------------------------------------

  ALTER TABLE "ADMIN"."R_ADDRESS_TYPE" MODIFY ("ADDRESS_TYPE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."R_ADDRESS_TYPE" ADD PRIMARY KEY ("ADDRESS_TYPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table R_BA_TYPE
--------------------------------------------------------

  ALTER TABLE "ADMIN"."R_BA_TYPE" MODIFY ("BA_TYPE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."R_BA_TYPE" ADD PRIMARY KEY ("BA_TYPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table R_PPDM_ROW_QUALITY
--------------------------------------------------------

  ALTER TABLE "ADMIN"."R_PPDM_ROW_QUALITY" MODIFY ("ROW_QUALITY_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."R_PPDM_ROW_QUALITY" ADD PRIMARY KEY ("ROW_QUALITY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SPATIAL_DESCRIPTION
--------------------------------------------------------

  ALTER TABLE "ADMIN"."SPATIAL_DESCRIPTION" MODIFY ("SPATIAL_DESCRIPTION_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."SPATIAL_DESCRIPTION" ADD PRIMARY KEY ("SPATIAL_DESCRIPTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table R_STORE_STATUS
--------------------------------------------------------

  ALTER TABLE "ADMIN"."R_STORE_STATUS" MODIFY ("PHYSICAL_STORE_STATUS" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."R_STORE_STATUS" ADD PRIMARY KEY ("PHYSICAL_STORE_STATUS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PROJECT
--------------------------------------------------------

  ALTER TABLE "ADMIN"."PROJECT" MODIFY ("PROJECT_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."PROJECT" ADD PRIMARY KEY ("PROJECT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FIELD
--------------------------------------------------------

  ALTER TABLE "ADMIN"."FIELD" MODIFY ("FIELD_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."FIELD" ADD PRIMARY KEY ("FIELD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table R_STRAT_TYPE
--------------------------------------------------------

  ALTER TABLE "ADMIN"."R_STRAT_TYPE" MODIFY ("STRAT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."R_STRAT_TYPE" ADD PRIMARY KEY ("STRAT_TYPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RA_LR_SIZE_TYPE
--------------------------------------------------------

  ALTER TABLE "ADMIN"."RA_LR_SIZE_TYPE" MODIFY ("SIZE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."RA_LR_SIZE_TYPE" MODIFY ("ALIAS_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."RA_LR_SIZE_TYPE" ADD PRIMARY KEY ("ALIAS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table R_FAULT_TYPE
--------------------------------------------------------

  ALTER TABLE "ADMIN"."R_FAULT_TYPE" MODIFY ("FAULT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."R_FAULT_TYPE" ADD PRIMARY KEY ("FAULT_TYPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table R_BA_CATEGORY
--------------------------------------------------------

  ALTER TABLE "ADMIN"."R_BA_CATEGORY" MODIFY ("BA_CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."R_BA_CATEGORY" ADD PRIMARY KEY ("BA_CATEGORY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LAND_RIGHT
--------------------------------------------------------

  ALTER TABLE "ADMIN"."LAND_RIGHT" MODIFY ("LAND_RIGHT_SUBTYPE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."LAND_RIGHT" MODIFY ("LAND_RIGHT_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."LAND_RIGHT" ADD PRIMARY KEY ("LAND_RIGHT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STRAT_UNIT
--------------------------------------------------------

  ALTER TABLE "ADMIN"."STRAT_UNIT" MODIFY ("STRAT_NAME_SET_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."STRAT_UNIT" MODIFY ("STRAT_UNIT_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."STRAT_UNIT" ADD PRIMARY KEY ("STRAT_NAME_SET_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table R_LANGUAGE
--------------------------------------------------------

  ALTER TABLE "ADMIN"."R_LANGUAGE" MODIFY ("LANGUAGE_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."R_LANGUAGE" ADD PRIMARY KEY ("LANGUAGE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RM_PHYSICAL_ITEM
--------------------------------------------------------

  ALTER TABLE "ADMIN"."RM_PHYSICAL_ITEM" MODIFY ("PHYSICAL_ITEM_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."RM_PHYSICAL_ITEM" ADD PRIMARY KEY ("PHYSICAL_ITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table R_SERVICE_QUALITY
--------------------------------------------------------

  ALTER TABLE "ADMIN"."R_SERVICE_QUALITY" MODIFY ("SERVICE_QUALITY" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."R_SERVICE_QUALITY" ADD PRIMARY KEY ("SERVICE_QUALITY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table R_PUBLICATION_NAME
--------------------------------------------------------

  ALTER TABLE "ADMIN"."R_PUBLICATION_NAME" MODIFY ("PUBLICATION" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."R_PUBLICATION_NAME" ADD PRIMARY KEY ("PUBLICATION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BA_ALIAS
--------------------------------------------------------

  ALTER TABLE "ADMIN"."BA_ALIAS" MODIFY ("BUSINESS_ASSOCIATE_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."BA_ALIAS" MODIFY ("SOURCE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."BA_ALIAS" MODIFY ("BA_ALIAS_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."BA_ALIAS" ADD PRIMARY KEY ("BUSINESS_ASSOCIATE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RM_DATA_STORE
--------------------------------------------------------

  ALTER TABLE "ADMIN"."RM_DATA_STORE" MODIFY ("STORE_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."RM_DATA_STORE" ADD PRIMARY KEY ("STORE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BUSINESS_ASSOCIATE
--------------------------------------------------------

  ALTER TABLE "ADMIN"."BUSINESS_ASSOCIATE" MODIFY ("BUSINESS_ASSOCIATE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CONT_TYPE
--------------------------------------------------------

  ALTER TABLE "ADMIN"."CONT_TYPE" MODIFY ("CONTRACT_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."CONT_TYPE" MODIFY ("CONTRACT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."CONT_TYPE" ADD PRIMARY KEY ("CONTRACT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SOURCE_DOCUMENT
--------------------------------------------------------

  ALTER TABLE "ADMIN"."SOURCE_DOCUMENT" MODIFY ("SOURCE_DOCUMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."SOURCE_DOCUMENT" ADD PRIMARY KEY ("SOURCE_DOCUMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table R_DATA_STORE_TYPE
--------------------------------------------------------

  ALTER TABLE "ADMIN"."R_DATA_STORE_TYPE" MODIFY ("DATA_STORE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."R_DATA_STORE_TYPE" ADD PRIMARY KEY ("DATA_STORE_TYPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table R_AUTHOR_TYPE
--------------------------------------------------------

  ALTER TABLE "ADMIN"."R_AUTHOR_TYPE" MODIFY ("AUTHOR_TYPE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."R_AUTHOR_TYPE" ADD PRIMARY KEY ("AUTHOR_TYPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RA_MEDIA_TYPE
--------------------------------------------------------

  ALTER TABLE "ADMIN"."RA_MEDIA_TYPE" MODIFY ("MEDIA_TYPE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."RA_MEDIA_TYPE" MODIFY ("ALIAS_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."RA_MEDIA_TYPE" ADD PRIMARY KEY ("ALIAS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table R_DOCUMENT_TYPE
--------------------------------------------------------

  ALTER TABLE "ADMIN"."R_DOCUMENT_TYPE" MODIFY ("DOCUMENT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."R_DOCUMENT_TYPE" ADD PRIMARY KEY ("DOCUMENT_TYPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RESENT_PRODUCT
--------------------------------------------------------

  ALTER TABLE "ADMIN"."RESENT_PRODUCT" MODIFY ("RESENT_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."RESENT_PRODUCT" MODIFY ("RESERVE_CLASS_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."RESENT_PRODUCT" MODIFY ("PRODUCT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."RESENT_PRODUCT" ADD PRIMARY KEY ("RESENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table R_BA_STATUS
--------------------------------------------------------

  ALTER TABLE "ADMIN"."R_BA_STATUS" MODIFY ("BA_STATUS" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."R_BA_STATUS" ADD PRIMARY KEY ("BA_STATUS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table R_STRAT_STATUS
--------------------------------------------------------

  ALTER TABLE "ADMIN"."R_STRAT_STATUS" MODIFY ("STRAT_STATUS" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."R_STRAT_STATUS" ADD PRIMARY KEY ("STRAT_STATUS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SOURCE_DOC_AUTHOR
--------------------------------------------------------

  ALTER TABLE "ADMIN"."SOURCE_DOC_AUTHOR" MODIFY ("SOURCE_DOCUMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."SOURCE_DOC_AUTHOR" MODIFY ("AUTHOR_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."SOURCE_DOC_AUTHOR" ADD PRIMARY KEY ("SOURCE_DOCUMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RESENT_VOL_SUMMARY
--------------------------------------------------------

  ALTER TABLE "ADMIN"."RESENT_VOL_SUMMARY" MODIFY ("RESENT_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."RESENT_VOL_SUMMARY" MODIFY ("RESERVE_CLASS_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."RESENT_VOL_SUMMARY" MODIFY ("PRODUCT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."RESENT_VOL_SUMMARY" MODIFY ("SUMMARY_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."RESENT_VOL_SUMMARY" ADD PRIMARY KEY ("RESENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PPDM_QUALITY_CONTROL
--------------------------------------------------------

  ALTER TABLE "ADMIN"."PPDM_QUALITY_CONTROL" MODIFY ("SYSTEM_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."PPDM_QUALITY_CONTROL" MODIFY ("TABLE_NAME" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."PPDM_QUALITY_CONTROL" ADD PRIMARY KEY ("SYSTEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RM_DATA_STORE_HIER_LEVEL
--------------------------------------------------------

  ALTER TABLE "ADMIN"."RM_DATA_STORE_HIER_LEVEL" MODIFY ("DATA_STORE_HIER_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."RM_DATA_STORE_HIER_LEVEL" MODIFY ("HIER_LEVEL_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."RM_DATA_STORE_HIER_LEVEL" ADD PRIMARY KEY ("HIER_LEVEL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BA_ADDRESS
--------------------------------------------------------

  ALTER TABLE "ADMIN"."BA_ADDRESS" MODIFY ("BUSINESS_ASSOCIATE_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."BA_ADDRESS" MODIFY ("SOURCE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."BA_ADDRESS" MODIFY ("ADDRESS_OBS_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AREA
--------------------------------------------------------

  ALTER TABLE "ADMIN"."AREA" MODIFY ("AREA_ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."AREA" MODIFY ("AREA_TYPE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."AREA" ADD PRIMARY KEY ("AREA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
