CREATE TABLE USERS (
  ID NUMBER GENERATED ALWAYS AS IDENTITY,
  FIRST_NAME VARCHAR(255) NOT NULL,
  LAST_NAME VARCHAR(255) NOT NULL,
  EMAIL VARCHAR(255) NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  DATE_JOINED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  EXPIRED_DATE DATE NOT NULL,
  ROLE_NAME VARCHAR(255) NOT NULL,
  PROFILE_PICTURE CLOB,
  PRIMARY KEY (ID),
  UNIQUE (EMAIL),
  CONSTRAINT FK_CUSTOMER_ROLE FOREIGN KEY (ROLE_NAME)
    REFERENCES ROLES (ROLE_NAME)
);
