-- CREATE TABLE USERS (
--   ID NUMBER GENERATED ALWAYS AS IDENTITY,
--   FIRST_NAME VARCHAR(255) NOT NULL,
--   LAST_NAME VARCHAR(255) NOT NULL,
--   EMAIL VARCHAR(255) NOT NULL,
--   PASSWORD VARCHAR(255) NOT NULL,
--   DATE_JOINED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--   EXPIRED_DATE DATE NOT NULL,
--   ROLE_NAME VARCHAR(255) NOT NULL,
--   PROFILE_PICTURE CLOB,
--   PRIMARY KEY (ID),
--   UNIQUE (EMAIL),
--   CONSTRAINT FK_CUSTOMER_ROLE FOREIGN KEY (ROLE_NAME)
--     REFERENCES ROLES (ROLE_NAME)
-- );


  CREATE TABLE "ADMIN"."USERS" 
   (	"ID" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"FIRST_NAME" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"LAST_NAME" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"DATE_JOINED" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"EXPIRED_DATE" DATE NOT NULL ENABLE, 
	"ROLE_NAME" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"PROFILE_PICTURE" CLOB, 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_CUSTOMER_ROLE" FOREIGN KEY ("ROLE_NAME")
	  REFERENCES "ADMIN"."ROLES" ("ROLE_NAME") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("PROFILE_PICTURE") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

