openapi: 3.0.0
info:
  description: This is the swagger API for Bibliography
  version: 1.0.0
  title: Bibliography
  termsOfService: http://swagger.io/terms/
  contact:
    email: darren.mannuela@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
- description: Bibliography
  url: http://localhost:8080/api/v1
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/DarrenMannuela/Bibliography/1.0.0
tags:
- name: Afe
  description: All endpoints related to get Bibliography AFE
- name: Workspace
  description: All endpoints related to Bibliography Workspace
- name: Bibliography
  description: All endpoints related to Bibliography
- name: Bibliography Dummy Data
  description: All endpoints related to Bibliography
paths:
  /Bibliography-afe:
    get:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Get Bibliography AFE
      responses:
        '200':
          description: get Bibliography AFE data to be returned
          content:
            application/json:
              example:
                afe_number: 1
                workspace_name: LoremIpsum
                kkks_name: LoremIpsum
                working_area: LoremIpsum
                submission_type: Lorem
                data_type: Bibliography
              user_id: 1
    post:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Post a new Bibliography AFE
      description: Create a new Bibliography AFE data
      requestBody:
        required: true
        description: Request body to create Bibliography AFE data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Bibliography'
            example:
              afe_number: 1
              workspace_name: LoremIpsum
              kkks_name: LoremIpsum
              working_area: LoremIpsum
              submission_type: Lorem
              data_type: Bibliography
            user_id: 1
      responses:
        '200':
          description: Bibliography data is added
          content:
            application/json:
              example:
                message: The Bibliography AFE data was successfully added
  /Bibliography-afe/{afe}:
    parameters:
    - in: path
      name: afe
      required: true
      description: afe of Bibliography data to fetch
      schema:
        type: interger
    get:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Get Bibliography AFE
      responses:
        '200':
          description: get Bibliography AFE data to be returned
          content:
            application/json:
              example:
                afe_number: 1
                workspace_name: LoremIpsum
                kkks_name: LoremIpsum
                working_area: LoremIpsum
                submission_type: Lorem
                data_type: Bibliography
              user_id: 1
    put:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Update a new Bibliography AFE data
      description: Update a new Bibliography data
      requestBody:
        required: true
        description: Request body to update Bibliography AFE data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Bibliography'
            example:
              afe_number: 1
              workspace_name: LoremIpsum
              kkks_name: LoremIpsum
              working_area: LoremIpsum
              submission_type: Lorem
              data_type: Bibliography
            user_id: 1
      responses:
        '200':
          description: Bibliography data is completely updated
          content:
            application/json:
              example:
                message: The Bibliography AFE data is completely updated
    patch:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Update a new Bibliography AFE data
      description: Update a new Bibliography data
      requestBody:
        required: true
        description: Request body to update Bibliography AFE data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Bibliography'
            example:
              afe_number: 1
              workspace_name: LoremIpsum
              kkks_name: LoremIpsum
              working_area: LoremIpsum
              submission_type: Lorem
              data_type: Bibliography
            user_id: 1
      responses:
        '200':
          description: one row in Bibliography data is updated
          content:
            application/json:
              example:
                message: The one row in Bibliography AFE data is updated
    delete:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Delete Bibliography AFE data
      description: Delete Bibliography AFE data
      responses:
        '200':
          description: Bibliography AFE data is deleted
          content:
            application/json:
              example:
                message: The Bibliography AFE data was successfully deleted
  /Bibliography-workspace:
    get:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Get Bibliography Workspace
      responses:
        '200':
          description: get Bibliography Workspace data to be returned
          content:
            application/json:
              example:
                Id: 1
                Afe_number: 1
                Bibliography_id: 1
    post:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Post a new Bibliography Workspace
      description: Create a new Bibliography Workspace data
      requestBody:
        required: true
        description: Request body to create Bibliography Workspace data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Bibliography'
            example:
              Id: 1
              Afe_number: 1
              Bibliography_id: 1
      responses:
        '200':
          description: Bibliography Workspace data is added
          content:
            application/json:
              example:
                message: The Bibliography Workspace data was successfully added
  /Bibliography-workspace/{afe}}:
    parameters:
    - in: path
      name: afe
      required: true
      description: afe of Bibliography data to fetch
      schema:
        type: interger
    get:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Get Bibliography Workspace
      responses:
        '200':
          description: get Bibliography Workspace data to be returned
          content:
            application/json:
              example:
                Id: 1
                Afe_number: 1
                Bibliography_id: 1
  /Bibliography-workspace/{id}:
    parameters:
    - in: path
      name: id
      required: true
      description: id of Bibliography data to fetch
      schema:
        type: interger
    put:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Update a new Bibliography Workspace data
      description: Update a new Bibliography Workspace Workspace data
      requestBody:
        required: true
        description: Request body to update Bibliography data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Bibliography'
            example:
              Id: 1
              Afe_number: 1
              Bibliography_id: 1
      responses:
        '200':
          description: Bibliography Workspace data is completely updated
          content:
            application/json:
              example:
                message: The Bibliography Workspace data is completely updated
    patch:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Update a new Bibliography data
      description: Update a new Bibliography data
      requestBody:
        required: true
        description: Request body to update Bibliography data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Bibliography'
            example:
              Id: 1
              Afe_number: 1
              Bibliography_id: 1
      responses:
        '200':
          description: one row in Bibliography data is updated
          content:
            application/json:
              example:
                message: The one row in Bibliography Workspace data is updated
    delete:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Delete Bibliography Workspace data
      description: Delete Bibliography data
      responses:
        '200':
          description: Bibliography Workspace data is deleted
          content:
            application/json:
              example:
                message: The Bibliography Workspace data was successfully deleted
  /Bibliography:
    get:
      security:
      - Authorization: []
      tags:
      - Bibliography
      summary: Get Bibliography
      responses:
        '200':
          description: get Bibliography data to be returned
          content:
            application/json:
              example:
                Publisher: LoremIpsum
                Document_title: LoremIpsum
                Issue: LoremIpsum
                Author_id: LoremIpsum
                Publication_date: LoremIpsum
                Document_type: LoremIpsum
                Data_store_name: LoremIpsum
    post:
      security:
      - Authorization: []
      tags:
      - Bibliography
      summary: Post a new Bibliography
      description: Create a new Bibliography data
      requestBody:
        required: true
        description: Request body to create Bibliography data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Bibliography'
            example: []
      responses:
        '200':
          description: Bibliography data is added
          content:
            application/json:
              example:
                message: The Bibliography data was successfully added
  /Bibliography/{id}:
    parameters:
    - in: path
      name: id
      required: true
      description: id of Bibliography data to fetch
      schema:
        type: interger
    get:
      security:
      - Authorization: []
      tags:
      - Bibliography
      summary: Get Bibliography
      responses:
        '200':
          description: get Bibliography data to be returned
          content:
            application/json:
              example:
              - []
    put:
      security:
      - Authorization: []
      tags:
      - Bibliography
      summary: Update a new Bibliography data
      description: Update a new Bibliography data
      requestBody:
        required: true
        description: Request body to update Bibliography data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Bibliography'
            example: []
      responses:
        '200':
          description: Bibliography data is completely updated
          content:
            application/json:
              example:
                message: The Bibliography data is completely updated
    patch:
      security:
      - Authorization: []
      tags:
      - Bibliography
      summary: Update a new Bibliography data
      description: Update a new Bibliography data
      requestBody:
        required: true
        description: Request body to update Bibliography data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Bibliography'
            example: []
      responses:
        '200':
          description: one row in Bibliography data is updated
          content:
            application/json:
              example:
                message: The one row in Bibliography data is updated
    delete:
      security:
      - Authorization: []
      tags:
      - Bibliography
      summary: Delete Bibliography data
      description: Delete Bibliography data
      responses:
        '200':
          description: Bibliography data is deleted
          content:
            application/json:
              example:
                message: The Bibliography data was successfully deleted
  /Bibliography/{num}:
    parameters:
    - in: path
      name: num
      required: true
      description: number of dummy data to add
      schema:
        type: interger
    get:
      security:
      - Authorization: []
      tags:
      - Bibliography Dummy Data
      summary: Add dummy data to Bibliography
      responses:
        '200':
          description: add data to Bibliography
          content:
            application/json: {}
components:
  schemas:
    afe:
      type: array
      items:
        type: object
        properties:
          afe_number:
            type: integer
          workspace_name:
            type: string
          kkks_name:
            type: string
          working_area:
            type: string
          submission_type:
            type: string
          data_type:
            type: string
    Bibliography_workspace:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
          afe_number:
            type: integer
          Bibliography_id:
            type: integer
    Bibliography:
      type: object
      properties:
        Publisher:
          type: string
        Document_title:
          type: string
        Issue:
          type: string
        Author_id:
          type: string
        Publication_date:
          type: string
        Document_type:
          type: string
        Data_store_name:
          type: string
  securitySchemes:
    OAuth2PasswordBearer:
      type: oauth2
      flows:
        password:
          scopes: {}
          tokenUrl: v1/token
