openapi: 3.0.0
info:
  description: This is the swagger API for Digita_Well_Log
  version: 1.0.0
  title: Digita_Well_Log
  termsOfService: http://swagger.io/terms/
  contact:
    email: darren.mannuela@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
- description: Digita_Well_Log
  url: http://localhost:8080/api/v1
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/DarrenMannuela/Digita_Well_Log/1.0.0
tags:
- name: Afe
  description: All endpoints related to get Digita_Well_Log AFE
- name: Workspace
  description: All endpoints related to Digita_Well_Log Workspace
- name: Digita Well Log
  description: All endpoints related to Digita_Well_Log
- name: Digita Well Log Dummy Data
  description: All endpoints related to Digita_Well_Log
paths:
  /Digita-Well-Log-afe:
    get:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Get Digita_Well_Log AFE
      responses:
        '200':
          description: get Digita_Well_Log AFE data to be returned
          content:
            application/json:
              example:
                afe_number: 1
                workspace_name: LoremIpsum
                kkks_name: LoremIpsum
                working_area: LoremIpsum
                submission_type: Lorem
                data_type: Digita Well Log
    post:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Post a new Digita_Well_Log AFE
      description: Create a new Digita_Well_Log AFE data
      requestBody:
        required: true
        description: Request body to create Digita_Well_Log AFE data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Digita_Well_Log'
            example:
              afe_number: 1
              workspace_name: LoremIpsum
              kkks_name: LoremIpsum
              working_area: LoremIpsum
              submission_type: Lorem
              data_type: Digita Well Log
      responses:
        '200':
          description: Digita_Well_Log data is added
          content:
            application/json:
              example:
                message: The Digita_Well_Log AFE data was successfully added
  /Digita-Well-Log-afe/{afe}:
    parameters:
    - in: path
      name: afe
      required: true
      description: afe of Digita_Well_Log data to fetch
      schema:
        type: interger
    get:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Get Digita_Well_Log AFE
      responses:
        '200':
          description: get Digita_Well_Log AFE data to be returned
          content:
            application/json:
              example:
                afe_number: 1
                workspace_name: LoremIpsum
                kkks_name: LoremIpsum
                working_area: LoremIpsum
                submission_type: Lorem
                data_type: Digita Well Log
    put:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Update a new Digita_Well_Log AFE data
      description: Update a new Digita_Well_Log data
      requestBody:
        required: true
        description: Request body to update Digita_Well_Log AFE data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Digita_Well_Log'
            example:
              afe_number: 1
              workspace_name: LoremIpsum
              kkks_name: LoremIpsum
              working_area: LoremIpsum
              submission_type: Lorem
              data_type: Digita Well Log
      responses:
        '200':
          description: Digita_Well_Log data is completely updated
          content:
            application/json:
              example:
                message: The Digita_Well_Log AFE data is completely updated
    patch:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Update a new Digita_Well_Log AFE data
      description: Update a new Digita_Well_Log data
      requestBody:
        required: true
        description: Request body to update Digita_Well_Log AFE data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Digita_Well_Log'
            example:
              afe_number: 1
              workspace_name: LoremIpsum
              kkks_name: LoremIpsum
              working_area: LoremIpsum
              submission_type: Lorem
              data_type: Digita Well Log
      responses:
        '200':
          description: one row in Digita_Well_Log data is updated
          content:
            application/json:
              example:
                message: The one row in Digita_Well_Log AFE data is updated
    delete:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Delete Digita_Well_Log AFE data
      description: Delete Digita_Well_Log AFE data
      responses:
        '200':
          description: Digita_Well_Log AFE data is deleted
          content:
            application/json:
              example:
                message: The Digita_Well_Log AFE data was successfully deleted
  /Digita-Well-Log-workspace:
    get:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Get Digita_Well_Log Workspace
      responses:
        '200':
          description: get Digita_Well_Log Workspace data to be returned
          content:
            application/json:
              example:
                Id: 1
                Afe_number: 1
                Dwl_id: 1
    post:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Post a new Digita_Well_Log Workspace
      description: Create a new Digita_Well_Log Workspace data
      requestBody:
        required: true
        description: Request body to create Digita_Well_Log Workspace data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Digita_Well_Log'
            example:
              Id: 1
              Afe_number: 1
              Dwl_id: 1
      responses:
        '200':
          description: Digita_Well_Log Workspace data is added
          content:
            application/json:
              example:
                message: The Digita_Well_Log Workspace data was successfully added
  /Digita-Well-Log-workspace/{afe}}:
    parameters:
    - in: path
      name: afe
      required: true
      description: afe of Digita_Well_Log data to fetch
      schema:
        type: interger
    get:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Get Digita_Well_Log Workspace
      responses:
        '200':
          description: get Digita_Well_Log Workspace data to be returned
          content:
            application/json:
              example:
                Id: 1
                Afe_number: 1
                Dwl_id: 1
  /Digita-Well-Log-workspace/{id}:
    parameters:
    - in: path
      name: id
      required: true
      description: id of Digita_Well_Log data to fetch
      schema:
        type: interger
    put:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Update a new Digita_Well_Log Workspace data
      description: Update a new Digita_Well_Log Workspace Workspace data
      requestBody:
        required: true
        description: Request body to update Digita_Well_Log data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Digita_Well_Log'
            example:
              Id: 1
              Afe_number: 1
              Dwl_id: 1
      responses:
        '200':
          description: Digita_Well_Log Workspace data is completely updated
          content:
            application/json:
              example:
                message: The Digita_Well_Log Workspace data is completely updated
    patch:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Update a new Digita_Well_Log data
      description: Update a new Digita_Well_Log data
      requestBody:
        required: true
        description: Request body to update Digita_Well_Log data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Digita_Well_Log'
            example:
              Id: 1
              Afe_number: 1
              Dwl_id: 1
      responses:
        '200':
          description: one row in Digita_Well_Log data is updated
          content:
            application/json:
              example:
                message: The one row in Digita_Well_Log Workspace data is updated
    delete:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Delete Digita_Well_Log Workspace data
      description: Delete Digita_Well_Log data
      responses:
        '200':
          description: Digita_Well_Log Workspace data is deleted
          content:
            application/json:
              example:
                message: The Digita_Well_Log Workspace data was successfully deleted
  /Digita-Well-Log:
    get:
      security:
      - Authorization: []
      tags:
      - Digita Well Log
      summary: Get Digita_Well_Log
      responses:
        '200':
          description: get Digita_Well_Log data to be returned
          content:
            application/json:
              example:
                Ba_long_name: LoremIpsum
                Ba_type: LoremIpsum
                Area_id: LoremIpsum
                Area_type: LoremIpsum
                Field_name: LoremIpsum
                Well_name: LoremIpsum
                Uwi: LoremIpsum
                Logging_company: LoremIpsum
                Media_type: LoremIpsum
                Well_log_class_id: LoremIpsum
                Digital_format: LoremIpsum
                Report_log_run: LoremIpsum
                Trip_date: LoremIpsum
                Top_depth: LoremIpsum
                Top_depth_ouom: LoremIpsum
                Base_depth: LoremIpsum
                Base_depth_ouom: LoremIpsum
                Original_file_name: LoremIpsum
                Password: LoremIpsum
                Digital_size: LoremIpsum
                Digital_size_uom: LoremIpsum
                Data_store_name: LoremIpsum
                Remark: LoremIpsum
                Source: LoremIpsum
                Qc_status: LoremIpsum
                Checked_by_ba_id: LoremIpsum
    post:
      security:
      - Authorization: []
      tags:
      - Digita Well Log
      summary: Post a new Digita_Well_Log
      description: Create a new Digita_Well_Log data
      requestBody:
        required: true
        description: Request body to create Digita_Well_Log data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Digita_Well_Log'
            example: []
      responses:
        '200':
          description: Digita_Well_Log data is added
          content:
            application/json:
              example:
                message: The Digita_Well_Log data was successfully added
  /Digita-Well-Log/{id}:
    parameters:
    - in: path
      name: id
      required: true
      description: id of Digita_Well_Log data to fetch
      schema:
        type: interger
    get:
      security:
      - Authorization: []
      tags:
      - Digita Well Log
      summary: Get Digita_Well_Log
      responses:
        '200':
          description: get Digita_Well_Log data to be returned
          content:
            application/json:
              example:
              - []
    put:
      security:
      - Authorization: []
      tags:
      - Digita Well Log
      summary: Update a new Digita_Well_Log data
      description: Update a new Digita_Well_Log data
      requestBody:
        required: true
        description: Request body to update Digita_Well_Log data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Digita_Well_Log'
            example: []
      responses:
        '200':
          description: Digita_Well_Log data is completely updated
          content:
            application/json:
              example:
                message: The Digita_Well_Log data is completely updated
    patch:
      security:
      - Authorization: []
      tags:
      - Digita Well Log
      summary: Update a new Digita_Well_Log data
      description: Update a new Digita_Well_Log data
      requestBody:
        required: true
        description: Request body to update Digita_Well_Log data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Digita_Well_Log'
            example: []
      responses:
        '200':
          description: one row in Digita_Well_Log data is updated
          content:
            application/json:
              example:
                message: The one row in Digita_Well_Log data is updated
    delete:
      security:
      - Authorization: []
      tags:
      - Digita Well Log
      summary: Delete Digita_Well_Log data
      description: Delete Digita_Well_Log data
      responses:
        '200':
          description: Digita_Well_Log data is deleted
          content:
            application/json:
              example:
                message: The Digita_Well_Log data was successfully deleted
components:
  schemas:
    afe:
      type: array
      items:
        type: object
        properties:
          afe_number:
            type: integer
          workspace_name:
            type: string
          kkks_name:
            type: string
          working_area:
            type: string
          submission_type:
            type: string
          data_type:
            type: string
    Digita_Well_Log_workspace:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
          afe_number:
            type: integer
          Dwl_id:
            type: integer
    Digita_Well_Log:
      type: object
      properties:
        Ba_long_name:
          type: string
        Ba_type:
          type: string
        Area_id:
          type: string
        Area_type:
          type: string
        Field_name:
          type: string
        Well_name:
          type: string
        Uwi:
          type: string
        Logging_company:
          type: string
        Media_type:
          type: string
        Well_log_class_id:
          type: string
        Digital_format:
          type: string
        Report_log_run:
          type: string
        Trip_date:
          type: string
        Top_depth:
          type: string
        Top_depth_ouom:
          type: string
        Base_depth:
          type: string
        Base_depth_ouom:
          type: string
        Original_file_name:
          type: string
        Password:
          type: string
        Digital_size:
          type: string
        Digital_size_uom:
          type: string
        Data_store_name:
          type: string
        Remark:
          type: string
        Source:
          type: string
        Qc_status:
          type: string
        Checked_by_ba_id:
          type: string
  securitySchemes:
    Authorization:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Please enter the access token
