openapi: 3.0.0
info:
  description: This is the swagger API for Digital_well_log
  version: 1.0.0
  title: Digital_well_log
  termsOfService: http://swagger.io/terms/
  contact:
    email: darren.mannuela@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
- description: Digital_well_log
  url: http://localhost:8080/api/v1
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/DarrenMannuela/Digital_well_log/1.0.0
tags:
- name: Afe
  description: All endpoints related to get Digital_well_log AFE
- name: Workspace
  description: All endpoints related to Digital_well_log Workspace
- name: Digital_well_log
  description: All endpoints related to Digital_well_log
- name: Digital_well_log Dummy Data
  description: All endpoints related to Digital_well_log
- name: User Mgmt
  description: All endpoints related to tokens
paths:
  /Digital_well_log-afe:
    get:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Get Digital_well_log AFE
      responses:
        '200':
          description: get Digital_well_log AFE data to be returned
          content:
            application/json:
              example:
                afe_number: 1
                workspace_name: LoremIpsum
                kkks_name: LoremIpsum
                working_area: LoremIpsum
                submission_type: Lorem
                data_type: Digital_well_log
                email: john.richardson@gtn.id
    post:
      security:
      - OAuth2PasswordBearer: []
      tags:
      - Afe
      summary: Post a new Digital_well_log AFE
      description: Create a new Digital_well_log AFE data
      requestBody:
        required: true
        description: Request body to create Digital_well_log AFE data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Digital_well_log'
            example:
              afe_number: 1
              workspace_name: LoremIpsum
              kkks_name: LoremIpsum
              working_area: LoremIpsum
              submission_type: Lorem
              data_type: Digital_well_log
              email: john.richardson@gtn.id
      responses:
        '200':
          description: Digital_well_log data is added
          content:
            application/json:
              example:
                message: The Digital_well_log AFE data was successfully added
  /Digital_well_log-afe/{afe}:
    parameters:
    - in: path
      name: afe
      required: true
      description: afe of Digital_well_log data to fetch
      schema:
        type: integer
    get:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Get Digital_well_log AFE
      responses:
        '200':
          description: get Digital_well_log AFE data to be returned
          content:
            application/json:
              example:
                afe_number: 1
                workspace_name: LoremIpsum
                kkks_name: LoremIpsum
                working_area: LoremIpsum
                submission_type: Lorem
                data_type: Digital_well_log
                email: john.richardson@gtn.id
    put:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Update a new Digital_well_log AFE data
      description: Update a new Digital_well_log data
      requestBody:
        required: true
        description: Request body to update Digital_well_log AFE data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Digital_well_log'
            example:
              afe_number: 1
              workspace_name: LoremIpsum
              kkks_name: LoremIpsum
              working_area: LoremIpsum
              submission_type: Lorem
              data_type: Digital_well_log
              email: john.richardson@gtn.id
      responses:
        '200':
          description: Digital_well_log data is completely updated
          content:
            application/json:
              example:
                message: The Digital_well_log AFE data is completely updated
    patch:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Update a new Digital_well_log AFE data
      description: Update a new Digital_well_log data
      requestBody:
        required: true
        description: Request body to update Digital_well_log AFE data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Digital_well_log'
            example:
              afe_number: 1
              workspace_name: LoremIpsum
              kkks_name: LoremIpsum
              working_area: LoremIpsum
              submission_type: Lorem
              data_type: Digital_well_log
              email: john.richardson@gtn.id
      responses:
        '200':
          description: one row in Digital_well_log data is updated
          content:
            application/json:
              example:
                message: The one row in Digital_well_log AFE data is updated
    delete:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Delete Digital_well_log AFE data
      description: Delete Digital_well_log AFE data
      responses:
        '200':
          description: Digital_well_log AFE data is deleted
          content:
            application/json:
              example:
                message: The Digital_well_log AFE data was successfully deleted
  /Digital_well_log-workspace:
    get:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Get Digital_well_log Workspace
      responses:
        '200':
          description: get Digital_well_log Workspace data to be returned
          content:
            application/json:
              example:
                Id: 1
                Afe_number: 1
                Digital_well_log_id: 1
    post:
      security:
      - OAuth2PasswordBearer: []
      tags:
      - Workspace
      summary: Post a new Digital_well_log Workspace
      description: Create a new Digital_well_log Workspace data
      requestBody:
        required: true
        description: Request body to create Digital_well_log Workspace data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Digital_well_log'
            example:
              Id: 1
              Afe_number: 1
              Digital_well_log_id: 1
      responses:
        '200':
          description: Digital_well_log Workspace data is added
          content:
            application/json:
              example:
                message: The Digital_well_log Workspace data was successfully added
  /Digital_well_log-workspace/{afe}}:
    parameters:
    - in: path
      name: afe
      required: true
      description: afe of Digital_well_log data to fetch
      schema:
        type: integer
    get:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Get Digital_well_log Workspace
      responses:
        '200':
          description: get Digital_well_log Workspace data to be returned
          content:
            application/json:
              example:
                Id: 1
                Afe_number: 1
                Digital_well_log_id: 1
  /Digital_well_log-workspace/{id}:
    parameters:
    - in: path
      name: id
      required: true
      description: id of Digital_well_log data to fetch
      schema:
        type: integer
    put:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Update a new Digital_well_log Workspace data
      description: Update a new Digital_well_log Workspace Workspace data
      requestBody:
        required: true
        description: Request body to update Digital_well_log data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Digital_well_log'
            example:
              Id: 1
              Afe_number: 1
              Digital_well_log_id: 1
      responses:
        '200':
          description: Digital_well_log Workspace data is completely updated
          content:
            application/json:
              example:
                message: The Digital_well_log Workspace data is completely updated
    patch:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Update a new Digital_well_log data
      description: Update a new Digital_well_log data
      requestBody:
        required: true
        description: Request body to update Digital_well_log data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Digital_well_log'
            example:
              Id: 1
              Afe_number: 1
              Digital_well_log_id: 1
      responses:
        '200':
          description: one row in Digital_well_log data is updated
          content:
            application/json:
              example:
                message: The one row in Digital_well_log Workspace data is updated
    delete:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Delete Digital_well_log Workspace data
      description: Delete Digital_well_log data
      responses:
        '200':
          description: Digital_well_log Workspace data is deleted
          content:
            application/json:
              example:
                message: The Digital_well_log Workspace data was successfully deleted
  /Digital_well_log:
    get:
      security:
      - Authorization: []
      tags:
      - Digital_well_log
      summary: Get Digital_well_log
      responses:
        '200':
          description: get Digital_well_log data to be returned
          content:
            application/json:
              example:
                Id: 1
                Ba_long_name: LoremIpsum
                Ba_type: LoremIpsum
                Area_id: LoremIpsum
                Area_type: LoremIpsum
                Field_name: LoremIpsum
                Well_name: LoremIpsum
                Uwi_: LoremIpsum
                Logging_company: LoremIpsum
                Media_type: LoremIpsum
                Well_log_class_id: LoremIpsum
                Digital_format: LoremIpsum
                Report_log_run: LoremIpsum
                Trip_date: LoremIpsum
                Top_depth: 1
                Top_depth_ouom: LoremIpsum
                Base_depth: 1
                Base_depth_ouom: LoremIpsum
                Original_file_name: LoremIpsum
                Password_: LoremIpsum
                Digital_size: 1
                Digital_size_uom: LoremIpsum
                Ba_long_name_2: LoremIpsum
                Ba_type_2: LoremIpsum
                Data_store_name: LoremIpsum
                Remark_: LoremIpsum
                Source_: LoremIpsum
                Qc_status: LoremIpsum
                Checked_by_ba_id: LoremIpsum
    post:
      security:
      - OAuth2PasswordBearer: []
      tags:
      - Digital_well_log
      summary: Post a new Digital_well_log
      description: Create a new Digital_well_log data
      requestBody:
        required: true
        description: Request body to create Digital_well_log data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Digital_well_log'
            example: []
      responses:
        '200':
          description: Digital_well_log data is added
          content:
            application/json:
              example:
                message: The Digital_well_log data was successfully added
  /Digital_well_log/{id}:
    parameters:
    - in: path
      name: id
      required: true
      description: id of Digital_well_log data to fetch
      schema:
        type: integer
    get:
      security:
      - Authorization: []
      tags:
      - Digital_well_log
      summary: Get Digital_well_log
      responses:
        '200':
          description: get Digital_well_log data to be returned
          content:
            application/json:
              example:
              - []
    put:
      security:
      - Authorization: []
      tags:
      - Digital_well_log
      summary: Update a new Digital_well_log data
      description: Update a new Digital_well_log data
      requestBody:
        required: true
        description: Request body to update Digital_well_log data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Digital_well_log'
            example: []
      responses:
        '200':
          description: Digital_well_log data is completely updated
          content:
            application/json:
              example:
                message: The Digital_well_log data is completely updated
    patch:
      security:
      - Authorization: []
      tags:
      - Digital_well_log
      summary: Update a new Digital_well_log data
      description: Update a new Digital_well_log data
      requestBody:
        required: true
        description: Request body to update Digital_well_log data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Digital_well_log'
            example: []
      responses:
        '200':
          description: one row in Digital_well_log data is updated
          content:
            application/json:
              example:
                message: The one row in Digital_well_log data is updated
    delete:
      security:
      - Authorization: []
      tags:
      - Digital_well_log
      summary: Delete Digital_well_log data
      description: Delete Digital_well_log data
      responses:
        '200':
          description: Digital_well_log data is deleted
          content:
            application/json:
              example:
                message: The Digital_well_log data was successfully deleted
  /Digital_well_log/{num}:
    parameters:
    - in: path
      name: num
      required: true
      description: number of dummy data to add
      schema:
        type: integer
    get:
      security:
      - Authorization: []
      tags:
      - Digital_well_log Dummy Data
      summary: Add dummy data to Digital_well_log
      responses:
        '200':
          description: add data to Digital_well_log
          content:
            application/json: {}
  /token:
    post:
      security:
      - OAuth2PasswordBearer: []
      tags:
      - User Mgmt
      summary: Login For Access Token
      operationId: login_for_access_token_token_post
      requestBody:
        required: true
        description: Request body to create Digital_well_log AFE data
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Body_login_for_access_token_token_post'
            example: []
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    afe:
      type: array
      items:
        type: object
        properties:
          afe_number:
            type: integer
          workspace_name:
            type: string
          kkks_name:
            type: string
          working_area:
            type: string
          submission_type:
            type: string
          data_type:
            type: string
    Token:
      title: Token
      required:
      - access_token
      - token_type
      - type
      - name
      - expiry_date
      - affiliation
      type: object
      properties:
        access_token:
          title: Access Token
          type: string
        token_type:
          title: Token Type
          type: string
        type:
          $ref: '#/components/schemas/UserType'
        name:
          title: Name
          type: string
        expiry_date:
          title: Expiry Date
          type: string
        affiliation:
          title: Affiliation
          type: string
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
    UserType:
      title: UserType
      enum:
      - Administrator
      - Regular User
      - Premium User
      type: string
      description: An enumeration.
    ValidationError:
      title: ValidationError
      required:
      - loc
      - msg
      - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            anyOf:
            - type: string
            - type: integer
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
    Body_login_for_access_token_token_post:
      title: Body_login_for_access_token_token_post
      required:
      - username
      - password
      type: object
      properties:
        grant_type:
          title: Grant Type
          pattern: password
          type: string
        username:
          title: Username
          type: string
        password:
          title: Password
          type: string
        scope:
          title: Scope
          type: string
          default: ''
        client_id:
          title: Client Id
          type: string
        client_secret:
          title: Client Secret
          type: string
    Digital_well_log_workspace:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
          afe_number:
            type: integer
          Digital_well_log_id:
            type: integer
    Digital_well_log:
      type: object
      properties:
        Id:
          type: integer
        Ba_long_name:
          type: string
        Ba_type:
          type: string
        Area_id:
          type: string
        Area_type:
          type: string
        Field_name:
          type: string
        Well_name:
          type: string
        Uwi_:
          type: string
        Logging_company:
          type: string
        Media_type:
          type: string
        Well_log_class_id:
          type: string
        Digital_format:
          type: string
        Report_log_run:
          type: string
        Trip_date:
          type: string
        Top_depth:
          type: integer
        Top_depth_ouom:
          type: string
        Base_depth:
          type: integer
        Base_depth_ouom:
          type: string
        Original_file_name:
          type: string
        Password_:
          type: string
        Digital_size:
          type: integer
        Digital_size_uom:
          type: string
        Ba_long_name_2:
          type: string
        Ba_type_2:
          type: string
        Data_store_name:
          type: string
        Remark_:
          type: string
        Source_:
          type: string
        Qc_status:
          type: string
        Checked_by_ba_id:
          type: string
  securitySchemes:
    OAuth2PasswordBearer:
      type: oauth2
      flows:
        password:
          scopes: {}
          tokenUrl: v1/token
