openapi: 3.0.0
info:
  description: This is the swagger API for Digital_Maps_And_Technical_Drawing
  version: 1.0.0
  title: Digital_Maps_And_Technical_Drawing
  termsOfService: http://swagger.io/terms/
  contact:
    email: darren.mannuela@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
- description: Digital_Maps_And_Technical_Drawing
  url: http://localhost:8080/api/v1
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/DarrenMannuela/Digital_Maps_And_Technical_Drawing/1.0.0
tags:
- name: Afe
  description: All endpoints related to get Digital_Maps_And_Technical_Drawing AFE
- name: Workspace
  description: All endpoints related to Digital_Maps_And_Technical_Drawing Workspace
- name: Digital Maps And Technical Drawing
  description: All endpoints related to Digital_Maps_And_Technical_Drawing
- name: Digital Maps And Technical Drawing Dummy Data
  description: All endpoints related to Digital_Maps_And_Technical_Drawing
paths:
  /Digital-Maps-And-Technical-Drawing-afe:
    get:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Get Digital_Maps_And_Technical_Drawing AFE
      responses:
        '200':
          description: get Digital_Maps_And_Technical_Drawing AFE data to be returned
          content:
            application/json:
              example:
                afe_number: 1
                workspace_name: LoremIpsum
                kkks_name: LoremIpsum
                working_area: LoremIpsum
                submission_type: Lorem
                data_type: Digital Maps And Technical Drawing
              user_id: 1
    post:
      security:
      - OAuth2PasswordBearer: []
      tags:
      - Afe
      summary: Post a new Digital_Maps_And_Technical_Drawing AFE
      description: Create a new Digital_Maps_And_Technical_Drawing AFE data
      requestBody:
        required: true
        description: Request body to create Digital_Maps_And_Technical_Drawing AFE
          data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Digital_Maps_And_Technical_Drawing'
            example:
              afe_number: 1
              workspace_name: LoremIpsum
              kkks_name: LoremIpsum
              working_area: LoremIpsum
              submission_type: Lorem
              data_type: Digital Maps And Technical Drawing
            user_id: 1
      responses:
        '200':
          description: Digital_Maps_And_Technical_Drawing data is added
          content:
            application/json:
              example:
                message: The Digital_Maps_And_Technical_Drawing AFE data was successfully
                  added
  /Digital-Maps-And-Technical-Drawing-afe/{afe}:
    parameters:
    - in: path
      name: afe
      required: true
      description: afe of Digital_Maps_And_Technical_Drawing data to fetch
      schema:
        type: interger
    get:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Get Digital_Maps_And_Technical_Drawing AFE
      responses:
        '200':
          description: get Digital_Maps_And_Technical_Drawing AFE data to be returned
          content:
            application/json:
              example:
                afe_number: 1
                workspace_name: LoremIpsum
                kkks_name: LoremIpsum
                working_area: LoremIpsum
                submission_type: Lorem
                data_type: Digital Maps And Technical Drawing
              user_id: 1
    put:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Update a new Digital_Maps_And_Technical_Drawing AFE data
      description: Update a new Digital_Maps_And_Technical_Drawing data
      requestBody:
        required: true
        description: Request body to update Digital_Maps_And_Technical_Drawing AFE
          data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Digital_Maps_And_Technical_Drawing'
            example:
              afe_number: 1
              workspace_name: LoremIpsum
              kkks_name: LoremIpsum
              working_area: LoremIpsum
              submission_type: Lorem
              data_type: Digital Maps And Technical Drawing
            user_id: 1
      responses:
        '200':
          description: Digital_Maps_And_Technical_Drawing data is completely updated
          content:
            application/json:
              example:
                message: The Digital_Maps_And_Technical_Drawing AFE data is completely
                  updated
    patch:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Update a new Digital_Maps_And_Technical_Drawing AFE data
      description: Update a new Digital_Maps_And_Technical_Drawing data
      requestBody:
        required: true
        description: Request body to update Digital_Maps_And_Technical_Drawing AFE
          data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Digital_Maps_And_Technical_Drawing'
            example:
              afe_number: 1
              workspace_name: LoremIpsum
              kkks_name: LoremIpsum
              working_area: LoremIpsum
              submission_type: Lorem
              data_type: Digital Maps And Technical Drawing
            user_id: 1
      responses:
        '200':
          description: one row in Digital_Maps_And_Technical_Drawing data is updated
          content:
            application/json:
              example:
                message: The one row in Digital_Maps_And_Technical_Drawing AFE data
                  is updated
    delete:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Delete Digital_Maps_And_Technical_Drawing AFE data
      description: Delete Digital_Maps_And_Technical_Drawing AFE data
      responses:
        '200':
          description: Digital_Maps_And_Technical_Drawing AFE data is deleted
          content:
            application/json:
              example:
                message: The Digital_Maps_And_Technical_Drawing AFE data was successfully
                  deleted
  /Digital-Maps-And-Technical-Drawing-workspace:
    get:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Get Digital_Maps_And_Technical_Drawing Workspace
      responses:
        '200':
          description: get Digital_Maps_And_Technical_Drawing Workspace data to be
            returned
          content:
            application/json:
              example:
                Id: 1
                Afe_number: 1
                Digital_maps_and_technical_drawing_id: 1
    post:
      security:
      - OAuth2PasswordBearer: []
      tags:
      - Workspace
      summary: Post a new Digital_Maps_And_Technical_Drawing Workspace
      description: Create a new Digital_Maps_And_Technical_Drawing Workspace data
      requestBody:
        required: true
        description: Request body to create Digital_Maps_And_Technical_Drawing Workspace
          data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Digital_Maps_And_Technical_Drawing'
            example:
              Id: 1
              Afe_number: 1
              Digital_maps_and_technical_drawing_id: 1
      responses:
        '200':
          description: Digital_Maps_And_Technical_Drawing Workspace data is added
          content:
            application/json:
              example:
                message: The Digital_Maps_And_Technical_Drawing Workspace data was
                  successfully added
  /Digital-Maps-And-Technical-Drawing-workspace/{afe}}:
    parameters:
    - in: path
      name: afe
      required: true
      description: afe of Digital_Maps_And_Technical_Drawing data to fetch
      schema:
        type: interger
    get:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Get Digital_Maps_And_Technical_Drawing Workspace
      responses:
        '200':
          description: get Digital_Maps_And_Technical_Drawing Workspace data to be
            returned
          content:
            application/json:
              example:
                Id: 1
                Afe_number: 1
                Digital_maps_and_technical_drawing_id: 1
  /Digital-Maps-And-Technical-Drawing-workspace/{id}:
    parameters:
    - in: path
      name: id
      required: true
      description: id of Digital_Maps_And_Technical_Drawing data to fetch
      schema:
        type: interger
    put:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Update a new Digital_Maps_And_Technical_Drawing Workspace data
      description: Update a new Digital_Maps_And_Technical_Drawing Workspace Workspace
        data
      requestBody:
        required: true
        description: Request body to update Digital_Maps_And_Technical_Drawing data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Digital_Maps_And_Technical_Drawing'
            example:
              Id: 1
              Afe_number: 1
              Digital_maps_and_technical_drawing_id: 1
      responses:
        '200':
          description: Digital_Maps_And_Technical_Drawing Workspace data is completely
            updated
          content:
            application/json:
              example:
                message: The Digital_Maps_And_Technical_Drawing Workspace data is
                  completely updated
    patch:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Update a new Digital_Maps_And_Technical_Drawing data
      description: Update a new Digital_Maps_And_Technical_Drawing data
      requestBody:
        required: true
        description: Request body to update Digital_Maps_And_Technical_Drawing data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Digital_Maps_And_Technical_Drawing'
            example:
              Id: 1
              Afe_number: 1
              Digital_maps_and_technical_drawing_id: 1
      responses:
        '200':
          description: one row in Digital_Maps_And_Technical_Drawing data is updated
          content:
            application/json:
              example:
                message: The one row in Digital_Maps_And_Technical_Drawing Workspace
                  data is updated
    delete:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Delete Digital_Maps_And_Technical_Drawing Workspace data
      description: Delete Digital_Maps_And_Technical_Drawing data
      responses:
        '200':
          description: Digital_Maps_And_Technical_Drawing Workspace data is deleted
          content:
            application/json:
              example:
                message: The Digital_Maps_And_Technical_Drawing Workspace data was
                  successfully deleted
  /Digital-Maps-And-Technical-Drawing:
    get:
      security:
      - Authorization: []
      tags:
      - Digital Maps And Technical Drawing
      summary: Get Digital_Maps_And_Technical_Drawing
      responses:
        '200':
          description: get Digital_Maps_And_Technical_Drawing data to be returned
          content:
            application/json:
              example:
                Ba_long_name: LoremIpsum
                Ba_type: LoremIpsum
                Area_id: LoremIpsum
                Area_type: LoremIpsum
                Title: LoremIpsum
                Creator_name: LoremIpsum
                Create_date: LoremIpsum
                Digital_format: LoremIpsum
                Media_type: LoremIpsum
                Map_scale: LoremIpsum
                Projection_type: LoremIpsum
                Geodetic_datum_name: LoremIpsum
                Document_type: LoremIpsum
                Item_category: LoremIpsum
                Data_store_name: LoremIpsum
                Original_file_name: LoremIpsum
                Password: LoremIpsum
                Digital_size: LoremIpsum
                Digital_size_uom: LoremIpsum
                Remark: LoremIpsum
                Source: LoremIpsum
                Qc_status: LoremIpsum
                Checked_by_ba_id: LoremIpsum
    post:
      security:
      - OAuth2PasswordBearer: []
      tags:
      - Digital Maps And Technical Drawing
      summary: Post a new Digital_Maps_And_Technical_Drawing
      description: Create a new Digital_Maps_And_Technical_Drawing data
      requestBody:
        required: true
        description: Request body to create Digital_Maps_And_Technical_Drawing data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Digital_Maps_And_Technical_Drawing'
            example: []
      responses:
        '200':
          description: Digital_Maps_And_Technical_Drawing data is added
          content:
            application/json:
              example:
                message: The Digital_Maps_And_Technical_Drawing data was successfully
                  added
  /Digital-Maps-And-Technical-Drawing/{id}:
    parameters:
    - in: path
      name: id
      required: true
      description: id of Digital_Maps_And_Technical_Drawing data to fetch
      schema:
        type: interger
    get:
      security:
      - Authorization: []
      tags:
      - Digital Maps And Technical Drawing
      summary: Get Digital_Maps_And_Technical_Drawing
      responses:
        '200':
          description: get Digital_Maps_And_Technical_Drawing data to be returned
          content:
            application/json:
              example:
              - []
    put:
      security:
      - Authorization: []
      tags:
      - Digital Maps And Technical Drawing
      summary: Update a new Digital_Maps_And_Technical_Drawing data
      description: Update a new Digital_Maps_And_Technical_Drawing data
      requestBody:
        required: true
        description: Request body to update Digital_Maps_And_Technical_Drawing data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Digital_Maps_And_Technical_Drawing'
            example: []
      responses:
        '200':
          description: Digital_Maps_And_Technical_Drawing data is completely updated
          content:
            application/json:
              example:
                message: The Digital_Maps_And_Technical_Drawing data is completely
                  updated
    patch:
      security:
      - Authorization: []
      tags:
      - Digital Maps And Technical Drawing
      summary: Update a new Digital_Maps_And_Technical_Drawing data
      description: Update a new Digital_Maps_And_Technical_Drawing data
      requestBody:
        required: true
        description: Request body to update Digital_Maps_And_Technical_Drawing data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Digital_Maps_And_Technical_Drawing'
            example: []
      responses:
        '200':
          description: one row in Digital_Maps_And_Technical_Drawing data is updated
          content:
            application/json:
              example:
                message: The one row in Digital_Maps_And_Technical_Drawing data is
                  updated
    delete:
      security:
      - Authorization: []
      tags:
      - Digital Maps And Technical Drawing
      summary: Delete Digital_Maps_And_Technical_Drawing data
      description: Delete Digital_Maps_And_Technical_Drawing data
      responses:
        '200':
          description: Digital_Maps_And_Technical_Drawing data is deleted
          content:
            application/json:
              example:
                message: The Digital_Maps_And_Technical_Drawing data was successfully
                  deleted
  /Digital-Maps-And-Technical-Drawing/{num}:
    parameters:
    - in: path
      name: num
      required: true
      description: number of dummy data to add
      schema:
        type: interger
    get:
      security:
      - Authorization: []
      tags:
      - Digital Maps And Technical Drawing Dummy Data
      summary: Add dummy data to Digital_Maps_And_Technical_Drawing
      responses:
        '200':
          description: add data to Digital_Maps_And_Technical_Drawing
          content:
            application/json: {}
components:
  schemas:
    afe:
      type: array
      items:
        type: object
        properties:
          afe_number:
            type: integer
          workspace_name:
            type: string
          kkks_name:
            type: string
          working_area:
            type: string
          submission_type:
            type: string
          data_type:
            type: string
    Digital_Maps_And_Technical_Drawing_workspace:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
          afe_number:
            type: integer
          Digital_maps_and_technical_drawing_id:
            type: integer
    Digital_Maps_And_Technical_Drawing:
      type: object
      properties:
        Ba_long_name:
          type: string
        Ba_type:
          type: string
        Area_id:
          type: string
        Area_type:
          type: string
        Title:
          type: string
        Creator_name:
          type: string
        Create_date:
          type: string
        Digital_format:
          type: string
        Media_type:
          type: string
        Map_scale:
          type: string
        Projection_type:
          type: string
        Geodetic_datum_name:
          type: string
        Document_type:
          type: string
        Item_category:
          type: string
        Data_store_name:
          type: string
        Original_file_name:
          type: string
        Password:
          type: string
        Digital_size:
          type: string
        Digital_size_uom:
          type: string
        Remark:
          type: string
        Source:
          type: string
        Qc_status:
          type: string
        Checked_by_ba_id:
          type: string
  securitySchemes:
    OAuth2PasswordBearer:
      type: oauth2
      flows:
        password:
          scopes: {}
          tokenUrl: v1/token
