openapi: 3.0.0
info:
  description: This is the swagger API for Digital_Well_Report
  version: 1.0.0
  title: Digital_Well_Report
  termsOfService: http://swagger.io/terms/
  contact:
    email: darren.mannuela@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
- description: Digital_Well_Report
  url: http://localhost:8080/api/v1
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/DarrenMannuela/Digital_Well_Report/1.0.0
tags:
- name: Afe
  description: All endpoints related to get Digital_Well_Report AFE
- name: Workspace
  description: All endpoints related to Digital_Well_Report Workspace
- name: Digital Well Report
  description: All endpoints related to Digital_Well_Report
- name: Digital Well Report Dummy Data
  description: All endpoints related to Digital_Well_Report
- name: User Mgmt
  description: All endpoints related to tokens
paths:
  /Digital-Well-Report-afe:
    get:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Get Digital_Well_Report AFE
      responses:
        '200':
          description: get Digital_Well_Report AFE data to be returned
          content:
            application/json:
              example:
                afe_number: 1
                workspace_name: LoremIpsum
                kkks_name: LoremIpsum
                working_area: LoremIpsum
                submission_type: Lorem
                data_type: Digital Well Report
                email: john.richardson@gtn.id
    post:
      security:
      - OAuth2PasswordBearer: []
      tags:
      - Afe
      summary: Post a new Digital_Well_Report AFE
      description: Create a new Digital_Well_Report AFE data
      requestBody:
        required: true
        description: Request body to create Digital_Well_Report AFE data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Digital_Well_Report'
            example:
              afe_number: 1
              workspace_name: LoremIpsum
              kkks_name: LoremIpsum
              working_area: LoremIpsum
              submission_type: Lorem
              data_type: Digital Well Report
              email: john.richardson@gtn.id
      responses:
        '200':
          description: Digital_Well_Report data is added
          content:
            application/json:
              example:
                message: The Digital_Well_Report AFE data was successfully added
  /Digital-Well-Report-afe/{afe}:
    parameters:
    - in: path
      name: afe
      required: true
      description: afe of Digital_Well_Report data to fetch
      schema:
        type: integer
    get:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Get Digital_Well_Report AFE
      responses:
        '200':
          description: get Digital_Well_Report AFE data to be returned
          content:
            application/json:
              example:
                afe_number: 1
                workspace_name: LoremIpsum
                kkks_name: LoremIpsum
                working_area: LoremIpsum
                submission_type: Lorem
                data_type: Digital Well Report
                email: john.richardson@gtn.id
    put:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Update a new Digital_Well_Report AFE data
      description: Update a new Digital_Well_Report data
      requestBody:
        required: true
        description: Request body to update Digital_Well_Report AFE data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Digital_Well_Report'
            example:
              afe_number: 1
              workspace_name: LoremIpsum
              kkks_name: LoremIpsum
              working_area: LoremIpsum
              submission_type: Lorem
              data_type: Digital Well Report
              email: john.richardson@gtn.id
      responses:
        '200':
          description: Digital_Well_Report data is completely updated
          content:
            application/json:
              example:
                message: The Digital_Well_Report AFE data is completely updated
    patch:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Update a new Digital_Well_Report AFE data
      description: Update a new Digital_Well_Report data
      requestBody:
        required: true
        description: Request body to update Digital_Well_Report AFE data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Digital_Well_Report'
            example:
              afe_number: 1
              workspace_name: LoremIpsum
              kkks_name: LoremIpsum
              working_area: LoremIpsum
              submission_type: Lorem
              data_type: Digital Well Report
              email: john.richardson@gtn.id
      responses:
        '200':
          description: one row in Digital_Well_Report data is updated
          content:
            application/json:
              example:
                message: The one row in Digital_Well_Report AFE data is updated
    delete:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Delete Digital_Well_Report AFE data
      description: Delete Digital_Well_Report AFE data
      responses:
        '200':
          description: Digital_Well_Report AFE data is deleted
          content:
            application/json:
              example:
                message: The Digital_Well_Report AFE data was successfully deleted
  /Digital-Well-Report-workspace:
    get:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Get Digital_Well_Report Workspace
      responses:
        '200':
          description: get Digital_Well_Report Workspace data to be returned
          content:
            application/json:
              example:
                Id: 1
                Afe_number: 1
                Digital_well_report_id: 1
    post:
      security:
      - OAuth2PasswordBearer: []
      tags:
      - Workspace
      summary: Post a new Digital_Well_Report Workspace
      description: Create a new Digital_Well_Report Workspace data
      requestBody:
        required: true
        description: Request body to create Digital_Well_Report Workspace data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Digital_Well_Report'
            example:
              Id: 1
              Afe_number: 1
              Digital_well_report_id: 1
      responses:
        '200':
          description: Digital_Well_Report Workspace data is added
          content:
            application/json:
              example:
                message: The Digital_Well_Report Workspace data was successfully added
  /Digital-Well-Report-workspace/{afe}}:
    parameters:
    - in: path
      name: afe
      required: true
      description: afe of Digital_Well_Report data to fetch
      schema:
        type: integer
    get:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Get Digital_Well_Report Workspace
      responses:
        '200':
          description: get Digital_Well_Report Workspace data to be returned
          content:
            application/json:
              example:
                Id: 1
                Afe_number: 1
                Digital_well_report_id: 1
  /Digital-Well-Report-workspace/{id}:
    parameters:
    - in: path
      name: id
      required: true
      description: id of Digital_Well_Report data to fetch
      schema:
        type: integer
    put:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Update a new Digital_Well_Report Workspace data
      description: Update a new Digital_Well_Report Workspace Workspace data
      requestBody:
        required: true
        description: Request body to update Digital_Well_Report data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Digital_Well_Report'
            example:
              Id: 1
              Afe_number: 1
              Digital_well_report_id: 1
      responses:
        '200':
          description: Digital_Well_Report Workspace data is completely updated
          content:
            application/json:
              example:
                message: The Digital_Well_Report Workspace data is completely updated
    patch:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Update a new Digital_Well_Report data
      description: Update a new Digital_Well_Report data
      requestBody:
        required: true
        description: Request body to update Digital_Well_Report data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Digital_Well_Report'
            example:
              Id: 1
              Afe_number: 1
              Digital_well_report_id: 1
      responses:
        '200':
          description: one row in Digital_Well_Report data is updated
          content:
            application/json:
              example:
                message: The one row in Digital_Well_Report Workspace data is updated
    delete:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Delete Digital_Well_Report Workspace data
      description: Delete Digital_Well_Report data
      responses:
        '200':
          description: Digital_Well_Report Workspace data is deleted
          content:
            application/json:
              example:
                message: The Digital_Well_Report Workspace data was successfully deleted
  /Digital-Well-Report:
    get:
      security:
      - Authorization: []
      tags:
      - Digital Well Report
      summary: Get Digital_Well_Report
      responses:
        '200':
          description: get Digital_Well_Report data to be returned
          content:
            application/json:
              example:
                Ba_long_name: LoremIpsum
                Ba_type: LoremIpsum
                Area_id: LoremIpsum
                Area_type: LoremIpsum
                Field_name: LoremIpsum
                Well_name: LoremIpsum
                Uwi: LoremIpsum
                Title: LoremIpsum
                Creator_name: LoremIpsum
                Create_date: LoremIpsum
                Media_type: LoremIpsum
                Document_type: LoremIpsum
                Item_category: LoremIpsum
                Item_sub_category: LoremIpsum
                Digital_format: LoremIpsum
                Data_store_name: LoremIpsum
                Original_file_name: LoremIpsum
                Password: LoremIpsum
                Digital_size: LoremIpsum
                Digital_size_uom: LoremIpsum
                Remark: LoremIpsum
                Source: LoremIpsum
                Qc_status: LoremIpsum
                Checked_by_ba_id: LoremIpsum
    post:
      security:
      - OAuth2PasswordBearer: []
      tags:
      - Digital Well Report
      summary: Post a new Digital_Well_Report
      description: Create a new Digital_Well_Report data
      requestBody:
        required: true
        description: Request body to create Digital_Well_Report data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Digital_Well_Report'
            example: []
      responses:
        '200':
          description: Digital_Well_Report data is added
          content:
            application/json:
              example:
                message: The Digital_Well_Report data was successfully added
  /Digital-Well-Report/{id}:
    parameters:
    - in: path
      name: id
      required: true
      description: id of Digital_Well_Report data to fetch
      schema:
        type: integer
    get:
      security:
      - Authorization: []
      tags:
      - Digital Well Report
      summary: Get Digital_Well_Report
      responses:
        '200':
          description: get Digital_Well_Report data to be returned
          content:
            application/json:
              example:
              - []
    put:
      security:
      - Authorization: []
      tags:
      - Digital Well Report
      summary: Update a new Digital_Well_Report data
      description: Update a new Digital_Well_Report data
      requestBody:
        required: true
        description: Request body to update Digital_Well_Report data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Digital_Well_Report'
            example: []
      responses:
        '200':
          description: Digital_Well_Report data is completely updated
          content:
            application/json:
              example:
                message: The Digital_Well_Report data is completely updated
    patch:
      security:
      - Authorization: []
      tags:
      - Digital Well Report
      summary: Update a new Digital_Well_Report data
      description: Update a new Digital_Well_Report data
      requestBody:
        required: true
        description: Request body to update Digital_Well_Report data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Digital_Well_Report'
            example: []
      responses:
        '200':
          description: one row in Digital_Well_Report data is updated
          content:
            application/json:
              example:
                message: The one row in Digital_Well_Report data is updated
    delete:
      security:
      - Authorization: []
      tags:
      - Digital Well Report
      summary: Delete Digital_Well_Report data
      description: Delete Digital_Well_Report data
      responses:
        '200':
          description: Digital_Well_Report data is deleted
          content:
            application/json:
              example:
                message: The Digital_Well_Report data was successfully deleted
  /Digital-Well-Report/{num}:
    parameters:
    - in: path
      name: num
      required: true
      description: number of dummy data to add
      schema:
        type: integer
    get:
      security:
      - Authorization: []
      tags:
      - Digital Well Report Dummy Data
      summary: Add dummy data to Digital_Well_Report
      responses:
        '200':
          description: add data to Digital_Well_Report
          content:
            application/json: {}
  /token:
    post:
      security:
      - OAuth2PasswordBearer: []
      tags:
      - User Mgmt
      summary: Login For Access Token
      operationId: login_for_access_token_token_post
      requestBody:
        required: true
        description: Request body to create Digital_Well_Report AFE data
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Body_login_for_access_token_token_post'
            example: []
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    afe:
      type: array
      items:
        type: object
        properties:
          afe_number:
            type: integer
          workspace_name:
            type: string
          kkks_name:
            type: string
          working_area:
            type: string
          submission_type:
            type: string
          data_type:
            type: string
    Token:
      title: Token
      required:
      - access_token
      - token_type
      - type
      - name
      - expiry_date
      - affiliation
      type: object
      properties:
        access_token:
          title: Access Token
          type: string
        token_type:
          title: Token Type
          type: string
        type:
          $ref: '#/components/schemas/UserType'
        name:
          title: Name
          type: string
        expiry_date:
          title: Expiry Date
          type: string
        affiliation:
          title: Affiliation
          type: string
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
    UserType:
      title: UserType
      enum:
      - Administrator
      - Regular User
      - Premium User
      type: string
      description: An enumeration.
    ValidationError:
      title: ValidationError
      required:
      - loc
      - msg
      - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            anyOf:
            - type: string
            - type: integer
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
    Body_login_for_access_token_token_post:
      title: Body_login_for_access_token_token_post
      required:
      - username
      - password
      type: object
      properties:
        grant_type:
          title: Grant Type
          pattern: password
          type: string
        username:
          title: Username
          type: string
        password:
          title: Password
          type: string
        scope:
          title: Scope
          type: string
          default: ''
        client_id:
          title: Client Id
          type: string
        client_secret:
          title: Client Secret
          type: string
    Digital_Well_Report_workspace:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
          afe_number:
            type: integer
          Digital_well_report_id:
            type: integer
    Digital_Well_Report:
      type: object
      properties:
        Ba_long_name:
          type: string
        Ba_type:
          type: string
        Area_id:
          type: string
        Area_type:
          type: string
        Field_name:
          type: string
        Well_name:
          type: string
        Uwi:
          type: string
        Title:
          type: string
        Creator_name:
          type: string
        Create_date:
          type: string
        Media_type:
          type: string
        Document_type:
          type: string
        Item_category:
          type: string
        Item_sub_category:
          type: string
        Digital_format:
          type: string
        Data_store_name:
          type: string
        Original_file_name:
          type: string
        Password:
          type: string
        Digital_size:
          type: string
        Digital_size_uom:
          type: string
        Remark:
          type: string
        Source:
          type: string
        Qc_status:
          type: string
        Checked_by_ba_id:
          type: string
  securitySchemes:
    OAuth2PasswordBearer:
      type: oauth2
      flows:
        password:
          scopes: {}
          tokenUrl: v1/token
