openapi: 3.0.0
info:
  description: This is the swagger API for Digital_project_file
  version: 1.0.0
  title: Digital_project_file
  termsOfService: http://swagger.io/terms/
  contact:
    email: darren.mannuela@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
- description: Digital_project_file
  url: http://localhost:8080/api/v1
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/DarrenMannuela/Digital_project_file/1.0.0
tags:
- name: Afe
  description: All endpoints related to get Digital_project_file AFE
- name: Workspace
  description: All endpoints related to Digital_project_file Workspace
- name: Digital_project_file
  description: All endpoints related to Digital_project_file
- name: Digital_project_file Dummy Data
  description: All endpoints related to Digital_project_file
- name: User Mgmt
  description: All endpoints related to tokens
paths:
  /Digital_project_file-afe:
    get:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Get Digital_project_file AFE
      responses:
        '200':
          description: get Digital_project_file AFE data to be returned
          content:
            application/json:
              example:
                afe_number: 1
                workspace_name: LoremIpsum
                kkks_name: LoremIpsum
                working_area: LoremIpsum
                submission_type: Lorem
                data_type: Digital_project_file
                email: john.richardson@gtn.id
    post:
      security:
      - OAuth2PasswordBearer: []
      tags:
      - Afe
      summary: Post a new Digital_project_file AFE
      description: Create a new Digital_project_file AFE data
      requestBody:
        required: true
        description: Request body to create Digital_project_file AFE data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Digital_project_file'
            example:
              afe_number: 1
              workspace_name: LoremIpsum
              kkks_name: LoremIpsum
              working_area: LoremIpsum
              submission_type: Lorem
              data_type: Digital_project_file
              email: john.richardson@gtn.id
      responses:
        '200':
          description: Digital_project_file data is added
          content:
            application/json:
              example:
                message: The Digital_project_file AFE data was successfully added
  /Digital_project_file-afe/{afe}:
    parameters:
    - in: path
      name: afe
      required: true
      description: afe of Digital_project_file data to fetch
      schema:
        type: integer
    get:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Get Digital_project_file AFE
      responses:
        '200':
          description: get Digital_project_file AFE data to be returned
          content:
            application/json:
              example:
                afe_number: 1
                workspace_name: LoremIpsum
                kkks_name: LoremIpsum
                working_area: LoremIpsum
                submission_type: Lorem
                data_type: Digital_project_file
                email: john.richardson@gtn.id
    put:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Update a new Digital_project_file AFE data
      description: Update a new Digital_project_file data
      requestBody:
        required: true
        description: Request body to update Digital_project_file AFE data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Digital_project_file'
            example:
              afe_number: 1
              workspace_name: LoremIpsum
              kkks_name: LoremIpsum
              working_area: LoremIpsum
              submission_type: Lorem
              data_type: Digital_project_file
              email: john.richardson@gtn.id
      responses:
        '200':
          description: Digital_project_file data is completely updated
          content:
            application/json:
              example:
                message: The Digital_project_file AFE data is completely updated
    patch:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Update a new Digital_project_file AFE data
      description: Update a new Digital_project_file data
      requestBody:
        required: true
        description: Request body to update Digital_project_file AFE data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Digital_project_file'
            example:
              afe_number: 1
              workspace_name: LoremIpsum
              kkks_name: LoremIpsum
              working_area: LoremIpsum
              submission_type: Lorem
              data_type: Digital_project_file
              email: john.richardson@gtn.id
      responses:
        '200':
          description: one row in Digital_project_file data is updated
          content:
            application/json:
              example:
                message: The one row in Digital_project_file AFE data is updated
    delete:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Delete Digital_project_file AFE data
      description: Delete Digital_project_file AFE data
      responses:
        '200':
          description: Digital_project_file AFE data is deleted
          content:
            application/json:
              example:
                message: The Digital_project_file AFE data was successfully deleted
  /Digital_project_file-workspace:
    get:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Get Digital_project_file Workspace
      responses:
        '200':
          description: get Digital_project_file Workspace data to be returned
          content:
            application/json:
              example:
                Id: 1
                Afe_number: 1
                Digital_project_file_id: 1
    post:
      security:
      - OAuth2PasswordBearer: []
      tags:
      - Workspace
      summary: Post a new Digital_project_file Workspace
      description: Create a new Digital_project_file Workspace data
      requestBody:
        required: true
        description: Request body to create Digital_project_file Workspace data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Digital_project_file'
            example:
              Id: 1
              Afe_number: 1
              Digital_project_file_id: 1
      responses:
        '200':
          description: Digital_project_file Workspace data is added
          content:
            application/json:
              example:
                message: The Digital_project_file Workspace data was successfully
                  added
  /Digital_project_file-workspace/{afe}}:
    parameters:
    - in: path
      name: afe
      required: true
      description: afe of Digital_project_file data to fetch
      schema:
        type: integer
    get:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Get Digital_project_file Workspace
      responses:
        '200':
          description: get Digital_project_file Workspace data to be returned
          content:
            application/json:
              example:
                Id: 1
                Afe_number: 1
                Digital_project_file_id: 1
  /Digital_project_file-workspace/{id}:
    parameters:
    - in: path
      name: id
      required: true
      description: id of Digital_project_file data to fetch
      schema:
        type: integer
    put:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Update a new Digital_project_file Workspace data
      description: Update a new Digital_project_file Workspace Workspace data
      requestBody:
        required: true
        description: Request body to update Digital_project_file data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Digital_project_file'
            example:
              Id: 1
              Afe_number: 1
              Digital_project_file_id: 1
      responses:
        '200':
          description: Digital_project_file Workspace data is completely updated
          content:
            application/json:
              example:
                message: The Digital_project_file Workspace data is completely updated
    patch:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Update a new Digital_project_file data
      description: Update a new Digital_project_file data
      requestBody:
        required: true
        description: Request body to update Digital_project_file data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Digital_project_file'
            example:
              Id: 1
              Afe_number: 1
              Digital_project_file_id: 1
      responses:
        '200':
          description: one row in Digital_project_file data is updated
          content:
            application/json:
              example:
                message: The one row in Digital_project_file Workspace data is updated
    delete:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Delete Digital_project_file Workspace data
      description: Delete Digital_project_file data
      responses:
        '200':
          description: Digital_project_file Workspace data is deleted
          content:
            application/json:
              example:
                message: The Digital_project_file Workspace data was successfully
                  deleted
  /Digital_project_file:
    get:
      security:
      - Authorization: []
      tags:
      - Digital_project_file
      summary: Get Digital_project_file
      responses:
        '200':
          description: get Digital_project_file data to be returned
          content:
            application/json:
              example:
                Id: 1
                Ba_long_name: LoremIpsum
                Ba_type: LoremIpsum
                Area_id: LoremIpsum
                Area_type: LoremIpsum
                Field_name: LoremIpsum
                Project_name: LoremIpsum
                Sw_application_id: LoremIpsum
                Application_version: LoremIpsum
                Item_category: LoremIpsum
                Process_date: LoremIpsum
                Interpreter_: LoremIpsum
                Digital_format: LoremIpsum
                Media_type: LoremIpsum
                Original_file_name: LoremIpsum
                Password_: LoremIpsum
                Digital_size: 1
                Digital_size_uom: LoremIpsum
                Ba_long_name_2: LoremIpsum
                Ba_type_2: LoremIpsum
                Data_store_name: LoremIpsum
                Remark_: LoremIpsum
                Source_: LoremIpsum
                Qc_status: LoremIpsum
                Checked_by_ba_id: LoremIpsum
    post:
      security:
      - OAuth2PasswordBearer: []
      tags:
      - Digital_project_file
      summary: Post a new Digital_project_file
      description: Create a new Digital_project_file data
      requestBody:
        required: true
        description: Request body to create Digital_project_file data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Digital_project_file'
            example: []
      responses:
        '200':
          description: Digital_project_file data is added
          content:
            application/json:
              example:
                message: The Digital_project_file data was successfully added
  /Digital_project_file/{id}:
    parameters:
    - in: path
      name: id
      required: true
      description: id of Digital_project_file data to fetch
      schema:
        type: integer
    get:
      security:
      - Authorization: []
      tags:
      - Digital_project_file
      summary: Get Digital_project_file
      responses:
        '200':
          description: get Digital_project_file data to be returned
          content:
            application/json:
              example:
              - []
    put:
      security:
      - Authorization: []
      tags:
      - Digital_project_file
      summary: Update a new Digital_project_file data
      description: Update a new Digital_project_file data
      requestBody:
        required: true
        description: Request body to update Digital_project_file data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Digital_project_file'
            example: []
      responses:
        '200':
          description: Digital_project_file data is completely updated
          content:
            application/json:
              example:
                message: The Digital_project_file data is completely updated
    patch:
      security:
      - Authorization: []
      tags:
      - Digital_project_file
      summary: Update a new Digital_project_file data
      description: Update a new Digital_project_file data
      requestBody:
        required: true
        description: Request body to update Digital_project_file data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Digital_project_file'
            example: []
      responses:
        '200':
          description: one row in Digital_project_file data is updated
          content:
            application/json:
              example:
                message: The one row in Digital_project_file data is updated
    delete:
      security:
      - Authorization: []
      tags:
      - Digital_project_file
      summary: Delete Digital_project_file data
      description: Delete Digital_project_file data
      responses:
        '200':
          description: Digital_project_file data is deleted
          content:
            application/json:
              example:
                message: The Digital_project_file data was successfully deleted
  /Digital_project_file/{num}:
    parameters:
    - in: path
      name: num
      required: true
      description: number of dummy data to add
      schema:
        type: integer
    get:
      security:
      - Authorization: []
      tags:
      - Digital_project_file Dummy Data
      summary: Add dummy data to Digital_project_file
      responses:
        '200':
          description: add data to Digital_project_file
          content:
            application/json: {}
  /token:
    post:
      security:
      - OAuth2PasswordBearer: []
      tags:
      - User Mgmt
      summary: Login For Access Token
      operationId: login_for_access_token_token_post
      requestBody:
        required: true
        description: Request body to create Digital_project_file AFE data
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Body_login_for_access_token_token_post'
            example: []
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    afe:
      type: array
      items:
        type: object
        properties:
          afe_number:
            type: integer
          workspace_name:
            type: string
          kkks_name:
            type: string
          working_area:
            type: string
          submission_type:
            type: string
          data_type:
            type: string
    Token:
      title: Token
      required:
      - access_token
      - token_type
      - type
      - name
      - expiry_date
      - affiliation
      type: object
      properties:
        access_token:
          title: Access Token
          type: string
        token_type:
          title: Token Type
          type: string
        type:
          $ref: '#/components/schemas/UserType'
        name:
          title: Name
          type: string
        expiry_date:
          title: Expiry Date
          type: string
        affiliation:
          title: Affiliation
          type: string
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
    UserType:
      title: UserType
      enum:
      - Administrator
      - Regular User
      - Premium User
      type: string
      description: An enumeration.
    ValidationError:
      title: ValidationError
      required:
      - loc
      - msg
      - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            anyOf:
            - type: string
            - type: integer
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
    Body_login_for_access_token_token_post:
      title: Body_login_for_access_token_token_post
      required:
      - username
      - password
      type: object
      properties:
        grant_type:
          title: Grant Type
          pattern: password
          type: string
        username:
          title: Username
          type: string
        password:
          title: Password
          type: string
        scope:
          title: Scope
          type: string
          default: ''
        client_id:
          title: Client Id
          type: string
        client_secret:
          title: Client Secret
          type: string
    Digital_project_file_workspace:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
          afe_number:
            type: integer
          Digital_project_file_id:
            type: integer
    Digital_project_file:
      type: object
      properties:
        Id:
          type: integer
        Ba_long_name:
          type: string
        Ba_type:
          type: string
        Area_id:
          type: string
        Area_type:
          type: string
        Field_name:
          type: string
        Project_name:
          type: string
        Sw_application_id:
          type: string
        Application_version:
          type: string
        Item_category:
          type: string
        Process_date:
          type: string
        Interpreter_:
          type: string
        Digital_format:
          type: string
        Media_type:
          type: string
        Original_file_name:
          type: string
        Password_:
          type: string
        Digital_size:
          type: integer
        Digital_size_uom:
          type: string
        Ba_long_name_2:
          type: string
        Ba_type_2:
          type: string
        Data_store_name:
          type: string
        Remark_:
          type: string
        Source_:
          type: string
        Qc_status:
          type: string
        Checked_by_ba_id:
          type: string
  securitySchemes:
    OAuth2PasswordBearer:
      type: oauth2
      flows:
        password:
          scopes: {}
          tokenUrl: v1/token
