openapi: 3.0.0
info:
  description: This is the swagger API for Outcrop_sample
  version: 1.0.0
  title: Outcrop_sample
  termsOfService: http://swagger.io/terms/
  contact:
    email: darren.mannuela@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
- description: Outcrop_sample
  url: http://localhost:8080/api/v1
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/DarrenMannuela/Outcrop_sample/1.0.0
tags:
- name: Afe
  description: All endpoints related to get Outcrop_sample AFE
- name: Workspace
  description: All endpoints related to Outcrop_sample Workspace
- name: Outcrop_sample
  description: All endpoints related to Outcrop_sample
- name: Outcrop_sample Dummy Data
  description: All endpoints related to Outcrop_sample
- name: User Mgmt
  description: All endpoints related to tokens
paths:
  /Outcrop_sample-afe:
    get:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Get Outcrop_sample AFE
      responses:
        '200':
          description: get Outcrop_sample AFE data to be returned
          content:
            application/json:
              example:
                afe_number: 1
                workspace_name: LoremIpsum
                kkks_name: LoremIpsum
                working_area: LoremIpsum
                submission_type: Lorem
                data_type: Outcrop_sample
                email: john.richardson@gtn.id
    post:
      security:
      - OAuth2PasswordBearer: []
      tags:
      - Afe
      summary: Post a new Outcrop_sample AFE
      description: Create a new Outcrop_sample AFE data
      requestBody:
        required: true
        description: Request body to create Outcrop_sample AFE data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Outcrop_sample'
            example:
              afe_number: 1
              workspace_name: LoremIpsum
              kkks_name: LoremIpsum
              working_area: LoremIpsum
              submission_type: Lorem
              data_type: Outcrop_sample
              email: john.richardson@gtn.id
      responses:
        '200':
          description: Outcrop_sample data is added
          content:
            application/json:
              example:
                message: The Outcrop_sample AFE data was successfully added
  /Outcrop_sample-afe/{afe}:
    parameters:
    - in: path
      name: afe
      required: true
      description: afe of Outcrop_sample data to fetch
      schema:
        type: integer
    get:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Get Outcrop_sample AFE
      responses:
        '200':
          description: get Outcrop_sample AFE data to be returned
          content:
            application/json:
              example:
                afe_number: 1
                workspace_name: LoremIpsum
                kkks_name: LoremIpsum
                working_area: LoremIpsum
                submission_type: Lorem
                data_type: Outcrop_sample
                email: john.richardson@gtn.id
    put:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Update a new Outcrop_sample AFE data
      description: Update a new Outcrop_sample data
      requestBody:
        required: true
        description: Request body to update Outcrop_sample AFE data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Outcrop_sample'
            example:
              afe_number: 1
              workspace_name: LoremIpsum
              kkks_name: LoremIpsum
              working_area: LoremIpsum
              submission_type: Lorem
              data_type: Outcrop_sample
              email: john.richardson@gtn.id
      responses:
        '200':
          description: Outcrop_sample data is completely updated
          content:
            application/json:
              example:
                message: The Outcrop_sample AFE data is completely updated
    patch:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Update a new Outcrop_sample AFE data
      description: Update a new Outcrop_sample data
      requestBody:
        required: true
        description: Request body to update Outcrop_sample AFE data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Outcrop_sample'
            example:
              afe_number: 1
              workspace_name: LoremIpsum
              kkks_name: LoremIpsum
              working_area: LoremIpsum
              submission_type: Lorem
              data_type: Outcrop_sample
              email: john.richardson@gtn.id
      responses:
        '200':
          description: one row in Outcrop_sample data is updated
          content:
            application/json:
              example:
                message: The one row in Outcrop_sample AFE data is updated
    delete:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Delete Outcrop_sample AFE data
      description: Delete Outcrop_sample AFE data
      responses:
        '200':
          description: Outcrop_sample AFE data is deleted
          content:
            application/json:
              example:
                message: The Outcrop_sample AFE data was successfully deleted
  /Outcrop_sample-workspace:
    get:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Get Outcrop_sample Workspace
      responses:
        '200':
          description: get Outcrop_sample Workspace data to be returned
          content:
            application/json:
              example:
                Id: 1
                Afe_number: 1
                Outcrop_sample_id: 1
    post:
      security:
      - OAuth2PasswordBearer: []
      tags:
      - Workspace
      summary: Post a new Outcrop_sample Workspace
      description: Create a new Outcrop_sample Workspace data
      requestBody:
        required: true
        description: Request body to create Outcrop_sample Workspace data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Outcrop_sample'
            example:
              Id: 1
              Afe_number: 1
              Outcrop_sample_id: 1
      responses:
        '200':
          description: Outcrop_sample Workspace data is added
          content:
            application/json:
              example:
                message: The Outcrop_sample Workspace data was successfully added
  /Outcrop_sample-workspace/{afe}}:
    parameters:
    - in: path
      name: afe
      required: true
      description: afe of Outcrop_sample data to fetch
      schema:
        type: integer
    get:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Get Outcrop_sample Workspace
      responses:
        '200':
          description: get Outcrop_sample Workspace data to be returned
          content:
            application/json:
              example:
                Id: 1
                Afe_number: 1
                Outcrop_sample_id: 1
  /Outcrop_sample-workspace/{id}:
    parameters:
    - in: path
      name: id
      required: true
      description: id of Outcrop_sample data to fetch
      schema:
        type: integer
    put:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Update a new Outcrop_sample Workspace data
      description: Update a new Outcrop_sample Workspace Workspace data
      requestBody:
        required: true
        description: Request body to update Outcrop_sample data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Outcrop_sample'
            example:
              Id: 1
              Afe_number: 1
              Outcrop_sample_id: 1
      responses:
        '200':
          description: Outcrop_sample Workspace data is completely updated
          content:
            application/json:
              example:
                message: The Outcrop_sample Workspace data is completely updated
    patch:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Update a new Outcrop_sample data
      description: Update a new Outcrop_sample data
      requestBody:
        required: true
        description: Request body to update Outcrop_sample data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Outcrop_sample'
            example:
              Id: 1
              Afe_number: 1
              Outcrop_sample_id: 1
      responses:
        '200':
          description: one row in Outcrop_sample data is updated
          content:
            application/json:
              example:
                message: The one row in Outcrop_sample Workspace data is updated
    delete:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Delete Outcrop_sample Workspace data
      description: Delete Outcrop_sample data
      responses:
        '200':
          description: Outcrop_sample Workspace data is deleted
          content:
            application/json:
              example:
                message: The Outcrop_sample Workspace data was successfully deleted
  /Outcrop_sample:
    get:
      security:
      - Authorization: []
      tags:
      - Outcrop_sample
      summary: Get Outcrop_sample
      responses:
        '200':
          description: get Outcrop_sample data to be returned
          content:
            application/json:
              example:
                Id: 1
                Ba_long_name: LoremIpsum
                Ba_type: LoremIpsum
                Area_id: LoremIpsum
                Area_type: LoremIpsum
                Project_name: LoremIpsum
                Field_station_id: LoremIpsum
                Longitude_: LoremIpsum
                Latitude_: LoremIpsum
                Easting_: LoremIpsum
                Easting_ouom: LoremIpsum
                Northing_: LoremIpsum
                Northing_ouom: LoremIpsum
                Utm_quadrant: LoremIpsum
                Geodetic_datum_name: LoremIpsum
                Sample_num: LoremIpsum
                Sample_count: 1
                Study_type: LoremIpsum
                Collected_date: LoremIpsum
                Pick_location: LoremIpsum
                Ba_long_name_2: LoremIpsum
                Ba_type_2: LoremIpsum
                Data_store_name: LoremIpsum
                Data_store_type: LoremIpsum
                Location_id: LoremIpsum
                Remark_: LoremIpsum
                Source_: LoremIpsum
                Qc_status: LoremIpsum
                Checked_by_ba_id: LoremIpsum
    post:
      security:
      - OAuth2PasswordBearer: []
      tags:
      - Outcrop_sample
      summary: Post a new Outcrop_sample
      description: Create a new Outcrop_sample data
      requestBody:
        required: true
        description: Request body to create Outcrop_sample data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Outcrop_sample'
            example: []
      responses:
        '200':
          description: Outcrop_sample data is added
          content:
            application/json:
              example:
                message: The Outcrop_sample data was successfully added
  /Outcrop_sample/{id}:
    parameters:
    - in: path
      name: id
      required: true
      description: id of Outcrop_sample data to fetch
      schema:
        type: integer
    get:
      security:
      - Authorization: []
      tags:
      - Outcrop_sample
      summary: Get Outcrop_sample
      responses:
        '200':
          description: get Outcrop_sample data to be returned
          content:
            application/json:
              example:
              - []
    put:
      security:
      - Authorization: []
      tags:
      - Outcrop_sample
      summary: Update a new Outcrop_sample data
      description: Update a new Outcrop_sample data
      requestBody:
        required: true
        description: Request body to update Outcrop_sample data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Outcrop_sample'
            example: []
      responses:
        '200':
          description: Outcrop_sample data is completely updated
          content:
            application/json:
              example:
                message: The Outcrop_sample data is completely updated
    patch:
      security:
      - Authorization: []
      tags:
      - Outcrop_sample
      summary: Update a new Outcrop_sample data
      description: Update a new Outcrop_sample data
      requestBody:
        required: true
        description: Request body to update Outcrop_sample data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Outcrop_sample'
            example: []
      responses:
        '200':
          description: one row in Outcrop_sample data is updated
          content:
            application/json:
              example:
                message: The one row in Outcrop_sample data is updated
    delete:
      security:
      - Authorization: []
      tags:
      - Outcrop_sample
      summary: Delete Outcrop_sample data
      description: Delete Outcrop_sample data
      responses:
        '200':
          description: Outcrop_sample data is deleted
          content:
            application/json:
              example:
                message: The Outcrop_sample data was successfully deleted
  /Outcrop_sample/{num}:
    parameters:
    - in: path
      name: num
      required: true
      description: number of dummy data to add
      schema:
        type: integer
    get:
      security:
      - Authorization: []
      tags:
      - Outcrop_sample Dummy Data
      summary: Add dummy data to Outcrop_sample
      responses:
        '200':
          description: add data to Outcrop_sample
          content:
            application/json: {}
  /token:
    post:
      security:
      - OAuth2PasswordBearer: []
      tags:
      - User Mgmt
      summary: Login For Access Token
      operationId: login_for_access_token_token_post
      requestBody:
        required: true
        description: Request body to create Outcrop_sample AFE data
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Body_login_for_access_token_token_post'
            example: []
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    afe:
      type: array
      items:
        type: object
        properties:
          afe_number:
            type: integer
          workspace_name:
            type: string
          kkks_name:
            type: string
          working_area:
            type: string
          submission_type:
            type: string
          data_type:
            type: string
    Token:
      title: Token
      required:
      - access_token
      - token_type
      - type
      - name
      - expiry_date
      - affiliation
      type: object
      properties:
        access_token:
          title: Access Token
          type: string
        token_type:
          title: Token Type
          type: string
        type:
          $ref: '#/components/schemas/UserType'
        name:
          title: Name
          type: string
        expiry_date:
          title: Expiry Date
          type: string
        affiliation:
          title: Affiliation
          type: string
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
    UserType:
      title: UserType
      enum:
      - Administrator
      - Regular User
      - Premium User
      type: string
      description: An enumeration.
    ValidationError:
      title: ValidationError
      required:
      - loc
      - msg
      - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            anyOf:
            - type: string
            - type: integer
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
    Body_login_for_access_token_token_post:
      title: Body_login_for_access_token_token_post
      required:
      - username
      - password
      type: object
      properties:
        grant_type:
          title: Grant Type
          pattern: password
          type: string
        username:
          title: Username
          type: string
        password:
          title: Password
          type: string
        scope:
          title: Scope
          type: string
          default: ''
        client_id:
          title: Client Id
          type: string
        client_secret:
          title: Client Secret
          type: string
    Outcrop_sample_workspace:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
          afe_number:
            type: integer
          Outcrop_sample_id:
            type: integer
    Outcrop_sample:
      type: object
      properties:
        Id:
          type: integer
        Ba_long_name:
          type: string
        Ba_type:
          type: string
        Area_id:
          type: string
        Area_type:
          type: string
        Project_name:
          type: string
        Field_station_id:
          type: string
        Longitude_:
          type: string
        Latitude_:
          type: string
        Easting_:
          type: string
        Easting_ouom:
          type: string
        Northing_:
          type: string
        Northing_ouom:
          type: string
        Utm_quadrant:
          type: string
        Geodetic_datum_name:
          type: string
        Sample_num:
          type: string
        Sample_count:
          type: integer
        Study_type:
          type: string
        Collected_date:
          type: string
        Pick_location:
          type: string
        Ba_long_name_2:
          type: string
        Ba_type_2:
          type: string
        Data_store_name:
          type: string
        Data_store_type:
          type: string
        Location_id:
          type: string
        Remark_:
          type: string
        Source_:
          type: string
        Qc_status:
          type: string
        Checked_by_ba_id:
          type: string
  securitySchemes:
    OAuth2PasswordBearer:
      type: oauth2
      flows:
        password:
          scopes: {}
          tokenUrl: v1/token
