openapi: 3.0.0
info:
  description: This is the swagger API for Project_File_Stored_In_Media
  version: 1.0.0
  title: Project_File_Stored_In_Media
  termsOfService: http://swagger.io/terms/
  contact:
    email: darren.mannuela@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
- description: Project_File_Stored_In_Media
  url: http://localhost:8080/api/v1
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/DarrenMannuela/Project_File_Stored_In_Media/1.0.0
tags:
- name: Afe
  description: All endpoints related to get Project_File_Stored_In_Media AFE
- name: Workspace
  description: All endpoints related to Project_File_Stored_In_Media Workspace
- name: Project File Stored In Media
  description: All endpoints related to Project_File_Stored_In_Media
- name: Project File Stored In Media Dummy Data
  description: All endpoints related to Project_File_Stored_In_Media
paths:
  /Project-File-Stored-In-Media-afe:
    get:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Get Project_File_Stored_In_Media AFE
      responses:
        '200':
          description: get Project_File_Stored_In_Media AFE data to be returned
          content:
            application/json:
              example:
                afe_number: 1
                workspace_name: LoremIpsum
                kkks_name: LoremIpsum
                working_area: LoremIpsum
                submission_type: Lorem
                data_type: Project File Stored In Media
    post:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Post a new Project_File_Stored_In_Media AFE
      description: Create a new Project_File_Stored_In_Media AFE data
      requestBody:
        required: true
        description: Request body to create Project_File_Stored_In_Media AFE data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Project_File_Stored_In_Media'
            example:
              afe_number: 1
              workspace_name: LoremIpsum
              kkks_name: LoremIpsum
              working_area: LoremIpsum
              submission_type: Lorem
              data_type: Project File Stored In Media
      responses:
        '200':
          description: Project_File_Stored_In_Media data is added
          content:
            application/json:
              example:
                message: The Project_File_Stored_In_Media AFE data was successfully
                  added
  /Project-File-Stored-In-Media-afe/{afe}:
    parameters:
    - in: path
      name: afe
      required: true
      description: afe of Project_File_Stored_In_Media data to fetch
      schema:
        type: interger
    get:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Get Project_File_Stored_In_Media AFE
      responses:
        '200':
          description: get Project_File_Stored_In_Media AFE data to be returned
          content:
            application/json:
              example:
                afe_number: 1
                workspace_name: LoremIpsum
                kkks_name: LoremIpsum
                working_area: LoremIpsum
                submission_type: Lorem
                data_type: Project File Stored In Media
    put:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Update a new Project_File_Stored_In_Media AFE data
      description: Update a new Project_File_Stored_In_Media data
      requestBody:
        required: true
        description: Request body to update Project_File_Stored_In_Media AFE data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Project_File_Stored_In_Media'
            example:
              afe_number: 1
              workspace_name: LoremIpsum
              kkks_name: LoremIpsum
              working_area: LoremIpsum
              submission_type: Lorem
              data_type: Project File Stored In Media
      responses:
        '200':
          description: Project_File_Stored_In_Media data is completely updated
          content:
            application/json:
              example:
                message: The Project_File_Stored_In_Media AFE data is completely updated
    patch:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Update a new Project_File_Stored_In_Media AFE data
      description: Update a new Project_File_Stored_In_Media data
      requestBody:
        required: true
        description: Request body to update Project_File_Stored_In_Media AFE data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Project_File_Stored_In_Media'
            example:
              afe_number: 1
              workspace_name: LoremIpsum
              kkks_name: LoremIpsum
              working_area: LoremIpsum
              submission_type: Lorem
              data_type: Project File Stored In Media
      responses:
        '200':
          description: one row in Project_File_Stored_In_Media data is updated
          content:
            application/json:
              example:
                message: The one row in Project_File_Stored_In_Media AFE data is updated
    delete:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Delete Project_File_Stored_In_Media AFE data
      description: Delete Project_File_Stored_In_Media AFE data
      responses:
        '200':
          description: Project_File_Stored_In_Media AFE data is deleted
          content:
            application/json:
              example:
                message: The Project_File_Stored_In_Media AFE data was successfully
                  deleted
  /Project-File-Stored-In-Media-workspace:
    get:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Get Project_File_Stored_In_Media Workspace
      responses:
        '200':
          description: get Project_File_Stored_In_Media Workspace data to be returned
          content:
            application/json:
              example:
                Id: 1
                Afe_number: 1
                Pfsim_id: 1
    post:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Post a new Project_File_Stored_In_Media Workspace
      description: Create a new Project_File_Stored_In_Media Workspace data
      requestBody:
        required: true
        description: Request body to create Project_File_Stored_In_Media Workspace
          data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Project_File_Stored_In_Media'
            example:
              Id: 1
              Afe_number: 1
              Pfsim_id: 1
      responses:
        '200':
          description: Project_File_Stored_In_Media Workspace data is added
          content:
            application/json:
              example:
                message: The Project_File_Stored_In_Media Workspace data was successfully
                  added
  /Project-File-Stored-In-Media-workspace/{afe}}:
    parameters:
    - in: path
      name: afe
      required: true
      description: afe of Project_File_Stored_In_Media data to fetch
      schema:
        type: interger
    get:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Get Project_File_Stored_In_Media Workspace
      responses:
        '200':
          description: get Project_File_Stored_In_Media Workspace data to be returned
          content:
            application/json:
              example:
                Id: 1
                Afe_number: 1
                Pfsim_id: 1
  /Project-File-Stored-In-Media-workspace/{id}:
    parameters:
    - in: path
      name: id
      required: true
      description: id of Project_File_Stored_In_Media data to fetch
      schema:
        type: interger
    put:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Update a new Project_File_Stored_In_Media Workspace data
      description: Update a new Project_File_Stored_In_Media Workspace Workspace data
      requestBody:
        required: true
        description: Request body to update Project_File_Stored_In_Media data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Project_File_Stored_In_Media'
            example:
              Id: 1
              Afe_number: 1
              Pfsim_id: 1
      responses:
        '200':
          description: Project_File_Stored_In_Media Workspace data is completely updated
          content:
            application/json:
              example:
                message: The Project_File_Stored_In_Media Workspace data is completely
                  updated
    patch:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Update a new Project_File_Stored_In_Media data
      description: Update a new Project_File_Stored_In_Media data
      requestBody:
        required: true
        description: Request body to update Project_File_Stored_In_Media data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Project_File_Stored_In_Media'
            example:
              Id: 1
              Afe_number: 1
              Pfsim_id: 1
      responses:
        '200':
          description: one row in Project_File_Stored_In_Media data is updated
          content:
            application/json:
              example:
                message: The one row in Project_File_Stored_In_Media Workspace data
                  is updated
    delete:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Delete Project_File_Stored_In_Media Workspace data
      description: Delete Project_File_Stored_In_Media data
      responses:
        '200':
          description: Project_File_Stored_In_Media Workspace data is deleted
          content:
            application/json:
              example:
                message: The Project_File_Stored_In_Media Workspace data was successfully
                  deleted
  /Project-File-Stored-In-Media:
    get:
      security:
      - Authorization: []
      tags:
      - Project File Stored In Media
      summary: Get Project_File_Stored_In_Media
      responses:
        '200':
          description: get Project_File_Stored_In_Media data to be returned
          content:
            application/json:
              example:
                Ba_long_name: LoremIpsum
                Ba_type: LoremIpsum
                Area_id: LoremIpsum
                Area_type: LoremIpsum
                Field_name: LoremIpsum
                Project_name: LoremIpsum
                Sw_application_id: LoremIpsum
                Application_version: LoremIpsum
                Item_category: LoremIpsum
                Process_date: LoremIpsum
                Interpreter: LoremIpsum
                Digital_format: LoremIpsum
                Media_type: LoremIpsum
                Data_store_name: LoremIpsum
                Data_store_type: LoremIpsum
                Location_id: LoremIpsum
                Remark: LoremIpsum
                Source: LoremIpsum
                Qc_status: LoremIpsum
                Checked_by_ba_id: LoremIpsum
    post:
      security:
      - Authorization: []
      tags:
      - Project File Stored In Media
      summary: Post a new Project_File_Stored_In_Media
      description: Create a new Project_File_Stored_In_Media data
      requestBody:
        required: true
        description: Request body to create Project_File_Stored_In_Media data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Project_File_Stored_In_Media'
            example: []
      responses:
        '200':
          description: Project_File_Stored_In_Media data is added
          content:
            application/json:
              example:
                message: The Project_File_Stored_In_Media data was successfully added
  /Project-File-Stored-In-Media/{id}:
    parameters:
    - in: path
      name: id
      required: true
      description: id of Project_File_Stored_In_Media data to fetch
      schema:
        type: interger
    get:
      security:
      - Authorization: []
      tags:
      - Project File Stored In Media
      summary: Get Project_File_Stored_In_Media
      responses:
        '200':
          description: get Project_File_Stored_In_Media data to be returned
          content:
            application/json:
              example:
              - []
    put:
      security:
      - Authorization: []
      tags:
      - Project File Stored In Media
      summary: Update a new Project_File_Stored_In_Media data
      description: Update a new Project_File_Stored_In_Media data
      requestBody:
        required: true
        description: Request body to update Project_File_Stored_In_Media data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Project_File_Stored_In_Media'
            example: []
      responses:
        '200':
          description: Project_File_Stored_In_Media data is completely updated
          content:
            application/json:
              example:
                message: The Project_File_Stored_In_Media data is completely updated
    patch:
      security:
      - Authorization: []
      tags:
      - Project File Stored In Media
      summary: Update a new Project_File_Stored_In_Media data
      description: Update a new Project_File_Stored_In_Media data
      requestBody:
        required: true
        description: Request body to update Project_File_Stored_In_Media data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Project_File_Stored_In_Media'
            example: []
      responses:
        '200':
          description: one row in Project_File_Stored_In_Media data is updated
          content:
            application/json:
              example:
                message: The one row in Project_File_Stored_In_Media data is updated
    delete:
      security:
      - Authorization: []
      tags:
      - Project File Stored In Media
      summary: Delete Project_File_Stored_In_Media data
      description: Delete Project_File_Stored_In_Media data
      responses:
        '200':
          description: Project_File_Stored_In_Media data is deleted
          content:
            application/json:
              example:
                message: The Project_File_Stored_In_Media data was successfully deleted
components:
  schemas:
    afe:
      type: array
      items:
        type: object
        properties:
          afe_number:
            type: integer
          workspace_name:
            type: string
          kkks_name:
            type: string
          working_area:
            type: string
          submission_type:
            type: string
          data_type:
            type: string
    Project_File_Stored_In_Media_workspace:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
          afe_number:
            type: integer
          Pfsim_id:
            type: integer
    Project_File_Stored_In_Media:
      type: object
      properties:
        Ba_long_name:
          type: string
        Ba_type:
          type: string
        Area_id:
          type: string
        Area_type:
          type: string
        Field_name:
          type: string
        Project_name:
          type: string
        Sw_application_id:
          type: string
        Application_version:
          type: string
        Item_category:
          type: string
        Process_date:
          type: string
        Interpreter:
          type: string
        Digital_format:
          type: string
        Media_type:
          type: string
        Data_store_name:
          type: string
        Data_store_type:
          type: string
        Location_id:
          type: string
        Remark:
          type: string
        Source:
          type: string
        Qc_status:
          type: string
        Checked_by_ba_id:
          type: string
  securitySchemes:
    Authorization:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Please enter the access token
