openapi: 3.0.0
info:
  description: This is the swagger API for Seismic_Interpretation_Data
  version: 1.0.0
  title: Seismic_Interpretation_Data
  termsOfService: http://swagger.io/terms/
  contact:
    email: darren.mannuela@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
- description: Seismic_Interpretation_Data
  url: http://localhost:8080/api/v1
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/DarrenMannuela/Seismic_Interpretation_Data/1.0.0
tags:
- name: Afe
  description: All endpoints related to get Seismic_Interpretation_Data AFE
- name: Workspace
  description: All endpoints related to Seismic_Interpretation_Data Workspace
- name: Seismic Interpretation Data
  description: All endpoints related to Seismic_Interpretation_Data
- name: Seismic Interpretation Data Dummy Data
  description: All endpoints related to Seismic_Interpretation_Data
paths:
  /Seismic-Interpretation-Data-afe:
    get:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Get Seismic_Interpretation_Data AFE
      responses:
        '200':
          description: get Seismic_Interpretation_Data AFE data to be returned
          content:
            application/json:
              example:
                afe_number: 1
                workspace_name: LoremIpsum
                kkks_name: LoremIpsum
                working_area: LoremIpsum
                submission_type: Lorem
                data_type: Seismic Interpretation Data
    post:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Post a new Seismic_Interpretation_Data AFE
      description: Create a new Seismic_Interpretation_Data AFE data
      requestBody:
        required: true
        description: Request body to create Seismic_Interpretation_Data AFE data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Seismic_Interpretation_Data'
            example:
              afe_number: 1
              workspace_name: LoremIpsum
              kkks_name: LoremIpsum
              working_area: LoremIpsum
              submission_type: Lorem
              data_type: Seismic Interpretation Data
      responses:
        '200':
          description: Seismic_Interpretation_Data data is added
          content:
            application/json:
              example:
                message: The Seismic_Interpretation_Data AFE data was successfully
                  added
  /Seismic-Interpretation-Data-afe/{afe}:
    parameters:
    - in: path
      name: afe
      required: true
      description: afe of Seismic_Interpretation_Data data to fetch
      schema:
        type: interger
    get:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Get Seismic_Interpretation_Data AFE
      responses:
        '200':
          description: get Seismic_Interpretation_Data AFE data to be returned
          content:
            application/json:
              example:
                afe_number: 1
                workspace_name: LoremIpsum
                kkks_name: LoremIpsum
                working_area: LoremIpsum
                submission_type: Lorem
                data_type: Seismic Interpretation Data
    put:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Update a new Seismic_Interpretation_Data AFE data
      description: Update a new Seismic_Interpretation_Data data
      requestBody:
        required: true
        description: Request body to update Seismic_Interpretation_Data AFE data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Seismic_Interpretation_Data'
            example:
              afe_number: 1
              workspace_name: LoremIpsum
              kkks_name: LoremIpsum
              working_area: LoremIpsum
              submission_type: Lorem
              data_type: Seismic Interpretation Data
      responses:
        '200':
          description: Seismic_Interpretation_Data data is completely updated
          content:
            application/json:
              example:
                message: The Seismic_Interpretation_Data AFE data is completely updated
    patch:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Update a new Seismic_Interpretation_Data AFE data
      description: Update a new Seismic_Interpretation_Data data
      requestBody:
        required: true
        description: Request body to update Seismic_Interpretation_Data AFE data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Seismic_Interpretation_Data'
            example:
              afe_number: 1
              workspace_name: LoremIpsum
              kkks_name: LoremIpsum
              working_area: LoremIpsum
              submission_type: Lorem
              data_type: Seismic Interpretation Data
      responses:
        '200':
          description: one row in Seismic_Interpretation_Data data is updated
          content:
            application/json:
              example:
                message: The one row in Seismic_Interpretation_Data AFE data is updated
    delete:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Delete Seismic_Interpretation_Data AFE data
      description: Delete Seismic_Interpretation_Data AFE data
      responses:
        '200':
          description: Seismic_Interpretation_Data AFE data is deleted
          content:
            application/json:
              example:
                message: The Seismic_Interpretation_Data AFE data was successfully
                  deleted
  /Seismic-Interpretation-Data-workspace:
    get:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Get Seismic_Interpretation_Data Workspace
      responses:
        '200':
          description: get Seismic_Interpretation_Data Workspace data to be returned
          content:
            application/json:
              example:
                Id: 1
                Afe_number: 1
                Sid_id: 1
    post:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Post a new Seismic_Interpretation_Data Workspace
      description: Create a new Seismic_Interpretation_Data Workspace data
      requestBody:
        required: true
        description: Request body to create Seismic_Interpretation_Data Workspace
          data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Seismic_Interpretation_Data'
            example:
              Id: 1
              Afe_number: 1
              Sid_id: 1
      responses:
        '200':
          description: Seismic_Interpretation_Data Workspace data is added
          content:
            application/json:
              example:
                message: The Seismic_Interpretation_Data Workspace data was successfully
                  added
  /Seismic-Interpretation-Data-workspace/{afe}}:
    parameters:
    - in: path
      name: afe
      required: true
      description: afe of Seismic_Interpretation_Data data to fetch
      schema:
        type: interger
    get:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Get Seismic_Interpretation_Data Workspace
      responses:
        '200':
          description: get Seismic_Interpretation_Data Workspace data to be returned
          content:
            application/json:
              example:
                Id: 1
                Afe_number: 1
                Sid_id: 1
  /Seismic-Interpretation-Data-workspace/{id}:
    parameters:
    - in: path
      name: id
      required: true
      description: id of Seismic_Interpretation_Data data to fetch
      schema:
        type: interger
    put:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Update a new Seismic_Interpretation_Data Workspace data
      description: Update a new Seismic_Interpretation_Data Workspace Workspace data
      requestBody:
        required: true
        description: Request body to update Seismic_Interpretation_Data data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Seismic_Interpretation_Data'
            example:
              Id: 1
              Afe_number: 1
              Sid_id: 1
      responses:
        '200':
          description: Seismic_Interpretation_Data Workspace data is completely updated
          content:
            application/json:
              example:
                message: The Seismic_Interpretation_Data Workspace data is completely
                  updated
    patch:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Update a new Seismic_Interpretation_Data data
      description: Update a new Seismic_Interpretation_Data data
      requestBody:
        required: true
        description: Request body to update Seismic_Interpretation_Data data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Seismic_Interpretation_Data'
            example:
              Id: 1
              Afe_number: 1
              Sid_id: 1
      responses:
        '200':
          description: one row in Seismic_Interpretation_Data data is updated
          content:
            application/json:
              example:
                message: The one row in Seismic_Interpretation_Data Workspace data
                  is updated
    delete:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Delete Seismic_Interpretation_Data Workspace data
      description: Delete Seismic_Interpretation_Data data
      responses:
        '200':
          description: Seismic_Interpretation_Data Workspace data is deleted
          content:
            application/json:
              example:
                message: The Seismic_Interpretation_Data Workspace data was successfully
                  deleted
  /Seismic-Interpretation-Data:
    get:
      security:
      - Authorization: []
      tags:
      - Seismic Interpretation Data
      summary: Get Seismic_Interpretation_Data
      responses:
        '200':
          description: get Seismic_Interpretation_Data data to be returned
          content:
            application/json:
              example:
                Ba_long_name: LoremIpsum
                Ba_type: LoremIpsum
                Area_id: LoremIpsum
                Area_type: LoremIpsum
                Field_name: LoremIpsum
                Project_name: LoremIpsum
                Interpreter: LoremIpsum
                Interp_date: LoremIpsum
                Interp_objective: LoremIpsum
                Interp_type: LoremIpsum
                Pick_method: LoremIpsum
                Sw_application_id: LoremIpsum
                Application_version: LoremIpsum
                Trace_position: LoremIpsum
                Media_type: LoremIpsum
                Tape_number: LoremIpsum
                Digital_format: LoremIpsum
                Remark: LoremIpsum
                Data_store_name: LoremIpsum
                Original_file_name: LoremIpsum
                Password: LoremIpsum
                Digital_size: LoremIpsum
                Digital_size_uom: LoremIpsum
                Source: LoremIpsum
                Qc_status: LoremIpsum
                Checked_by_ba_id: LoremIpsum
    post:
      security:
      - Authorization: []
      tags:
      - Seismic Interpretation Data
      summary: Post a new Seismic_Interpretation_Data
      description: Create a new Seismic_Interpretation_Data data
      requestBody:
        required: true
        description: Request body to create Seismic_Interpretation_Data data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Seismic_Interpretation_Data'
            example: []
      responses:
        '200':
          description: Seismic_Interpretation_Data data is added
          content:
            application/json:
              example:
                message: The Seismic_Interpretation_Data data was successfully added
  /Seismic-Interpretation-Data/{id}:
    parameters:
    - in: path
      name: id
      required: true
      description: id of Seismic_Interpretation_Data data to fetch
      schema:
        type: interger
    get:
      security:
      - Authorization: []
      tags:
      - Seismic Interpretation Data
      summary: Get Seismic_Interpretation_Data
      responses:
        '200':
          description: get Seismic_Interpretation_Data data to be returned
          content:
            application/json:
              example:
              - []
    put:
      security:
      - Authorization: []
      tags:
      - Seismic Interpretation Data
      summary: Update a new Seismic_Interpretation_Data data
      description: Update a new Seismic_Interpretation_Data data
      requestBody:
        required: true
        description: Request body to update Seismic_Interpretation_Data data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Seismic_Interpretation_Data'
            example: []
      responses:
        '200':
          description: Seismic_Interpretation_Data data is completely updated
          content:
            application/json:
              example:
                message: The Seismic_Interpretation_Data data is completely updated
    patch:
      security:
      - Authorization: []
      tags:
      - Seismic Interpretation Data
      summary: Update a new Seismic_Interpretation_Data data
      description: Update a new Seismic_Interpretation_Data data
      requestBody:
        required: true
        description: Request body to update Seismic_Interpretation_Data data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Seismic_Interpretation_Data'
            example: []
      responses:
        '200':
          description: one row in Seismic_Interpretation_Data data is updated
          content:
            application/json:
              example:
                message: The one row in Seismic_Interpretation_Data data is updated
    delete:
      security:
      - Authorization: []
      tags:
      - Seismic Interpretation Data
      summary: Delete Seismic_Interpretation_Data data
      description: Delete Seismic_Interpretation_Data data
      responses:
        '200':
          description: Seismic_Interpretation_Data data is deleted
          content:
            application/json:
              example:
                message: The Seismic_Interpretation_Data data was successfully deleted
components:
  schemas:
    afe:
      type: array
      items:
        type: object
        properties:
          afe_number:
            type: integer
          workspace_name:
            type: string
          kkks_name:
            type: string
          working_area:
            type: string
          submission_type:
            type: string
          data_type:
            type: string
    Seismic_Interpretation_Data_workspace:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
          afe_number:
            type: integer
          Sid_id:
            type: integer
    Seismic_Interpretation_Data:
      type: object
      properties:
        Ba_long_name:
          type: string
        Ba_type:
          type: string
        Area_id:
          type: string
        Area_type:
          type: string
        Field_name:
          type: string
        Project_name:
          type: string
        Interpreter:
          type: string
        Interp_date:
          type: string
        Interp_objective:
          type: string
        Interp_type:
          type: string
        Pick_method:
          type: string
        Sw_application_id:
          type: string
        Application_version:
          type: string
        Trace_position:
          type: string
        Media_type:
          type: string
        Tape_number:
          type: string
        Digital_format:
          type: string
        Remark:
          type: string
        Data_store_name:
          type: string
        Original_file_name:
          type: string
        Password:
          type: string
        Digital_size:
          type: string
        Digital_size_uom:
          type: string
        Source:
          type: string
        Qc_status:
          type: string
        Checked_by_ba_id:
          type: string
  securitySchemes:
    Authorization:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Please enter the access token
