openapi: 3.0.0
info:
  description: This is the swagger API for Three_D_Seismic_Navigation_Data_Stored_In_Media
  version: 1.0.0
  title: Three_D_Seismic_Navigation_Data_Stored_In_Media
  termsOfService: http://swagger.io/terms/
  contact:
    email: darren.mannuela@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
- description: Three_D_Seismic_Navigation_Data_Stored_In_Media
  url: http://localhost:8080/api/v1
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/DarrenMannuela/Three_D_Seismic_Navigation_Data_Stored_In_Media/1.0.0
tags:
- name: Afe
  description: All endpoints related to get Three_D_Seismic_Navigation_Data_Stored_In_Media
    AFE
- name: Workspace
  description: All endpoints related to Three_D_Seismic_Navigation_Data_Stored_In_Media
    Workspace
- name: Three D Seismic Navigation Data Stored In Media
  description: All endpoints related to Three_D_Seismic_Navigation_Data_Stored_In_Media
- name: Three D Seismic Navigation Data Stored In Media Dummy Data
  description: All endpoints related to Three_D_Seismic_Navigation_Data_Stored_In_Media
paths:
  /Three-D-Seismic-Navigation-Data-Stored-In-Media-afe:
    get:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Get Three_D_Seismic_Navigation_Data_Stored_In_Media AFE
      responses:
        '200':
          description: get Three_D_Seismic_Navigation_Data_Stored_In_Media AFE data
            to be returned
          content:
            application/json:
              example:
                afe_number: 1
                workspace_name: LoremIpsum
                kkks_name: LoremIpsum
                working_area: LoremIpsum
                submission_type: Lorem
                data_type: Three D Seismic Navigation Data Stored In Media
              user_id: 1
    post:
      security:
      - OAuth2PasswordBearer: []
      tags:
      - Afe
      summary: Post a new Three_D_Seismic_Navigation_Data_Stored_In_Media AFE
      description: Create a new Three_D_Seismic_Navigation_Data_Stored_In_Media AFE
        data
      requestBody:
        required: true
        description: Request body to create Three_D_Seismic_Navigation_Data_Stored_In_Media
          AFE data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Three_D_Seismic_Navigation_Data_Stored_In_Media'
            example:
              afe_number: 1
              workspace_name: LoremIpsum
              kkks_name: LoremIpsum
              working_area: LoremIpsum
              submission_type: Lorem
              data_type: Three D Seismic Navigation Data Stored In Media
            user_id: 1
      responses:
        '200':
          description: Three_D_Seismic_Navigation_Data_Stored_In_Media data is added
          content:
            application/json:
              example:
                message: The Three_D_Seismic_Navigation_Data_Stored_In_Media AFE data
                  was successfully added
  /Three-D-Seismic-Navigation-Data-Stored-In-Media-afe/{afe}:
    parameters:
    - in: path
      name: afe
      required: true
      description: afe of Three_D_Seismic_Navigation_Data_Stored_In_Media data to
        fetch
      schema:
        type: interger
    get:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Get Three_D_Seismic_Navigation_Data_Stored_In_Media AFE
      responses:
        '200':
          description: get Three_D_Seismic_Navigation_Data_Stored_In_Media AFE data
            to be returned
          content:
            application/json:
              example:
                afe_number: 1
                workspace_name: LoremIpsum
                kkks_name: LoremIpsum
                working_area: LoremIpsum
                submission_type: Lorem
                data_type: Three D Seismic Navigation Data Stored In Media
              user_id: 1
    put:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Update a new Three_D_Seismic_Navigation_Data_Stored_In_Media AFE data
      description: Update a new Three_D_Seismic_Navigation_Data_Stored_In_Media data
      requestBody:
        required: true
        description: Request body to update Three_D_Seismic_Navigation_Data_Stored_In_Media
          AFE data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Three_D_Seismic_Navigation_Data_Stored_In_Media'
            example:
              afe_number: 1
              workspace_name: LoremIpsum
              kkks_name: LoremIpsum
              working_area: LoremIpsum
              submission_type: Lorem
              data_type: Three D Seismic Navigation Data Stored In Media
            user_id: 1
      responses:
        '200':
          description: Three_D_Seismic_Navigation_Data_Stored_In_Media data is completely
            updated
          content:
            application/json:
              example:
                message: The Three_D_Seismic_Navigation_Data_Stored_In_Media AFE data
                  is completely updated
    patch:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Update a new Three_D_Seismic_Navigation_Data_Stored_In_Media AFE data
      description: Update a new Three_D_Seismic_Navigation_Data_Stored_In_Media data
      requestBody:
        required: true
        description: Request body to update Three_D_Seismic_Navigation_Data_Stored_In_Media
          AFE data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Three_D_Seismic_Navigation_Data_Stored_In_Media'
            example:
              afe_number: 1
              workspace_name: LoremIpsum
              kkks_name: LoremIpsum
              working_area: LoremIpsum
              submission_type: Lorem
              data_type: Three D Seismic Navigation Data Stored In Media
            user_id: 1
      responses:
        '200':
          description: one row in Three_D_Seismic_Navigation_Data_Stored_In_Media
            data is updated
          content:
            application/json:
              example:
                message: The one row in Three_D_Seismic_Navigation_Data_Stored_In_Media
                  AFE data is updated
    delete:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Delete Three_D_Seismic_Navigation_Data_Stored_In_Media AFE data
      description: Delete Three_D_Seismic_Navigation_Data_Stored_In_Media AFE data
      responses:
        '200':
          description: Three_D_Seismic_Navigation_Data_Stored_In_Media AFE data is
            deleted
          content:
            application/json:
              example:
                message: The Three_D_Seismic_Navigation_Data_Stored_In_Media AFE data
                  was successfully deleted
  /Three-D-Seismic-Navigation-Data-Stored-In-Media-workspace:
    get:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Get Three_D_Seismic_Navigation_Data_Stored_In_Media Workspace
      responses:
        '200':
          description: get Three_D_Seismic_Navigation_Data_Stored_In_Media Workspace
            data to be returned
          content:
            application/json:
              example:
                Id: 1
                Afe_number: 1
                Three_d_seismic_navigation_data_stored_in_media_id: 1
    post:
      security:
      - OAuth2PasswordBearer: []
      tags:
      - Workspace
      summary: Post a new Three_D_Seismic_Navigation_Data_Stored_In_Media Workspace
      description: Create a new Three_D_Seismic_Navigation_Data_Stored_In_Media Workspace
        data
      requestBody:
        required: true
        description: Request body to create Three_D_Seismic_Navigation_Data_Stored_In_Media
          Workspace data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Three_D_Seismic_Navigation_Data_Stored_In_Media'
            example:
              Id: 1
              Afe_number: 1
              Three_d_seismic_navigation_data_stored_in_media_id: 1
      responses:
        '200':
          description: Three_D_Seismic_Navigation_Data_Stored_In_Media Workspace data
            is added
          content:
            application/json:
              example:
                message: The Three_D_Seismic_Navigation_Data_Stored_In_Media Workspace
                  data was successfully added
  /Three-D-Seismic-Navigation-Data-Stored-In-Media-workspace/{afe}}:
    parameters:
    - in: path
      name: afe
      required: true
      description: afe of Three_D_Seismic_Navigation_Data_Stored_In_Media data to
        fetch
      schema:
        type: interger
    get:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Get Three_D_Seismic_Navigation_Data_Stored_In_Media Workspace
      responses:
        '200':
          description: get Three_D_Seismic_Navigation_Data_Stored_In_Media Workspace
            data to be returned
          content:
            application/json:
              example:
                Id: 1
                Afe_number: 1
                Three_d_seismic_navigation_data_stored_in_media_id: 1
  /Three-D-Seismic-Navigation-Data-Stored-In-Media-workspace/{id}:
    parameters:
    - in: path
      name: id
      required: true
      description: id of Three_D_Seismic_Navigation_Data_Stored_In_Media data to fetch
      schema:
        type: interger
    put:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Update a new Three_D_Seismic_Navigation_Data_Stored_In_Media Workspace
        data
      description: Update a new Three_D_Seismic_Navigation_Data_Stored_In_Media Workspace
        Workspace data
      requestBody:
        required: true
        description: Request body to update Three_D_Seismic_Navigation_Data_Stored_In_Media
          data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Three_D_Seismic_Navigation_Data_Stored_In_Media'
            example:
              Id: 1
              Afe_number: 1
              Three_d_seismic_navigation_data_stored_in_media_id: 1
      responses:
        '200':
          description: Three_D_Seismic_Navigation_Data_Stored_In_Media Workspace data
            is completely updated
          content:
            application/json:
              example:
                message: The Three_D_Seismic_Navigation_Data_Stored_In_Media Workspace
                  data is completely updated
    patch:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Update a new Three_D_Seismic_Navigation_Data_Stored_In_Media data
      description: Update a new Three_D_Seismic_Navigation_Data_Stored_In_Media data
      requestBody:
        required: true
        description: Request body to update Three_D_Seismic_Navigation_Data_Stored_In_Media
          data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Three_D_Seismic_Navigation_Data_Stored_In_Media'
            example:
              Id: 1
              Afe_number: 1
              Three_d_seismic_navigation_data_stored_in_media_id: 1
      responses:
        '200':
          description: one row in Three_D_Seismic_Navigation_Data_Stored_In_Media
            data is updated
          content:
            application/json:
              example:
                message: The one row in Three_D_Seismic_Navigation_Data_Stored_In_Media
                  Workspace data is updated
    delete:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Delete Three_D_Seismic_Navigation_Data_Stored_In_Media Workspace data
      description: Delete Three_D_Seismic_Navigation_Data_Stored_In_Media data
      responses:
        '200':
          description: Three_D_Seismic_Navigation_Data_Stored_In_Media Workspace data
            is deleted
          content:
            application/json:
              example:
                message: The Three_D_Seismic_Navigation_Data_Stored_In_Media Workspace
                  data was successfully deleted
  /Three-D-Seismic-Navigation-Data-Stored-In-Media:
    get:
      security:
      - Authorization: []
      tags:
      - Three D Seismic Navigation Data Stored In Media
      summary: Get Three_D_Seismic_Navigation_Data_Stored_In_Media
      responses:
        '200':
          description: get Three_D_Seismic_Navigation_Data_Stored_In_Media data to
            be returned
          content:
            application/json:
              example:
                Ba_long_name: LoremIpsum
                Ba_type: LoremIpsum
                Area_id: LoremIpsum
                Area_type: LoremIpsum
                Acqtn_survey_name: LoremIpsum
                Seis_dimension: LoremIpsum
                Shot_by: LoremIpsum
                Process_date: LoremIpsum
                Digital_format: LoremIpsum
                Media_type: LoremIpsum
                Tape_number: LoremIpsum
                Data_store_name: LoremIpsum
                Data_store_type: LoremIpsum
                Location_id: LoremIpsum
                Remark: LoremIpsum
                Source: LoremIpsum
                Qc_status: LoremIpsum
                Checked_by_ba_id: LoremIpsum
    post:
      security:
      - OAuth2PasswordBearer: []
      tags:
      - Three D Seismic Navigation Data Stored In Media
      summary: Post a new Three_D_Seismic_Navigation_Data_Stored_In_Media
      description: Create a new Three_D_Seismic_Navigation_Data_Stored_In_Media data
      requestBody:
        required: true
        description: Request body to create Three_D_Seismic_Navigation_Data_Stored_In_Media
          data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Three_D_Seismic_Navigation_Data_Stored_In_Media'
            example: []
      responses:
        '200':
          description: Three_D_Seismic_Navigation_Data_Stored_In_Media data is added
          content:
            application/json:
              example:
                message: The Three_D_Seismic_Navigation_Data_Stored_In_Media data
                  was successfully added
  /Three-D-Seismic-Navigation-Data-Stored-In-Media/{id}:
    parameters:
    - in: path
      name: id
      required: true
      description: id of Three_D_Seismic_Navigation_Data_Stored_In_Media data to fetch
      schema:
        type: interger
    get:
      security:
      - Authorization: []
      tags:
      - Three D Seismic Navigation Data Stored In Media
      summary: Get Three_D_Seismic_Navigation_Data_Stored_In_Media
      responses:
        '200':
          description: get Three_D_Seismic_Navigation_Data_Stored_In_Media data to
            be returned
          content:
            application/json:
              example:
              - []
    put:
      security:
      - Authorization: []
      tags:
      - Three D Seismic Navigation Data Stored In Media
      summary: Update a new Three_D_Seismic_Navigation_Data_Stored_In_Media data
      description: Update a new Three_D_Seismic_Navigation_Data_Stored_In_Media data
      requestBody:
        required: true
        description: Request body to update Three_D_Seismic_Navigation_Data_Stored_In_Media
          data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Three_D_Seismic_Navigation_Data_Stored_In_Media'
            example: []
      responses:
        '200':
          description: Three_D_Seismic_Navigation_Data_Stored_In_Media data is completely
            updated
          content:
            application/json:
              example:
                message: The Three_D_Seismic_Navigation_Data_Stored_In_Media data
                  is completely updated
    patch:
      security:
      - Authorization: []
      tags:
      - Three D Seismic Navigation Data Stored In Media
      summary: Update a new Three_D_Seismic_Navigation_Data_Stored_In_Media data
      description: Update a new Three_D_Seismic_Navigation_Data_Stored_In_Media data
      requestBody:
        required: true
        description: Request body to update Three_D_Seismic_Navigation_Data_Stored_In_Media
          data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Three_D_Seismic_Navigation_Data_Stored_In_Media'
            example: []
      responses:
        '200':
          description: one row in Three_D_Seismic_Navigation_Data_Stored_In_Media
            data is updated
          content:
            application/json:
              example:
                message: The one row in Three_D_Seismic_Navigation_Data_Stored_In_Media
                  data is updated
    delete:
      security:
      - Authorization: []
      tags:
      - Three D Seismic Navigation Data Stored In Media
      summary: Delete Three_D_Seismic_Navigation_Data_Stored_In_Media data
      description: Delete Three_D_Seismic_Navigation_Data_Stored_In_Media data
      responses:
        '200':
          description: Three_D_Seismic_Navigation_Data_Stored_In_Media data is deleted
          content:
            application/json:
              example:
                message: The Three_D_Seismic_Navigation_Data_Stored_In_Media data
                  was successfully deleted
  /Three-D-Seismic-Navigation-Data-Stored-In-Media/{num}:
    parameters:
    - in: path
      name: num
      required: true
      description: number of dummy data to add
      schema:
        type: interger
    get:
      security:
      - Authorization: []
      tags:
      - Three D Seismic Navigation Data Stored In Media Dummy Data
      summary: Add dummy data to Three_D_Seismic_Navigation_Data_Stored_In_Media
      responses:
        '200':
          description: add data to Three_D_Seismic_Navigation_Data_Stored_In_Media
          content:
            application/json: {}
components:
  schemas:
    afe:
      type: array
      items:
        type: object
        properties:
          afe_number:
            type: integer
          workspace_name:
            type: string
          kkks_name:
            type: string
          working_area:
            type: string
          submission_type:
            type: string
          data_type:
            type: string
    Three_D_Seismic_Navigation_Data_Stored_In_Media_workspace:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
          afe_number:
            type: integer
          Three_d_seismic_navigation_data_stored_in_media_id:
            type: integer
    Three_D_Seismic_Navigation_Data_Stored_In_Media:
      type: object
      properties:
        Ba_long_name:
          type: string
        Ba_type:
          type: string
        Area_id:
          type: string
        Area_type:
          type: string
        Acqtn_survey_name:
          type: string
        Seis_dimension:
          type: string
        Shot_by:
          type: string
        Process_date:
          type: string
        Digital_format:
          type: string
        Media_type:
          type: string
        Tape_number:
          type: string
        Data_store_name:
          type: string
        Data_store_type:
          type: string
        Location_id:
          type: string
        Remark:
          type: string
        Source:
          type: string
        Qc_status:
          type: string
        Checked_by_ba_id:
          type: string
  securitySchemes:
    OAuth2PasswordBearer:
      type: oauth2
      flows:
        password:
          scopes: {}
          tokenUrl: v1/token
