openapi: 3.0.0
info:
  description: This is the swagger API for Two_D_Seismic_Summary
  version: 1.0.0
  title: Two_D_Seismic_Summary
  termsOfService: http://swagger.io/terms/
  contact:
    email: darren.mannuela@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
- description: Two_D_Seismic_Summary
  url: http://localhost:8080/api/v1
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/DarrenMannuela/Two_D_Seismic_Summary/1.0.0
tags:
- name: Afe
  description: All endpoints related to get Two_D_Seismic_Summary AFE
- name: Workspace
  description: All endpoints related to Two_D_Seismic_Summary Workspace
- name: Two D Seismic Summary
  description: All endpoints related to Two_D_Seismic_Summary
- name: Two D Seismic Summary Dummy Data
  description: All endpoints related to Two_D_Seismic_Summary
paths:
  /Two-D-Seismic-Summary-afe:
    get:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Get Two_D_Seismic_Summary AFE
      responses:
        '200':
          description: get Two_D_Seismic_Summary AFE data to be returned
          content:
            application/json:
              example:
                afe_number: 1
                workspace_name: LoremIpsum
                kkks_name: LoremIpsum
                working_area: LoremIpsum
                submission_type: Lorem
                data_type: Two D Seismic Summary
    post:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Post a new Two_D_Seismic_Summary AFE
      description: Create a new Two_D_Seismic_Summary AFE data
      requestBody:
        required: true
        description: Request body to create Two_D_Seismic_Summary AFE data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Two_D_Seismic_Summary'
            example:
              afe_number: 1
              workspace_name: LoremIpsum
              kkks_name: LoremIpsum
              working_area: LoremIpsum
              submission_type: Lorem
              data_type: Two D Seismic Summary
      responses:
        '200':
          description: Two_D_Seismic_Summary data is added
          content:
            application/json:
              example:
                message: The Two_D_Seismic_Summary AFE data was successfully added
  /Two-D-Seismic-Summary-afe/{afe}:
    parameters:
    - in: path
      name: afe
      required: true
      description: afe of Two_D_Seismic_Summary data to fetch
      schema:
        type: interger
    get:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Get Two_D_Seismic_Summary AFE
      responses:
        '200':
          description: get Two_D_Seismic_Summary AFE data to be returned
          content:
            application/json:
              example:
                afe_number: 1
                workspace_name: LoremIpsum
                kkks_name: LoremIpsum
                working_area: LoremIpsum
                submission_type: Lorem
                data_type: Two D Seismic Summary
    put:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Update a new Two_D_Seismic_Summary AFE data
      description: Update a new Two_D_Seismic_Summary data
      requestBody:
        required: true
        description: Request body to update Two_D_Seismic_Summary AFE data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Two_D_Seismic_Summary'
            example:
              afe_number: 1
              workspace_name: LoremIpsum
              kkks_name: LoremIpsum
              working_area: LoremIpsum
              submission_type: Lorem
              data_type: Two D Seismic Summary
      responses:
        '200':
          description: Two_D_Seismic_Summary data is completely updated
          content:
            application/json:
              example:
                message: The Two_D_Seismic_Summary AFE data is completely updated
    patch:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Update a new Two_D_Seismic_Summary AFE data
      description: Update a new Two_D_Seismic_Summary data
      requestBody:
        required: true
        description: Request body to update Two_D_Seismic_Summary AFE data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Two_D_Seismic_Summary'
            example:
              afe_number: 1
              workspace_name: LoremIpsum
              kkks_name: LoremIpsum
              working_area: LoremIpsum
              submission_type: Lorem
              data_type: Two D Seismic Summary
      responses:
        '200':
          description: one row in Two_D_Seismic_Summary data is updated
          content:
            application/json:
              example:
                message: The one row in Two_D_Seismic_Summary AFE data is updated
    delete:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Delete Two_D_Seismic_Summary AFE data
      description: Delete Two_D_Seismic_Summary AFE data
      responses:
        '200':
          description: Two_D_Seismic_Summary AFE data is deleted
          content:
            application/json:
              example:
                message: The Two_D_Seismic_Summary AFE data was successfully deleted
  /Two-D-Seismic-Summary-workspace:
    get:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Get Two_D_Seismic_Summary Workspace
      responses:
        '200':
          description: get Two_D_Seismic_Summary Workspace data to be returned
          content:
            application/json:
              example:
                Id: 1
                Afe_number: 1
                Tdss_id: 1
    post:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Post a new Two_D_Seismic_Summary Workspace
      description: Create a new Two_D_Seismic_Summary Workspace data
      requestBody:
        required: true
        description: Request body to create Two_D_Seismic_Summary Workspace data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Two_D_Seismic_Summary'
            example:
              Id: 1
              Afe_number: 1
              Tdss_id: 1
      responses:
        '200':
          description: Two_D_Seismic_Summary Workspace data is added
          content:
            application/json:
              example:
                message: The Two_D_Seismic_Summary Workspace data was successfully
                  added
  /Two-D-Seismic-Summary-workspace/{afe}}:
    parameters:
    - in: path
      name: afe
      required: true
      description: afe of Two_D_Seismic_Summary data to fetch
      schema:
        type: interger
    get:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Get Two_D_Seismic_Summary Workspace
      responses:
        '200':
          description: get Two_D_Seismic_Summary Workspace data to be returned
          content:
            application/json:
              example:
                Id: 1
                Afe_number: 1
                Tdss_id: 1
  /Two-D-Seismic-Summary-workspace/{id}:
    parameters:
    - in: path
      name: id
      required: true
      description: id of Two_D_Seismic_Summary data to fetch
      schema:
        type: interger
    put:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Update a new Two_D_Seismic_Summary Workspace data
      description: Update a new Two_D_Seismic_Summary Workspace Workspace data
      requestBody:
        required: true
        description: Request body to update Two_D_Seismic_Summary data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Two_D_Seismic_Summary'
            example:
              Id: 1
              Afe_number: 1
              Tdss_id: 1
      responses:
        '200':
          description: Two_D_Seismic_Summary Workspace data is completely updated
          content:
            application/json:
              example:
                message: The Two_D_Seismic_Summary Workspace data is completely updated
    patch:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Update a new Two_D_Seismic_Summary data
      description: Update a new Two_D_Seismic_Summary data
      requestBody:
        required: true
        description: Request body to update Two_D_Seismic_Summary data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Two_D_Seismic_Summary'
            example:
              Id: 1
              Afe_number: 1
              Tdss_id: 1
      responses:
        '200':
          description: one row in Two_D_Seismic_Summary data is updated
          content:
            application/json:
              example:
                message: The one row in Two_D_Seismic_Summary Workspace data is updated
    delete:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Delete Two_D_Seismic_Summary Workspace data
      description: Delete Two_D_Seismic_Summary data
      responses:
        '200':
          description: Two_D_Seismic_Summary Workspace data is deleted
          content:
            application/json:
              example:
                message: The Two_D_Seismic_Summary Workspace data was successfully
                  deleted
  /Two-D-Seismic-Summary:
    get:
      security:
      - Authorization: []
      tags:
      - Two D Seismic Summary
      summary: Get Two_D_Seismic_Summary
      responses:
        '200':
          description: get Two_D_Seismic_Summary data to be returned
          content:
            application/json:
              example:
                Ba_long_name: LoremIpsum
                Ba_type: LoremIpsum
                Area_id: LoremIpsum
                Area_type: LoremIpsum
                Acqtn_survey_name: LoremIpsum
                Seis_dimension: LoremIpsum
                Start_date: LoremIpsum
                Shot_by: LoremIpsum
                Crew_long_name: LoremIpsum
                Acqtn_shotpt_interval: LoremIpsum
                Acqtn_shotpt_interval_ouom: LoremIpsum
                Rcvr_spacing: LoremIpsum
                Rcvr_spacing_ouom: LoremIpsum
                Energy_type: LoremIpsum
                Fold_coverage: LoremIpsum
                Rcrd_channel_count: LoremIpsum
                Rcrd_rec_length: LoremIpsum
                Rcrd_rec_length_ouom: LoremIpsum
                Rcrd_sample_rate: LoremIpsum
                Rcrd_sample_rate_ouom: LoremIpsum
                Line_name: LoremIpsum
                First_seis_point_id: LoremIpsum
                Last_seis_point_id: LoremIpsum
                Acqtn_direction: LoremIpsum
                Line_length: LoremIpsum
                Line_length_ouom: LoremIpsum
                Alias_long_name: LoremIpsum
                Environment: LoremIpsum
                Remark: LoremIpsum
                Source: LoremIpsum
                Qc_status: LoremIpsum
                Checked_by_ba_id: LoremIpsum
    post:
      security:
      - Authorization: []
      tags:
      - Two D Seismic Summary
      summary: Post a new Two_D_Seismic_Summary
      description: Create a new Two_D_Seismic_Summary data
      requestBody:
        required: true
        description: Request body to create Two_D_Seismic_Summary data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Two_D_Seismic_Summary'
            example: []
      responses:
        '200':
          description: Two_D_Seismic_Summary data is added
          content:
            application/json:
              example:
                message: The Two_D_Seismic_Summary data was successfully added
  /Two-D-Seismic-Summary/{id}:
    parameters:
    - in: path
      name: id
      required: true
      description: id of Two_D_Seismic_Summary data to fetch
      schema:
        type: interger
    get:
      security:
      - Authorization: []
      tags:
      - Two D Seismic Summary
      summary: Get Two_D_Seismic_Summary
      responses:
        '200':
          description: get Two_D_Seismic_Summary data to be returned
          content:
            application/json:
              example:
              - []
    put:
      security:
      - Authorization: []
      tags:
      - Two D Seismic Summary
      summary: Update a new Two_D_Seismic_Summary data
      description: Update a new Two_D_Seismic_Summary data
      requestBody:
        required: true
        description: Request body to update Two_D_Seismic_Summary data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Two_D_Seismic_Summary'
            example: []
      responses:
        '200':
          description: Two_D_Seismic_Summary data is completely updated
          content:
            application/json:
              example:
                message: The Two_D_Seismic_Summary data is completely updated
    patch:
      security:
      - Authorization: []
      tags:
      - Two D Seismic Summary
      summary: Update a new Two_D_Seismic_Summary data
      description: Update a new Two_D_Seismic_Summary data
      requestBody:
        required: true
        description: Request body to update Two_D_Seismic_Summary data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Two_D_Seismic_Summary'
            example: []
      responses:
        '200':
          description: one row in Two_D_Seismic_Summary data is updated
          content:
            application/json:
              example:
                message: The one row in Two_D_Seismic_Summary data is updated
    delete:
      security:
      - Authorization: []
      tags:
      - Two D Seismic Summary
      summary: Delete Two_D_Seismic_Summary data
      description: Delete Two_D_Seismic_Summary data
      responses:
        '200':
          description: Two_D_Seismic_Summary data is deleted
          content:
            application/json:
              example:
                message: The Two_D_Seismic_Summary data was successfully deleted
  /Two-D-Seismic-Summary/{num}:
    parameters:
    - in: path
      name: num
      required: true
      description: number of dummy data to add
      schema:
        type: interger
    get:
      security:
      - Authorization: []
      tags:
      - Two D Seismic Summary Dummy Data
      summary: Add dummy data to Two_D_Seismic_Summary
      responses:
        '200':
          description: add data to Two_D_Seismic_Summary
          content:
            application/json: {}
components:
  schemas:
    afe:
      type: array
      items:
        type: object
        properties:
          afe_number:
            type: integer
          workspace_name:
            type: string
          kkks_name:
            type: string
          working_area:
            type: string
          submission_type:
            type: string
          data_type:
            type: string
    Two_D_Seismic_Summary_workspace:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
          afe_number:
            type: integer
          Tdss_id:
            type: integer
    Two_D_Seismic_Summary:
      type: object
      properties:
        Ba_long_name:
          type: string
        Ba_type:
          type: string
        Area_id:
          type: string
        Area_type:
          type: string
        Acqtn_survey_name:
          type: string
        Seis_dimension:
          type: string
        Start_date:
          type: string
        Shot_by:
          type: string
        Crew_long_name:
          type: string
        Acqtn_shotpt_interval:
          type: string
        Acqtn_shotpt_interval_ouom:
          type: string
        Rcvr_spacing:
          type: string
        Rcvr_spacing_ouom:
          type: string
        Energy_type:
          type: string
        Fold_coverage:
          type: string
        Rcrd_channel_count:
          type: string
        Rcrd_rec_length:
          type: string
        Rcrd_rec_length_ouom:
          type: string
        Rcrd_sample_rate:
          type: string
        Rcrd_sample_rate_ouom:
          type: string
        Line_name:
          type: string
        First_seis_point_id:
          type: string
        Last_seis_point_id:
          type: string
        Acqtn_direction:
          type: string
        Line_length:
          type: string
        Line_length_ouom:
          type: string
        Alias_long_name:
          type: string
        Environment:
          type: string
        Remark:
          type: string
        Source:
          type: string
        Qc_status:
          type: string
        Checked_by_ba_id:
          type: string
  securitySchemes:
    Authorization:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Please enter the access token
