openapi: 3.0.0
info:
  description: This is the swagger API for Two_D_Or_Three_D_Seismic_Report
  version: 1.0.0
  title: Two_D_Or_Three_D_Seismic_Report
  termsOfService: http://swagger.io/terms/
  contact:
    email: darren.mannuela@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
- description: Two_D_Or_Three_D_Seismic_Report
  url: http://localhost:8080/api/v1
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/DarrenMannuela/Two_D_Or_Three_D_Seismic_Report/1.0.0
tags:
- name: Afe
  description: All endpoints related to get Two_D_Or_Three_D_Seismic_Report AFE
- name: Workspace
  description: All endpoints related to Two_D_Or_Three_D_Seismic_Report Workspace
- name: Two D Or Three D Seismic Report
  description: All endpoints related to Two_D_Or_Three_D_Seismic_Report
- name: Two D Or Three D Seismic Report Dummy Data
  description: All endpoints related to Two_D_Or_Three_D_Seismic_Report
paths:
  /Two-D-Or-Three-D-Seismic-Report-afe:
    get:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Get Two_D_Or_Three_D_Seismic_Report AFE
      responses:
        '200':
          description: get Two_D_Or_Three_D_Seismic_Report AFE data to be returned
          content:
            application/json:
              example:
                afe_number: 1
                workspace_name: LoremIpsum
                kkks_name: LoremIpsum
                working_area: LoremIpsum
                submission_type: Lorem
                data_type: Two D Or Three D Seismic Report
    post:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Post a new Two_D_Or_Three_D_Seismic_Report AFE
      description: Create a new Two_D_Or_Three_D_Seismic_Report AFE data
      requestBody:
        required: true
        description: Request body to create Two_D_Or_Three_D_Seismic_Report AFE data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Two_D_Or_Three_D_Seismic_Report'
            example:
              afe_number: 1
              workspace_name: LoremIpsum
              kkks_name: LoremIpsum
              working_area: LoremIpsum
              submission_type: Lorem
              data_type: Two D Or Three D Seismic Report
      responses:
        '200':
          description: Two_D_Or_Three_D_Seismic_Report data is added
          content:
            application/json:
              example:
                message: The Two_D_Or_Three_D_Seismic_Report AFE data was successfully
                  added
  /Two-D-Or-Three-D-Seismic-Report-afe/{afe}:
    parameters:
    - in: path
      name: afe
      required: true
      description: afe of Two_D_Or_Three_D_Seismic_Report data to fetch
      schema:
        type: interger
    get:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Get Two_D_Or_Three_D_Seismic_Report AFE
      responses:
        '200':
          description: get Two_D_Or_Three_D_Seismic_Report AFE data to be returned
          content:
            application/json:
              example:
                afe_number: 1
                workspace_name: LoremIpsum
                kkks_name: LoremIpsum
                working_area: LoremIpsum
                submission_type: Lorem
                data_type: Two D Or Three D Seismic Report
    put:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Update a new Two_D_Or_Three_D_Seismic_Report AFE data
      description: Update a new Two_D_Or_Three_D_Seismic_Report data
      requestBody:
        required: true
        description: Request body to update Two_D_Or_Three_D_Seismic_Report AFE data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Two_D_Or_Three_D_Seismic_Report'
            example:
              afe_number: 1
              workspace_name: LoremIpsum
              kkks_name: LoremIpsum
              working_area: LoremIpsum
              submission_type: Lorem
              data_type: Two D Or Three D Seismic Report
      responses:
        '200':
          description: Two_D_Or_Three_D_Seismic_Report data is completely updated
          content:
            application/json:
              example:
                message: The Two_D_Or_Three_D_Seismic_Report AFE data is completely
                  updated
    patch:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Update a new Two_D_Or_Three_D_Seismic_Report AFE data
      description: Update a new Two_D_Or_Three_D_Seismic_Report data
      requestBody:
        required: true
        description: Request body to update Two_D_Or_Three_D_Seismic_Report AFE data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Two_D_Or_Three_D_Seismic_Report'
            example:
              afe_number: 1
              workspace_name: LoremIpsum
              kkks_name: LoremIpsum
              working_area: LoremIpsum
              submission_type: Lorem
              data_type: Two D Or Three D Seismic Report
      responses:
        '200':
          description: one row in Two_D_Or_Three_D_Seismic_Report data is updated
          content:
            application/json:
              example:
                message: The one row in Two_D_Or_Three_D_Seismic_Report AFE data is
                  updated
    delete:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Delete Two_D_Or_Three_D_Seismic_Report AFE data
      description: Delete Two_D_Or_Three_D_Seismic_Report AFE data
      responses:
        '200':
          description: Two_D_Or_Three_D_Seismic_Report AFE data is deleted
          content:
            application/json:
              example:
                message: The Two_D_Or_Three_D_Seismic_Report AFE data was successfully
                  deleted
  /Two-D-Or-Three-D-Seismic-Report-workspace:
    get:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Get Two_D_Or_Three_D_Seismic_Report Workspace
      responses:
        '200':
          description: get Two_D_Or_Three_D_Seismic_Report Workspace data to be returned
          content:
            application/json:
              example:
                Id: 1
                Afe_number: 1
                Tdotdsr_id: 1
    post:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Post a new Two_D_Or_Three_D_Seismic_Report Workspace
      description: Create a new Two_D_Or_Three_D_Seismic_Report Workspace data
      requestBody:
        required: true
        description: Request body to create Two_D_Or_Three_D_Seismic_Report Workspace
          data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Two_D_Or_Three_D_Seismic_Report'
            example:
              Id: 1
              Afe_number: 1
              Tdotdsr_id: 1
      responses:
        '200':
          description: Two_D_Or_Three_D_Seismic_Report Workspace data is added
          content:
            application/json:
              example:
                message: The Two_D_Or_Three_D_Seismic_Report Workspace data was successfully
                  added
  /Two-D-Or-Three-D-Seismic-Report-workspace/{afe}}:
    parameters:
    - in: path
      name: afe
      required: true
      description: afe of Two_D_Or_Three_D_Seismic_Report data to fetch
      schema:
        type: interger
    get:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Get Two_D_Or_Three_D_Seismic_Report Workspace
      responses:
        '200':
          description: get Two_D_Or_Three_D_Seismic_Report Workspace data to be returned
          content:
            application/json:
              example:
                Id: 1
                Afe_number: 1
                Tdotdsr_id: 1
  /Two-D-Or-Three-D-Seismic-Report-workspace/{id}:
    parameters:
    - in: path
      name: id
      required: true
      description: id of Two_D_Or_Three_D_Seismic_Report data to fetch
      schema:
        type: interger
    put:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Update a new Two_D_Or_Three_D_Seismic_Report Workspace data
      description: Update a new Two_D_Or_Three_D_Seismic_Report Workspace Workspace
        data
      requestBody:
        required: true
        description: Request body to update Two_D_Or_Three_D_Seismic_Report data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Two_D_Or_Three_D_Seismic_Report'
            example:
              Id: 1
              Afe_number: 1
              Tdotdsr_id: 1
      responses:
        '200':
          description: Two_D_Or_Three_D_Seismic_Report Workspace data is completely
            updated
          content:
            application/json:
              example:
                message: The Two_D_Or_Three_D_Seismic_Report Workspace data is completely
                  updated
    patch:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Update a new Two_D_Or_Three_D_Seismic_Report data
      description: Update a new Two_D_Or_Three_D_Seismic_Report data
      requestBody:
        required: true
        description: Request body to update Two_D_Or_Three_D_Seismic_Report data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Two_D_Or_Three_D_Seismic_Report'
            example:
              Id: 1
              Afe_number: 1
              Tdotdsr_id: 1
      responses:
        '200':
          description: one row in Two_D_Or_Three_D_Seismic_Report data is updated
          content:
            application/json:
              example:
                message: The one row in Two_D_Or_Three_D_Seismic_Report Workspace
                  data is updated
    delete:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Delete Two_D_Or_Three_D_Seismic_Report Workspace data
      description: Delete Two_D_Or_Three_D_Seismic_Report data
      responses:
        '200':
          description: Two_D_Or_Three_D_Seismic_Report Workspace data is deleted
          content:
            application/json:
              example:
                message: The Two_D_Or_Three_D_Seismic_Report Workspace data was successfully
                  deleted
  /Two-D-Or-Three-D-Seismic-Report:
    get:
      security:
      - Authorization: []
      tags:
      - Two D Or Three D Seismic Report
      summary: Get Two_D_Or_Three_D_Seismic_Report
      responses:
        '200':
          description: get Two_D_Or_Three_D_Seismic_Report data to be returned
          content:
            application/json:
              example:
                Ba_long_name: LoremIpsum
                Ba_type: LoremIpsum
                Area_id: LoremIpsum
                Area_type: LoremIpsum
                Acqtn_survey_name: LoremIpsum
                Start_date: LoremIpsum
                Seis_dimension: LoremIpsum
                Line_name: LoremIpsum
                Title: LoremIpsum
                Creator_name: LoremIpsum
                Create_date: LoremIpsum
                Item_category: LoremIpsum
                Media_type: LoremIpsum
                Data_store_name: LoremIpsum
                Data_store_type: LoremIpsum
                Location_id: LoremIpsum
                Remark: LoremIpsum
                Source: LoremIpsum
                Qc_status: LoremIpsum
                Checked_by_ba_id: LoremIpsum
    post:
      security:
      - Authorization: []
      tags:
      - Two D Or Three D Seismic Report
      summary: Post a new Two_D_Or_Three_D_Seismic_Report
      description: Create a new Two_D_Or_Three_D_Seismic_Report data
      requestBody:
        required: true
        description: Request body to create Two_D_Or_Three_D_Seismic_Report data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Two_D_Or_Three_D_Seismic_Report'
            example: []
      responses:
        '200':
          description: Two_D_Or_Three_D_Seismic_Report data is added
          content:
            application/json:
              example:
                message: The Two_D_Or_Three_D_Seismic_Report data was successfully
                  added
  /Two-D-Or-Three-D-Seismic-Report/{id}:
    parameters:
    - in: path
      name: id
      required: true
      description: id of Two_D_Or_Three_D_Seismic_Report data to fetch
      schema:
        type: interger
    get:
      security:
      - Authorization: []
      tags:
      - Two D Or Three D Seismic Report
      summary: Get Two_D_Or_Three_D_Seismic_Report
      responses:
        '200':
          description: get Two_D_Or_Three_D_Seismic_Report data to be returned
          content:
            application/json:
              example:
              - []
    put:
      security:
      - Authorization: []
      tags:
      - Two D Or Three D Seismic Report
      summary: Update a new Two_D_Or_Three_D_Seismic_Report data
      description: Update a new Two_D_Or_Three_D_Seismic_Report data
      requestBody:
        required: true
        description: Request body to update Two_D_Or_Three_D_Seismic_Report data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Two_D_Or_Three_D_Seismic_Report'
            example: []
      responses:
        '200':
          description: Two_D_Or_Three_D_Seismic_Report data is completely updated
          content:
            application/json:
              example:
                message: The Two_D_Or_Three_D_Seismic_Report data is completely updated
    patch:
      security:
      - Authorization: []
      tags:
      - Two D Or Three D Seismic Report
      summary: Update a new Two_D_Or_Three_D_Seismic_Report data
      description: Update a new Two_D_Or_Three_D_Seismic_Report data
      requestBody:
        required: true
        description: Request body to update Two_D_Or_Three_D_Seismic_Report data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Two_D_Or_Three_D_Seismic_Report'
            example: []
      responses:
        '200':
          description: one row in Two_D_Or_Three_D_Seismic_Report data is updated
          content:
            application/json:
              example:
                message: The one row in Two_D_Or_Three_D_Seismic_Report data is updated
    delete:
      security:
      - Authorization: []
      tags:
      - Two D Or Three D Seismic Report
      summary: Delete Two_D_Or_Three_D_Seismic_Report data
      description: Delete Two_D_Or_Three_D_Seismic_Report data
      responses:
        '200':
          description: Two_D_Or_Three_D_Seismic_Report data is deleted
          content:
            application/json:
              example:
                message: The Two_D_Or_Three_D_Seismic_Report data was successfully
                  deleted
components:
  schemas:
    afe:
      type: array
      items:
        type: object
        properties:
          afe_number:
            type: integer
          workspace_name:
            type: string
          kkks_name:
            type: string
          working_area:
            type: string
          submission_type:
            type: string
          data_type:
            type: string
    Two_D_Or_Three_D_Seismic_Report_workspace:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
          afe_number:
            type: integer
          Tdotdsr_id:
            type: integer
    Two_D_Or_Three_D_Seismic_Report:
      type: object
      properties:
        Ba_long_name:
          type: string
        Ba_type:
          type: string
        Area_id:
          type: string
        Area_type:
          type: string
        Acqtn_survey_name:
          type: string
        Start_date:
          type: string
        Seis_dimension:
          type: string
        Line_name:
          type: string
        Title:
          type: string
        Creator_name:
          type: string
        Create_date:
          type: string
        Item_category:
          type: string
        Media_type:
          type: string
        Data_store_name:
          type: string
        Data_store_type:
          type: string
        Location_id:
          type: string
        Remark:
          type: string
        Source:
          type: string
        Qc_status:
          type: string
        Checked_by_ba_id:
          type: string
  securitySchemes:
    Authorization:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Please enter the access token
