openapi: 3.0.0
info:
  description: This is the swagger API for Well_Core_Sample
  version: 1.0.0
  title: Well_Core_Sample
  termsOfService: http://swagger.io/terms/
  contact:
    email: darren.mannuela@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
- description: Well_Core_Sample
  url: http://localhost:8080/api/v1
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/DarrenMannuela/Well_Core_Sample/1.0.0
tags:
- name: Afe
  description: All endpoints related to get Well_Core_Sample AFE
- name: Workspace
  description: All endpoints related to Well_Core_Sample Workspace
- name: Well Core Sample
  description: All endpoints related to Well_Core_Sample
- name: Well Core Sample Dummy Data
  description: All endpoints related to Well_Core_Sample
paths:
  /Well-Core-Sample-afe:
    get:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Get Well_Core_Sample AFE
      responses:
        '200':
          description: get Well_Core_Sample AFE data to be returned
          content:
            application/json:
              example:
                afe_number: 1
                workspace_name: LoremIpsum
                kkks_name: LoremIpsum
                working_area: LoremIpsum
                submission_type: Lorem
                data_type: Well Core Sample
              user_id: 1
    post:
      security:
      - OAuth2PasswordBearer: []
      tags:
      - Afe
      summary: Post a new Well_Core_Sample AFE
      description: Create a new Well_Core_Sample AFE data
      requestBody:
        required: true
        description: Request body to create Well_Core_Sample AFE data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Well_Core_Sample'
            example:
              afe_number: 1
              workspace_name: LoremIpsum
              kkks_name: LoremIpsum
              working_area: LoremIpsum
              submission_type: Lorem
              data_type: Well Core Sample
            user_id: 1
      responses:
        '200':
          description: Well_Core_Sample data is added
          content:
            application/json:
              example:
                message: The Well_Core_Sample AFE data was successfully added
  /Well-Core-Sample-afe/{afe}:
    parameters:
    - in: path
      name: afe
      required: true
      description: afe of Well_Core_Sample data to fetch
      schema:
        type: interger
    get:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Get Well_Core_Sample AFE
      responses:
        '200':
          description: get Well_Core_Sample AFE data to be returned
          content:
            application/json:
              example:
                afe_number: 1
                workspace_name: LoremIpsum
                kkks_name: LoremIpsum
                working_area: LoremIpsum
                submission_type: Lorem
                data_type: Well Core Sample
              user_id: 1
    put:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Update a new Well_Core_Sample AFE data
      description: Update a new Well_Core_Sample data
      requestBody:
        required: true
        description: Request body to update Well_Core_Sample AFE data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Well_Core_Sample'
            example:
              afe_number: 1
              workspace_name: LoremIpsum
              kkks_name: LoremIpsum
              working_area: LoremIpsum
              submission_type: Lorem
              data_type: Well Core Sample
            user_id: 1
      responses:
        '200':
          description: Well_Core_Sample data is completely updated
          content:
            application/json:
              example:
                message: The Well_Core_Sample AFE data is completely updated
    patch:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Update a new Well_Core_Sample AFE data
      description: Update a new Well_Core_Sample data
      requestBody:
        required: true
        description: Request body to update Well_Core_Sample AFE data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Well_Core_Sample'
            example:
              afe_number: 1
              workspace_name: LoremIpsum
              kkks_name: LoremIpsum
              working_area: LoremIpsum
              submission_type: Lorem
              data_type: Well Core Sample
            user_id: 1
      responses:
        '200':
          description: one row in Well_Core_Sample data is updated
          content:
            application/json:
              example:
                message: The one row in Well_Core_Sample AFE data is updated
    delete:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Delete Well_Core_Sample AFE data
      description: Delete Well_Core_Sample AFE data
      responses:
        '200':
          description: Well_Core_Sample AFE data is deleted
          content:
            application/json:
              example:
                message: The Well_Core_Sample AFE data was successfully deleted
  /Well-Core-Sample-workspace:
    get:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Get Well_Core_Sample Workspace
      responses:
        '200':
          description: get Well_Core_Sample Workspace data to be returned
          content:
            application/json:
              example:
                Id: 1
                Afe_number: 1
                Well_core_sample_id: 1
    post:
      security:
      - OAuth2PasswordBearer: []
      tags:
      - Workspace
      summary: Post a new Well_Core_Sample Workspace
      description: Create a new Well_Core_Sample Workspace data
      requestBody:
        required: true
        description: Request body to create Well_Core_Sample Workspace data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Well_Core_Sample'
            example:
              Id: 1
              Afe_number: 1
              Well_core_sample_id: 1
      responses:
        '200':
          description: Well_Core_Sample Workspace data is added
          content:
            application/json:
              example:
                message: The Well_Core_Sample Workspace data was successfully added
  /Well-Core-Sample-workspace/{afe}}:
    parameters:
    - in: path
      name: afe
      required: true
      description: afe of Well_Core_Sample data to fetch
      schema:
        type: interger
    get:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Get Well_Core_Sample Workspace
      responses:
        '200':
          description: get Well_Core_Sample Workspace data to be returned
          content:
            application/json:
              example:
                Id: 1
                Afe_number: 1
                Well_core_sample_id: 1
  /Well-Core-Sample-workspace/{id}:
    parameters:
    - in: path
      name: id
      required: true
      description: id of Well_Core_Sample data to fetch
      schema:
        type: interger
    put:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Update a new Well_Core_Sample Workspace data
      description: Update a new Well_Core_Sample Workspace Workspace data
      requestBody:
        required: true
        description: Request body to update Well_Core_Sample data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Well_Core_Sample'
            example:
              Id: 1
              Afe_number: 1
              Well_core_sample_id: 1
      responses:
        '200':
          description: Well_Core_Sample Workspace data is completely updated
          content:
            application/json:
              example:
                message: The Well_Core_Sample Workspace data is completely updated
    patch:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Update a new Well_Core_Sample data
      description: Update a new Well_Core_Sample data
      requestBody:
        required: true
        description: Request body to update Well_Core_Sample data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Well_Core_Sample'
            example:
              Id: 1
              Afe_number: 1
              Well_core_sample_id: 1
      responses:
        '200':
          description: one row in Well_Core_Sample data is updated
          content:
            application/json:
              example:
                message: The one row in Well_Core_Sample Workspace data is updated
    delete:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Delete Well_Core_Sample Workspace data
      description: Delete Well_Core_Sample data
      responses:
        '200':
          description: Well_Core_Sample Workspace data is deleted
          content:
            application/json:
              example:
                message: The Well_Core_Sample Workspace data was successfully deleted
  /Well-Core-Sample:
    get:
      security:
      - Authorization: []
      tags:
      - Well Core Sample
      summary: Get Well_Core_Sample
      responses:
        '200':
          description: get Well_Core_Sample data to be returned
          content:
            application/json:
              example:
                Ba_long_name: LoremIpsum
                Ba_type: LoremIpsum
                Area_id: LoremIpsum
                Area_type: LoremIpsum
                Field_name: LoremIpsum
                Well_name: LoremIpsum
                Uwi: LoremIpsum
                Core_type: LoremIpsum
                Sample_num: LoremIpsum
                Sample_count: LoremIpsum
                Top_depth: LoremIpsum
                Top_depth_ouom: LoremIpsum
                Base_depth: LoremIpsum
                Base_depth_ouom: LoremIpsum
                Portion_volume: LoremIpsum
                Portion_volume_ouom: LoremIpsum
                Study_type: LoremIpsum
                Data_store_name: LoremIpsum
                Data_store_type: LoremIpsum
                Location_id: LoremIpsum
                Remark: LoremIpsum
                Source: LoremIpsum
                Qc_status: LoremIpsum
                Checked_by_ba_id: LoremIpsum
    post:
      security:
      - OAuth2PasswordBearer: []
      tags:
      - Well Core Sample
      summary: Post a new Well_Core_Sample
      description: Create a new Well_Core_Sample data
      requestBody:
        required: true
        description: Request body to create Well_Core_Sample data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Well_Core_Sample'
            example: []
      responses:
        '200':
          description: Well_Core_Sample data is added
          content:
            application/json:
              example:
                message: The Well_Core_Sample data was successfully added
  /Well-Core-Sample/{id}:
    parameters:
    - in: path
      name: id
      required: true
      description: id of Well_Core_Sample data to fetch
      schema:
        type: interger
    get:
      security:
      - Authorization: []
      tags:
      - Well Core Sample
      summary: Get Well_Core_Sample
      responses:
        '200':
          description: get Well_Core_Sample data to be returned
          content:
            application/json:
              example:
              - []
    put:
      security:
      - Authorization: []
      tags:
      - Well Core Sample
      summary: Update a new Well_Core_Sample data
      description: Update a new Well_Core_Sample data
      requestBody:
        required: true
        description: Request body to update Well_Core_Sample data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Well_Core_Sample'
            example: []
      responses:
        '200':
          description: Well_Core_Sample data is completely updated
          content:
            application/json:
              example:
                message: The Well_Core_Sample data is completely updated
    patch:
      security:
      - Authorization: []
      tags:
      - Well Core Sample
      summary: Update a new Well_Core_Sample data
      description: Update a new Well_Core_Sample data
      requestBody:
        required: true
        description: Request body to update Well_Core_Sample data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Well_Core_Sample'
            example: []
      responses:
        '200':
          description: one row in Well_Core_Sample data is updated
          content:
            application/json:
              example:
                message: The one row in Well_Core_Sample data is updated
    delete:
      security:
      - Authorization: []
      tags:
      - Well Core Sample
      summary: Delete Well_Core_Sample data
      description: Delete Well_Core_Sample data
      responses:
        '200':
          description: Well_Core_Sample data is deleted
          content:
            application/json:
              example:
                message: The Well_Core_Sample data was successfully deleted
  /Well-Core-Sample/{num}:
    parameters:
    - in: path
      name: num
      required: true
      description: number of dummy data to add
      schema:
        type: interger
    get:
      security:
      - Authorization: []
      tags:
      - Well Core Sample Dummy Data
      summary: Add dummy data to Well_Core_Sample
      responses:
        '200':
          description: add data to Well_Core_Sample
          content:
            application/json: {}
components:
  schemas:
    afe:
      type: array
      items:
        type: object
        properties:
          afe_number:
            type: integer
          workspace_name:
            type: string
          kkks_name:
            type: string
          working_area:
            type: string
          submission_type:
            type: string
          data_type:
            type: string
    Well_Core_Sample_workspace:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
          afe_number:
            type: integer
          Well_core_sample_id:
            type: integer
    Well_Core_Sample:
      type: object
      properties:
        Ba_long_name:
          type: string
        Ba_type:
          type: string
        Area_id:
          type: string
        Area_type:
          type: string
        Field_name:
          type: string
        Well_name:
          type: string
        Uwi:
          type: string
        Core_type:
          type: string
        Sample_num:
          type: string
        Sample_count:
          type: string
        Top_depth:
          type: string
        Top_depth_ouom:
          type: string
        Base_depth:
          type: string
        Base_depth_ouom:
          type: string
        Portion_volume:
          type: string
        Portion_volume_ouom:
          type: string
        Study_type:
          type: string
        Data_store_name:
          type: string
        Data_store_type:
          type: string
        Location_id:
          type: string
        Remark:
          type: string
        Source:
          type: string
        Qc_status:
          type: string
        Checked_by_ba_id:
          type: string
  securitySchemes:
    OAuth2PasswordBearer:
      type: oauth2
      flows:
        password:
          scopes: {}
          tokenUrl: v1/token
