openapi: 3.0.0
info:
  description: This is the swagger API for Well_samples
  version: 1.0.0
  title: Well_samples
  termsOfService: http://swagger.io/terms/
  contact:
    email: darren.mannuela@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
- description: Well_samples
  url: http://localhost:8080/api/v1
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/DarrenMannuela/Well_samples/1.0.0
tags:
- name: Afe
  description: All endpoints related to get Well_samples AFE
- name: Workspace
  description: All endpoints related to Well_samples Workspace
- name: Well_samples
  description: All endpoints related to Well_samples
- name: Well_samples Dummy Data
  description: All endpoints related to Well_samples
- name: User Mgmt
  description: All endpoints related to tokens
paths:
  /Well_samples-afe:
    get:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Get Well_samples AFE
      responses:
        '200':
          description: get Well_samples AFE data to be returned
          content:
            application/json:
              example:
                afe_number: 1
                workspace_name: LoremIpsum
                kkks_name: LoremIpsum
                working_area: LoremIpsum
                submission_type: Lorem
                data_type: Well_samples
                email: john.richardson@gtn.id
    post:
      security:
      - OAuth2PasswordBearer: []
      tags:
      - Afe
      summary: Post a new Well_samples AFE
      description: Create a new Well_samples AFE data
      requestBody:
        required: true
        description: Request body to create Well_samples AFE data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Well_samples'
            example:
              afe_number: 1
              workspace_name: LoremIpsum
              kkks_name: LoremIpsum
              working_area: LoremIpsum
              submission_type: Lorem
              data_type: Well_samples
              email: john.richardson@gtn.id
      responses:
        '200':
          description: Well_samples data is added
          content:
            application/json:
              example:
                message: The Well_samples AFE data was successfully added
  /Well_samples-afe/{afe}:
    parameters:
    - in: path
      name: afe
      required: true
      description: afe of Well_samples data to fetch
      schema:
        type: integer
    get:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Get Well_samples AFE
      responses:
        '200':
          description: get Well_samples AFE data to be returned
          content:
            application/json:
              example:
                afe_number: 1
                workspace_name: LoremIpsum
                kkks_name: LoremIpsum
                working_area: LoremIpsum
                submission_type: Lorem
                data_type: Well_samples
                email: john.richardson@gtn.id
    put:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Update a new Well_samples AFE data
      description: Update a new Well_samples data
      requestBody:
        required: true
        description: Request body to update Well_samples AFE data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Well_samples'
            example:
              afe_number: 1
              workspace_name: LoremIpsum
              kkks_name: LoremIpsum
              working_area: LoremIpsum
              submission_type: Lorem
              data_type: Well_samples
              email: john.richardson@gtn.id
      responses:
        '200':
          description: Well_samples data is completely updated
          content:
            application/json:
              example:
                message: The Well_samples AFE data is completely updated
    patch:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Update a new Well_samples AFE data
      description: Update a new Well_samples data
      requestBody:
        required: true
        description: Request body to update Well_samples AFE data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Well_samples'
            example:
              afe_number: 1
              workspace_name: LoremIpsum
              kkks_name: LoremIpsum
              working_area: LoremIpsum
              submission_type: Lorem
              data_type: Well_samples
              email: john.richardson@gtn.id
      responses:
        '200':
          description: one row in Well_samples data is updated
          content:
            application/json:
              example:
                message: The one row in Well_samples AFE data is updated
    delete:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Delete Well_samples AFE data
      description: Delete Well_samples AFE data
      responses:
        '200':
          description: Well_samples AFE data is deleted
          content:
            application/json:
              example:
                message: The Well_samples AFE data was successfully deleted
  /Well_samples-workspace:
    get:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Get Well_samples Workspace
      responses:
        '200':
          description: get Well_samples Workspace data to be returned
          content:
            application/json:
              example:
                Id: 1
                Afe_number: 1
                Well_samples_id: 1
    post:
      security:
      - OAuth2PasswordBearer: []
      tags:
      - Workspace
      summary: Post a new Well_samples Workspace
      description: Create a new Well_samples Workspace data
      requestBody:
        required: true
        description: Request body to create Well_samples Workspace data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Well_samples'
            example:
              Id: 1
              Afe_number: 1
              Well_samples_id: 1
      responses:
        '200':
          description: Well_samples Workspace data is added
          content:
            application/json:
              example:
                message: The Well_samples Workspace data was successfully added
  /Well_samples-workspace/{afe}}:
    parameters:
    - in: path
      name: afe
      required: true
      description: afe of Well_samples data to fetch
      schema:
        type: integer
    get:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Get Well_samples Workspace
      responses:
        '200':
          description: get Well_samples Workspace data to be returned
          content:
            application/json:
              example:
                Id: 1
                Afe_number: 1
                Well_samples_id: 1
  /Well_samples-workspace/{id}:
    parameters:
    - in: path
      name: id
      required: true
      description: id of Well_samples data to fetch
      schema:
        type: integer
    put:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Update a new Well_samples Workspace data
      description: Update a new Well_samples Workspace Workspace data
      requestBody:
        required: true
        description: Request body to update Well_samples data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Well_samples'
            example:
              Id: 1
              Afe_number: 1
              Well_samples_id: 1
      responses:
        '200':
          description: Well_samples Workspace data is completely updated
          content:
            application/json:
              example:
                message: The Well_samples Workspace data is completely updated
    patch:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Update a new Well_samples data
      description: Update a new Well_samples data
      requestBody:
        required: true
        description: Request body to update Well_samples data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Well_samples'
            example:
              Id: 1
              Afe_number: 1
              Well_samples_id: 1
      responses:
        '200':
          description: one row in Well_samples data is updated
          content:
            application/json:
              example:
                message: The one row in Well_samples Workspace data is updated
    delete:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Delete Well_samples Workspace data
      description: Delete Well_samples data
      responses:
        '200':
          description: Well_samples Workspace data is deleted
          content:
            application/json:
              example:
                message: The Well_samples Workspace data was successfully deleted
  /Well_samples:
    get:
      security:
      - Authorization: []
      tags:
      - Well_samples
      summary: Get Well_samples
      responses:
        '200':
          description: get Well_samples data to be returned
          content:
            application/json:
              example:
                Id: 1
                Ba_long_name: LoremIpsum
                Ba_type: LoremIpsum
                Area_id: LoremIpsum
                Area_type: LoremIpsum
                Field_name: LoremIpsum
                Well_name: LoremIpsum
                Uwi_: LoremIpsum
                Sample_type: LoremIpsum
                Sample_num: LoremIpsum
                Sample_count: 1
                Top_md: 1
                Top_md_ouom: LoremIpsum
                Base_md: 1
                Base_md_ouom: LoremIpsum
                Study_type: LoremIpsum
                Ba_long_name_2: LoremIpsum
                Ba_type_2: LoremIpsum
                Data_store_name: LoremIpsum
                Data_store_type: LoremIpsum
                Location_id: LoremIpsum
                Remark_: LoremIpsum
                Source_: LoremIpsum
                Qc_status: LoremIpsum
                Checked_by_ba_id: LoremIpsum
    post:
      security:
      - OAuth2PasswordBearer: []
      tags:
      - Well_samples
      summary: Post a new Well_samples
      description: Create a new Well_samples data
      requestBody:
        required: true
        description: Request body to create Well_samples data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Well_samples'
            example: []
      responses:
        '200':
          description: Well_samples data is added
          content:
            application/json:
              example:
                message: The Well_samples data was successfully added
  /Well_samples/{id}:
    parameters:
    - in: path
      name: id
      required: true
      description: id of Well_samples data to fetch
      schema:
        type: integer
    get:
      security:
      - Authorization: []
      tags:
      - Well_samples
      summary: Get Well_samples
      responses:
        '200':
          description: get Well_samples data to be returned
          content:
            application/json:
              example:
              - []
    put:
      security:
      - Authorization: []
      tags:
      - Well_samples
      summary: Update a new Well_samples data
      description: Update a new Well_samples data
      requestBody:
        required: true
        description: Request body to update Well_samples data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Well_samples'
            example: []
      responses:
        '200':
          description: Well_samples data is completely updated
          content:
            application/json:
              example:
                message: The Well_samples data is completely updated
    patch:
      security:
      - Authorization: []
      tags:
      - Well_samples
      summary: Update a new Well_samples data
      description: Update a new Well_samples data
      requestBody:
        required: true
        description: Request body to update Well_samples data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Well_samples'
            example: []
      responses:
        '200':
          description: one row in Well_samples data is updated
          content:
            application/json:
              example:
                message: The one row in Well_samples data is updated
    delete:
      security:
      - Authorization: []
      tags:
      - Well_samples
      summary: Delete Well_samples data
      description: Delete Well_samples data
      responses:
        '200':
          description: Well_samples data is deleted
          content:
            application/json:
              example:
                message: The Well_samples data was successfully deleted
  /Well_samples/{num}:
    parameters:
    - in: path
      name: num
      required: true
      description: number of dummy data to add
      schema:
        type: integer
    get:
      security:
      - Authorization: []
      tags:
      - Well_samples Dummy Data
      summary: Add dummy data to Well_samples
      responses:
        '200':
          description: add data to Well_samples
          content:
            application/json: {}
  /token:
    post:
      security:
      - OAuth2PasswordBearer: []
      tags:
      - User Mgmt
      summary: Login For Access Token
      operationId: login_for_access_token_token_post
      requestBody:
        required: true
        description: Request body to create Well_samples AFE data
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Body_login_for_access_token_token_post'
            example: []
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    afe:
      type: array
      items:
        type: object
        properties:
          afe_number:
            type: integer
          workspace_name:
            type: string
          kkks_name:
            type: string
          working_area:
            type: string
          submission_type:
            type: string
          data_type:
            type: string
    Token:
      title: Token
      required:
      - access_token
      - token_type
      - type
      - name
      - expiry_date
      - affiliation
      type: object
      properties:
        access_token:
          title: Access Token
          type: string
        token_type:
          title: Token Type
          type: string
        type:
          $ref: '#/components/schemas/UserType'
        name:
          title: Name
          type: string
        expiry_date:
          title: Expiry Date
          type: string
        affiliation:
          title: Affiliation
          type: string
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
    UserType:
      title: UserType
      enum:
      - Administrator
      - Regular User
      - Premium User
      type: string
      description: An enumeration.
    ValidationError:
      title: ValidationError
      required:
      - loc
      - msg
      - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            anyOf:
            - type: string
            - type: integer
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
    Body_login_for_access_token_token_post:
      title: Body_login_for_access_token_token_post
      required:
      - username
      - password
      type: object
      properties:
        grant_type:
          title: Grant Type
          pattern: password
          type: string
        username:
          title: Username
          type: string
        password:
          title: Password
          type: string
        scope:
          title: Scope
          type: string
          default: ''
        client_id:
          title: Client Id
          type: string
        client_secret:
          title: Client Secret
          type: string
    Well_samples_workspace:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
          afe_number:
            type: integer
          Well_samples_id:
            type: integer
    Well_samples:
      type: object
      properties:
        Id:
          type: integer
        Ba_long_name:
          type: string
        Ba_type:
          type: string
        Area_id:
          type: string
        Area_type:
          type: string
        Field_name:
          type: string
        Well_name:
          type: string
        Uwi_:
          type: string
        Sample_type:
          type: string
        Sample_num:
          type: string
        Sample_count:
          type: integer
        Top_md:
          type: integer
        Top_md_ouom:
          type: string
        Base_md:
          type: integer
        Base_md_ouom:
          type: string
        Study_type:
          type: string
        Ba_long_name_2:
          type: string
        Ba_type_2:
          type: string
        Data_store_name:
          type: string
        Data_store_type:
          type: string
        Location_id:
          type: string
        Remark_:
          type: string
        Source_:
          type: string
        Qc_status:
          type: string
        Checked_by_ba_id:
          type: string
  securitySchemes:
    OAuth2PasswordBearer:
      type: oauth2
      flows:
        password:
          scopes: {}
          tokenUrl: v1/token
