openapi: 3.0.0
info:
  description: This is the swagger API for Working_area
  version: 1.0.0
  title: Working_area
  termsOfService: http://swagger.io/terms/
  contact:
    email: darren.mannuela@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
- description: Working_area
  url: http://localhost:8080/api/v1
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/DarrenMannuela/Working_area/1.0.0
tags:
- name: Afe
  description: All endpoints related to get Working_area AFE
- name: Workspace
  description: All endpoints related to Working_area Workspace
- name: Working_area
  description: All endpoints related to Working_area
- name: Working_area Dummy Data
  description: All endpoints related to Working_area
- name: User Mgmt
  description: All endpoints related to tokens
paths:
  /Working_area-afe:
    get:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Get Working_area AFE
      responses:
        '200':
          description: get Working_area AFE data to be returned
          content:
            application/json:
              example:
                afe_number: 1
                workspace_name: LoremIpsum
                kkks_name: LoremIpsum
                working_area: LoremIpsum
                submission_type: Lorem
                data_type: Working_area
                email: john.richardson@gtn.id
    post:
      security:
      - OAuth2PasswordBearer: []
      tags:
      - Afe
      summary: Post a new Working_area AFE
      description: Create a new Working_area AFE data
      requestBody:
        required: true
        description: Request body to create Working_area AFE data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Working_area'
            example:
              afe_number: 1
              workspace_name: LoremIpsum
              kkks_name: LoremIpsum
              working_area: LoremIpsum
              submission_type: Lorem
              data_type: Working_area
              email: john.richardson@gtn.id
      responses:
        '200':
          description: Working_area data is added
          content:
            application/json:
              example:
                message: The Working_area AFE data was successfully added
  /Working_area-afe/{afe}:
    parameters:
    - in: path
      name: afe
      required: true
      description: afe of Working_area data to fetch
      schema:
        type: integer
    get:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Get Working_area AFE
      responses:
        '200':
          description: get Working_area AFE data to be returned
          content:
            application/json:
              example:
                afe_number: 1
                workspace_name: LoremIpsum
                kkks_name: LoremIpsum
                working_area: LoremIpsum
                submission_type: Lorem
                data_type: Working_area
                email: john.richardson@gtn.id
    put:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Update a new Working_area AFE data
      description: Update a new Working_area data
      requestBody:
        required: true
        description: Request body to update Working_area AFE data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Working_area'
            example:
              afe_number: 1
              workspace_name: LoremIpsum
              kkks_name: LoremIpsum
              working_area: LoremIpsum
              submission_type: Lorem
              data_type: Working_area
              email: john.richardson@gtn.id
      responses:
        '200':
          description: Working_area data is completely updated
          content:
            application/json:
              example:
                message: The Working_area AFE data is completely updated
    patch:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Update a new Working_area AFE data
      description: Update a new Working_area data
      requestBody:
        required: true
        description: Request body to update Working_area AFE data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Working_area'
            example:
              afe_number: 1
              workspace_name: LoremIpsum
              kkks_name: LoremIpsum
              working_area: LoremIpsum
              submission_type: Lorem
              data_type: Working_area
              email: john.richardson@gtn.id
      responses:
        '200':
          description: one row in Working_area data is updated
          content:
            application/json:
              example:
                message: The one row in Working_area AFE data is updated
    delete:
      security:
      - Authorization: []
      tags:
      - Afe
      summary: Delete Working_area AFE data
      description: Delete Working_area AFE data
      responses:
        '200':
          description: Working_area AFE data is deleted
          content:
            application/json:
              example:
                message: The Working_area AFE data was successfully deleted
  /Working_area-workspace:
    get:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Get Working_area Workspace
      responses:
        '200':
          description: get Working_area Workspace data to be returned
          content:
            application/json:
              example:
                Id: 1
                Afe_number: 1
                Working_area_id: 1
    post:
      security:
      - OAuth2PasswordBearer: []
      tags:
      - Workspace
      summary: Post a new Working_area Workspace
      description: Create a new Working_area Workspace data
      requestBody:
        required: true
        description: Request body to create Working_area Workspace data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Working_area'
            example:
              Id: 1
              Afe_number: 1
              Working_area_id: 1
      responses:
        '200':
          description: Working_area Workspace data is added
          content:
            application/json:
              example:
                message: The Working_area Workspace data was successfully added
  /Working_area-workspace/{afe}}:
    parameters:
    - in: path
      name: afe
      required: true
      description: afe of Working_area data to fetch
      schema:
        type: integer
    get:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Get Working_area Workspace
      responses:
        '200':
          description: get Working_area Workspace data to be returned
          content:
            application/json:
              example:
                Id: 1
                Afe_number: 1
                Working_area_id: 1
  /Working_area-workspace/{id}:
    parameters:
    - in: path
      name: id
      required: true
      description: id of Working_area data to fetch
      schema:
        type: integer
    put:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Update a new Working_area Workspace data
      description: Update a new Working_area Workspace Workspace data
      requestBody:
        required: true
        description: Request body to update Working_area data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Working_area'
            example:
              Id: 1
              Afe_number: 1
              Working_area_id: 1
      responses:
        '200':
          description: Working_area Workspace data is completely updated
          content:
            application/json:
              example:
                message: The Working_area Workspace data is completely updated
    patch:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Update a new Working_area data
      description: Update a new Working_area data
      requestBody:
        required: true
        description: Request body to update Working_area data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Working_area'
            example:
              Id: 1
              Afe_number: 1
              Working_area_id: 1
      responses:
        '200':
          description: one row in Working_area data is updated
          content:
            application/json:
              example:
                message: The one row in Working_area Workspace data is updated
    delete:
      security:
      - Authorization: []
      tags:
      - Workspace
      summary: Delete Working_area Workspace data
      description: Delete Working_area data
      responses:
        '200':
          description: Working_area Workspace data is deleted
          content:
            application/json:
              example:
                message: The Working_area Workspace data was successfully deleted
  /Working_area:
    get:
      security:
      - Authorization: []
      tags:
      - Working_area
      summary: Get Working_area
      responses:
        '200':
          description: get Working_area data to be returned
          content:
            application/json:
              example:
                Id: 1
                Area_id: LoremIpsum
                Area_type: LoremIpsum
                Ba_long_name: LoremIpsum
                Ba_type: LoremIpsum
                Effective_date: LoremIpsum
                Term_exiry_date: LoremIpsum
                Contract_type: LoremIpsum
                R_granted_right_type: LoremIpsum
                Gross_size: LoremIpsum
                Gross_size_ouom: LoremIpsum
                Land_right_category: LoremIpsum
                Producing_ind: LoremIpsum
                Original_file_name: LoremIpsum
                Password_: LoremIpsum
                Digital_size: 1
                Digital_size_uom: LoremIpsum
                Media_type: LoremIpsum
                Data_store_name: LoremIpsum
                Source_: LoremIpsum
                Qc_status: LoremIpsum
                Checked_by_ba_id: LoremIpsum
    post:
      security:
      - OAuth2PasswordBearer: []
      tags:
      - Working_area
      summary: Post a new Working_area
      description: Create a new Working_area data
      requestBody:
        required: true
        description: Request body to create Working_area data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Working_area'
            example: []
      responses:
        '200':
          description: Working_area data is added
          content:
            application/json:
              example:
                message: The Working_area data was successfully added
  /Working_area/{id}:
    parameters:
    - in: path
      name: id
      required: true
      description: id of Working_area data to fetch
      schema:
        type: integer
    get:
      security:
      - Authorization: []
      tags:
      - Working_area
      summary: Get Working_area
      responses:
        '200':
          description: get Working_area data to be returned
          content:
            application/json:
              example:
              - []
    put:
      security:
      - Authorization: []
      tags:
      - Working_area
      summary: Update a new Working_area data
      description: Update a new Working_area data
      requestBody:
        required: true
        description: Request body to update Working_area data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Working_area'
            example: []
      responses:
        '200':
          description: Working_area data is completely updated
          content:
            application/json:
              example:
                message: The Working_area data is completely updated
    patch:
      security:
      - Authorization: []
      tags:
      - Working_area
      summary: Update a new Working_area data
      description: Update a new Working_area data
      requestBody:
        required: true
        description: Request body to update Working_area data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Working_area'
            example: []
      responses:
        '200':
          description: one row in Working_area data is updated
          content:
            application/json:
              example:
                message: The one row in Working_area data is updated
    delete:
      security:
      - Authorization: []
      tags:
      - Working_area
      summary: Delete Working_area data
      description: Delete Working_area data
      responses:
        '200':
          description: Working_area data is deleted
          content:
            application/json:
              example:
                message: The Working_area data was successfully deleted
  /Working_area/{num}:
    parameters:
    - in: path
      name: num
      required: true
      description: number of dummy data to add
      schema:
        type: integer
    get:
      security:
      - Authorization: []
      tags:
      - Working_area Dummy Data
      summary: Add dummy data to Working_area
      responses:
        '200':
          description: add data to Working_area
          content:
            application/json: {}
  /token:
    post:
      security:
      - OAuth2PasswordBearer: []
      tags:
      - User Mgmt
      summary: Login For Access Token
      operationId: login_for_access_token_token_post
      requestBody:
        required: true
        description: Request body to create Working_area AFE data
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Body_login_for_access_token_token_post'
            example: []
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    afe:
      type: array
      items:
        type: object
        properties:
          afe_number:
            type: integer
          workspace_name:
            type: string
          kkks_name:
            type: string
          working_area:
            type: string
          submission_type:
            type: string
          data_type:
            type: string
    Token:
      title: Token
      required:
      - access_token
      - token_type
      - type
      - name
      - expiry_date
      - affiliation
      type: object
      properties:
        access_token:
          title: Access Token
          type: string
        token_type:
          title: Token Type
          type: string
        type:
          $ref: '#/components/schemas/UserType'
        name:
          title: Name
          type: string
        expiry_date:
          title: Expiry Date
          type: string
        affiliation:
          title: Affiliation
          type: string
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
    UserType:
      title: UserType
      enum:
      - Administrator
      - Regular User
      - Premium User
      type: string
      description: An enumeration.
    ValidationError:
      title: ValidationError
      required:
      - loc
      - msg
      - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            anyOf:
            - type: string
            - type: integer
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
    Body_login_for_access_token_token_post:
      title: Body_login_for_access_token_token_post
      required:
      - username
      - password
      type: object
      properties:
        grant_type:
          title: Grant Type
          pattern: password
          type: string
        username:
          title: Username
          type: string
        password:
          title: Password
          type: string
        scope:
          title: Scope
          type: string
          default: ''
        client_id:
          title: Client Id
          type: string
        client_secret:
          title: Client Secret
          type: string
    Working_area_workspace:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
          afe_number:
            type: integer
          Working_area_id:
            type: integer
    Working_area:
      type: object
      properties:
        Id:
          type: integer
        Area_id:
          type: string
        Area_type:
          type: string
        Ba_long_name:
          type: string
        Ba_type:
          type: string
        Effective_date:
          type: string
        Term_exiry_date:
          type: string
        Contract_type:
          type: string
        R_granted_right_type:
          type: string
        Gross_size:
          type: string
        Gross_size_ouom:
          type: string
        Land_right_category:
          type: string
        Producing_ind:
          type: string
        Original_file_name:
          type: string
        Password_:
          type: string
        Digital_size:
          type: integer
        Digital_size_uom:
          type: string
        Media_type:
          type: string
        Data_store_name:
          type: string
        Source_:
          type: string
        Qc_status:
          type: string
        Checked_by_ba_id:
          type: string
  securitySchemes:
    OAuth2PasswordBearer:
      type: oauth2
      flows:
        password:
          scopes: {}
          tokenUrl: v1/token
