import oracledb
import sys
import lib_platform as platform

if platform.system == "darwin":
    sys.path.insert(0, "database")
elif platform.system == "windows":
    sys.path.insert(0, "../database")

from conn import connection

# pw = getpass.getpass("Enter password: ")

# connection = oracledb.connect(
#     user="admin",
#     password="ppdm-3.9",
#     dsn="/kei-oracle-test.chkxr21l2l5s.ap-southeast-3.rds.amazonaws.com:1521/ORCL")

# print("Successfully connected to Oracle Database")

cursor = connection.cursor()


cursor.execute("""
    begin
        execute immediate 'drop table land_right';
        exception when others then if sqlcode <> -942 then raise; end if;
    end;""")

cursor.execute(
    """CREATE TABLE land_right(
    LAND_RIGHT_SUBTYPE VARCHAR(30) NOT NULL,
    LAND_RIGHT_ID VARCHAR(40) PRIMARY KEY  NOT NULL,
    ACQTN_DATE TIMESTAMP(0),
    ACTIVE_IND VARCHAR(1),
    AREA_ID VARCHAR(40),
    AREA_TYPE VARCHAR(40),
    CALCULATED_INTEREST DECIMAL(15,12),
    CASE_SERIAL_NUM VARCHAR(30),
    CONFIDENTIAL_IND VARCHAR(1),
    COST_CENTER_NUM VARCHAR(30),
    EFFECTIVE_DATE TIMESTAMP(0),
    EXPIRY_DATE TIMESTAMP(0),
    FIRST_PLATFORM_APPROVE_DATE TIMESTAMP(0),
    FIRST_PLATFORM_INSTALL_DATE TIMESTAMP(0),
    FIRST_PRODUCTION_DATE TIMESTAMP(0),
    FRACTIONAL_INTEREST VARCHAR(100),
    GRANTED_RIGHT_TYPE VARCHAR(40),
    GROSS_SIZE DECIMAL(20,10),
    GROSS_SIZE_OUOM VARCHAR(40),
    HIGH_WATER_DEPTH DECIMAL(15,5),
    HIGH_WATER_DEPTH_OUOM VARCHAR(40),
    INACTIVATION_DATE TIMESTAMP(0),
    INCENT_CERT_NO INT,
    ISSUE_DATE TIMESTAMP(0),
    JURISDICTION VARCHAR(40),
    LAND_ACQTN_METHOD VARCHAR(40),
    LAND_CASE_ACTION VARCHAR(40),
    LAND_CASE_TYPE VARCHAR(40),
    LAND_PROPERTY_TYPE VARCHAR(40),
    LAND_RIGHT_CATEGORY VARCHAR(40),
    LAND_SALE_NUMBER VARCHAR(30),
    LAND_SALE_OFFERING_ID VARCHAR(40),
    LAST_ACTION_DATE TIMESTAMP(0),
    LESSOR_NAME VARCHAR(255),
    LESSOR_NUM VARCHAR(30),
    LESSOR_TYPE VARCHAR(40),
    LOW_WATER_DEPTH DECIMAL(15,5),
    LOW_WATER_DEPTH_OUOM VARCHAR(40),
    MUNICIPALITY VARCHAR(40),
    OCCUPANT_NAME VARCHAR(255),
    OFFSHORE_DISTANCE DECIMAL(10,3),
    OFFSHORE_DISTANCE_OUOM VARCHAR(40),
    OIL_SAND_DEPOSIT VARCHAR(40),
    OVERLAP_IND VARCHAR(1),
    PLATFORM_COUNT INT,
    PPDM_GUID VARCHAR(38),
    PRIMARY_TERM DECIMAL(10,5),
    PRIMARY_TERM_OUOM VARCHAR(40),
    PRODUCING_IND VARCHAR(1),
    PROPRIETARY_NUM VARCHAR(30),
    QUALIFICATION_DATE TIMESTAMP(0),
    RECLAMATION_CERT_NUM VARCHAR(40),
    RECLAMATION_END_DATE TIMESTAMP(0),
    RECLAMATION_START_DATE TIMESTAMP(0),
    RELINQUISHABLE_IND VARCHAR(1),
    REMARK VARCHAR(2000),
    RENTAL_ALLOCATION_IND VARCHAR(1),
    REPORT_ACREAGE_IND VARCHAR(1),
    SCHEME_APPROVAL_NUM VARCHAR(30),
    SCHEME_EXPIRY_DATE TIMESTAMP(0),
    SECONDARY_TERM DECIMAL(10,5),
    SECONDARY_TERM_OUOM VARCHAR(40),
    SOURCE VARCHAR(40),
    SUBSURFACE_IND VARCHAR(1),
    SURFACE_IND VARCHAR(1),
    TERMIN_NOTICE_PERIOD DECIMAL(10,5),
    TERMIN_NOTICE_PERIOD_OUOM VARCHAR(40),
    TERM_EXIRY_DATE TIMESTAMP(0),
    UNIT_OPERATED_IND VARCHAR(1),
    WELL_QUALIFIC_TYPE VARCHAR(40),
    ROW_CHANGED_BY VARCHAR(30),
    ROW_CHANGED_DATE TIMESTAMP(0),
    ROW_CREATED_BY VARCHAR(30),
    ROW_CREATED_DATE TIMESTAMP(0),
    ROW_EFFECTIVE_DATE TIMESTAMP(0),
    ROW_EXPIRY_DATE TIMESTAMP(0),
    ROW_QUALITY VARCHAR(40))""")