package dto

type Rm_physical_item struct {
	Physical_item_id        string   `json:"physical_item_id" default:"source"`
	Active_ind              *string  `json:"active_ind" default:""`
	Bar_code                *string  `json:"bar_code" default:""`
	Catalogue_by_name       *string  `json:"catalogue_by_name" default:""`
	Catalogue_date          *string  `json:"catalogue_date" default:""`
	Certified_true_copy_ind *string  `json:"certified_true_copy_ind" default:""`
	Circulation_allowed_ind *string  `json:"circulation_allowed_ind" default:""`
	Circulation_out_ind     *string  `json:"circulation_out_ind" default:""`
	Color_format            *string  `json:"color_format" default:""`
	Create_date             *string  `json:"create_date" default:""`
	Digital_format          *string  `json:"digital_format" default:""`
	Digital_size            *float64 `json:"digital_size" default:""`
	Digital_size_uom        *string  `json:"digital_size_uom" default:""`
	Dim_height              *float64 `json:"dim_height" default:""`
	Dim_height_uom          *string  `json:"dim_height_uom" default:""`
	Dim_length              *float64 `json:"dim_length" default:""`
	Dim_length_uom          *string  `json:"dim_length_uom" default:""`
	Dim_weight              *float64 `json:"dim_weight" default:""`
	Dim_weight_uom          *string  `json:"dim_weight_uom" default:""`
	Dim_width               *float64 `json:"dim_width" default:""`
	Dim_width_uom           *string  `json:"dim_width_uom" default:""`
	Effective_date          *string  `json:"effective_date" default:""`
	Expiry_date             *string  `json:"expiry_date" default:""`
	File_count              *int     `json:"file_count" default:""`
	Group_ind               *string  `json:"group_ind" default:""`
	Image_resolution_uom    *string  `json:"image_resolution_uom" default:""`
	Image_x_resolution      *float64 `json:"image_x_resolution" default:""`
	Image_y_resolution      *float64 `json:"image_y_resolution" default:""`
	Item_category           *string  `json:"item_category" default:""`
	Item_sub_category       *string  `json:"item_sub_category" default:""`
	Label                   *string  `json:"label" default:""`
	Language                *string  `json:"language" default:""`
	Last_condition          *string  `json:"last_condition" default:""`
	Location_reference      *string  `json:"location_reference" default:""`
	Media_type              *string  `json:"media_type" default:""`
	Original_file_name      *string  `json:"original_file_name" default:""`
	Original_ind            *string  `json:"original_ind" default:""`
	Output_file_name        *string  `json:"output_file_name" default:""`
	Page_count              *float64 `json:"page_count" default:""`
	Physical_item_status    *string  `json:"physical_item_status" default:""`
	Ppdm_guid               *string  `json:"ppdm_guid" default:""`
	Preferred_ind           *string  `json:"preferred_ind" default:""`
	Qc_by_name              *string  `json:"qc_by_name" default:""`
	Remark                  *string  `json:"remark" default:""`
	Retention_period        *string  `json:"retention_period" default:""`
	Sale_allowed_ind        *string  `json:"sale_allowed_ind" default:""`
	Source                  *string  `json:"source" default:""`
	Store_id                *string  `json:"store_id" default:""`
	Row_changed_by          *string  `json:"row_changed_by" default:""`
	Row_changed_date        *string  `json:"row_changed_date" default:""`
	Row_created_by          *string  `json:"row_created_by" default:""`
	Row_created_date        *string  `json:"row_created_date" default:""`
	Row_effective_date      *string  `json:"row_effective_date" default:""`
	Row_expiry_date         *string  `json:"row_expiry_date" default:""`
	Row_quality             *string  `json:"row_quality" default:""`
}
