package dto

import (
	"time"
)

type Anl_oil_analysis struct {
	Analysis_id                 string     `json:"analysis_id"`
	Anl_source                  string     `json:"anl_source"`
	Oil_analysis_obs_no         int        `json:"oil_analysis_obs_no"`
	Absolute_gravity            *float64   `json:"absolute_gravity"`
	Absolute_gravity_ouom       *string    `json:"absolute_gravity_ouom"`
	Active_ind                  *string    `json:"active_ind"`
	Asphaltene_content          *float64   `json:"asphaltene_content"`
	Asphaltene_content_ouom     *string    `json:"asphaltene_content_ouom"`
	Asph_content_preferred_ind  *string    `json:"asph_content_preferred_ind"`
	Asph_content_problem_ind    *string    `json:"asph_content_problem_ind"`
	Asph_content_step_seq_no    *int       `json:"asph_content_step_seq_no"`
	Characterize_factor         *string    `json:"characterize_factor"`
	Characterize_factor_ouom    *string    `json:"characterize_factor_ouom"`
	Cloud_point_preferred_ind   *string    `json:"cloud_point_preferred_ind"`
	Cloud_point_problem_ind     *string    `json:"cloud_point_problem_ind"`
	Cloud_point_step_seq_no     *int       `json:"cloud_point_step_seq_no"`
	Cloud_point_temp            *float64   `json:"cloud_point_temp"`
	Cloud_point_temp_ouom       *string    `json:"cloud_point_temp_ouom"`
	Dew_point_preferred_ind     *string    `json:"dew_point_preferred_ind"`
	Dew_point_problem_ind       *string    `json:"dew_point_problem_ind"`
	Dew_point_step_seq_no       *int       `json:"dew_point_step_seq_no"`
	Dew_point_temp              *float64   `json:"dew_point_temp"`
	Dew_point_temp_ouom         *string    `json:"dew_point_temp_ouom"`
	Distillation_base_type      *string    `json:"distillation_base_type"`
	Distillation_preferred_ind  *string    `json:"distillation_preferred_ind"`
	Distillation_problem_ind    *string    `json:"distillation_problem_ind"`
	Distillation_step_seq_no    *int       `json:"distillation_step_seq_no"`
	Effective_date              *time.Time `json:"effective_date"`
	Expiry_date                 *time.Time `json:"expiry_date"`
	Flash_point_preferred_ind   *string    `json:"flash_point_preferred_ind"`
	Flash_point_problem_ind     *string    `json:"flash_point_problem_ind"`
	Flash_point_step_seq_no     *int       `json:"flash_point_step_seq_no"`
	Flash_point_temp            *float64   `json:"flash_point_temp"`
	Flash_point_temp_ouom       *string    `json:"flash_point_temp_ouom"`
	Gor                         *float64   `json:"gor"`
	Gor_ouom                    *string    `json:"gor_ouom"`
	Measured_pressure           *float64   `json:"measured_pressure"`
	Measured_pressure_ouom      *string    `json:"measured_pressure_ouom"`
	Measured_volume             *float64   `json:"measured_volume"`
	Measured_volume_ouom        *string    `json:"measured_volume_ouom"`
	Method_type                 *string    `json:"method_type"`
	Oil_analysis_temp           *float64   `json:"oil_analysis_temp"`
	Oil_analysis_temp_ouom      *string    `json:"oil_analysis_temp_ouom"`
	Oil_color                   *string    `json:"oil_color"`
	Oil_color_preferred_ind     *string    `json:"oil_color_preferred_ind"`
	Oil_color_problem_ind       *string    `json:"oil_color_problem_ind"`
	Oil_color_step_seq_no       *int       `json:"oil_color_step_seq_no"`
	Oil_density                 *float64   `json:"oil_density"`
	Oil_density_ouom            *string    `json:"oil_density_ouom"`
	Oil_density_preferred_ind   *string    `json:"oil_density_preferred_ind"`
	Oil_density_problem_ind     *string    `json:"oil_density_problem_ind"`
	Oil_density_step_seq_no     *int       `json:"oil_density_step_seq_no"`
	Oil_gravity                 *float64   `json:"oil_gravity"`
	Oil_gravity_ouom            *string    `json:"oil_gravity_ouom"`
	Oil_gravity_preferred_ind   *string    `json:"oil_gravity_preferred_ind"`
	Oil_gravity_step_seq_no     *int       `json:"oil_gravity_step_seq_no"`
	Oil_gravity_temp            *float64   `json:"oil_gravity_temp"`
	Oil_gravity_temp_ouom       *string    `json:"oil_gravity_temp_ouom"`
	Oil_gravity_temp_prefer_ind *string    `json:"oil_gravity_temp_prefer_ind"`
	Oil_gravity_temp_prob_ind   *string    `json:"oil_gravity_temp_prob_ind"`
	Oil_gravity_temp_step_seq   *int       `json:"oil_gravity_temp_step_seq"`
	Oil_type                    *string    `json:"oil_type"`
	Ppdm_guid                   string     `json:"ppdm_guid"`
	Relative_density            *float64   `json:"relative_density"`
	Relative_density_ouom       *string    `json:"relative_density_ouom"`
	Relative_std_density        *float64   `json:"relative_std_density"`
	Relative_std_density_ouom   *string    `json:"relative_std_density_ouom"`
	Remark                      *string    `json:"remark"`
	Reservoir_press             *float64   `json:"reservoir_press"`
	Reservoir_press_ouom        *string    `json:"reservoir_press_ouom"`
	Reservoir_temp              *float64   `json:"reservoir_temp"`
	Reservoir_temp_ouom         *string    `json:"reservoir_temp_ouom"`
	Sediment_content            *float64   `json:"sediment_content"`
	Sediment_content_ouom       *string    `json:"sediment_content_ouom"`
	Sediment_preferred_ind      *string    `json:"sediment_preferred_ind"`
	Sediment_problem_ind        *string    `json:"sediment_problem_ind"`
	Sediment_step_seq_no        *int       `json:"sediment_step_seq_no"`
	Shrinkage_factor            *float64   `json:"shrinkage_factor"`
	Shrink_factor_preferred_ind *string    `json:"shrink_factor_preferred_ind"`
	Shrink_factor_problem_ind   *string    `json:"shrink_factor_problem_ind"`
	Shrink_factor_step_seq_no   *int       `json:"shrink_factor_step_seq_no"`
	Source                      *string    `json:"source"`
	Sulphur_content             *float64   `json:"sulphur_content"`
	Vapour_press                *float64   `json:"vapour_press"`
	Vapour_press_ouom           *string    `json:"vapour_press_ouom"`
	Vapour_press_temp           *float64   `json:"vapour_press_temp"`
	Vapour_press_temp_ouom      *string    `json:"vapour_press_temp_ouom"`
	Water_content               *float64   `json:"water_content"`
	Water_content_ouom          *string    `json:"water_content_ouom"`
	Wax_content                 *float64   `json:"wax_content"`
	Wax_content_ouom            *string    `json:"wax_content_ouom"`
	Wax_content_preferred_ind   *string    `json:"wax_content_preferred_ind"`
	Wax_content_problem_ind     *string    `json:"wax_content_problem_ind"`
	Wax_content_step_seq_no     *int       `json:"wax_content_step_seq_no"`
	Row_changed_by              *string    `json:"row_changed_by"`
	Row_changed_date            *time.Time `json:"row_changed_date"`
	Row_created_by              *string    `json:"row_created_by"`
	Row_created_date            *time.Time `json:"row_created_date"`
	Row_effective_date          *time.Time `json:"row_effective_date"`
	Row_expiry_date             *time.Time `json:"row_expiry_date"`
	Row_quality                 *string    `json:"row_quality"`
}
