package dto

import (
	"time"
)

type Rm_info_item_content struct {
	Info_item_subtype        string     `json:"info_item_subtype"`
	Information_item_id      string     `json:"information_item_id"`
	Content_obs_no           int        `json:"content_obs_no"`
	Active_ind               *string    `json:"active_ind"`
	Activity_obs_no          *int       `json:"activity_obs_no"`
	Analysis_id              *string    `json:"analysis_id"`
	Application_id           *string    `json:"application_id"`
	Applic_attachment_id     *string    `json:"applic_attachment_id"`
	Area_id                  *string    `json:"area_id"`
	Area_type                *string    `json:"area_type"`
	Authority_id             *string    `json:"authority_id"`
	Ba_licensee_ba_id        *string    `json:"ba_licensee_ba_id"`
	Ba_license_id            *string    `json:"ba_license_id"`
	Bin_grid_id              *string    `json:"bin_grid_id"`
	Bin_grid_source          *string    `json:"bin_grid_source"`
	Business_associate_id    *string    `json:"business_associate_id"`
	Catalogue_equip_id       *string    `json:"catalogue_equip_id"`
	Column_name              *string    `json:"column_name"`
	Consent_id               *string    `json:"consent_id"`
	Consult_id               *string    `json:"consult_id"`
	Content_type             *string    `json:"content_type"`
	Contest_id               *string    `json:"contest_id"`
	Contract_id              *string    `json:"contract_id"`
	Discussion_id            *string    `json:"discussion_id"`
	Drill_report_id          *string    `json:"drill_report_id"`
	Ecozone_id               *string    `json:"ecozone_id"`
	Ecozone_set_id           *string    `json:"ecozone_set_id"`
	Effective_date           *time.Time `json:"effective_date"`
	Entitlement_id           *string    `json:"entitlement_id"`
	Equipment_id             *string    `json:"equipment_id"`
	Expiry_date              *time.Time `json:"expiry_date"`
	Facility_id              *string    `json:"facility_id"`
	Facility_license_id      *string    `json:"facility_license_id"`
	Facility_type            *string    `json:"facility_type"`
	Field_id                 *string    `json:"field_id"`
	Finance_id               *string    `json:"finance_id"`
	Fossil_desc_id           *string    `json:"fossil_desc_id"`
	Fossil_id                *string    `json:"fossil_id"`
	Hse_incident_id          *string    `json:"hse_incident_id"`
	Instrument_id            *string    `json:"instrument_id"`
	Interest_set_id          *string    `json:"interest_set_id"`
	Interest_set_seq_no      *int       `json:"interest_set_seq_no"`
	Interp_id                *string    `json:"interp_id"`
	Jurisdiction             *string    `json:"jurisdiction"`
	Land_request_id          *string    `json:"land_request_id"`
	Land_right_id            *string    `json:"land_right_id"`
	Land_right_subtype       *string    `json:"land_right_subtype"`
	Land_sale_number         *string    `json:"land_sale_number"`
	Land_sale_offering_id    *string    `json:"land_sale_offering_id"`
	Lithology_log_id         *string    `json:"lithology_log_id"`
	Lith_log_source          *string    `json:"lith_log_source"`
	Lith_sample_id           *string    `json:"lith_sample_id"`
	Notification_id          *string    `json:"notification_id"`
	Obligation_id            *string    `json:"obligation_id"`
	Obligation_seq_no        *int       `json:"obligation_seq_no"`
	Organization_id          *string    `json:"organization_id"`
	Organization_seq_no      *int       `json:"organization_seq_no"`
	Paleo_summary_id         *string    `json:"paleo_summary_id"`
	Pden_id                  *string    `json:"pden_id"`
	Pden_source              *string    `json:"pden_source"`
	Pden_subtype             *string    `json:"pden_subtype"`
	Physical_item_custody_id *string    `json:"physical_item_custody_id"`
	Physical_item_id         *string    `json:"physical_item_id"`
	Platform_id              *string    `json:"platform_id"`
	Platform_sf_subtype      *string    `json:"platform_sf_subtype"`
	Pool_id                  *string    `json:"pool_id"`
	Ppdm_audit_row_guid      *string    `json:"ppdm_audit_row_guid"`
	Ppdm_audit_seq_no        *int       `json:"ppdm_audit_seq_no"`
	Ppdm_guid                string     `json:"ppdm_guid"`
	Product_type             *string    `json:"product_type"`
	Prod_string_id           *string    `json:"prod_string_id"`
	Prod_string_source       *string    `json:"prod_string_source"`
	Project_id               *string    `json:"project_id"`
	Project_step_id          *string    `json:"project_step_id"`
	Rate_schedule_id         *string    `json:"rate_schedule_id"`
	Remark                   *string    `json:"remark"`
	Resent_id                *string    `json:"resent_id"`
	Reserve_class_id         *string    `json:"reserve_class_id"`
	Reserve_product          *string    `json:"reserve_product"`
	Reserve_revision_id      *string    `json:"reserve_revision_id"`
	Reserve_revision_obs_no  *int       `json:"reserve_revision_obs_no"`
	Reserve_summary_id       *string    `json:"reserve_summary_id"`
	Reserve_summary_obs_no   *int       `json:"reserve_summary_obs_no"`
	Restriction_id           *string    `json:"restriction_id"`
	Restriction_version      *int       `json:"restriction_version"`
	Sample_anal_source       *string    `json:"sample_anal_source"`
	Seis_license_id          *string    `json:"seis_license_id"`
	Seis_patch_id            *string    `json:"seis_patch_id"`
	Seis_set_id              *string    `json:"seis_set_id"`
	Seis_set_subtype         *string    `json:"seis_set_subtype"`
	Source                   *string    `json:"source"`
	Source_document_id       *string    `json:"source_document_id"`
	Spatial_description_id   *string    `json:"spatial_description_id"`
	Spatial_obs_no           *int       `json:"spatial_obs_no"`
	Strat_column_id          *string    `json:"strat_column_id"`
	Strat_column_source      *string    `json:"strat_column_source"`
	Strat_field_station_id   *string    `json:"strat_field_station_id"`
	Strat_name_set_id        *string    `json:"strat_name_set_id"`
	Strat_unit_id            *string    `json:"strat_unit_id"`
	Support_facility_id      *string    `json:"support_facility_id"`
	Support_facility_subtype *string    `json:"support_facility_subtype"`
	System_id                *string    `json:"system_id"`
	Table_name               *string    `json:"table_name"`
	Uwi                      *string    `json:"uwi"`
	Velocity_volume_id       *string    `json:"velocity_volume_id"`
	Wc_core_id               *string    `json:"wc_core_id"`
	Wc_source                *string    `json:"wc_source"`
	Wc_uwi                   *string    `json:"wc_uwi"`
	Wds_source               *string    `json:"wds_source"`
	Wds_survey_id            *string    `json:"wds_survey_id"`
	Wds_uwi                  *string    `json:"wds_uwi"`
	Well_activity_source     *string    `json:"well_activity_source"`
	Well_license_id          *string    `json:"well_license_id"`
	Well_license_source      *string    `json:"well_license_source"`
	Well_log_curve_id        *string    `json:"well_log_curve_id"`
	Well_log_id              *string    `json:"well_log_id"`
	Well_log_source          *string    `json:"well_log_source"`
	Wl_dgtz_curve_id         *string    `json:"wl_dgtz_curve_id"`
	Work_order_id            *string    `json:"work_order_id"`
	Wtf_fluid_type           *string    `json:"wtf_fluid_type"`
	Wtf_period_obs_no        *int       `json:"wtf_period_obs_no"`
	Wtf_period_type          *string    `json:"wtf_period_type"`
	Wtf_run_num              *string    `json:"wtf_run_num"`
	Wtf_source               *string    `json:"wtf_source"`
	Wtf_test_num             *string    `json:"wtf_test_num"`
	Wtf_test_type            *string    `json:"wtf_test_type"`
	Wtp_period_obs_no        *int       `json:"wtp_period_obs_no"`
	Wtp_period_type          *string    `json:"wtp_period_type"`
	Wtp_run_num              *string    `json:"wtp_run_num"`
	Wtp_source               *string    `json:"wtp_source"`
	Wtp_test_num             *string    `json:"wtp_test_num"`
	Wtp_test_type            *string    `json:"wtp_test_type"`
	Row_changed_by           *string    `json:"row_changed_by"`
	Row_changed_date         *time.Time `json:"row_changed_date"`
	Row_created_by           *string    `json:"row_created_by"`
	Row_created_date         *time.Time `json:"row_created_date"`
	Row_effective_date       *time.Time `json:"row_effective_date"`
	Row_expiry_date          *time.Time `json:"row_expiry_date"`
	Row_quality              *string    `json:"row_quality"`
}
