package dto

import (
	"time"
)

type Seis_acqtn_design struct {
	Acqtn_design_id              string     `json:"acqtn_design_id"`
	Acqtn_completed_date         *time.Time `json:"acqtn_completed_date"`
	Acqtn_completed_date_desc    *string    `json:"acqtn_completed_date_desc"`
	Acqtn_dimension              *string    `json:"acqtn_dimension"`
	Acqtn_direction              *string    `json:"acqtn_direction"`
	Acqtn_inline_bin_size        *float64   `json:"acqtn_inline_bin_size"`
	Acqtn_inline_bin_size_ouom   *string    `json:"acqtn_inline_bin_size_ouom"`
	Acqtn_remark                 *string    `json:"acqtn_remark"`
	Acqtn_shotpt_interval        *float64   `json:"acqtn_shotpt_interval"`
	Acqtn_shotpt_interval_ouom   *string    `json:"acqtn_shotpt_interval_ouom"`
	Acqtn_shot_line_spacing      *float64   `json:"acqtn_shot_line_spacing"`
	Acqtn_shot_line_spacing_ouom *string    `json:"acqtn_shot_line_spacing_ouom"`
	Acqtn_shot_time_intvl        *float64   `json:"acqtn_shot_time_intvl"`
	Acqtn_shot_time_intvl_ouom   *string    `json:"acqtn_shot_time_intvl_ouom"`
	Acqtn_start_date             *time.Time `json:"acqtn_start_date"`
	Acqtn_start_date_desc        *string    `json:"acqtn_start_date_desc"`
	Acqtn_xline_bin_size         *float64   `json:"acqtn_xline_bin_size"`
	Acqtn_xline_bin_size_ouom    *string    `json:"acqtn_xline_bin_size_ouom"`
	Active_ind                   *string    `json:"active_ind"`
	Actual_ind                   *string    `json:"actual_ind"`
	Cdp_coverage                 *float64   `json:"cdp_coverage"`
	Effective_date               *time.Time `json:"effective_date"`
	Energy_charge_size           *float64   `json:"energy_charge_size"`
	Energy_charge_size_ouom      *string    `json:"energy_charge_size_ouom"`
	Energy_oprg_psr              *float64   `json:"energy_oprg_psr"`
	Energy_oprg_psr_ouom         *string    `json:"energy_oprg_psr_ouom"`
	Energy_oprg_volume           *float64   `json:"energy_oprg_volume"`
	Energy_oprg_volume_ouom      *string    `json:"energy_oprg_volume_ouom"`
	Energy_shot_depth            *float64   `json:"energy_shot_depth"`
	Energy_shot_depth_ouom       *string    `json:"energy_shot_depth_ouom"`
	Energy_src_array_spc         *float64   `json:"energy_src_array_spc"`
	Energy_src_array_spc_ouom    *string    `json:"energy_src_array_spc_ouom"`
	Energy_src_array_type        *string    `json:"energy_src_array_type"`
	Energy_src_make              *string    `json:"energy_src_make"`
	Energy_src_per_shot          *float64   `json:"energy_src_per_shot"`
	Energy_sweep_duration        *float64   `json:"energy_sweep_duration"`
	Energy_sweep_duration_ouom   *string    `json:"energy_sweep_duration_ouom"`
	Energy_sweep_end_freq        *float64   `json:"energy_sweep_end_freq"`
	Energy_sweep_freq_ouom       *string    `json:"energy_sweep_freq_ouom"`
	Energy_sweep_mvup_dist       *float64   `json:"energy_sweep_mvup_dist"`
	Energy_sweep_mvup_dist_ouom  *string    `json:"energy_sweep_mvup_dist_ouom"`
	Energy_sweep_no              *int       `json:"energy_sweep_no"`
	Energy_sweep_st_freq         *float64   `json:"energy_sweep_st_freq"`
	Energy_sweep_taper           *float64   `json:"energy_sweep_taper"`
	Energy_sweep_taper_ouom      *string    `json:"energy_sweep_taper_ouom"`
	Energy_sweep_type            *string    `json:"energy_sweep_type"`
	Energy_type                  *string    `json:"energy_type"`
	Environment                  *string    `json:"environment"`
	Expiry_date                  *time.Time `json:"expiry_date"`
	Monitor_depth                *float64   `json:"monitor_depth"`
	Monitor_depth_ouom           *string    `json:"monitor_depth_ouom"`
	Nominal_ind                  *string    `json:"nominal_ind"`
	Ppdm_guid                    string     `json:"ppdm_guid"`
	Rcrd_channel_count           *int       `json:"rcrd_channel_count"`
	Rcrd_format_type             *string    `json:"rcrd_format_type"`
	Rcrd_gain_mode               *string    `json:"rcrd_gain_mode"`
	Rcrd_hf_freq                 *float64   `json:"rcrd_hf_freq"`
	Rcrd_hf_slope                *float64   `json:"rcrd_hf_slope"`
	Rcrd_lf_freq                 *float64   `json:"rcrd_lf_freq"`
	Rcrd_lf_slope                *float64   `json:"rcrd_lf_slope"`
	Rcrd_make                    *string    `json:"rcrd_make"`
	Rcrd_near_surf_corr          *string    `json:"rcrd_near_surf_corr"`
	Rcrd_near_surf_corr_ouom     *string    `json:"rcrd_near_surf_corr_ouom"`
	Rcrd_nf_freq                 *float64   `json:"rcrd_nf_freq"`
	Rcrd_nf_ind                  *string    `json:"rcrd_nf_ind"`
	Rcrd_polarity                *string    `json:"rcrd_polarity"`
	Rcrd_rec_length              *float64   `json:"rcrd_rec_length"`
	Rcrd_rec_length_ouom         *string    `json:"rcrd_rec_length_ouom"`
	Rcrd_sample_rate             *float64   `json:"rcrd_sample_rate"`
	Rcrd_sample_rate_ouom        *string    `json:"rcrd_sample_rate_ouom"`
	Rcvr_line_spacing            *float64   `json:"rcvr_line_spacing"`
	Rcvr_line_spacing_ouom       *string    `json:"rcvr_line_spacing_ouom"`
	Remark                       *string    `json:"remark"`
	Rep_water_acoustic_vel       *float64   `json:"rep_water_acoustic_vel"`
	Rep_water_acoustic_vel_ouom  *string    `json:"rep_water_acoustic_vel_ouom"`
	Shot_by                      *string    `json:"shot_by"`
	Shot_for                     *string    `json:"shot_for"`
	Source                       *string    `json:"source"`
	Well_src_azimuth             *float64   `json:"well_src_azimuth"`
	Well_src_azimuth_north       *string    `json:"well_src_azimuth_north"`
	Well_src_offset              *float64   `json:"well_src_offset"`
	Well_src_offset_ouom         *string    `json:"well_src_offset_ouom"`
	Row_changed_by               *string    `json:"row_changed_by"`
	Row_changed_date             *time.Time `json:"row_changed_date"`
	Row_created_by               *string    `json:"row_created_by"`
	Row_created_date             *time.Time `json:"row_created_date"`
	Row_effective_date           *time.Time `json:"row_effective_date"`
	Row_expiry_date              *time.Time `json:"row_expiry_date"`
	Row_quality                  *string    `json:"row_quality"`
}
