package dto

import (
	"time"
)

type Well_test struct {
	Uwi                         string     `json:"uwi"`
	Source                      string     `json:"source"`
	Test_type                   string     `json:"test_type"`
	Run_num                     string     `json:"run_num"`
	Test_num                    string     `json:"test_num"`
	Active_ind                  *string    `json:"active_ind"`
	Base_depth                  *float64   `json:"base_depth"`
	Base_depth_ouom             *string    `json:"base_depth_ouom"`
	Base_strat_unit_id          *string    `json:"base_strat_unit_id"`
	Bhp_z                       *float64   `json:"bhp_z"`
	Bottom_choke_desc           *string    `json:"bottom_choke_desc"`
	Bsw_percent                 *float64   `json:"bsw_percent"`
	Caliper_hole_diameter       *float64   `json:"caliper_hole_diameter"`
	Caliper_hole_diameter_ouom  *string    `json:"caliper_hole_diameter_ouom"`
	Cased_hole_ind              *string    `json:"cased_hole_ind"`
	Casing_pressure             *float64   `json:"casing_pressure"`
	Casing_pressure_ouom        *string    `json:"casing_pressure_ouom"`
	Choke_size_desc             *string    `json:"choke_size_desc"`
	Completion_obs_no           *int       `json:"completion_obs_no"`
	Completion_source           *string    `json:"completion_source"`
	Condensate_amount_percent   *float64   `json:"condensate_amount_percent"`
	Condensate_flow_amount      *float64   `json:"condensate_flow_amount"`
	Condensate_flow_amount_ouom *string    `json:"condensate_flow_amount_ouom"`
	Condensate_flow_amount_uom  *string    `json:"condensate_flow_amount_uom"`
	Condensate_gravity          *float64   `json:"condensate_gravity"`
	Condensate_ratio            *float64   `json:"condensate_ratio"`
	Condensate_ratio_ouom       *string    `json:"condensate_ratio_ouom"`
	Damage_quality              *string    `json:"damage_quality"`
	Effective_date              *time.Time `json:"effective_date"`
	Event_obs_no                *int       `json:"event_obs_no"`
	Event_source                *string    `json:"event_source"`
	Expiry_date                 *time.Time `json:"expiry_date"`
	Flow_pressure               *float64   `json:"flow_pressure"`
	Flow_pressure_ouom          *string    `json:"flow_pressure_ouom"`
	Flow_temperature            *float64   `json:"flow_temperature"`
	Flow_temperature_ouom       *string    `json:"flow_temperature_ouom"`
	Gas_flow_amount             *float64   `json:"gas_flow_amount"`
	Gas_flow_amount_ouom        *string    `json:"gas_flow_amount_ouom"`
	Gas_flow_amount_uom         *string    `json:"gas_flow_amount_uom"`
	Gas_gravity                 *float64   `json:"gas_gravity"`
	Gor                         *float64   `json:"gor"`
	Gor_ouom                    *string    `json:"gor_ouom"`
	H2s_percent                 *float64   `json:"h_2_s_percent"`
	Hole_condition              *string    `json:"hole_condition"`
	Max_condens_flow_rate       *float64   `json:"max_condens_flow_rate"`
	Max_condens_flow_rate_ouom  *string    `json:"max_condens_flow_rate_ouom"`
	Max_gas_flow_rate           *float64   `json:"max_gas_flow_rate"`
	Max_gas_flow_rate_ouom      *string    `json:"max_gas_flow_rate_ouom"`
	Max_hydrostatic_pressure    *float64   `json:"max_hydrostatic_pressure"`
	Max_hydrostatic_press_ouom  *string    `json:"max_hydrostatic_press_ouom"`
	Max_oil_flow_rate           *float64   `json:"max_oil_flow_rate"`
	Max_oil_flow_rate_ouom      *string    `json:"max_oil_flow_rate_ouom"`
	Max_water_flow_rate         *float64   `json:"max_water_flow_rate"`
	Max_water_flow_rate_ouom    *string    `json:"max_water_flow_rate_ouom"`
	Oil_amount_percent          *float64   `json:"oil_amount_percent"`
	Oil_flow_amount             *float64   `json:"oil_flow_amount"`
	Oil_flow_amount_ouom        *string    `json:"oil_flow_amount_ouom"`
	Oil_flow_amount_uom         *string    `json:"oil_flow_amount_uom"`
	Oil_gravity                 *float64   `json:"oil_gravity"`
	Permeability_quality        *string    `json:"permeability_quality"`
	Ppdm_guid                   string     `json:"ppdm_guid"`
	Primary_fluid_recovered     *string    `json:"primary_fluid_recovered"`
	Production_method           *string    `json:"production_method"`
	Prod_string_id              *string    `json:"prod_string_id"`
	Prod_str_form_obs_no        *int       `json:"prod_str_form_obs_no"`
	Rat_hole_diameter           *float64   `json:"rat_hole_diameter"`
	Rat_hole_diameter_ouom      *string    `json:"rat_hole_diameter_ouom"`
	Rat_hole_length             *float64   `json:"rat_hole_length"`
	Rat_hole_length_ouom        *string    `json:"rat_hole_length_ouom"`
	Remark                      *string    `json:"remark"`
	Reported_strat_unit_id      *string    `json:"reported_strat_unit_id"`
	Report_temperature          *float64   `json:"report_temperature"`
	Report_temperature_ouom     *string    `json:"report_temperature_ouom"`
	Report_test_num             *string    `json:"report_test_num"`
	Show_type                   *string    `json:"show_type"`
	Si_flow_ratio               *float64   `json:"si_flow_ratio"`
	Start_time                  *time.Time `json:"start_time"`
	Start_timezone              *string    `json:"start_timezone"`
	Static_pressure             *float64   `json:"static_pressure"`
	Static_pressure_ouom        *string    `json:"static_pressure_ouom"`
	Strat_age                   *string    `json:"strat_age"`
	Strat_age_name_set_id       *string    `json:"strat_age_name_set_id"`
	Strat_name_set_id           *string    `json:"strat_name_set_id"`
	String_source               *string    `json:"string_source"`
	Sulphur_ind                 *string    `json:"sulphur_ind"`
	Td                          *float64   `json:"td"`
	Td_ouom                     *string    `json:"td_ouom"`
	Temperature_correction      *float64   `json:"temperature_correction"`
	Temperature_correction_ind  *string    `json:"temperature_correction_ind"`
	Temperature_correction_ouom *string    `json:"temperature_correction_ouom"`
	Test_company                *string    `json:"test_company"`
	Test_date                   *time.Time `json:"test_date"`
	Test_duration               *float64   `json:"test_duration"`
	Test_duration_ouom          *string    `json:"test_duration_ouom"`
	Test_hole_diameter          *float64   `json:"test_hole_diameter"`
	Test_hole_diameter_ouom     *string    `json:"test_hole_diameter_ouom"`
	Test_result_code            *string    `json:"test_result_code"`
	Test_subtype                *string    `json:"test_subtype"`
	Tool_open_time              *time.Time `json:"tool_open_time"`
	Tool_open_timezone          *string    `json:"tool_open_timezone"`
	Top_choke_desc              *string    `json:"top_choke_desc"`
	Top_depth                   *float64   `json:"top_depth"`
	Top_depth_ouom              *string    `json:"top_depth_ouom"`
	Top_strat_unit_id           *string    `json:"top_strat_unit_id"`
	Water_amount_percent        *float64   `json:"water_amount_percent"`
	Water_cut_percent           *float64   `json:"water_cut_percent"`
	Water_flow_amount           *float64   `json:"water_flow_amount"`
	Water_flow_amount_ouom      *string    `json:"water_flow_amount_ouom"`
	Water_flow_amount_uom       *string    `json:"water_flow_amount_uom"`
	Wellbore_completion_type    *string    `json:"wellbore_completion_type"`
	Z_factor                    *float64   `json:"z_factor"`
	Row_changed_by              *string    `json:"row_changed_by"`
	Row_changed_date            *time.Time `json:"row_changed_date"`
	Row_created_by              *string    `json:"row_created_by"`
	Row_created_date            *time.Time `json:"row_created_date"`
	Row_effective_date          *time.Time `json:"row_effective_date"`
	Row_expiry_date             *time.Time `json:"row_expiry_date"`
	Row_quality                 *string    `json:"row_quality"`
}
