package dto

import (
	"time"
)

type Well_drill_period struct {
	Uwi                        string     `json:"uwi"`
	Period_obs_no              int        `json:"period_obs_no"`
	Active_ind                 *string    `json:"active_ind"`
	Bha_weight                 *float64   `json:"bha_weight"`
	Bha_weight_ouom            *string    `json:"bha_weight_ouom"`
	Boiler_fuel                *float64   `json:"boiler_fuel"`
	Boiler_fuel_ouom           *string    `json:"boiler_fuel_ouom"`
	Camp_ind                   *string    `json:"camp_ind"`
	Casing_press_max           *float64   `json:"casing_press_max"`
	Casing_press_max_ouom      *string    `json:"casing_press_max_ouom"`
	Circ_pressure              *float64   `json:"circ_pressure"`
	Circ_pressure_max          *float64   `json:"circ_pressure_max"`
	Circ_pressure_max_ouom     *string    `json:"circ_pressure_max_ouom"`
	Circ_pressure_min          *float64   `json:"circ_pressure_min"`
	Circ_pressure_min_ouom     *string    `json:"circ_pressure_min_ouom"`
	Circ_pressure_ouom         *string    `json:"circ_pressure_ouom"`
	Circ_pressure_type         *string    `json:"circ_pressure_type"`
	Contractor_ba_id           *string    `json:"contractor_ba_id"`
	Contractor_rep_ba_id       *string    `json:"contractor_rep_ba_id"`
	Contractor_rep_name        *string    `json:"contractor_rep_name"`
	Contractor_rep_signed_ind  *string    `json:"contractor_rep_signed_ind"`
	Cum_crew_safety_days       *int       `json:"cum_crew_safety_days"`
	Cum_rig_safety_days        *int       `json:"cum_rig_safety_days"`
	Drill_activity_set_id      *string    `json:"drill_activity_set_id"`
	Drill_activity_type_id     *string    `json:"drill_activity_type_id"`
	Drill_pipe_single_count    *int       `json:"drill_pipe_single_count"`
	Drill_pipe_single_len      *float64   `json:"drill_pipe_single_len"`
	Drill_pipe_single_len_ouom *string    `json:"drill_pipe_single_len_ouom"`
	Drill_pipe_stand_count     *int       `json:"drill_pipe_stand_count"`
	Drill_pipe_stand_len       *float64   `json:"drill_pipe_stand_len"`
	Drill_pipe_stand_len_ouom  *string    `json:"drill_pipe_stand_len_ouom"`
	Drill_string_torque        *float64   `json:"drill_string_torque"`
	Drill_string_torque_ouom   *string    `json:"drill_string_torque_ouom"`
	Effective_date             *time.Time `json:"effective_date"`
	End_date                   *time.Time `json:"end_date"`
	End_time                   *time.Time `json:"end_time"`
	End_timezone               *string    `json:"end_timezone"`
	Expiry_date                *time.Time `json:"expiry_date"`
	Finance_id                 *string    `json:"finance_id"`
	Hole_drag                  *float64   `json:"hole_drag"`
	Hole_drag_ouom             *string    `json:"hole_drag_ouom"`
	Hole_fill_length           *float64   `json:"hole_fill_length"`
	Hole_fill_length_ouom      *string    `json:"hole_fill_length_ouom"`
	Hookload_max               *float64   `json:"hookload_max"`
	Hookload_max_ouom          *string    `json:"hookload_max_ouom"`
	Job_num                    *string    `json:"job_num"`
	Kb_down_length             *float64   `json:"kb_down_length"`
	Kb_down_length_ouom        *string    `json:"kb_down_length_ouom"`
	Mud_system_type            *string    `json:"mud_system_type"`
	Mud_type_oil_ind           *string    `json:"mud_type_oil_ind"`
	Mud_type_water_ind         *string    `json:"mud_type_water_ind"`
	Operator_ba_id             *string    `json:"operator_ba_id"`
	Operator_fuel              *float64   `json:"operator_fuel"`
	Operator_fuel_ouom         *string    `json:"operator_fuel_ouom"`
	Operator_fuel_uom          *string    `json:"operator_fuel_uom"`
	Operator_rep_ba_id         *string    `json:"operator_rep_ba_id"`
	Operator_rep_name          *string    `json:"operator_rep_name"`
	Operator_rep_signed_ind    *string    `json:"operator_rep_signed_ind"`
	Ppdm_guid                  string     `json:"ppdm_guid"`
	Primary_activity_ind       *string    `json:"primary_activity_ind"`
	Rate_schedule_id           *string    `json:"rate_schedule_id"`
	Reentry_ind                *string    `json:"reentry_ind"`
	Remark                     *string    `json:"remark"`
	Reported_base_location     *string    `json:"reported_base_location"`
	Reported_kb_elev           *float64   `json:"reported_kb_elev"`
	Reported_kb_elev_ouom      *string    `json:"reported_kb_elev_ouom"`
	Reported_license_num       *string    `json:"reported_license_num"`
	Reported_period_num        *string    `json:"reported_period_num"`
	Reported_profile_type      *string    `json:"reported_profile_type"`
	Reported_rig_name          *string    `json:"reported_rig_name"`
	Reported_rig_rel_date      *time.Time `json:"reported_rig_rel_date"`
	Reported_rig_rel_time      *time.Time `json:"reported_rig_rel_time"`
	Reported_rig_rel_timezone  *string    `json:"reported_rig_rel_timezone"`
	Reported_spud_date         *time.Time `json:"reported_spud_date"`
	Reported_spud_time         *time.Time `json:"reported_spud_time"`
	Reported_spud_timezone     *string    `json:"reported_spud_timezone"`
	Reported_top_location      *string    `json:"reported_top_location"`
	Reported_uwi               *string    `json:"reported_uwi"`
	Reported_well_name         *string    `json:"reported_well_name"`
	Report_time_type           *string    `json:"report_time_type"`
	Rig_fuel                   *float64   `json:"rig_fuel"`
	Rig_fuel_ouom              *string    `json:"rig_fuel_ouom"`
	Rig_fuel_uom               *string    `json:"rig_fuel_uom"`
	Safety_meeting_topic       *string    `json:"safety_meeting_topic"`
	Source                     *string    `json:"source"`
	Start_date                 *time.Time `json:"start_date"`
	Start_time                 *time.Time `json:"start_time"`
	Start_timezone             *string    `json:"start_timezone"`
	Tot_drill_tool_length      *float64   `json:"tot_drill_tool_length"`
	Tot_drill_tool_length_ouom *string    `json:"tot_drill_tool_length_ouom"`
	Tot_drill_tool_weight      *float64   `json:"tot_drill_tool_weight"`
	Tot_drill_tool_weight_ouom *string    `json:"tot_drill_tool_weight_ouom"`
	Row_changed_by             *string    `json:"row_changed_by"`
	Row_changed_date           *time.Time `json:"row_changed_date"`
	Row_created_by             *string    `json:"row_created_by"`
	Row_created_date           *time.Time `json:"row_created_date"`
	Row_effective_date         *time.Time `json:"row_effective_date"`
	Row_expiry_date            *time.Time `json:"row_expiry_date"`
	Row_quality                *string    `json:"row_quality"`
}
