package dto

import (
	"time"
)

type Well_dir_srvy_version struct {
	Uwi                         string     `json:"uwi"`
	Survey_id                   string     `json:"survey_id"`
	Source                      string     `json:"source"`
	Version_obs_no              int        `json:"version_obs_no"`
	Active_ind                  *string    `json:"active_ind"`
	Azimuth_coord_sys_id        *string    `json:"azimuth_coord_sys_id"`
	Azimuth_coord_sys_qualifier *string    `json:"azimuth_coord_sys_qualifier"`
	Azimuth_coord_sys_remark    *string    `json:"azimuth_coord_sys_remark"`
	Azimuth_corr_angle          *float64   `json:"azimuth_corr_angle"`
	Azimuth_corr_angle_ouom     *string    `json:"azimuth_corr_angle_ouom"`
	Azimuth_corr_angle_type     *string    `json:"azimuth_corr_angle_type"`
	Azimuth_north_type          *string    `json:"azimuth_north_type"`
	Base_depth                  *float64   `json:"base_depth"`
	Base_depth_ouom             *string    `json:"base_depth_ouom"`
	Compute_method              *string    `json:"compute_method"`
	Confidential_type           *string    `json:"confidential_type"`
	Coord_acquisition_id        *string    `json:"coord_acquisition_id"`
	Dir_survey_class            *string    `json:"dir_survey_class"`
	Effective_date              *time.Time `json:"effective_date"`
	Expiry_date                 *time.Time `json:"expiry_date"`
	Extrapolate_depth           *float64   `json:"extrapolate_depth"`
	Extrapolate_depth_ouom      *string    `json:"extrapolate_depth_ouom"`
	Extrapolate_ind             *string    `json:"extrapolate_ind"`
	Geog_coord_sys_id           *string    `json:"geog_coord_sys_id"`
	Local_coord_sys_id          *string    `json:"local_coord_sys_id"`
	Magnetic_declination        *float64   `json:"magnetic_declination"`
	Magnetic_declination_ouom   *string    `json:"magnetic_declination_ouom"`
	Mag_decl_ew_direction       *string    `json:"mag_decl_ew_direction"`
	Offset_coord_sys_id         *string    `json:"offset_coord_sys_id"`
	Offset_coord_sys_qualifier  *string    `json:"offset_coord_sys_qualifier"`
	Offset_coord_sys_remark     *string    `json:"offset_coord_sys_remark"`
	Offset_north_type           *string    `json:"offset_north_type"`
	Plane_of_proposal           *float64   `json:"plane_of_proposal"`
	Plane_of_proposal_ouom      *string    `json:"plane_of_proposal_ouom"`
	Ppdm_guid                   string     `json:"ppdm_guid"`
	Preferred_ind               *string    `json:"preferred_ind"`
	Rad_uncert_dist             *float64   `json:"rad_uncert_dist"`
	Rad_uncert_dist_ouom        *string    `json:"rad_uncert_dist_ouom"`
	Rad_uncert_dist_reason      *string    `json:"rad_uncert_dist_reason"`
	Record_mode                 *string    `json:"record_mode"`
	Remark                      *string    `json:"remark"`
	Report_apd                  *float64   `json:"report_apd"`
	Report_log_datum            *string    `json:"report_log_datum"`
	Report_log_datum_elev       *float64   `json:"report_log_datum_elev"`
	Report_log_datum_elev_ouom  *string    `json:"report_log_datum_elev_ouom"`
	Report_perm_datum           *string    `json:"report_perm_datum"`
	Report_perm_datum_elev      *float64   `json:"report_perm_datum_elev"`
	Report_perm_datum_elev_ouom *string    `json:"report_perm_datum_elev_ouom"`
	Resample_interval           *float64   `json:"resample_interval"`
	Resample_interval_ouom      *string    `json:"resample_interval_ouom"`
	Rpt_coord_sys_id            *string    `json:"rpt_coord_sys_id"`
	Rpt_coord_sys_qualifier     *string    `json:"rpt_coord_sys_qualifier"`
	Rpt_coord_sys_remark        *string    `json:"rpt_coord_sys_remark"`
	Rpt_corr_angle              *float64   `json:"rpt_corr_angle"`
	Rpt_corr_angle_ouom         *string    `json:"rpt_corr_angle_ouom"`
	Rpt_corr_angle_type         *string    `json:"rpt_corr_angle_type"`
	Rpt_north_type              *string    `json:"rpt_north_type"`
	Rpt_survey_type             *string    `json:"rpt_survey_type"`
	Rpt_tie_azimuth             *float64   `json:"rpt_tie_azimuth"`
	Rpt_tie_azimuth_ouom        *string    `json:"rpt_tie_azimuth_ouom"`
	Rpt_tie_inclination         *float64   `json:"rpt_tie_inclination"`
	Rpt_tie_inclination_ouom    *string    `json:"rpt_tie_inclination_ouom"`
	Rpt_tie_md                  *float64   `json:"rpt_tie_md"`
	Rpt_tie_md_ouom             *string    `json:"rpt_tie_md_ouom"`
	Rpt_tie_point_ind           *string    `json:"rpt_tie_point_ind"`
	Rpt_tie_tvd                 *float64   `json:"rpt_tie_tvd"`
	Rpt_tie_tvd_ouom            *string    `json:"rpt_tie_tvd_ouom"`
	Rpt_tie_x_offset            *float64   `json:"rpt_tie_x_offset"`
	Rpt_tie_x_offset_ew_dir     *string    `json:"rpt_tie_x_offset_ew_dir"`
	Rpt_tie_x_offset_ouom       *string    `json:"rpt_tie_x_offset_ouom"`
	Rpt_tie_y_offset            *float64   `json:"rpt_tie_y_offset"`
	Rpt_tie_y_offset_ns_dir     *string    `json:"rpt_tie_y_offset_ns_dir"`
	Rpt_tie_y_offset_ouom       *string    `json:"rpt_tie_y_offset_ouom"`
	Source_document_id          *string    `json:"source_document_id"`
	Survey_company_ba_id        *string    `json:"survey_company_ba_id"`
	Survey_compiler_ba_id       *string    `json:"survey_compiler_ba_id"`
	Survey_digital_prvdr_ba_id  *string    `json:"survey_digital_prvdr_ba_id"`
	Survey_end_date             *time.Time `json:"survey_end_date"`
	Survey_end_date_qualifier   *string    `json:"survey_end_date_qualifier"`
	Survey_process_method       *string    `json:"survey_process_method"`
	Survey_quality              *string    `json:"survey_quality"`
	Survey_ref_num              *string    `json:"survey_ref_num"`
	Survey_report_type          *string    `json:"survey_report_type"`
	Survey_run_num              *string    `json:"survey_run_num"`
	Survey_start_date           *time.Time `json:"survey_start_date"`
	Survey_start_date_qualifier *string    `json:"survey_start_date_qualifier"`
	Survey_type                 *string    `json:"survey_type"`
	Top_depth                   *float64   `json:"top_depth"`
	Top_depth_ouom              *string    `json:"top_depth_ouom"`
	Row_changed_by              *string    `json:"row_changed_by"`
	Row_changed_date            *time.Time `json:"row_changed_date"`
	Row_created_by              *string    `json:"row_created_by"`
	Row_created_date            *time.Time `json:"row_created_date"`
	Row_effective_date          *time.Time `json:"row_effective_date"`
	Row_expiry_date             *time.Time `json:"row_expiry_date"`
	Row_quality                 *string    `json:"row_quality"`
}
