package dto

import (
	"time"
)

type Well_version struct {
	Uwi                       string     `json:"uwi"`
	Source                    string     `json:"source"`
	Abandonment_date          *time.Time `json:"abandonment_date"`
	Active_ind                *string    `json:"active_ind"`
	Assigned_field            *string    `json:"assigned_field"`
	Base_depth                *float64   `json:"base_depth"`
	Base_depth_ouom           *string    `json:"base_depth_ouom"`
	Base_node_id              *string    `json:"base_node_id"`
	Base_strat_name_set_id    *string    `json:"base_strat_name_set_id"`
	Base_strat_unit_id        *string    `json:"base_strat_unit_id"`
	Bottom_hole_latitude      *float64   `json:"bottom_hole_latitude"`
	Bottom_hole_longitude     *float64   `json:"bottom_hole_longitude"`
	Casing_flange_elev        *float64   `json:"casing_flange_elev"`
	Casing_flange_elev_ouom   *string    `json:"casing_flange_elev_ouom"`
	Completion_date           *time.Time `json:"completion_date"`
	Confidential_date         *time.Time `json:"confidential_date"`
	Confidential_depth        *float64   `json:"confidential_depth"`
	Confidential_depth_ouom   *string    `json:"confidential_depth_ouom"`
	Confidential_type         *string    `json:"confidential_type"`
	Confid_strat_name_set_id  *string    `json:"confid_strat_name_set_id"`
	Confid_strat_unit_id      *string    `json:"confid_strat_unit_id"`
	Current_class             *string    `json:"current_class"`
	Current_status            *string    `json:"current_status"`
	Current_status_date       *time.Time `json:"current_status_date"`
	Deepest_depth             *float64   `json:"deepest_depth"`
	Deepest_depth_ouom        *string    `json:"deepest_depth_ouom"`
	Depth_datum               *string    `json:"depth_datum"`
	Depth_datum_elev          *float64   `json:"depth_datum_elev"`
	Depth_datum_elev_ouom     *string    `json:"depth_datum_elev_ouom"`
	Derrick_floor_elev        *float64   `json:"derrick_floor_elev"`
	Derrick_floor_elev_ouom   *string    `json:"derrick_floor_elev_ouom"`
	Difference_lat_msl        *float64   `json:"difference_lat_msl"`
	Discovery_ind             *string    `json:"discovery_ind"`
	Drill_td                  *float64   `json:"drill_td"`
	Drill_td_ouom             *string    `json:"drill_td_ouom"`
	Effective_date            *time.Time `json:"effective_date"`
	Elev_ref_datum            *string    `json:"elev_ref_datum"`
	Environment_type          *string    `json:"environment_type"`
	Expiry_date               *time.Time `json:"expiry_date"`
	Faulted_ind               *string    `json:"faulted_ind"`
	Final_drill_date          *time.Time `json:"final_drill_date"`
	Final_td                  *float64   `json:"final_td"`
	Final_td_ouom             *string    `json:"final_td_ouom"`
	Ground_elev               *float64   `json:"ground_elev"`
	Ground_elev_ouom          *string    `json:"ground_elev_ouom"`
	Ground_elev_type          *string    `json:"ground_elev_type"`
	Initial_class             *string    `json:"initial_class"`
	Kb_elev                   *float64   `json:"kb_elev"`
	Kb_elev_ouom              *string    `json:"kb_elev_ouom"`
	Lease_name                *string    `json:"lease_name"`
	Lease_num                 *string    `json:"lease_num"`
	Legal_survey_type         *string    `json:"legal_survey_type"`
	Location_type             *string    `json:"location_type"`
	Log_td                    *float64   `json:"log_td"`
	Log_td_ouom               *string    `json:"log_td_ouom"`
	Max_tvd                   *float64   `json:"max_tvd"`
	Max_tvd_ouom              *string    `json:"max_tvd_ouom"`
	Net_pay                   *float64   `json:"net_pay"`
	Net_pay_ouom              *string    `json:"net_pay_ouom"`
	Oldest_strat_age          *string    `json:"oldest_strat_age"`
	Oldest_strat_name_set_age *string    `json:"oldest_strat_name_set_age"`
	Oldest_strat_name_set_id  *string    `json:"oldest_strat_name_set_id"`
	Oldest_strat_unit_id      *string    `json:"oldest_strat_unit_id"`
	Operator                  *string    `json:"operator"`
	Platform_id               *string    `json:"platform_id"`
	Platform_sf_subtype       *string    `json:"platform_sf_subtype"`
	Plot_name                 *string    `json:"plot_name"`
	Plot_symbol               *string    `json:"plot_symbol"`
	Plugback_depth            *float64   `json:"plugback_depth"`
	Plugback_depth_ouom       *string    `json:"plugback_depth_ouom"`
	Ppdm_guid                 string     `json:"ppdm_guid"`
	Profile_type              *string    `json:"profile_type"`
	Regulatory_agency         *string    `json:"regulatory_agency"`
	Remark                    *string    `json:"remark"`
	Rig_on_site_date          *time.Time `json:"rig_on_site_date"`
	Rig_release_date          *time.Time `json:"rig_release_date"`
	Rotary_table_elev         *float64   `json:"rotary_table_elev"`
	Rotary_table_elev_ouom    *string    `json:"rotary_table_elev_ouom"`
	Source_document_id        *string    `json:"source_document_id"`
	Spud_date                 *time.Time `json:"spud_date"`
	Status_type               *string    `json:"status_type"`
	Subsea_elev_ref_type      *string    `json:"subsea_elev_ref_type"`
	Surface_latitude          *float64   `json:"surface_latitude"`
	Surface_longitude         *float64   `json:"surface_longitude"`
	Surface_node_id           *string    `json:"surface_node_id"`
	Tax_credit_code           *string    `json:"tax_credit_code"`
	Td_strat_age              *string    `json:"td_strat_age"`
	Td_strat_name_set_age     *string    `json:"td_strat_name_set_age"`
	Td_strat_name_set_id      *string    `json:"td_strat_name_set_id"`
	Td_strat_unit_id          *string    `json:"td_strat_unit_id"`
	Top_depth                 *float64   `json:"top_depth"`
	Top_depth_ouom            *string    `json:"top_depth_ouom"`
	Top_strat_name_set_id     *string    `json:"top_strat_name_set_id"`
	Top_strat_unit_id         *string    `json:"top_strat_unit_id"`
	Water_acoustic_vel        *float64   `json:"water_acoustic_vel"`
	Water_acoustic_vel_ouom   *string    `json:"water_acoustic_vel_ouom"`
	Water_depth               *float64   `json:"water_depth"`
	Water_depth_datum         *string    `json:"water_depth_datum"`
	Water_depth_ouom          *string    `json:"water_depth_ouom"`
	Well_event_num            *string    `json:"well_event_num"`
	Well_government_id        *string    `json:"well_government_id"`
	Well_intersect_md         *float64   `json:"well_intersect_md"`
	Well_level_type           *string    `json:"well_level_type"`
	Well_name                 *string    `json:"well_name"`
	Well_num                  *string    `json:"well_num"`
	Whipstock_depth           *float64   `json:"whipstock_depth"`
	Whipstock_depth_ouom      *string    `json:"whipstock_depth_ouom"`
	Row_changed_by            *string    `json:"row_changed_by"`
	Row_changed_date          *time.Time `json:"row_changed_date"`
	Row_created_by            *string    `json:"row_created_by"`
	Row_created_date          *time.Time `json:"row_created_date"`
	Row_effective_date        *time.Time `json:"row_effective_date"`
	Row_expiry_date           *time.Time `json:"row_expiry_date"`
	Row_quality               *string    `json:"row_quality"`
}
