application:
  type: array
  items:
    type: object
    properties:
      application_id:
        type: string
        maxLength: 40
      active_ind:
        type: string
        maxLength: 1
      application_type:
        type: string
        maxLength: 40
      contract_id:
        type: string
        maxLength: 40
      current_status:
        type: string
        maxLength: 40
      decision:
        type: string
        maxLength: 40
      decision_date:
        type: string
      effective_date:
        type: string
      expiry_date:
        type: string
      extension_id:
        type: string
        maxLength: 40
      fees_desc:
        type: string
        maxLength: 240
      fees_paid_ind:
        type: string
        maxLength: 1
      ppdm_guid:
        type: string
        maxLength: 38
      previous_application_id:
        type: string
        maxLength: 40
      rate_schedule_id:
        type: string
        maxLength: 40
      received_date:
        type: string
      reference_num:
        type: string
        maxLength: 40
      remark:
        type: string
        maxLength: 2000
      resubmission_ind:
        type: string
        maxLength: 1
      section_of_act:
        type: string
        maxLength: 240
      section_of_act_date:
        type: string
      source:
        type: string
        maxLength: 40
      submission_complete_ind:
        type: string
        maxLength: 1
      submission_desc:
        type: string
        maxLength: 240
      submitted_by:
        type: string
        maxLength: 255
      submitted_date:
        type: string
      submitted_to:
        type: string
        maxLength: 255
      row_changed_by:
        type: string
        maxLength: 30
      row_changed_date:
        type: string
      row_created_by:
        type: string
        maxLength: 30
      row_created_date:
        type: string
      row_effective_date:
        type: string
      row_expiry_date:
        type: string
      row_quality:
        type: string
        maxLength: 40
