prod_string:
  type: array
  items:
    type: object
    properties:
      uwi:
        type: string
        maxLength: 40
      source:
        type: string
        maxLength: 40
      string_id:
        type: string
        maxLength: 40
      active_ind:
        type: string
        maxLength: 1
      base_depth:
        type: number
        format: decimal
      base_depth_ouom:
        type: string
        maxLength: 40
      business_associate_id:
        type: string
        maxLength: 40
      commingled_ind:
        type: string
        maxLength: 1
      current_status:
        type: string
        maxLength: 40
      current_status_date:
        type: string
      effective_date:
        type: string
      expiry_date:
        type: string
      facility_id:
        type: string
        maxLength: 40
      facility_type:
        type: string
        maxLength: 40
      field_id:
        type: string
        maxLength: 40
      government_string_id:
        type: string
        maxLength: 40
      lease_unit_id:
        type: string
        maxLength: 40
      on_injection_date:
        type: string
      on_production_date:
        type: string
      plot_symbol:
        type: string
        maxLength: 40
      pool_id:
        type: string
        maxLength: 40
      ppdm_guid:
        type: string
        maxLength: 38
      prod_string_tvd:
        type: number
        format: decimal
      prod_string_tvd_ouom:
        type: string
        maxLength: 40
      prod_string_type:
        type: string
        maxLength: 40
      profile_type:
        type: string
        maxLength: 40
      remark:
        type: string
        maxLength: 2000
      status_type:
        type: string
        maxLength: 40
      strat_name_set_id:
        type: string
        maxLength: 40
      strat_unit_id:
        type: string
        maxLength: 40
      tax_credit_code:
        type: string
        maxLength: 40
      top_depth:
        type: number
        format: decimal
      top_depth_ouom:
        type: string
        maxLength: 40
      total_depth:
        type: number
        format: decimal
      total_depth_ouom:
        type: string
        maxLength: 40
      row_changed_by:
        type: string
        maxLength: 30
      row_changed_date:
        type: string
      row_created_by:
        type: string
        maxLength: 30
      row_created_date:
        type: string
      row_effective_date:
        type: string
      row_expiry_date:
        type: string
      row_quality:
        type: string
        maxLength: 40
