prod_string_formation:
  type: array
  items:
    type: object
    properties:
      uwi:
        type: string
        maxLength: 40
      prod_string_source:
        type: string
        maxLength: 40
      string_id:
        type: string
        maxLength: 40
      pr_str_form_obs_no:
        type: integer
      active_ind:
        type: string
        maxLength: 1
      allocation_factor:
        type: number
        format: decimal
      allocation_type:
        type: string
        maxLength: 40
      base_depth:
        type: number
        format: decimal
      base_depth_ouom:
        type: string
        maxLength: 40
      completion_obs_no:
        type: integer
      current_status:
        type: string
        maxLength: 40
      current_status_date:
        type: string
      effective_date:
        type: string
      expiry_date:
        type: string
      pool_id:
        type: string
        maxLength: 40
      ppdm_guid:
        type: string
        maxLength: 38
      remark:
        type: string
        maxLength: 2000
      source:
        type: string
        maxLength: 40
      status_type:
        type: string
        maxLength: 40
      strat_name_set_id:
        type: string
        maxLength: 40
      strat_unit_id:
        type: string
        maxLength: 40
      top_depth:
        type: number
        format: decimal
      top_depth_ouom:
        type: string
        maxLength: 40
      row_changed_by:
        type: string
        maxLength: 30
      row_changed_date:
        type: string
      row_created_by:
        type: string
        maxLength: 30
      row_created_date:
        type: string
      row_effective_date:
        type: string
      row_expiry_date:
        type: string
      row_quality:
        type: string
        maxLength: 40
