project:
  type: array
  items:
    type: object
    properties:
      project_id:
        type: string
        maxLength: 40
      active_ind:
        type: string
        maxLength: 1
      complete_date:
        type: string
      confidential_ind:
        type: string
        maxLength: 1
      confidential_release_date:
        type: string
      description:
        type: string
        maxLength: 240
      effective_date:
        type: string
      expiry_date:
        type: string
      field_station_ind:
        type: string
        maxLength: 1
      land_right_ind:
        type: string
        maxLength: 1
      pden_ind:
        type: string
        maxLength: 1
      ppdm_guid:
        type: string
        maxLength: 38
      project_name:
        type: string
        maxLength: 255
      project_num:
        type: string
        maxLength: 30
      project_type:
        type: string
        maxLength: 40
      remark:
        type: string
        maxLength: 2000
      seis_set_ind:
        type: string
        maxLength: 1
      source:
        type: string
        maxLength: 40
      start_date:
        type: string
      strat_column_ind:
        type: string
        maxLength: 1
      strat_interpretation_ind:
        type: integer
      well_ind:
        type: string
        maxLength: 1
      row_changed_by:
        type: string
        maxLength: 30
      row_changed_date:
        type: string
      row_created_by:
        type: string
        maxLength: 30
      row_created_date:
        type: string
      row_effective_date:
        type: string
      row_expiry_date:
        type: string
      row_quality:
        type: string
        maxLength: 40
