/ppdm-system-application:
  get:
    security:
    - Authorization: []
    tags:
    - Query
    summary: Get ppdm_system_application
    responses:
      '200':
        description: get ppdm_system_application data to be returned
        content:
          application/json:
            example:
            - system_id: Lorem Ipsum
              sw_application_id: Lorem Ipsum
              active_ind: y
              application_function_desc: Lorem Ipsum
              effective_date: 12/12/2023
              expiry_date: 12/12/2023
              language_id: Lorem Ipsum
              ppdm_guid: Lorem Ipsum
              remark: Lorem Ipsum
              source: Lorem Ipsum
              row_changed_by: Lorem Ipsum
              row_changed_date: 12/12/2023
              row_created_by: Lorem Ipsum
              row_created_date: 12/12/2023
              row_effective_date: 12/12/2023
              row_expiry_date: 12/12/2023
              row_quality: Lorem Ipsum
  post:
    security:
    - Authorization: []
    tags:
    - Create
    summary: Post a new ppdm_system_application
    description: Create a new ppdm_system_application data
    requestBody:
      required: true
      description: Request body to create ppdm_system_application data
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ppdm_system_application'
          example:
            system_id: Lorem Ipsum
            sw_application_id: Lorem Ipsum
            active_ind: y
            application_function_desc: Lorem Ipsum
            effective_date: 12/12/2023
            expiry_date: 12/12/2023
            language_id: Lorem Ipsum
            ppdm_guid: Lorem Ipsum
            remark: Lorem Ipsum
            source: Lorem Ipsum
            row_changed_by: Lorem Ipsum
            row_changed_date: 12/12/2023
            row_created_by: Lorem Ipsum
            row_created_date: 12/12/2023
            row_effective_date: 12/12/2023
            row_expiry_date: 12/12/2023
            row_quality: Lorem Ipsum
    responses:
      '200':
        description: ppdm_system_application data is added
        content:
          application/json:
            example:
              message: The ppdm_system_application data was successfully added
/ppdm-system-application/{id}:
  parameters:
  - in: path
    name: id
    required: true
    description: ID of ppdm_system_application data to fetch
    schema:
      type: string
  put:
    security:
    - Authorization: []
    tags:
    - Put
    summary: Update a new ppdm_system_application data
    description: Update a new ppdm_system_application data
    requestBody:
      required: true
      description: Request body to update ppdm_system_application data
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ppdm_system_application'
          example:
            system_id: Lorem Ipsum
            sw_application_id: Lorem Ipsum
            active_ind: y
            application_function_desc: Lorem Ipsum
            effective_date: 12/12/2023
            expiry_date: 12/12/2023
            language_id: Lorem Ipsum
            ppdm_guid: Lorem Ipsum
            remark: Lorem Ipsum
            source: Lorem Ipsum
            row_changed_by: Lorem Ipsum
            row_changed_date: 12/12/2023
            row_created_by: Lorem Ipsum
            row_created_date: 12/12/2023
            row_effective_date: 12/12/2023
            row_expiry_date: 12/12/2023
            row_quality: Lorem Ipsum
    responses:
      '200':
        description: ppdm_system_application data is completely updated
        content:
          application/json:
            example:
              message: The ppdm_system_application data is completely updated
  patch:
    security:
    - Authorization: []
    tags:
    - Patch
    summary: Update a new ppdm_system_application data
    description: Update a new ppdm_system_application data
    requestBody:
      required: true
      description: Request body to update ppdm_system_application data
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ppdm_system_application'
          example:
            system_id: Lorem Ipsum
            sw_application_id: Lorem Ipsum
            active_ind: y
            application_function_desc: Lorem Ipsum
            effective_date: 12/12/2023
            expiry_date: 12/12/2023
            language_id: Lorem Ipsum
            ppdm_guid: Lorem Ipsum
            remark: Lorem Ipsum
            source: Lorem Ipsum
            row_changed_by: Lorem Ipsum
            row_changed_date: 12/12/2023
            row_created_by: Lorem Ipsum
            row_created_date: 12/12/2023
            row_effective_date: 12/12/2023
            row_expiry_date: 12/12/2023
            row_quality: Lorem Ipsum
    responses:
      '200':
        description: one row in ppdm_system_application data is updated
        content:
          application/json:
            example:
              message: The one row in ppdm_system_application data is updated
  delete:
    security:
    - Authorization: []
    tags:
    - Delete
    summary: Delete ppdm_system_application data
    description: Delete ppdm_system_application data
    responses:
      '200':
        description: ppdm_system_application data is deleted
        content:
          application/json:
            example:
              message: The ppdm_system_application data was successfully deleted
