/prod-lease-unit-ver-area:
  get:
    security:
    - Authorization: []
    tags:
    - Query
    summary: Get prod_lease_unit_ver_area
    responses:
      '200':
        description: get prod_lease_unit_ver_area data to be returned
        content:
          application/json:
            example:
            - lease_unit_id: Lorem Ipsum
              source: Lorem Ipsum
              area_id: Lorem Ipsum
              area_type: Lorem Ipsum
              active_ind: y
              effective_date: 12/12/2023
              expiry_date: 12/12/2023
              ppdm_guid: Lorem Ipsum
              remark: Lorem Ipsum
              row_changed_by: Lorem Ipsum
              row_changed_date: 12/12/2023
              row_created_by: Lorem Ipsum
              row_created_date: 12/12/2023
              row_effective_date: 12/12/2023
              row_expiry_date: 12/12/2023
              row_quality: Lorem Ipsum
  post:
    security:
    - Authorization: []
    tags:
    - Create
    summary: Post a new prod_lease_unit_ver_area
    description: Create a new prod_lease_unit_ver_area data
    requestBody:
      required: true
      description: Request body to create prod_lease_unit_ver_area data
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/prod_lease_unit_ver_area'
          example:
            lease_unit_id: Lorem Ipsum
            source: Lorem Ipsum
            area_id: Lorem Ipsum
            area_type: Lorem Ipsum
            active_ind: y
            effective_date: 12/12/2023
            expiry_date: 12/12/2023
            ppdm_guid: Lorem Ipsum
            remark: Lorem Ipsum
            row_changed_by: Lorem Ipsum
            row_changed_date: 12/12/2023
            row_created_by: Lorem Ipsum
            row_created_date: 12/12/2023
            row_effective_date: 12/12/2023
            row_expiry_date: 12/12/2023
            row_quality: Lorem Ipsum
    responses:
      '200':
        description: prod_lease_unit_ver_area data is added
        content:
          application/json:
            example:
              message: The prod_lease_unit_ver_area data was successfully added
/prod-lease-unit-ver-area/{id}:
  parameters:
  - in: path
    name: id
    required: true
    description: ID of prod_lease_unit_ver_area data to fetch
    schema:
      type: string
  put:
    security:
    - Authorization: []
    tags:
    - Put
    summary: Update a new prod_lease_unit_ver_area data
    description: Update a new prod_lease_unit_ver_area data
    requestBody:
      required: true
      description: Request body to update prod_lease_unit_ver_area data
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/prod_lease_unit_ver_area'
          example:
            lease_unit_id: Lorem Ipsum
            source: Lorem Ipsum
            area_id: Lorem Ipsum
            area_type: Lorem Ipsum
            active_ind: y
            effective_date: 12/12/2023
            expiry_date: 12/12/2023
            ppdm_guid: Lorem Ipsum
            remark: Lorem Ipsum
            row_changed_by: Lorem Ipsum
            row_changed_date: 12/12/2023
            row_created_by: Lorem Ipsum
            row_created_date: 12/12/2023
            row_effective_date: 12/12/2023
            row_expiry_date: 12/12/2023
            row_quality: Lorem Ipsum
    responses:
      '200':
        description: prod_lease_unit_ver_area data is completely updated
        content:
          application/json:
            example:
              message: The prod_lease_unit_ver_area data is completely updated
  patch:
    security:
    - Authorization: []
    tags:
    - Patch
    summary: Update a new prod_lease_unit_ver_area data
    description: Update a new prod_lease_unit_ver_area data
    requestBody:
      required: true
      description: Request body to update prod_lease_unit_ver_area data
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/prod_lease_unit_ver_area'
          example:
            lease_unit_id: Lorem Ipsum
            source: Lorem Ipsum
            area_id: Lorem Ipsum
            area_type: Lorem Ipsum
            active_ind: y
            effective_date: 12/12/2023
            expiry_date: 12/12/2023
            ppdm_guid: Lorem Ipsum
            remark: Lorem Ipsum
            row_changed_by: Lorem Ipsum
            row_changed_date: 12/12/2023
            row_created_by: Lorem Ipsum
            row_created_date: 12/12/2023
            row_effective_date: 12/12/2023
            row_expiry_date: 12/12/2023
            row_quality: Lorem Ipsum
    responses:
      '200':
        description: one row in prod_lease_unit_ver_area data is updated
        content:
          application/json:
            example:
              message: The one row in prod_lease_unit_ver_area data is updated
  delete:
    security:
    - Authorization: []
    tags:
    - Delete
    summary: Delete prod_lease_unit_ver_area data
    description: Delete prod_lease_unit_ver_area data
    responses:
      '200':
        description: prod_lease_unit_ver_area data is deleted
        content:
          application/json:
            example:
              message: The prod_lease_unit_ver_area data was successfully deleted
